"""Accepted deterministic Strategy error catalogue."""

from enum import StrEnum


class StrategyErrorCode(StrEnum):
    """Failure codes reachable from approved Strategy capabilities."""

    INVALID_CONFIG = "STRATEGY_INVALID_CONFIG"
    NOT_FOUND = "STRATEGY_NOT_FOUND"
    VERSION_CONSTRAINT_UNSATISFIABLE = "STRATEGY_VERSION_CONSTRAINT_UNSATISFIABLE"
    DEPRECATED = "STRATEGY_DEPRECATED"
    UNAPPROVED_MODULE = "STRATEGY_UNAPPROVED_MODULE"
    SCHEMA_VALIDATION_FAILED = "STRATEGY_SCHEMA_VALIDATION_FAILED"
    UNSUPPORTED_TIMING_POLICY = "STRATEGY_UNSUPPORTED_TIMING_POLICY"
    LOOKAHEAD_DETECTED = "STRATEGY_LOOKAHEAD_DETECTED"
    ARBITRARY_CODE_REJECTED = "STRATEGY_ARBITRARY_CODE_REJECTED"
    INTERNAL_ERROR = "STRATEGY_INTERNAL_ERROR"
    LIFECYCLE_NOT_APPROVED = "STRATEGY_LIFECYCLE_NOT_APPROVED"
    ENVIRONMENT_NOT_PERMITTED = "STRATEGY_ENVIRONMENT_NOT_PERMITTED"
    ARTIFACT_HASH_MISMATCH = "STRATEGY_ARTIFACT_HASH_MISMATCH"
    DEPENDENCY_HASH_MISMATCH = "STRATEGY_DEPENDENCY_HASH_MISMATCH"
    INDICATOR_MODULE_ERROR = "INDICATOR_MODULE_ERROR"
    CHECKPOINT_INVALID = "STRATEGY_CHECKPOINT_INVALID"
    CHECKPOINT_INCOMPATIBLE = "STRATEGY_CHECKPOINT_INCOMPATIBLE"
    DATA_NOT_READY = "STRATEGY_DATA_NOT_READY"
    INDICATOR_NOT_READY = "STRATEGY_INDICATOR_NOT_READY"
    MISSING_REQUIRED_DATA = "STRATEGY_MISSING_REQUIRED_DATA"
    STALE_DATA = "STRATEGY_STALE_DATA"
    DUPLICATE_INTENT = "STRATEGY_DUPLICATE_INTENT"
    RESOURCE_LIMIT_EXCEEDED = "STRATEGY_RESOURCE_LIMIT_EXCEEDED"
    TIMEOUT = "STRATEGY_TIMEOUT"
    VALIDATION_ARTIFACT_REQUIRED = "STRATEGY_VALIDATION_ARTIFACT_REQUIRED"
    RISK_PROFILE_REQUIRED = "STRATEGY_RISK_PROFILE_REQUIRED"
    POSITION_LIMIT_EXCEEDED = "STRATEGY_POSITION_LIMIT_EXCEEDED"
    DATA_QUALITY_GATE_FAILED = "STRATEGY_DATA_QUALITY_GATE_FAILED"
    HARD_KILLED = "STRATEGY_HARD_KILLED"


__all__ = ["StrategyErrorCode"]
