"""Canonical public port for the complete Strategy domain."""

from app.services.strategy.contracts import (
    StrategyConfig,
    StrategyDecision,
    StrategyEnvironment,
    StrategyError,
    StrategyEvent,
    StrategyExecutionContext,
    StrategyExecutionResult,
    StrategyLifecycleStatus,
    StrategyManifest,
    StrategyMutationResult,
    StrategyOutcome,
    StrategyParameterUpdateRequest,
    StrategyRef,
    StrategyRegistrationRequest,
    StrategySignal,
    StrategySignalEvidence,
    StrategyTimingPolicy,
    StrategyValidationPolicy,
    ValidatedStrategyConfig,
    ValidatedStrategyRef,
)
from app.services.strategy.diagnostics import (
    StrategyDiagnostics,
    StrategyErrorCode,
    export_strategy_diagnostics,
)
from app.services.strategy.evaluators import (
    DecomposingTradeEvaluator,
    HarrietHedgingEvaluator,
    MarketStructureEvaluator,
    NaiveMATrendEvaluator,
    RandomWalkEvaluator,
    SQXBreakoutAtrTrailingEvaluator,
    WhiteFairyEvaluator,
    evaluate_strategy_signals,
)
from app.services.strategy.event import EventStrategyEvaluator, run_event_strategy_hook
from app.services.strategy.intents import TradeIntent, build_trade_intent
from app.services.strategy.registry import (
    list_strategy_versions,
    register_strategy_version,
    update_strategy_parameters,
    validate_strategy_config,
    validate_strategy_ref,
)
from app.services.strategy.replay import (
    StrategyCheckpoint,
    StrategyReplayManifest,
    create_strategy_checkpoint,
    create_strategy_replay_manifest,
    validate_strategy_checkpoint,
)
from app.services.strategy.vectorized import (
    VectorizedStrategyEvaluator,
    run_vectorized_strategy_signals,
)

__all__ = [
    "DecomposingTradeEvaluator",
    "EventStrategyEvaluator",
    "HarrietHedgingEvaluator",
    "MarketStructureEvaluator",
    "NaiveMATrendEvaluator",
    "RandomWalkEvaluator",
    "SQXBreakoutAtrTrailingEvaluator",
    "StrategyCheckpoint",
    "StrategyConfig",
    "StrategyDecision",
    "StrategyDiagnostics",
    "StrategyEnvironment",
    "StrategyError",
    "StrategyErrorCode",
    "StrategyEvent",
    "StrategyExecutionContext",
    "StrategyExecutionResult",
    "StrategyLifecycleStatus",
    "StrategyManifest",
    "StrategyMutationResult",
    "StrategyOutcome",
    "StrategyParameterUpdateRequest",
    "StrategyRef",
    "StrategyRegistrationRequest",
    "StrategyReplayManifest",
    "StrategySignal",
    "StrategySignalEvidence",
    "StrategyTimingPolicy",
    "StrategyValidationPolicy",
    "TradeIntent",
    "ValidatedStrategyConfig",
    "ValidatedStrategyRef",
    "VectorizedStrategyEvaluator",
    "WhiteFairyEvaluator",
    "build_trade_intent",
    "create_strategy_checkpoint",
    "create_strategy_replay_manifest",
    "evaluate_strategy_signals",
    "export_strategy_diagnostics",
    "list_strategy_versions",
    "register_strategy_version",
    "run_event_strategy_hook",
    "run_vectorized_strategy_signals",
    "update_strategy_parameters",
    "validate_strategy_checkpoint",
    "validate_strategy_config",
    "validate_strategy_ref",
]
