import { useState } from 'react';
import { ChevronDown, ChevronUp, CirclePlus, Copy, Download, FileUp, Redo2, Save, Trash2, Undo2 } from 'lucide-react';
import { useAppStore } from '../../app/store';
import { Button, Field, Modal, Select, TextInput } from '../../components/ui';

const blocks = ['Moving Average', 'RSI', 'CCI', 'ATR', 'MACD', 'Bollinger Bands', 'Price comparison', 'Candle pattern', 'Time range', 'Market position', 'Enter at Market', 'Place Stop Order', 'Set Stop Loss', 'Set Profit Target', 'Exit at Market'];
export function AlgoWizard() { const store = useAppStore(); const [selected, setSelected] = useState('r3'); const [dialog, setDialog] = useState(false); const [block, setBlock] = useState(blocks[0]); const [search, setSearch] = useState(''); const rule = store.rules.find(r => r.id === selected);
  return <div className="algo"><div className="aw-toolbar"><Button><FileUp size={15}/>Open</Button><Button onClick={() => store.notify('Strategy definition saved as a new mock revision')}><Save size={15}/>Save</Button><span/><Button><Undo2 size={15}/>Undo</Button><Button><Redo2 size={15}/>Redo</Button><span/><Button onClick={() => setDialog(true)}><CirclePlus size={15}/>Add rule</Button><Button disabled={!rule} onClick={() => rule && store.removeRule(rule.id)}><Trash2 size={15}/>Remove</Button><Button disabled={!rule}><ChevronUp size={15}/></Button><Button disabled={!rule}><ChevronDown size={15}/></Button><span/><Button><Copy size={15}/>Generate strategy</Button><Button><Download size={15}/>Export</Button></div><div className="aw-main"><aside className="block-library"><h3>Building blocks</h3><div className="search"><input placeholder="Search blocks" value={search} onChange={e => setSearch(e.target.value)}/></div>{['Indicators', 'Price data', 'Conditions', 'Order actions', 'Trade management'].map((cat, ci) => <div className="block-category" key={cat}><strong>{cat}</strong>{blocks.filter((b, i) => i >= ci * 3 && i < ci * 3 + 4 && b.toLowerCase().includes(search.toLowerCase())).map(b => <button key={b} onDoubleClick={() => { setBlock(b); setDialog(true); }}>{b}</button>)}</div>)}</aside><main className="rule-editor"><div className="rule-title"><div><h1>Momentum Breakout Strategy</h1><span>Standard · On bar open · 1 chart</span></div><select className="text-input"><option>EURUSD / H1</option><option>GBPJPY / H1</option></select></div><div className="rule-tree">{store.rules.map(r => <button key={r.id} className={`${r.kind} ${selected === r.id ? 'selected' : ''}`} style={{ marginLeft: r.depth * 28 }} onClick={() => setSelected(r.id)}><span>{r.kind.toUpperCase()}</span><strong>{r.label}</strong></button>)}</div></main><aside className="properties"><h3>Block properties</h3>{rule ? <><Field label="Type"><TextInput value={rule.kind} readOnly/></Field><Field label="Expression"><textarea className="text-input textarea" value={rule.label} readOnly/></Field><Field label="Chart"><Select value="Chart 1" onChange={() => {}}><option>Chart 1 · EURUSD H1</option><option>Chart 2 · EURUSD D1</option></Select></Field>{rule.kind === 'condition' && <><Field label="Fast period"><TextInput type="number" defaultValue="12"/></Field><Field label="Slow period"><TextInput type="number" defaultValue="28"/></Field></>}<div className="validation success">✓ Block configuration is valid</div></> : <p className="muted">Select a rule to edit its configuration.</p>}<h3>Variables</h3><table className="mini-table"><tbody><tr><td>FastPeriod</td><td>12</td></tr><tr><td>SlowPeriod</td><td>28</td></tr><tr><td>StopLoss</td><td>90</td></tr></tbody></table></aside></div>
  {dialog && <Modal title="Add strategy block" onClose={() => setDialog(false)} footer={<><Button onClick={() => setDialog(false)}>Cancel</Button><Button className="primary" onClick={() => { store.addRule({ id: `rule-${Date.now()}`, depth: 2, kind: block.includes('Enter') || block.includes('Set') || block.includes('Exit') ? 'action' : 'condition', label: block }); setDialog(false); }}>Add block</Button></>}><Field label="Block"><Select value={block} onChange={setBlock}>{blocks.map(x => <option key={x}>{x}</option>)}</Select></Field><Field label="Parameters"><TextInput defaultValue={block.includes('Average') ? 'Period: 20, Applied price: Close' : 'Default values'}/></Field><Field label="Insert under"><Select value="IF" onChange={() => {}}><option>IF conditions</option><option>THEN actions</option></Select></Field></Modal>}</div>;
}
