"""Approved package-root public API for the Research domain."""

from app.services.research.contracts import (
    PUBLIC_API_CLASSIFICATIONS,
    ArtifactReference,
    ArtifactWriteConfig,
    CleaningConfig,
    CoreMetricProfile,
    DataQualityReport,
    EdgeLabConfig,
    EdgeResult,
    EnrichmentConfig,
    FeatureConfig,
    LeakageReport,
    MarketStructureConfig,
    MarketStructureProfile,
    MarketStructureQualityReport,
    PreparedDataset,
    ResearchProfileSnapshot,
    ResearchReport,
    ResearchResourceLimits,
    ResearchScorecard,
    ResearchWarning,
    SessionConfig,
    StatisticalConfig,
    StudyConfig,
    TimeSplitResult,
    UnsupervisedResearchConfig,
    UnsupervisedResearchResult,
)
from app.services.research.profiles import run_edge_lab_profile

__all__ = (
    "PUBLIC_API_CLASSIFICATIONS",
    "ArtifactReference",
    "ArtifactWriteConfig",
    "CleaningConfig",
    "CoreMetricProfile",
    "DataQualityReport",
    "EdgeLabConfig",
    "EdgeResult",
    "EnrichmentConfig",
    "FeatureConfig",
    "LeakageReport",
    "MarketStructureConfig",
    "MarketStructureProfile",
    "MarketStructureQualityReport",
    "PreparedDataset",
    "ResearchProfileSnapshot",
    "ResearchReport",
    "ResearchResourceLimits",
    "ResearchScorecard",
    "ResearchWarning",
    "SessionConfig",
    "StatisticalConfig",
    "StudyConfig",
    "TimeSplitResult",
    "UnsupervisedResearchConfig",
    "UnsupervisedResearchResult",
    "run_edge_lab_profile",
)
