"""Function-only public boundary for the Research domain."""

from collections.abc import Mapping
from typing import Literal

from app.services.research.artifacts import (
    build_candidate_profile,
    build_research_migration_request,
    build_scenario_evidence_port,
    parse_candidate_profile,
    record_expectancy_review_evidence,
    write_research_artifact,
)
from app.services.research.contracts.evidence_fields import (
    build_research_source_classification,
    parse_research_source_classification,
)
from app.services.research.contracts.factories import (
    create_research_metric_registry,
    create_research_value,
    execute_research_value_operation,
    get_research_value_field,
    is_research_metric_calculator,
    is_research_value,
    project_research_value,
)
from app.services.research.data import (
    clean_dataset,
    enrich_dataset,
    prepare_research_dataset,
    project_point_in_time_evidence,
    validate_dataset,
)
from app.services.research.drift import (
    build_performance_drift_evidence,
    monitor_performance_drift,
    parse_performance_drift_evidence,
    propose_drift_suspension,
)
from app.services.research.expectancy import (
    apply_expectancy_transition,
    build_approved_expectancy_profile,
    build_expectancy_profile,
    evaluate_expectancy_eligibility,
    get_min_reward_risk_override,
    is_governance_transition_permitted,
    load_eligible_expectancy_profile,
    load_expectancy_profile,
    parse_approved_expectancy_profile,
    persist_expectancy_profile,
    transition_expectancy_governance,
)
from app.services.research.features import (
    build_research_feature_frame,
    forward_max_adverse_excursion,
    forward_max_favorable_excursion,
    forward_returns,
    hurst_exponent,
    log_returns,
    rolling_hurst,
    simple_returns,
)
from app.services.research.intelligence import (
    assess_intelligence_applicability,
    build_fundamental_source_evidence,
    build_sentiment_source_evidence,
    project_intelligence_evidence,
)
from app.services.research.leakage import (
    enforce_time_split,
    mask_research_artifact,
    validate_no_lookahead_features,
)
from app.services.research.market_structure import (
    build_market_assumption_evidence,
    build_market_structure_profile,
    build_strategy_fit,
    build_validation_summary,
    calibrate_market_structure,
    evaluate_market_structure_quality,
    label_realized_market_behavior,
    parse_market_assumption_evidence,
)
from app.services.research.metrics import (
    build_core_metric_profile,
    build_default_registry,
)
from app.services.research.modeling import (
    analyze_cluster_outperformance,
    attach_cluster_labels,
    build_unsupervised_insight_report,
    cluster_feature_space,
    identify_pca_risk_factors,
    run_pca,
    run_unsupervised_research,
    summarize_investment_data,
)
from app.services.research.profiles import (
    build_dashboard_summary,
    build_profile_summary,
    build_research_profile_snapshot,
    build_research_scorecard,
    compare_research_profiles,
    generate_multi_symbol_report,
    render_profile_comparison,
    render_research_report,
    run_edge_lab_profile,
)
from app.services.research.seasonality import (
    active_sessions_for_hour,
    run_seasonality,
    session_hours_payload,
    session_label_for_hour,
    tag_sessions,
)
from app.services.research.statistics import (
    benjamini_hochberg,
    block_bootstrap_ci,
    block_bootstrap_distribution,
    compute_null_percentile,
    exceeds_null_threshold,
    holm_bonferroni,
    null_distribution_stats,
    permutation_test,
    r_space_null,
    random_entry_null,
    session_randomized_null,
    shuffle_returns_null,
)
from app.services.research.stress_evidence import (
    build_stress_scenario_evidence,
    parse_stress_scenario_evidence,
    validate_shock_basis,
)
from app.services.research.studies import (
    build_strategy_evidence_bundle,
    classify_symbol,
    compare_to_null,
    get_acceptance_criteria,
    parse_strategy_evidence_bundle,
    run_eds_mean_reversion,
    run_eds_null_baseline,
    run_eds_session,
    run_eds_trend_persistence,
)


def get_public_api_classifications() -> Mapping[str, Literal["stable"]]:
    """Return the immutable Research public API classification map."""
    from app.services.research.contracts import PUBLIC_API_CLASSIFICATIONS

    return PUBLIC_API_CLASSIFICATIONS


__all__ = (
    "active_sessions_for_hour",
    "analyze_cluster_outperformance",
    "apply_expectancy_transition",
    "assess_intelligence_applicability",
    "attach_cluster_labels",
    "benjamini_hochberg",
    "block_bootstrap_ci",
    "block_bootstrap_distribution",
    "build_approved_expectancy_profile",
    "build_candidate_profile",
    "build_core_metric_profile",
    "build_dashboard_summary",
    "build_default_registry",
    "build_expectancy_profile",
    "build_fundamental_source_evidence",
    "build_market_assumption_evidence",
    "build_market_structure_profile",
    "build_performance_drift_evidence",
    "build_profile_summary",
    "build_research_feature_frame",
    "build_research_migration_request",
    "build_research_profile_snapshot",
    "build_research_scorecard",
    "build_research_source_classification",
    "build_scenario_evidence_port",
    "build_sentiment_source_evidence",
    "build_strategy_evidence_bundle",
    "build_strategy_fit",
    "build_stress_scenario_evidence",
    "build_unsupervised_insight_report",
    "build_validation_summary",
    "calibrate_market_structure",
    "classify_symbol",
    "clean_dataset",
    "cluster_feature_space",
    "compare_research_profiles",
    "compare_to_null",
    "compute_null_percentile",
    "create_research_metric_registry",
    "create_research_value",
    "enforce_time_split",
    "enrich_dataset",
    "evaluate_expectancy_eligibility",
    "evaluate_market_structure_quality",
    "exceeds_null_threshold",
    "execute_research_value_operation",
    "forward_max_adverse_excursion",
    "forward_max_favorable_excursion",
    "forward_returns",
    "generate_multi_symbol_report",
    "get_acceptance_criteria",
    "get_min_reward_risk_override",
    "get_public_api_classifications",
    "get_research_value_field",
    "holm_bonferroni",
    "hurst_exponent",
    "identify_pca_risk_factors",
    "is_governance_transition_permitted",
    "is_research_metric_calculator",
    "is_research_value",
    "label_realized_market_behavior",
    "load_eligible_expectancy_profile",
    "load_expectancy_profile",
    "log_returns",
    "mask_research_artifact",
    "monitor_performance_drift",
    "null_distribution_stats",
    "parse_approved_expectancy_profile",
    "parse_candidate_profile",
    "parse_market_assumption_evidence",
    "parse_performance_drift_evidence",
    "parse_research_source_classification",
    "parse_strategy_evidence_bundle",
    "parse_stress_scenario_evidence",
    "permutation_test",
    "persist_expectancy_profile",
    "prepare_research_dataset",
    "project_intelligence_evidence",
    "project_point_in_time_evidence",
    "project_research_value",
    "propose_drift_suspension",
    "r_space_null",
    "random_entry_null",
    "record_expectancy_review_evidence",
    "render_profile_comparison",
    "render_research_report",
    "rolling_hurst",
    "run_edge_lab_profile",
    "run_eds_mean_reversion",
    "run_eds_null_baseline",
    "run_eds_session",
    "run_eds_trend_persistence",
    "run_pca",
    "run_seasonality",
    "run_unsupervised_research",
    "session_hours_payload",
    "session_label_for_hour",
    "session_randomized_null",
    "shuffle_returns_null",
    "simple_returns",
    "summarize_investment_data",
    "tag_sessions",
    "transition_expectancy_governance",
    "validate_dataset",
    "validate_no_lookahead_features",
    "validate_shock_basis",
    "write_research_artifact",
)
