# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from typing import Final

ERR_FTP_SEND_FAILED: Final[int] = 4514
ERR_FTP_NOSERVER: Final[int] = 4519
ERR_FTP_NOLOGIN: Final[int] = 4520
ERR_FTP_FILE_ERROR: Final[int] = 4521
ERR_FTP_CONNECT_FAILED: Final[int] = 4522
ERR_FTP_CHANGEDIR: Final[int] = 4523
ERR_TOO_MANY_FILES: Final[int] = 5001
ERR_WRONG_FILENAME: Final[int] = 5002
ERR_TOO_LONG_FILENAME: Final[int] = 5003
ERR_CANNOT_OPEN_FILE: Final[int] = 5004
ERR_FILE_CACHEBUFFER_ERROR: Final[int] = 5005
ERR_CANNOT_DELETE_FILE: Final[int] = 5006
ERR_INVALID_FILEHANDLE: Final[int] = 5007
ERR_WRONG_FILEHANDLE: Final[int] = 5008
ERR_FILE_NOTTOWRITE: Final[int] = 5009
ERR_FILE_NOTTOREAD: Final[int] = 5010
ERR_FILE_NOTBIN: Final[int] = 5011
ERR_FILE_NOTTXT: Final[int] = 5012
ERR_FILE_NOTTXTORCSV: Final[int] = 5013
ERR_FILE_NOTCSV: Final[int] = 5014
ERR_FILE_READERROR: Final[int] = 5015
ERR_FILE_BINSTRINGSIZE: Final[int] = 5016
ERR_INCOMPATIBLE_FILE: Final[int] = 5017
ERR_FILE_IS_DIRECTORY: Final[int] = 5018
ERR_FILE_NOT_EXIST: Final[int] = 5019
ERR_FILE_CANNOT_REWRITE: Final[int] = 5020
ERR_WRONG_DIRECTORYNAME: Final[int] = 5021
ERR_DIRECTORY_NOT_EXIST: Final[int] = 5022
ERR_FILE_ISNOT_DIRECTORY: Final[int] = 5023
ERR_CANNOT_DELETE_DIRECTORY: Final[int] = 5024
ERR_CANNOT_CLEAN_DIRECTORY: Final[int] = 5025
ERR_FILE_WRITEERROR: Final[int] = 5026
ERR_FILE_ENDOFFILE: Final[int] = 5027
ERR_WEBREQUEST_INVALID_ADDRESS: Final[int] = 5200
ERR_WEBREQUEST_CONNECT_FAILED: Final[int] = 5201
ERR_WEBREQUEST_TIMEOUT: Final[int] = 5202
ERR_WEBREQUEST_REQUEST_FAILED: Final[int] = 5203
ERR_NETSOCKET_INVALIDHANDLE: Final[int] = 5270
ERR_NETSOCKET_TOO_MANY_OPENED: Final[int] = 5271
ERR_NETSOCKET_CANNOT_CONNECT: Final[int] = 5272
ERR_NETSOCKET_IO_ERROR: Final[int] = 5273
ERR_NETSOCKET_HANDSHAKE_FAILED: Final[int] = 5274
ERR_NETSOCKET_NO_CERTIFICATE: Final[int] = 5275

__all__ = [
    "ERR_CANNOT_CLEAN_DIRECTORY",
    "ERR_CANNOT_DELETE_DIRECTORY",
    "ERR_CANNOT_DELETE_FILE",
    "ERR_CANNOT_OPEN_FILE",
    "ERR_DIRECTORY_NOT_EXIST",
    "ERR_FILE_BINSTRINGSIZE",
    "ERR_FILE_CACHEBUFFER_ERROR",
    "ERR_FILE_CANNOT_REWRITE",
    "ERR_FILE_ENDOFFILE",
    "ERR_FILE_IS_DIRECTORY",
    "ERR_FILE_ISNOT_DIRECTORY",
    "ERR_FILE_NOT_EXIST",
    "ERR_FILE_NOTBIN",
    "ERR_FILE_NOTCSV",
    "ERR_FILE_NOTTOREAD",
    "ERR_FILE_NOTTOWRITE",
    "ERR_FILE_NOTTXT",
    "ERR_FILE_NOTTXTORCSV",
    "ERR_FILE_READERROR",
    "ERR_FILE_WRITEERROR",
    "ERR_FTP_CHANGEDIR",
    "ERR_FTP_CONNECT_FAILED",
    "ERR_FTP_FILE_ERROR",
    "ERR_FTP_NOLOGIN",
    "ERR_FTP_NOSERVER",
    "ERR_FTP_SEND_FAILED",
    "ERR_INCOMPATIBLE_FILE",
    "ERR_INVALID_FILEHANDLE",
    "ERR_NETSOCKET_CANNOT_CONNECT",
    "ERR_NETSOCKET_HANDSHAKE_FAILED",
    "ERR_NETSOCKET_INVALIDHANDLE",
    "ERR_NETSOCKET_IO_ERROR",
    "ERR_NETSOCKET_NO_CERTIFICATE",
    "ERR_NETSOCKET_TOO_MANY_OPENED",
    "ERR_TOO_LONG_FILENAME",
    "ERR_TOO_MANY_FILES",
    "ERR_WEBREQUEST_CONNECT_FAILED",
    "ERR_WEBREQUEST_INVALID_ADDRESS",
    "ERR_WEBREQUEST_REQUEST_FAILED",
    "ERR_WEBREQUEST_TIMEOUT",
    "ERR_WRONG_DIRECTORYNAME",
    "ERR_WRONG_FILEHANDLE",
    "ERR_WRONG_FILENAME",
]
