# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from enum import IntEnum
from typing import Final


class ENUM_CRYPT_METHOD(IntEnum):
    """
    Defines the identifier set for crypt method. HaruQuantAI adds managed I/O

    and explicit security policy.
    """

    CRYPT_BASE64 = 0
    CRYPT_AES128 = 1
    CRYPT_AES256 = 2
    CRYPT_HASH_SHA256 = 5
    CRYPT_ARCH_ZIP = 7


CRYPT_BASE64: Final = ENUM_CRYPT_METHOD.CRYPT_BASE64
CRYPT_AES128: Final = ENUM_CRYPT_METHOD.CRYPT_AES128
CRYPT_AES256: Final = ENUM_CRYPT_METHOD.CRYPT_AES256
CRYPT_HASH_SHA256: Final = ENUM_CRYPT_METHOD.CRYPT_HASH_SHA256
CRYPT_ARCH_ZIP: Final = ENUM_CRYPT_METHOD.CRYPT_ARCH_ZIP


class ENUM_FILE_POSITION(IntEnum):
    """Defines the identifier set for file position."""

    SEEK_SET = 0
    SEEK_CUR = 1
    SEEK_END = 2


SEEK_SET: Final = ENUM_FILE_POSITION.SEEK_SET
SEEK_CUR: Final = ENUM_FILE_POSITION.SEEK_CUR
SEEK_END: Final = ENUM_FILE_POSITION.SEEK_END


class ENUM_FILE_PROPERTY_INTEGER(IntEnum):
    """Defines the identifier set for file property integer."""

    FILE_EXISTS = 0
    FILE_CREATE_DATE = 1
    FILE_MODIFY_DATE = 2
    FILE_ACCESS_DATE = 3
    FILE_SIZE = 4
    FILE_POSITION = 5
    FILE_END = 6
    FILE_LINE_END = 7
    FILE_IS_COMMON = 8
    FILE_IS_TEXT = 9
    FILE_IS_BINARY = 10
    FILE_IS_CSV = 11
    FILE_IS_ANSI = 12
    FILE_IS_READABLE = 13
    FILE_IS_WRITABLE = 14


FILE_EXISTS: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_EXISTS
FILE_CREATE_DATE: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_CREATE_DATE
FILE_MODIFY_DATE: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_MODIFY_DATE
FILE_ACCESS_DATE: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_ACCESS_DATE
FILE_SIZE: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_SIZE
FILE_POSITION: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_POSITION
FILE_END: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_END
FILE_LINE_END: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_LINE_END
FILE_IS_COMMON: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_IS_COMMON
FILE_IS_TEXT: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_IS_TEXT
FILE_IS_BINARY: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_IS_BINARY
FILE_IS_CSV: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_IS_CSV
FILE_IS_ANSI: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_IS_ANSI
FILE_IS_READABLE: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_IS_READABLE
FILE_IS_WRITABLE: Final = ENUM_FILE_PROPERTY_INTEGER.FILE_IS_WRITABLE

FILE_READ: Final[int] = 1
FILE_WRITE: Final[int] = 2
FILE_BIN: Final[int] = 4
FILE_CSV: Final[int] = 8
FILE_TXT: Final[int] = 16
FILE_ANSI: Final[int] = 32
FILE_UNICODE: Final[int] = 64
FILE_SHARE_READ: Final[int] = 128
FILE_SHARE_WRITE: Final[int] = 256
FILE_REWRITE: Final[int] = 512
FILE_SHARED: Final[int] = 4096
CP_UTF8: Final[int] = 65001

__all__ = [
    "CP_UTF8",
    "CRYPT_AES128",
    "CRYPT_AES256",
    "CRYPT_ARCH_ZIP",
    "CRYPT_BASE64",
    "CRYPT_HASH_SHA256",
    "ENUM_CRYPT_METHOD",
    "ENUM_FILE_POSITION",
    "ENUM_FILE_PROPERTY_INTEGER",
    "FILE_ACCESS_DATE",
    "FILE_ANSI",
    "FILE_BIN",
    "FILE_CREATE_DATE",
    "FILE_CSV",
    "FILE_END",
    "FILE_EXISTS",
    "FILE_IS_ANSI",
    "FILE_IS_BINARY",
    "FILE_IS_COMMON",
    "FILE_IS_CSV",
    "FILE_IS_READABLE",
    "FILE_IS_TEXT",
    "FILE_IS_WRITABLE",
    "FILE_LINE_END",
    "FILE_MODIFY_DATE",
    "FILE_POSITION",
    "FILE_READ",
    "FILE_REWRITE",
    "FILE_SHARE_READ",
    "FILE_SHARE_WRITE",
    "FILE_SHARED",
    "FILE_SIZE",
    "FILE_TXT",
    "FILE_UNICODE",
    "FILE_WRITE",
    "SEEK_CUR",
    "SEEK_END",
    "SEEK_SET",
]
