import { useMemo, useState } from 'react';
import { Button, Field, Modal, Select, TextInput } from '../../../components/ui';
import { activeExternalLines, builtInExternalFormats, detectExternalFormat, externalDateFormats, externalPreview, externalSeparators, readExternalFile, type ExternalColumnType, type ExternalImportFormat, type ExternalIndicatorDefinition } from './externalIndicators';
import { useExternalIndicators } from './externalIndicatorsStore';
import './externalIndicators.css';

const copyFormat = (format: ExternalImportFormat): ExternalImportFormat => structuredClone(format);
export function ExternalIndicatorImportDialog({ item, externalActive, onClose, onStarted }: { item: ExternalIndicatorDefinition; externalActive: boolean; onClose: () => void; onStarted: () => void }) {
  const store = useExternalIndicators(); const count = activeExternalLines(item).length;
  const formats = [...builtInExternalFormats, ...store.formats]; const [format, setFormat] = useState<ExternalImportFormat>(() => copyFormat(builtInExternalFormats[0])); const [file, setFile] = useState<File | null>(null); const [text, setText] = useState(''); const [ignoreErrors, setIgnoreErrors] = useState(false); const [error, setError] = useState(''); const [newName, setNewName] = useState(''); const [nested, setNested] = useState<'save-as' | 'delete' | null>(null);
  const preview = useMemo(() => { try { return text ? externalPreview(text, format).slice(0, 12) : []; } catch { return []; } }, [text, format]);
  const maxColumns = Math.max(format.columns.length, ...preview.map(row => row.length), 0); const options: ExternalColumnType[] = ['', 'Date', 'Time', 'Date & Time', 'Unused', ...Array.from({ length: count }, (_, i): ExternalColumnType => `Value ${i + 1}`)];
  function chooseFormat(name: string): void { const found = formats.find(item => item.name === name); if (found) setFormat(copyFormat(found)); }
  async function choose(next: File | null): Promise<void> { setFile(next); setText(''); setError(''); if (!next) return; try { const value = await readExternalFile(next); setText(value); setFormat(detectExternalFormat(value, count)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to read data file.'); } }
  async function saveAs(): Promise<void> { try { await store.saveFormat({ ...format, name: newName, predefined: false }); setFormat(current => ({ ...current, name: newName.trim(), predefined: false })); setNested(null); setNewName(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save data format.'); } }
  async function saveCurrent(): Promise<void> { try { await store.saveFormat({ ...format, predefined: false }, true); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save data format.'); } }
  async function removeFormat(): Promise<void> { try { await store.deleteFormat(format.name); setFormat(copyFormat(builtInExternalFormats[0])); setNested(null); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to delete data format.'); } }
  async function start(): Promise<void> { try { if (!file || !text) throw new Error('Choose a data file.'); await store.startImport(item.name, text, format, ignoreErrors, externalActive); onStarted(); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to import indicator data.'); } }
  if (nested === 'save-as') return <div className="external-flow"><Modal title="New data format" width={520} onClose={() => setNested(null)} footer={<><Button onClick={() => setNested(null)}>Close</Button><Button className="primary" onClick={saveAs}>Save</Button></>}><fieldset><p className="external-note">Enter the name of the new data format</p><Field label="Name"><TextInput aria-label="Format name" value={newName} maxLength={80} onChange={event => setNewName(event.target.value)}/></Field></fieldset>{error && <p className="external-error" role="alert">{error}</p>}</Modal></div>;
  if (nested === 'delete') return <div className="external-flow"><Modal title="Delete data format" width={520} onClose={() => setNested(null)} footer={<><Button onClick={() => setNested(null)}>Close</Button><Button className="danger" onClick={removeFormat}>Delete</Button></>}><p>Do you want to delete data format '{format.name}'?</p></Modal></div>;
  return <div className="external-flow"><Modal title={`Custom data import for '${item.name}'`} width={780} onClose={onClose} footer={<><Button onClick={onClose}>Close</Button><Button className="primary" onClick={start}>Start Import</Button></>}>
    {(error || store.storageError) && <p className="external-error" role="alert">{error || store.storageError}</p>}
    <fieldset><legend>Choose file</legend><Field label="Data file"><input className="file-input compact" aria-label="Data file" type="file" accept=".csv,.tsv,.txt,text/csv,text/plain" onChange={event => void choose(event.target.files?.[0] ?? null)}/></Field></fieldset>
    <fieldset><legend>File format</legend>
      <div className="external-format-head"><Field label="Predefined file format"><Select value={formats.some(item => item.name === format.name) ? format.name : 'Custom'} onChange={chooseFormat}>{formats.map(item => <option key={item.name}>{item.name}</option>)}</Select></Field><div className="external-format-actions"><Button disabled={format.predefined} onClick={saveCurrent}>Save</Button><Button onClick={() => { setError(''); setNested('save-as'); }}>Save as</Button><Button disabled={format.predefined || !store.formats.some(item => item.name === format.name)} onClick={() => setNested('delete')}>Delete</Button></div></div>
      <div className="external-format-grid"><Field label="Skip rows"><TextInput aria-label="Skip rows" type="number" min={0} max={1000} value={format.skipRows} onChange={event => setFormat(current => ({ ...current, skipRows: Number(event.target.value) }))}/></Field><Field label="Skip columns"><TextInput aria-label="Skip columns" type="number" min={0} max={100} value={format.skipColumns} onChange={event => setFormat(current => ({ ...current, skipColumns: Number(event.target.value) }))}/></Field><Field label="Separator"><Select value={format.separator} onChange={value => setFormat(current => ({ ...current, separator: value }))}>{externalSeparators.map(item => <option key={item.label} value={item.value}>{item.label}</option>)}</Select></Field><Field label="Date format"><TextInput aria-label="Date format" list="external-date-formats" value={format.dateFormat} onChange={event => setFormat(current => ({ ...current, dateFormat: event.target.value }))}/></Field><datalist id="external-date-formats">{externalDateFormats.map(value => <option key={value} value={value}/>)}</datalist></div>
      <div className="external-errors"><strong>Data errors handling</strong><label><input type="radio" name="external-errors" checked={!ignoreErrors} onChange={() => setIgnoreErrors(false)}/> Stop import</label><label><input type="radio" name="external-errors" checked={ignoreErrors} onChange={() => setIgnoreErrors(true)}/> Ignore lines with errors</label></div>
      <div className="external-preview"><table className="plain-table" aria-label="Indicator import preview"><thead><tr>{Array.from({ length: maxColumns }, (_, index) => <th key={index}><Select value={format.columns[index] ?? ''} onChange={value => setFormat(current => { const columns = [...current.columns]; columns[index] = value as ExternalColumnType; return { ...current, columns }; })}>{options.map((value, optionIndex) => <option key={`${value}-${optionIndex}`} value={value}>{value || 'Choose type...'}</option>)}</Select></th>)}</tr></thead><tbody>{preview.map((row, index) => <tr key={index}>{Array.from({ length: maxColumns }, (_, column) => <td key={column}>{row[column] ?? ''}</td>)}</tr>)}{!preview.length && <tr><td colSpan={Math.max(1, maxColumns)}>No data available.</td></tr>}</tbody></table></div>
    </fieldset>
  </Modal></div>;
}
