"""Public immutable contracts for the Research domain."""

from app.services.research.contracts.api import PUBLIC_API_CLASSIFICATIONS
from app.services.research.contracts.configurations import (
    ArtifactWriteConfig,
    CleaningConfig,
    EdgeLabConfig,
    EnrichmentConfig,
    FeatureConfig,
    MarketStructureConfig,
    ResearchResourceLimits,
    SessionConfig,
    StatisticalConfig,
    StudyConfig,
    UnsupervisedResearchConfig,
)
from app.services.research.contracts.results import (
    ArtifactReference,
    CoreMetricProfile,
    DataQualityReport,
    EdgeResult,
    LeakageReport,
    MarketStructureProfile,
    MarketStructureQualityReport,
    PreparedDataset,
    ResearchProfileSnapshot,
    ResearchReport,
    ResearchScorecard,
    ResearchWarning,
    TimeSplitResult,
    UnsupervisedResearchResult,
)

__all__ = (
    "PUBLIC_API_CLASSIFICATIONS",
    "ArtifactReference",
    "ArtifactWriteConfig",
    "CleaningConfig",
    "CoreMetricProfile",
    "DataQualityReport",
    "EdgeLabConfig",
    "EdgeResult",
    "EnrichmentConfig",
    "FeatureConfig",
    "LeakageReport",
    "MarketStructureConfig",
    "MarketStructureProfile",
    "MarketStructureQualityReport",
    "PreparedDataset",
    "ResearchProfileSnapshot",
    "ResearchReport",
    "ResearchResourceLimits",
    "ResearchScorecard",
    "ResearchWarning",
    "SessionConfig",
    "StatisticalConfig",
    "StudyConfig",
    "TimeSplitResult",
    "UnsupervisedResearchConfig",
    "UnsupervisedResearchResult",
)
