"""Classifications for the implemented Research contract surface."""

from __future__ import annotations

from types import MappingProxyType
from typing import Literal

from app.utils import get_logger

logger = get_logger(__name__)

logger.debug("Defining implemented Research contract API classifications")

_RESEARCH_PUBLIC_CALLABLES = (
    "assess_intelligence_applicability",
    "build_fundamental_source_evidence",
    "build_sentiment_source_evidence",
    "create_research_metric_registry",
    "create_research_value",
    "execute_research_value_operation",
    "get_research_value_field",
    "is_research_metric_calculator",
    "is_research_value",
    "project_research_value",
    "project_intelligence_evidence",
    "get_public_api_classifications",
    "active_sessions_for_hour",
    "analyze_cluster_outperformance",
    "apply_expectancy_transition",
    "assess_intelligence_applicability",
    "attach_cluster_labels",
    "benjamini_hochberg",
    "block_bootstrap_ci",
    "block_bootstrap_distribution",
    "build_approved_expectancy_profile",
    "build_candidate_profile",
    "build_core_metric_profile",
    "build_dashboard_summary",
    "build_default_registry",
    "build_expectancy_profile",
    "build_reasoned_stress_shock",
    "build_risk_expectancy_provider",
    "build_strategy_expectancy_provider",
    "build_stress_calibration_provider",
    "build_fundamental_source_evidence",
    "build_market_assumption_evidence",
    "build_market_structure_profile",
    "build_performance_drift_evidence",
    "build_profile_summary",
    "build_research_feature_frame",
    "build_research_migration_request",
    "build_research_profile_snapshot",
    "build_research_scorecard",
    "build_research_source_classification",
    "build_scenario_evidence_port",
    "build_sentiment_source_evidence",
    "build_strategy_evidence_bundle",
    "build_strategy_fit",
    "build_stress_scenario_evidence",
    "build_unsupervised_insight_report",
    "build_validation_summary",
    "calibrate_market_structure",
    "classify_symbol",
    "clean_dataset",
    "cluster_feature_space",
    "compare_research_profiles",
    "compare_to_null",
    "compute_null_percentile",
    "create_research_metric_registry",
    "create_research_value",
    "enforce_time_split",
    "enrich_dataset",
    "derive_historical_stress_shock",
    "evaluate_expectancy_eligibility",
    "evaluate_market_structure_quality",
    "exceeds_null_threshold",
    "execute_research_value_operation",
    "forward_max_adverse_excursion",
    "forward_max_favorable_excursion",
    "forward_returns",
    "generate_multi_symbol_report",
    "get_acceptance_criteria",
    "get_min_reward_risk_override",
    "get_public_api_classifications",
    "get_research_value_field",
    "holm_bonferroni",
    "hurst_exponent",
    "identify_pca_risk_factors",
    "is_governance_transition_permitted",
    "is_research_metric_calculator",
    "is_research_value",
    "label_realized_market_behavior",
    "load_eligible_expectancy_profile",
    "load_expectancy_profile",
    "load_latest_performance_drift_evidence",
    "load_latest_stress_scenario_evidence",
    "log_returns",
    "mask_research_artifact",
    "monitor_performance_drift",
    "null_distribution_stats",
    "parse_approved_expectancy_profile",
    "parse_candidate_profile",
    "parse_market_assumption_evidence",
    "parse_performance_drift_evidence",
    "parse_research_source_classification",
    "parse_stress_scenario_evidence",
    "parse_strategy_evidence_bundle",
    "permutation_test",
    "persist_expectancy_profile",
    "persist_performance_drift_evidence",
    "persist_stress_scenario_evidence",
    "prepare_research_dataset",
    "project_intelligence_evidence",
    "project_point_in_time_evidence",
    "project_research_value",
    "propose_drift_suspension",
    "random_entry_null",
    "record_expectancy_review_evidence",
    "render_profile_comparison",
    "render_research_report",
    "rolling_hurst",
    "run_edge_lab_profile",
    "run_eds_mean_reversion",
    "run_eds_null_baseline",
    "run_eds_session",
    "run_eds_trend_persistence",
    "run_pca",
    "run_seasonality",
    "run_unsupervised_research",
    "r_space_null",
    "session_hours_payload",
    "session_label_for_hour",
    "session_randomized_null",
    "shuffle_returns_null",
    "simple_returns",
    "summarize_investment_data",
    "tag_sessions",
    "transition_expectancy_governance",
    "validate_dataset",
    "validate_no_lookahead_features",
    "validate_shock_basis",
    "write_research_artifact",
)

PUBLIC_API_CLASSIFICATIONS: MappingProxyType[str, Literal["stable"]] = MappingProxyType(
    dict.fromkeys(_RESEARCH_PUBLIC_CALLABLES, "stable")
)

__all__ = ("PUBLIC_API_CLASSIFICATIONS",)
