# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from enum import IntEnum
from typing import Final


class ENUM_STATISTICS(IntEnum):
    """Defines the identifier set for statistics."""

    STAT_INITIAL_DEPOSIT = 0
    STAT_WITHDRAWAL = 1
    STAT_PROFIT = 2
    STAT_GROSS_PROFIT = 3
    STAT_GROSS_LOSS = 4
    STAT_MAX_PROFITTRADE = 5
    STAT_MAX_LOSSTRADE = 6
    STAT_CONPROFITMAX = 7
    STAT_CONPROFITMAX_TRADES = 8
    STAT_MAX_CONWINS = 9
    STAT_MAX_CONPROFIT_TRADES = 10
    STAT_CONLOSSMAX = 11
    STAT_CONLOSSMAX_TRADES = 12
    STAT_MAX_CONLOSSES = 13
    STAT_MAX_CONLOSS_TRADES = 14
    STAT_BALANCEMIN = 15
    STAT_BALANCE_DD = 16
    STAT_BALANCEDD_PERCENT = 17
    STAT_BALANCE_DDREL_PERCENT = 18
    STAT_BALANCE_DD_RELATIVE = 19
    STAT_EQUITYMIN = 20
    STAT_EQUITY_DD = 21
    STAT_EQUITYDD_PERCENT = 22
    STAT_EQUITY_DDREL_PERCENT = 23
    STAT_EQUITY_DD_RELATIVE = 24
    STAT_EXPECTED_PAYOFF = 25
    STAT_PROFIT_FACTOR = 26
    STAT_RECOVERY_FACTOR = 27
    STAT_SHARPE_RATIO = 28
    STAT_MIN_MARGINLEVEL = 29
    STAT_CUSTOM_ONTESTER = 30
    STAT_DEALS = 31
    STAT_TRADES = 32
    STAT_PROFIT_TRADES = 33
    STAT_LOSS_TRADES = 34
    STAT_SHORT_TRADES = 35
    STAT_LONG_TRADES = 36
    STAT_PROFIT_SHORTTRADES = 37
    STAT_PROFIT_LONGTRADES = 38
    STAT_PROFITTRADES_AVGCON = 39
    STAT_LOSSTRADES_AVGCON = 40
    STAT_COMPLEX_CRITERION = 41


STAT_INITIAL_DEPOSIT: Final = ENUM_STATISTICS.STAT_INITIAL_DEPOSIT
STAT_WITHDRAWAL: Final = ENUM_STATISTICS.STAT_WITHDRAWAL
STAT_PROFIT: Final = ENUM_STATISTICS.STAT_PROFIT
STAT_GROSS_PROFIT: Final = ENUM_STATISTICS.STAT_GROSS_PROFIT
STAT_GROSS_LOSS: Final = ENUM_STATISTICS.STAT_GROSS_LOSS
STAT_MAX_PROFITTRADE: Final = ENUM_STATISTICS.STAT_MAX_PROFITTRADE
STAT_MAX_LOSSTRADE: Final = ENUM_STATISTICS.STAT_MAX_LOSSTRADE
STAT_CONPROFITMAX: Final = ENUM_STATISTICS.STAT_CONPROFITMAX
STAT_CONPROFITMAX_TRADES: Final = ENUM_STATISTICS.STAT_CONPROFITMAX_TRADES
STAT_MAX_CONWINS: Final = ENUM_STATISTICS.STAT_MAX_CONWINS
STAT_MAX_CONPROFIT_TRADES: Final = ENUM_STATISTICS.STAT_MAX_CONPROFIT_TRADES
STAT_CONLOSSMAX: Final = ENUM_STATISTICS.STAT_CONLOSSMAX
STAT_CONLOSSMAX_TRADES: Final = ENUM_STATISTICS.STAT_CONLOSSMAX_TRADES
STAT_MAX_CONLOSSES: Final = ENUM_STATISTICS.STAT_MAX_CONLOSSES
STAT_MAX_CONLOSS_TRADES: Final = ENUM_STATISTICS.STAT_MAX_CONLOSS_TRADES
STAT_BALANCEMIN: Final = ENUM_STATISTICS.STAT_BALANCEMIN
STAT_BALANCE_DD: Final = ENUM_STATISTICS.STAT_BALANCE_DD
STAT_BALANCEDD_PERCENT: Final = ENUM_STATISTICS.STAT_BALANCEDD_PERCENT
STAT_BALANCE_DDREL_PERCENT: Final = ENUM_STATISTICS.STAT_BALANCE_DDREL_PERCENT
STAT_BALANCE_DD_RELATIVE: Final = ENUM_STATISTICS.STAT_BALANCE_DD_RELATIVE
STAT_EQUITYMIN: Final = ENUM_STATISTICS.STAT_EQUITYMIN
STAT_EQUITY_DD: Final = ENUM_STATISTICS.STAT_EQUITY_DD
STAT_EQUITYDD_PERCENT: Final = ENUM_STATISTICS.STAT_EQUITYDD_PERCENT
STAT_EQUITY_DDREL_PERCENT: Final = ENUM_STATISTICS.STAT_EQUITY_DDREL_PERCENT
STAT_EQUITY_DD_RELATIVE: Final = ENUM_STATISTICS.STAT_EQUITY_DD_RELATIVE
STAT_EXPECTED_PAYOFF: Final = ENUM_STATISTICS.STAT_EXPECTED_PAYOFF
STAT_PROFIT_FACTOR: Final = ENUM_STATISTICS.STAT_PROFIT_FACTOR
STAT_RECOVERY_FACTOR: Final = ENUM_STATISTICS.STAT_RECOVERY_FACTOR
STAT_SHARPE_RATIO: Final = ENUM_STATISTICS.STAT_SHARPE_RATIO
STAT_MIN_MARGINLEVEL: Final = ENUM_STATISTICS.STAT_MIN_MARGINLEVEL
STAT_CUSTOM_ONTESTER: Final = ENUM_STATISTICS.STAT_CUSTOM_ONTESTER
STAT_DEALS: Final = ENUM_STATISTICS.STAT_DEALS
STAT_TRADES: Final = ENUM_STATISTICS.STAT_TRADES
STAT_PROFIT_TRADES: Final = ENUM_STATISTICS.STAT_PROFIT_TRADES
STAT_LOSS_TRADES: Final = ENUM_STATISTICS.STAT_LOSS_TRADES
STAT_SHORT_TRADES: Final = ENUM_STATISTICS.STAT_SHORT_TRADES
STAT_LONG_TRADES: Final = ENUM_STATISTICS.STAT_LONG_TRADES
STAT_PROFIT_SHORTTRADES: Final = ENUM_STATISTICS.STAT_PROFIT_SHORTTRADES
STAT_PROFIT_LONGTRADES: Final = ENUM_STATISTICS.STAT_PROFIT_LONGTRADES
STAT_PROFITTRADES_AVGCON: Final = ENUM_STATISTICS.STAT_PROFITTRADES_AVGCON
STAT_LOSSTRADES_AVGCON: Final = ENUM_STATISTICS.STAT_LOSSTRADES_AVGCON
STAT_COMPLEX_CRITERION: Final = ENUM_STATISTICS.STAT_COMPLEX_CRITERION

__all__ = [
    "ENUM_STATISTICS",
    "STAT_BALANCE_DD",
    "STAT_BALANCE_DD_RELATIVE",
    "STAT_BALANCE_DDREL_PERCENT",
    "STAT_BALANCEDD_PERCENT",
    "STAT_BALANCEMIN",
    "STAT_COMPLEX_CRITERION",
    "STAT_CONLOSSMAX",
    "STAT_CONLOSSMAX_TRADES",
    "STAT_CONPROFITMAX",
    "STAT_CONPROFITMAX_TRADES",
    "STAT_CUSTOM_ONTESTER",
    "STAT_DEALS",
    "STAT_EQUITY_DD",
    "STAT_EQUITY_DD_RELATIVE",
    "STAT_EQUITY_DDREL_PERCENT",
    "STAT_EQUITYDD_PERCENT",
    "STAT_EQUITYMIN",
    "STAT_EXPECTED_PAYOFF",
    "STAT_GROSS_LOSS",
    "STAT_GROSS_PROFIT",
    "STAT_INITIAL_DEPOSIT",
    "STAT_LONG_TRADES",
    "STAT_LOSS_TRADES",
    "STAT_LOSSTRADES_AVGCON",
    "STAT_MAX_CONLOSS_TRADES",
    "STAT_MAX_CONLOSSES",
    "STAT_MAX_CONPROFIT_TRADES",
    "STAT_MAX_CONWINS",
    "STAT_MAX_LOSSTRADE",
    "STAT_MAX_PROFITTRADE",
    "STAT_MIN_MARGINLEVEL",
    "STAT_PROFIT",
    "STAT_PROFIT_FACTOR",
    "STAT_PROFIT_LONGTRADES",
    "STAT_PROFIT_SHORTTRADES",
    "STAT_PROFIT_TRADES",
    "STAT_PROFITTRADES_AVGCON",
    "STAT_RECOVERY_FACTOR",
    "STAT_SHARPE_RATIO",
    "STAT_SHORT_TRADES",
    "STAT_TRADES",
    "STAT_WITHDRAWAL",
]
