import { useEffect, useMemo, useRef, useState } from 'react';
import { createColumnHelper, flexRender, getCoreRowModel, useReactTable } from '@tanstack/react-table';
import { useVirtualizer } from '@tanstack/react-virtual';
import { Button, Field, Modal, Select, TextInput } from '../../../components/ui';
import { analyzeQuality, applyReviewMutation, availableReviewTimeframes, generateReviewRows, reviewKey, toolSessions, type ReviewRow, type ToolTarget } from './dataTools';
import { useDataTools } from './dataToolsStore';
import { DataReviewChart } from './DataReviewChart';
import './dataTools.css';

type Tab = 'data' | 'chart' | 'quality';
const column = createColumnHelper<ReviewRow>();

function ReviewGrid({ rows, tick, selected, changed, deleted, onSelect, onChange }: {
  rows: ReviewRow[]; tick: boolean; selected: string; changed: Record<string, Partial<ReviewRow>>; deleted: string[];
  onSelect: (id: string) => void; onChange: (id: string, key: keyof ReviewRow, value: number) => void;
}) {
  const editable = selected && Object.hasOwn(changed, selected); const fields = tick ? ['bid','ask','volume'] as const : ['open','high','low','close','volume'] as const;
  const columns = useMemo(() => [column.accessor('date', { header: 'Date', cell: info => new Date(info.getValue()).toLocaleString() }), ...fields.map(key => column.accessor(key, { header: key[0].toUpperCase() + key.slice(1), cell: info => editable && info.row.original.id === selected ? <input aria-label={`Edit ${key}`} type="number" step="any" value={Number(changed[selected]?.[key] ?? info.getValue())} onChange={event => onChange(selected, key, Number(event.target.value))}/> : info.getValue() }))], [changed, editable, fields, onChange, selected]);
  const table = useReactTable({ data: rows, columns, getCoreRowModel: getCoreRowModel() }); const parentRef = useRef<HTMLDivElement>(null); const tableRows = table.getRowModel().rows;
  const virtual = useVirtualizer({ count: tableRows.length, getScrollElement: () => parentRef.current, estimateSize: () => 28, overscan: 12 });
  useEffect(() => { const index = rows.findIndex(row => row.id === selected); if (index >= 0) virtual.scrollToIndex(index, { align: 'center' }); }, [rows, selected, virtual]);
  return <div className="review-virtual-table"><div className="review-grid-header" style={{ gridTemplateColumns: `180px repeat(${fields.length}, minmax(92px,1fr))` }}>{table.getHeaderGroups()[0].headers.map(header => <strong key={header.id}>{flexRender(header.column.columnDef.header, header.getContext())}</strong>)}</div>
    <div className="review-grid-scroll" ref={parentRef}><div style={{ height: virtual.getTotalSize(), position:'relative' }}>{virtual.getVirtualItems().map(item => { const row = tableRows[item.index]; return <button type="button" key={row.id} onClick={() => onSelect(row.original.id)} className={`${selected === row.original.id ? 'selected' : ''} ${deleted.includes(row.original.id) ? 'deleted' : ''} ${Object.hasOwn(changed, row.original.id) ? 'changed' : ''}`} style={{ transform:`translateY(${item.start}px)`, gridTemplateColumns:`180px repeat(${fields.length}, minmax(92px,1fr))` }}>{row.getVisibleCells().map(cell => <span key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</span>)}</button>; })}</div></div></div>;
}

export function ViewAnalyzeDialog({ target, externalActive, onClose }: { target: ToolTarget; externalActive: boolean; onClose: () => void }) {
  const store = useDataTools(); const frames = availableReviewTimeframes(target.timeframe); const [timeframe, setTimeframe] = useState(frames[0]); const [session, setSession] = useState<string>(toolSessions[0]); const [tab, setTab] = useState<Tab>('data');
  const [selected, setSelected] = useState(''); const [editing, setEditing] = useState<Record<string, Partial<ReviewRow>>>({}); const [deleted, setDeleted] = useState<string[]>([]); const [skipDate, setSkipDate] = useState(target.from); const [error, setError] = useState(''); const [discardOpen, setDiscardOpen] = useState(false);
  const key = reviewKey(target.id, timeframe, session); const baseRows = useMemo(() => generateReviewRows(target, timeframe, session), [target, timeframe, session]); const persisted = store.reviews[key];
  const visibleRows = useMemo(() => applyReviewMutation(baseRows, persisted), [baseRows, persisted]); const pendingRows = useMemo(() => applyReviewMutation(visibleRows.map(row => ({ ...row, ...(editing[row.id] ?? {}) })), { changed: {}, deleted }), [visibleRows, editing, deleted]);
  const tick = timeframe === 'TICK'; const unsupportedQuality = tick || timeframe === 'INTRADAY'; const quality = useMemo(() => unsupportedQuality ? null : analyzeQuality(pendingRows, timeframe), [pendingRows, timeframe, unsupportedQuality]); const dirty = Object.keys(editing).length > 0 || deleted.length > 0;
  function changeView(nextFrame: string, nextSession = session): void { setTimeframe(nextFrame); setSession(nextSession); setSelected(''); setEditing({}); setDeleted([]); setError(''); }
  function edit(): void { const row = visibleRows.find(item => item.id === selected); if (row) setEditing(current => ({ ...current, [selected]: current[selected] ?? { ...row } })); }
  function toggleDelete(): void { if (!selected) return; setDeleted(current => current.includes(selected) ? current.filter(id => id !== selected) : [...current, selected]); }
  function save(): void { try { if (externalActive) throw new Error('Finish or stop the active data operation before saving changes.'); store.saveReview(key, visibleRows, editing, deleted, tick); setEditing({}); setDeleted([]); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save changes.'); } }
  function close(): void { if (dirty) setDiscardOpen(true); else onClose(); }
  function skip(): void { const found = visibleRows.find(row => row.date.slice(0, 10) >= skipDate); if (found) setSelected(found.id); else setError('No row exists on or after that date.'); }
  return <div className="data-tools-flow"><Modal title={`View data for '${target.symbol}'`} width={860} onClose={close} footer={<>{dirty && <span className="review-unsaved">Data contains unsaved changes</span>}<Button onClick={close}>Close</Button><Button className="primary" disabled={!dirty} onClick={save}>Save</Button></>}>
    {(error || store.storageError) && <p className="tools-error" role="alert">{error || store.storageError}</p>}
    <fieldset className="review-metadata"><div><Field label="Symbol name"><TextInput value={target.symbol} readOnly/></Field><Field label="Instrument"><TextInput value={target.instrument} readOnly/></Field><Field label="Date from"><TextInput value={target.from} readOnly/></Field><Field label="Date to"><TextInput value={target.to} readOnly/></Field><Field label="Imported timeframe"><TextInput value={target.timeframe} readOnly/></Field><Field label="Imported records"><TextInput value={target.bars.toLocaleString()} readOnly/></Field><Field label="View timeframe"><Select value={timeframe} onChange={value => changeView(value)}>{frames.map(item => <option key={item}>{item}</option>)}</Select></Field><Field label="Session"><Select value={session} onChange={value => changeView(timeframe, value)}>{toolSessions.map(item => <option key={item}>{item}</option>)}</Select></Field></div></fieldset>
    <div className="review-tabs" role="tablist">{([['data','Data'],['chart','Chart'],['quality','Analyze data quality']] as const).map(([id,label]) => <button role="tab" aria-selected={tab === id} key={id} onClick={() => setTab(id)}>{label}</button>)}</div>
    <section className="review-tab-panel" role="tabpanel">
      {tab === 'data' && <><div className="review-data-toolbar"><div><Field label="Skip to data"><TextInput aria-label="Skip to data" type="date" min={target.from} max={target.to} value={skipDate} onChange={event => setSkipDate(event.target.value)}/></Field><Button onClick={skip}>Skip</Button></div><div><Button disabled={!selected} onClick={edit}>Edit line</Button><Button disabled={!selected} onClick={toggleDelete}>{deleted.includes(selected) ? 'Restore line' : 'Delete line'}</Button></div></div><ReviewGrid rows={visibleRows} tick={tick} selected={selected} changed={editing} deleted={deleted} onSelect={setSelected} onChange={(id, field, value) => setEditing(current => ({ ...current, [id]: { ...(current[id] ?? {}), [field]: value } }))}/></>}
      {tab === 'chart' && <DataReviewChart rows={pendingRows} tick={tick}/>}
      {tab === 'quality' && (unsupportedQuality ? <div className="review-unavailable">Analyze data quality is not available for Tick and Intraday data.</div> : quality && <div className="quality-view"><strong>Summary</strong><div className="quality-summary">{([['Gaps',quality.counts.gap,quality.percents.gap],['Spikes',quality.counts.spike,quality.percents.spike],['Bad OHLC',quality.counts.ohlc,quality.percents.ohlc]] as const).map(([label,count,percent]) => <table key={label}><tbody><tr><th>Issue</th><th>Count</th><th>% of data</th></tr><tr><td>{label}</td><td>{count}</td><td>{percent}</td></tr></tbody></table>)}</div><strong>Graphical view</strong><div className="quality-graph">{quality.distribution.length ? quality.distribution.map(item => <div key={item.bucket} title={`${item.bucket}: ${item.gaps + item.spikes + item.ohlc} issues`}><span style={{ height: `${Math.max(8, (item.gaps + item.spikes + item.ohlc) * 18)}px` }}/><small>{item.bucket}</small></div>) : <p>No detected issues.</p>}</div><strong>Detailed list</strong><div className="quality-details"><table><thead><tr><th>Date</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume</th><th>Problem</th></tr></thead><tbody>{quality.issues.map(issue => <tr key={issue.id}><td>{new Date(issue.date).toLocaleString()}</td><td>{issue.row.open}</td><td>{issue.row.high}</td><td>{issue.row.low}</td><td>{issue.row.close}</td><td>{issue.row.volume}</td><td>{issue.kind}</td></tr>)}</tbody></table></div></div>)}
    </section><p className="tools-mock-note">Deterministic offline review sample. Saving changes updates this browser profile only.</p>
  </Modal>{discardOpen && <Modal title="Unsaved data changes" width={440} onClose={() => setDiscardOpen(false)} footer={<><Button onClick={() => setDiscardOpen(false)}>Keep editing</Button><Button className="danger" onClick={onClose}>Discard changes</Button></>}><p>Close View &amp; Analyze and discard the unsaved row changes?</p></Modal>}</div>;
}
