# ruff: noqa: F401
"""Metrics package imports."""

from __future__ import annotations

# Import and expose all metrics modules and key functions
from app.services.analytics.metrics.aggregate import (
    breakeven_epsilon,
    calculate_analytics_for_subset,
    calculate_trade_metrics,
    compute_equity_metrics,
)
from app.services.analytics.metrics.costs import (
    calculate_commission_impact,
    calculate_slippage_impact,
    calculate_spread_cost_impact,
)
from app.services.analytics.metrics.curves import (
    balance_curve,
    balance_curve_metric,
    equity_curve,
    equity_curve_metric,
)
from app.services.analytics.metrics.distribution import (
    bootstrap_metric,
    distribution_summary,
    false_discovery_rate,
    fat_tail_score,
    jarque_bera_test,
    jarque_bera_test_metric,
    kurtosis_metric,
    percentile_summary,
    skewness_metric,
    upside_downside_summary,
)
from app.services.analytics.metrics.drawdown import (
    account_size_required,
    adjusted_net_profit_as_percent_of_max_strategy_drawdown,
    avg_drawdown,
    avg_drawdown_duration,
    avg_trade_drawdown,
    avg_underwater_drawdown_percent,
    avg_yearly_max_drawdown,
    calculate_drawdown_metrics,
    calmar_ratio,
    drawdown_distribution,
    drawdown_probability,
    drawdown_series_metric,
    fouse_ratio,
    max_close_to_close_drawdown,
    max_close_to_close_drawdown_date,
    max_close_to_close_drawdown_percent,
    max_consecutive_drawdown_trades,
    max_drawdown,
    max_drawdown_duration,
    max_drawdown_duration_from_returns,
    max_relative_drawdown_percent,
    max_strategy_drawdown,
    max_strategy_drawdown_date,
    max_strategy_drawdown_percent,
    pain_index,
    pain_ratio,
    recovery_factor,
    relative_drawdown_series,
    return_on_max_close_to_close_drawdown,
    return_on_max_strategy_drawdown,
    rina_index,
    sterling_ratio,
    time_to_recovery,
    trade_level_drawdowns,
    trade_level_drawdowns_metric,
    trade_pnl_distribution,
    ulcer_index,
)
from app.services.analytics.metrics.efficiency import (
    aggregate_loss_containment_efficiency,
    aggregate_mfe_capture_ratio,
    avg_trade_notional_efficiency,
    calculate_efficiency_metrics,
    capital_efficiency,
    exit_efficiency,
    longest_flat_period_duration,
    loss_containment_efficiency,
    mae_efficiency,
    median_mae_mfe,
    median_mae_r,
    median_mfe_r,
    mfe_efficiency,
    position_size_efficiency,
    profit_per_trade_per_day,
    return_per_calendar_day,
    return_per_market_hour,
    return_per_trade_hour,
    return_per_unit_mae,
    trade_efficiency,
    trades_per_day,
)
from app.services.analytics.metrics.equity_returns import (
    annual_returns,
    annualized_return,
    avg_monthly_return,
    benchmark_returns,
    best_return,
    calculate_return_metrics,
    daily_returns,
    downside_return_volatility_metric,
    geometric_mean_return_metric,
    kelly_criterion,
    log_returns_series_metric,
    monthly_return_stddev,
    monthly_returns,
    return_kurtosis,
    return_on_account,
    return_skewness,
    return_volatility_metric,
    returns_series_metric,
    total_return_usd,
    weekly_returns,
    win_loss_streaks,
    worst_return,
)
from app.services.analytics.metrics.exports import (
    benchmark_information_ratio,
    common_avg_loss,
    common_get_r_multiples,
    distributions_r_multiple_distribution,
    metrics_avg_loss,
    metrics_expectancy_r,
    metrics_get_r_multiples,
    metrics_r_multiple_distribution,
    metrics_win_rate_fraction,
    ratios_information_ratio,
)
from app.services.analytics.metrics.pnl import (
    adjusted_gross_loss,
    adjusted_gross_profit,
    adjusted_net_profit,
    adjusted_net_profit_as_percent_of_max_trade_drawdown,
    cagr_metric,
    compound_monthly_growth_rate,
    gross_loss,
    gross_profit,
    max_runup,
    max_runup_date,
    net_profit,
    return_on_initial_capital,
    return_over_drawdown,
    select_gross_loss,
    select_gross_profit,
    select_net_profit,
    total_return,
)
from app.services.analytics.metrics.position_exposure import (
    commission_paid,
    max_gross_size_held,
    max_long_size_held,
    max_net_size_held,
    max_short_size_held,
    max_size_held,
    open_position_pnl,
    percent_time_in_market,
    slippage_paid,
    swap_paid,
)
from app.services.analytics.metrics.r_multiples import (
    avg_return_per_risk_unit,
    compute_r_trade_metrics,
    compute_trade_metrics,
    get_r_multiples,
)
from app.services.analytics.metrics.ratios import (
    adjusted_expectancy,
    adjusted_payoff_ratio,
    adjusted_profit_factor,
    average_win_loss_ratio,
    cpc_index,
    drawdown_ratio,
    expected_value,
    expected_value_r,
    gain_loss_ratio,
    loss_ratio,
    martin_ratio,
    odds_calculator,
    payoff_ratio,
    payoff_ratio_metric,
    profit_factor,
    profit_factor_by_count,
    profit_factor_by_volume,
    profit_factor_by_volume_metric,
    profit_factor_metric,
    profit_loss_ratio,
    ratio_of_adjusted_gross_profit_to_adjusted_gross_loss,
    risk_reward_ratio,
    sharpe_ratio,
    sortino_ratio,
    sqn,
    system_quality_number,
    tail_ratio,
    treynor_ratio,
    ulcer_performance_index,
)
from app.services.analytics.metrics.ratios import (
    win_loss_ratio as ratios_win_loss_ratio,
)
from app.services.analytics.metrics.risk import (
    annualized_volatility,
    avg_single_trade_margin_utilization,
    avg_trade_nominal_exposure,
    calculate_risk_metrics,
    compounding_risk_of_ruin,
    conditional_var,
    downside_volatility,
    expected_shortfall,
    exposure_time_ratio,
    historical_var_by_symbol,
    max_gross_exposure,
    max_loss_probability,
    max_nominal_exposure_simple,
    max_single_trade_margin_utilization,
    portfolio_margin_utilization_curve,
    portfolio_var_from_covariance,
    profit_per_pip_risk,
    risk_adjusted_efficiency,
    risk_of_ruin_with_custom_horizon,
    time_weighted_avg_exposure,
    upside_potential_ratio,
    value_at_risk,
    volatility,
)
from app.services.analytics.metrics.risk import (
    risk_of_ruin as risk_of_ruin_sim,
)
from app.services.analytics.metrics.time_analysis import (
    avg_time_in_trade,
    calculate_long_short_split,
    calculate_period_analysis,
    calculate_session_performance,
    max_time_in_trade,
    median_time_in_trade,
    min_time_in_trade,
    time_in_market_duration_metric,
    trading_period_duration,
)
from app.services.analytics.metrics.trade_outcomes import (
    avg_consecutive_losses,
    avg_consecutive_wins,
    avg_loss,
    avg_loss_metric,
    avg_win,
    avg_win_metric,
    breakeven_trades,
    consecutive_wins_losses,
    expectancy,
    expectancy_metric,
    expectancy_r,
    get_closed_trades,
    get_ordered_closed_trades,
    largest_loss,
    largest_win,
    losing_trades,
    loss_rate_fraction,
    shannon_entropy,
    t_statistic,
    total_trades,
    winning_trades,
)
from app.services.analytics.metrics.trade_outcomes import (
    max_consecutive_losses as outcomes_max_consecutive_losses,
)
from app.services.analytics.metrics.trade_outcomes import (
    max_consecutive_wins as outcomes_max_consecutive_wins,
)
