import { normalizeLegacyBranding } from '../../../../host/branding';
import { create } from 'zustand';
import { effectiveSessions, validateSession, type SessionDefinition } from './sessions';

interface SessionState { sessions:SessionDefinition[]; overrides:Record<string,SessionDefinition>; removed:string[]; storageError:string;
  add:(item:SessionDefinition,brokers:string[])=>void; edit:(original:string,item:SessionDefinition,brokers:string[])=>void;
  clone:(item:SessionDefinition,brokers:string[])=>void; remove:(names:string[],referenced:string[])=>void;
  importSessions:(items:SessionDefinition[],overwrite:string[])=>void;
  importForBroker:(items:SessionDefinition[],overwrite:string[])=>void;
}
const key='haru-data-sessions-v1';
export const useSessions=create<SessionState>((set,get)=>{
  let initial:Pick<SessionState,'sessions'|'overrides'|'removed'|'storageError'>={sessions:[],overrides:{},removed:[],storageError:''};
  try { const raw=localStorage.getItem(key); if(raw){ const value=normalizeLegacyBranding(JSON.parse(raw)); if(value.version!==1||!Array.isArray(value.sessions)||!value.overrides||typeof value.overrides!=='object'||!Array.isArray(value.removed)||value.sessions.length>10000||Object.keys(value.overrides).length>10000||value.removed.length>10000) throw new Error('invalid');
    const names:string[]=[]; for(const item of value.sessions as SessionDefinition[]){validateSession(item,names,[item.broker],false);names.push(item.name);} for(const [name,item] of Object.entries(value.overrides) as [string,SessionDefinition][]){if(name!==item.name)throw new Error('invalid');validateSession(item,[],[item.broker],false);} if(value.removed.some((name:unknown)=>typeof name!=='string'))throw new Error('invalid'); initial={sessions:value.sessions,overrides:value.overrides,removed:value.removed,storageError:''}; }}
  catch { initial.storageError='Saved sessions could not be read. Existing browser storage has been preserved.'; }
  function persist(patch:Partial<SessionState>):void { if(get().storageError)throw new Error(get().storageError);const next={...get(),...patch};try{localStorage.setItem(key,JSON.stringify({version:1,sessions:next.sessions,overrides:next.overrides,removed:next.removed}));}catch{throw new Error('Unable to save sessions in browser storage. No changes were applied.');}set(patch); }
  return {...initial,
    add:(item,brokers)=>{validateSession(item,effectiveSessions(get().sessions,get().overrides,get().removed).map(row=>row.name),brokers);persist({sessions:[...get().sessions,structuredClone(item)]});},
    edit:(original,item,brokers)=>{if(item.name!==original)throw new Error('Session identity cannot be changed while editing.');const all=effectiveSessions(get().sessions,get().overrides,get().removed);validateSession(item,all.filter(row=>row.name!==original).map(row=>row.name),brokers,false);const index=get().sessions.findIndex(row=>row.name===original);if(index>=0){const sessions=[...get().sessions];sessions[index]=structuredClone(item);persist({sessions});}else if(Boolean(get().overrides[original]))persist({overrides:{...get().overrides,[original]:structuredClone(item)}});else throw new Error('Session no longer exists.');},
    clone:(item,brokers)=>{validateSession(item,effectiveSessions(get().sessions,get().overrides,get().removed).map(row=>row.name),brokers);persist({sessions:[...get().sessions,structuredClone(item)]});},
    remove:(names,referenced)=>{if(!names.length)throw new Error('No session selected');const blocked=names.find(name=>referenced.includes(name));if(blocked)throw new Error(`Session '${blocked}' is used by an instrument and cannot be removed.`);const selected=new Set(names);persist({sessions:get().sessions.filter(row=>!selected.has(row.name)),overrides:Object.fromEntries(Object.entries(get().overrides).filter(([name])=>!selected.has(name))),removed:[...new Set([...get().removed,...names.filter(name=>Boolean(get().overrides[name]))])]});},
    importSessions:(items,overwrite)=>{const current=effectiveSessions(get().sessions,get().overrides,get().removed);const replace=new Set(overwrite);const sessions=[...get().sessions];const overrides={...get().overrides};for(const item of items){const found=current.find(row=>row.name.toLowerCase()===item.name.toLowerCase());if(found){if(!replace.has(found.name))continue;const value={...item,name:found.name,broker:found.broker,brokerName:found.brokerName};const index=sessions.findIndex(row=>row.name===found.name);if(index>=0)sessions[index]=value;else overrides[found.name]=value;}else sessions.push(item);}persist({sessions,overrides});},
    importForBroker:(items,overwrite)=>{const current=effectiveSessions(get().sessions,get().overrides,get().removed);const replace=new Set(overwrite);const sessions=[...get().sessions];const overrides={...get().overrides};for(const item of items){const found=current.find(row=>row.name.toLowerCase()===item.name.toLowerCase());if(found){if(!replace.has(found.name))continue;const value={...structuredClone(item),name:found.name};const index=sessions.findIndex(row=>row.name===found.name);if(index>=0)sessions[index]=value;else overrides[found.name]=value;}else sessions.push(structuredClone(item));}persist({sessions,overrides});},
  };
});
