"""Analytics service tool exports.

Purpose:
    Expose every public analytics function from the focused service modules.
    Business logic lives outside this initializer.
"""

from __future__ import annotations

# benchmark.py tools
from app.services.analytics.benchmark import (
    alpha,
    batting_average,
    benchmark_returns,
    beta,
    calculate_benchmark_metrics,
    information_ratio,
    max_relative_drawdown_percent,
    r_squared,
    relative_drawdown_series,
    tracking_error,
    up_down_capture,
)
from app.services.analytics.benchmark import (
    information_ratio as benchmark_information_ratio,
)

# common.py tools
from app.services.analytics.common import (
    avg_loss,
    classify_trades,
    get_closed_trades,
    get_r_multiples,
    max_gross_size_held,
    percent_time_in_market,
    time_in_market_duration,
)
from app.services.analytics.common import (
    avg_loss as common_avg_loss,
)
from app.services.analytics.common import (
    get_r_multiples as common_get_r_multiples,
)

# decision_scorecard.py tools
from app.services.analytics.decision_scorecard import evaluate_strategy_quality

# distributions.py tools
from app.services.analytics.distributions import (
    calculate_distribution_metrics,
    detect_outliers,
    distribution_fit_quality,
    fat_tail_score,
    fit_distribution,
    higher_moments,
    histogram_data,
    jarque_bera_test,
    kurtosis,
    outlier_ratio,
    percentile_summary,
    qq_plot_data,
    r_multiple_distribution,
    return_distribution,
    shapiro_wilk_test,
    skewness,
    tail_ratio,
    trade_pnl_distribution,
    upside_downside_summary,
)
from app.services.analytics.distributions import (
    r_multiple_distribution as distributions_r_multiple_distribution,
)

# drawdowns.py tools
from app.services.analytics.drawdowns import (
    account_size_required,
    avg_drawdown,
    avg_drawdown_duration,
    avg_trade_drawdown,
    avg_underwater_drawdown_percent,
    avg_yearly_max_drawdown,
    calculate_drawdown_metrics,
    drawdown_distribution,
    drawdown_duration_series,
    drawdown_series,
    max_close_to_close_drawdown,
    max_close_to_close_drawdown_date,
    max_close_to_close_drawdown_percent,
    max_consecutive_drawdown_trades,
    max_drawdown,
    max_drawdown_duration,
    max_drawdown_duration_from_equity,
    max_drawdown_duration_from_returns,
    max_strategy_drawdown,
    max_strategy_drawdown_date,
    max_strategy_drawdown_percent,
    pain_index,
    pain_ratio,
    recovery_factor,
    time_to_recovery,
    trade_level_drawdowns,
    ulcer_index,
)

# efficiency.py tools
from app.services.analytics.efficiency import (
    aggregate_loss_containment_efficiency,
    aggregate_mfe_capture_ratio,
    avg_return_per_risk_unit,
    avg_trade_notional_efficiency,
    calculate_efficiency_metrics,
    capital_efficiency,
    exit_efficiency,
    loss_containment_efficiency,
    mae_efficiency,
    mfe_efficiency,
    position_size_efficiency,
    profit_per_pip_risk,
    profit_per_trade_per_day,
    return_per_calendar_day,
    return_per_market_hour,
    return_per_trade_hour,
    return_per_unit_mae,
    risk_adjusted_efficiency,
    trades_per_day,
)
from app.services.analytics.metrics import (
    avg_consecutive_losses,
    avg_consecutive_wins,
    avg_r_multiple,
    avg_time_in_trade,
    avg_win,
    avg_win_loss,
    breakeven_trades,
    calculate_trade_metrics,
    commission_paid,
    compute_equity_metrics,
    compute_r_trade_metrics,
    compute_trade_metrics,
    consecutive_wins_losses,
    count_open_trades,
    expectancy,
    expectancy_r,
    get_mae_mfe_r,
    get_ordered_closed_trades,
    kelly_criterion,
    largest_loss,
    largest_win,
    long_trades,
    longest_flat_period_duration,
    losing_trades,
    loss_rate,
    max_consecutive_losses,
    max_consecutive_wins,
    max_long_size_held,
    max_net_size_held,
    max_r_multiple,
    max_short_size_held,
    max_size_held,
    max_time_in_trade,
    median_loss,
    median_mae_mfe,
    median_mae_r,
    median_mfe_r,
    median_r_multiple,
    median_time_in_trade,
    median_win,
    min_r_multiple,
    min_time_in_trade,
    open_position_pnl,
    r_expectancy,
    r_signal_to_noise,
    rolling_expectancy_stability,
    runs_test_zscore,
    short_trades,
    slippage_paid,
    sqn,
    swap_paid,
    t_statistic,
    total_trades,
    trade_efficiency,
    trade_outcome_entropy,
    trading_period_duration,
    win_after_win_probability,
    win_loss_streaks,
    win_rate,
    win_rate_fraction,
    winning_trades,
)
from app.services.analytics.metrics import (
    avg_loss as metrics_avg_loss,
)
from app.services.analytics.metrics import (
    expectancy as metrics_expectancy,
)
from app.services.analytics.metrics import (
    expectancy_r as metrics_expectancy_r,
)

# metrics.py tools
from app.services.analytics.metrics import (
    get_r_multiples as metrics_get_r_multiples,
)
from app.services.analytics.metrics import (
    r_multiple_distribution as metrics_r_multiple_distribution,
)
from app.services.analytics.metrics import (
    win_rate_fraction as metrics_win_rate_fraction,
)

# overview.py tools
from app.services.analytics.overview import (
    build_backtest_report,
    build_overview_payload,
    calculate_analytics_for_subset,
    calculate_commission_impact,
    calculate_slippage_impact,
    calculate_spread_cost_impact,
    format_summary_as_rows,
    get_analytics_overview,
)
from app.services.analytics.ratios import (
    adjusted_net_profit_as_percent_of_largest_loss,
    adjusted_net_profit_as_percent_of_max_strategy_drawdown,
    adjusted_net_profit_as_percent_of_max_trade_drawdown,
    adjusted_profit_factor,
    annualized_sharpe_ratio,
    calculate_ratio_metrics,
    calmar_ratio,
    edge_ratio,
    expectancy_over_std,
    fouse_ratio,
    gain_to_pain_ratio,
    kappa_ratio,
    mfe_to_mae_ratio,
    net_profit_as_percent_of_largest_loss,
    net_profit_as_percent_of_max_strategy_drawdown,
    net_profit_as_percent_of_max_trade_drawdown,
    omega_ratio,
    payoff_ratio,
    profit_factor,
    profit_to_mae_ratio,
    return_over_drawdown,
    rina_index,
    select_net_profit_as_percent_of_largest_loss,
    select_net_profit_as_percent_of_max_strategy_drawdown,
    select_net_profit_as_percent_of_max_trade_drawdown,
    select_profit_factor,
    sharpe_ratio,
    sortino_ratio,
    sterling_ratio,
    upside_potential_ratio,
)
from app.services.analytics.ratios import (
    expectancy as ratios_expectancy,
)
from app.services.analytics.ratios import (
    expectancy_r as ratios_expectancy_r,
)
from app.services.analytics.ratios import (
    information_ratio as ratios_information_ratio,
)

# ratios.py tools
from app.services.analytics.ratios import (
    win_rate_fraction as ratios_win_rate_fraction,
)

# returns.py tools
from app.services.analytics.returns import (
    adjusted_gross_loss,
    adjusted_gross_profit,
    adjusted_net_profit,
    annual_returns,
    annualized_return,
    avg_monthly_return,
    balance_curve,
    balance_curve_from_closed_trades,
    best_return,
    buy_and_hold_cagr,
    buy_and_hold_return,
    cagr,
    calculate_long_short_split,
    calculate_period_analysis,
    calculate_return_metrics,
    calculate_session_performance,
    compound_monthly_growth_rate,
    daily_returns,
    downside_return_volatility,
    equity_curve,
    geometric_mean_return,
    gross_loss,
    gross_profit,
    log_returns_series,
    max_runup,
    max_runup_date,
    monthly_return_stddev,
    monthly_returns,
    net_profit,
    return_kurtosis,
    return_on_account,
    return_on_initial_capital,
    return_on_max_close_to_close_drawdown,
    return_on_max_strategy_drawdown,
    return_skewness,
    return_volatility,
    returns_series,
    select_gross_loss,
    select_gross_profit,
    select_net_profit,
    total_return,
    total_return_usd,
    weekly_returns,
    worst_return,
)

# risks.py tools
from app.services.analytics.risks import (
    annualized_volatility,
    avg_single_trade_margin_utilization,
    avg_trade_nominal_exposure,
    calculate_risk_metrics,
    compounding_risk_of_ruin,
    conditional_var,
    downside_volatility,
    drawdown_probability,
    expected_shortfall,
    exposure_time_ratio,
    historical_var_by_symbol,
    max_gross_exposure,
    max_loss_probability,
    max_nominal_exposure_simple,
    max_single_trade_margin_utilization,
    portfolio_margin_utilization_curve,
    portfolio_var_from_covariance,
    risk_of_ruin,
    risk_of_ruin_with_custom_horizon,
    time_weighted_avg_exposure,
    value_at_risk,
    volatility,
)

# statistical_tests.py tools
from app.services.analytics.statistical_tests import (
    benjamini_hochberg_correction,
    bonferroni_correction,
    bootstrap_confidence_intervals,
    bootstrap_confidence_intervals_backtest,
    bootstrap_probability_above_threshold,
    deflated_sharpe_ratio,
    permutation_test,
    permutation_test_backtest,
    print_statistical_validation_report,
    probability_of_backtest_overfitting,
    sample_size_warning,
    stability_score,
    walk_forward_degradation_score,
    whites_reality_check,
    whites_reality_check_backtests,
)
from app.services.utils.standard import (
    standardize_domain_exports as _standardize_domain_exports,
)

__all__ = [
    # benchmark.py tools
    "benchmark_returns",
    "beta",
    "alpha",
    "r_squared",
    "tracking_error",
    "information_ratio",
    "benchmark_information_ratio",
    "relative_drawdown_series",
    "max_relative_drawdown_percent",
    "batting_average",
    "up_down_capture",
    "calculate_benchmark_metrics",
    # common.py tools
    "get_closed_trades",
    "classify_trades",
    "avg_loss",
    "common_avg_loss",
    "get_r_multiples",
    "common_get_r_multiples",
    "max_gross_size_held",
    "time_in_market_duration",
    "percent_time_in_market",
    # decision_scorecard.py tools
    "evaluate_strategy_quality",
    # distributions.py tools
    "return_distribution",
    "trade_pnl_distribution",
    "r_multiple_distribution",
    "distributions_r_multiple_distribution",
    "percentile_summary",
    "upside_downside_summary",
    "skewness",
    "kurtosis",
    "higher_moments",
    "fat_tail_score",
    "tail_ratio",
    "jarque_bera_test",
    "shapiro_wilk_test",
    "qq_plot_data",
    "fit_distribution",
    "distribution_fit_quality",
    "histogram_data",
    "detect_outliers",
    "outlier_ratio",
    "calculate_distribution_metrics",
    # drawdowns.py tools
    "drawdown_series",
    "drawdown_duration_series",
    "max_strategy_drawdown",
    "max_strategy_drawdown_percent",
    "max_drawdown",
    "avg_drawdown",
    "drawdown_distribution",
    "max_drawdown_duration_from_equity",
    "max_drawdown_duration_from_returns",
    "max_drawdown_duration",
    "avg_drawdown_duration",
    "time_to_recovery",
    "recovery_factor",
    "trade_level_drawdowns",
    "max_close_to_close_drawdown",
    "max_close_to_close_drawdown_percent",
    "avg_trade_drawdown",
    "account_size_required",
    "max_consecutive_drawdown_trades",
    "avg_yearly_max_drawdown",
    "max_strategy_drawdown_date",
    "max_close_to_close_drawdown_date",
    "ulcer_index",
    "pain_index",
    "avg_underwater_drawdown_percent",
    "pain_ratio",
    "calculate_drawdown_metrics",
    # efficiency.py tools
    "capital_efficiency",
    "avg_trade_notional_efficiency",
    "return_per_unit_mae",
    "risk_adjusted_efficiency",
    "avg_return_per_risk_unit",
    "return_per_trade_hour",
    "return_per_market_hour",
    "trades_per_day",
    "return_per_calendar_day",
    "profit_per_trade_per_day",
    "mfe_efficiency",
    "aggregate_mfe_capture_ratio",
    "profit_per_pip_risk",
    "mae_efficiency",
    "exit_efficiency",
    "loss_containment_efficiency",
    "aggregate_loss_containment_efficiency",
    "position_size_efficiency",
    "calculate_efficiency_metrics",
    # metrics.py tools
    "metrics_get_r_multiples",
    "get_ordered_closed_trades",
    "win_rate_fraction",
    "metrics_win_rate_fraction",
    "avg_win_loss",
    "consecutive_wins_losses",
    "median_mae_mfe",
    "get_mae_mfe_r",
    "t_statistic",
    "open_position_pnl",
    "total_trades",
    "winning_trades",
    "losing_trades",
    "breakeven_trades",
    "long_trades",
    "short_trades",
    "count_open_trades",
    "slippage_paid",
    "commission_paid",
    "swap_paid",
    "win_rate",
    "loss_rate",
    "avg_win",
    "metrics_avg_loss",
    "largest_win",
    "largest_loss",
    "median_win",
    "median_loss",
    "expectancy",
    "metrics_expectancy",
    "expectancy_r",
    "metrics_expectancy_r",
    "max_size_held",
    "max_net_size_held",
    "max_long_size_held",
    "max_short_size_held",
    "avg_r_multiple",
    "median_r_multiple",
    "metrics_r_multiple_distribution",
    "r_expectancy",
    "max_r_multiple",
    "min_r_multiple",
    "median_mae_r",
    "median_mfe_r",
    "max_consecutive_wins",
    "max_consecutive_losses",
    "avg_consecutive_wins",
    "avg_consecutive_losses",
    "win_loss_streaks",
    "avg_time_in_trade",
    "median_time_in_trade",
    "max_time_in_trade",
    "min_time_in_trade",
    "sqn",
    "kelly_criterion",
    "compute_r_trade_metrics",
    "compute_trade_metrics",
    "compute_equity_metrics",
    "trade_efficiency",
    "r_signal_to_noise",
    "rolling_expectancy_stability",
    "win_after_win_probability",
    "runs_test_zscore",
    "trading_period_duration",
    "trade_outcome_entropy",
    "longest_flat_period_duration",
    "calculate_trade_metrics",
    # overview.py tools
    "calculate_analytics_for_subset",
    "get_analytics_overview",
    "format_summary_as_rows",
    "build_overview_payload",
    "calculate_spread_cost_impact",
    "calculate_slippage_impact",
    "calculate_commission_impact",
    "build_backtest_report",
    # ratios.py tools
    "ratios_win_rate_fraction",
    "sharpe_ratio",
    "annualized_sharpe_ratio",
    "sortino_ratio",
    "calmar_ratio",
    "ratios_information_ratio",
    "fouse_ratio",
    "upside_potential_ratio",
    "omega_ratio",
    "gain_to_pain_ratio",
    "kappa_ratio",
    "sterling_ratio",
    "rina_index",
    "profit_factor",
    "payoff_ratio",
    "edge_ratio",
    "profit_to_mae_ratio",
    "mfe_to_mae_ratio",
    "return_over_drawdown",
    "expectancy_over_std",
    "net_profit_as_percent_of_largest_loss",
    "net_profit_as_percent_of_max_trade_drawdown",
    "net_profit_as_percent_of_max_strategy_drawdown",
    "select_net_profit_as_percent_of_largest_loss",
    "select_net_profit_as_percent_of_max_trade_drawdown",
    "select_net_profit_as_percent_of_max_strategy_drawdown",
    "adjusted_net_profit_as_percent_of_largest_loss",
    "adjusted_net_profit_as_percent_of_max_trade_drawdown",
    "adjusted_net_profit_as_percent_of_max_strategy_drawdown",
    "adjusted_profit_factor",
    "select_profit_factor",
    "ratios_expectancy",
    "ratios_expectancy_r",
    "calculate_ratio_metrics",
    # returns.py tools
    "total_return_usd",
    "total_return",
    "net_profit",
    "gross_profit",
    "gross_loss",
    "balance_curve_from_closed_trades",
    "balance_curve",
    "equity_curve",
    "returns_series",
    "log_returns_series",
    "daily_returns",
    "weekly_returns",
    "monthly_returns",
    "annual_returns",
    "cagr",
    "compound_monthly_growth_rate",
    "avg_monthly_return",
    "monthly_return_stddev",
    "annualized_return",
    "geometric_mean_return",
    "best_return",
    "worst_return",
    "buy_and_hold_return",
    "buy_and_hold_cagr",
    "return_volatility",
    "downside_return_volatility",
    "return_skewness",
    "return_kurtosis",
    "adjusted_gross_profit",
    "adjusted_gross_loss",
    "adjusted_net_profit",
    "select_net_profit",
    "select_gross_profit",
    "select_gross_loss",
    "return_on_max_strategy_drawdown",
    "return_on_max_close_to_close_drawdown",
    "return_on_account",
    "return_on_initial_capital",
    "max_runup",
    "max_runup_date",
    "calculate_return_metrics",
    "calculate_period_analysis",
    "calculate_long_short_split",
    "calculate_session_performance",
    # risks.py tools
    "volatility",
    "annualized_volatility",
    "downside_volatility",
    "value_at_risk",
    "conditional_var",
    "expected_shortfall",
    "max_loss_probability",
    "drawdown_probability",
    "risk_of_ruin",
    "max_nominal_exposure_simple",
    "max_gross_exposure",
    "avg_trade_nominal_exposure",
    "exposure_time_ratio",
    "max_single_trade_margin_utilization",
    "avg_single_trade_margin_utilization",
    "time_weighted_avg_exposure",
    "portfolio_margin_utilization_curve",
    "compounding_risk_of_ruin",
    "risk_of_ruin_with_custom_horizon",
    "historical_var_by_symbol",
    "portfolio_var_from_covariance",
    "calculate_risk_metrics",
    # statistical_tests.py tools
    "whites_reality_check",
    "permutation_test",
    "bootstrap_confidence_intervals",
    "deflated_sharpe_ratio",
    "probability_of_backtest_overfitting",
    "walk_forward_degradation_score",
    "bootstrap_probability_above_threshold",
    "bonferroni_correction",
    "benjamini_hochberg_correction",
    "sample_size_warning",
    "stability_score",
    "whites_reality_check_backtests",
    "permutation_test_backtest",
    "bootstrap_confidence_intervals_backtest",
    "print_statistical_validation_report",
]

_standardize_domain_exports(globals(), __all__, tool_category="analytics")
