# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from enum import IntEnum
from typing import Final


class ENUM_DEAL_ENTRY(IntEnum):
    """Defines the identifier set for deal entry."""

    DEAL_ENTRY_IN = 0
    DEAL_ENTRY_OUT = 1
    DEAL_ENTRY_INOUT = 2
    DEAL_ENTRY_OUT_BY = 3


DEAL_ENTRY_IN: Final = ENUM_DEAL_ENTRY.DEAL_ENTRY_IN
DEAL_ENTRY_OUT: Final = ENUM_DEAL_ENTRY.DEAL_ENTRY_OUT
DEAL_ENTRY_INOUT: Final = ENUM_DEAL_ENTRY.DEAL_ENTRY_INOUT
DEAL_ENTRY_OUT_BY: Final = ENUM_DEAL_ENTRY.DEAL_ENTRY_OUT_BY


class ENUM_DEAL_PROPERTY_DOUBLE(IntEnum):
    """Defines the identifier set for deal property double."""

    DEAL_VOLUME = 0
    DEAL_PRICE = 1
    DEAL_COMMISSION = 2
    DEAL_SWAP = 3
    DEAL_PROFIT = 4
    DEAL_FEE = 5
    DEAL_SL = 6
    DEAL_TP = 7


DEAL_VOLUME: Final = ENUM_DEAL_PROPERTY_DOUBLE.DEAL_VOLUME
DEAL_PRICE: Final = ENUM_DEAL_PROPERTY_DOUBLE.DEAL_PRICE
DEAL_COMMISSION: Final = ENUM_DEAL_PROPERTY_DOUBLE.DEAL_COMMISSION
DEAL_SWAP: Final = ENUM_DEAL_PROPERTY_DOUBLE.DEAL_SWAP
DEAL_PROFIT: Final = ENUM_DEAL_PROPERTY_DOUBLE.DEAL_PROFIT
DEAL_FEE: Final = ENUM_DEAL_PROPERTY_DOUBLE.DEAL_FEE
DEAL_SL: Final = ENUM_DEAL_PROPERTY_DOUBLE.DEAL_SL
DEAL_TP: Final = ENUM_DEAL_PROPERTY_DOUBLE.DEAL_TP


class ENUM_DEAL_PROPERTY_INTEGER(IntEnum):
    """Defines the identifier set for deal property integer."""

    DEAL_TICKET = 0
    DEAL_ORDER = 1
    DEAL_TIME = 2
    DEAL_TIME_MSC = 3
    DEAL_TYPE = 4
    DEAL_ENTRY = 5
    DEAL_MAGIC = 6
    DEAL_REASON = 7
    DEAL_POSITION_ID = 8


DEAL_TICKET: Final = ENUM_DEAL_PROPERTY_INTEGER.DEAL_TICKET
DEAL_ORDER: Final = ENUM_DEAL_PROPERTY_INTEGER.DEAL_ORDER
DEAL_TIME: Final = ENUM_DEAL_PROPERTY_INTEGER.DEAL_TIME
DEAL_TIME_MSC: Final = ENUM_DEAL_PROPERTY_INTEGER.DEAL_TIME_MSC
DEAL_TYPE: Final = ENUM_DEAL_PROPERTY_INTEGER.DEAL_TYPE
DEAL_ENTRY: Final = ENUM_DEAL_PROPERTY_INTEGER.DEAL_ENTRY
DEAL_MAGIC: Final = ENUM_DEAL_PROPERTY_INTEGER.DEAL_MAGIC
DEAL_REASON: Final = ENUM_DEAL_PROPERTY_INTEGER.DEAL_REASON
DEAL_POSITION_ID: Final = ENUM_DEAL_PROPERTY_INTEGER.DEAL_POSITION_ID


class ENUM_DEAL_PROPERTY_STRING(IntEnum):
    """Defines the identifier set for deal property string."""

    DEAL_SYMBOL = 0
    DEAL_COMMENT = 1
    DEAL_EXTERNAL_ID = 2


DEAL_SYMBOL: Final = ENUM_DEAL_PROPERTY_STRING.DEAL_SYMBOL
DEAL_COMMENT: Final = ENUM_DEAL_PROPERTY_STRING.DEAL_COMMENT
DEAL_EXTERNAL_ID: Final = ENUM_DEAL_PROPERTY_STRING.DEAL_EXTERNAL_ID


class ENUM_DEAL_REASON(IntEnum):
    """Defines the identifier set for deal reason."""

    DEAL_REASON_CLIENT = 0
    DEAL_REASON_MOBILE = 1
    DEAL_REASON_WEB = 2
    DEAL_REASON_AUTOMATION = 3
    DEAL_REASON_SL = 4
    DEAL_REASON_TP = 5
    DEAL_REASON_SO = 6
    DEAL_REASON_ROLLOVER = 7
    DEAL_REASON_VMARGIN = 8
    DEAL_REASON_SPLIT = 9
    DEAL_REASON_CORPORATE_ACTION = 10


DEAL_REASON_CLIENT: Final = ENUM_DEAL_REASON.DEAL_REASON_CLIENT
DEAL_REASON_MOBILE: Final = ENUM_DEAL_REASON.DEAL_REASON_MOBILE
DEAL_REASON_WEB: Final = ENUM_DEAL_REASON.DEAL_REASON_WEB
DEAL_REASON_AUTOMATION: Final = ENUM_DEAL_REASON.DEAL_REASON_AUTOMATION
DEAL_REASON_SL: Final = ENUM_DEAL_REASON.DEAL_REASON_SL
DEAL_REASON_TP: Final = ENUM_DEAL_REASON.DEAL_REASON_TP
DEAL_REASON_SO: Final = ENUM_DEAL_REASON.DEAL_REASON_SO
DEAL_REASON_ROLLOVER: Final = ENUM_DEAL_REASON.DEAL_REASON_ROLLOVER
DEAL_REASON_VMARGIN: Final = ENUM_DEAL_REASON.DEAL_REASON_VMARGIN
DEAL_REASON_SPLIT: Final = ENUM_DEAL_REASON.DEAL_REASON_SPLIT
DEAL_REASON_CORPORATE_ACTION: Final = ENUM_DEAL_REASON.DEAL_REASON_CORPORATE_ACTION


class ENUM_DEAL_TYPE(IntEnum):
    """Defines the identifier set for deal type."""

    DEAL_TYPE_BUY = 0
    DEAL_TYPE_SELL = 1
    DEAL_TYPE_BALANCE = 2
    DEAL_TYPE_CREDIT = 3
    DEAL_TYPE_CHARGE = 4
    DEAL_TYPE_CORRECTION = 5
    DEAL_TYPE_BONUS = 6
    DEAL_TYPE_COMMISSION = 7
    DEAL_TYPE_COMMISSION_DAILY = 8
    DEAL_TYPE_COMMISSION_MONTHLY = 9
    DEAL_TYPE_COMMISSION_AGENT_DAILY = 10
    DEAL_TYPE_COMMISSION_AGENT_MONTHLY = 11
    DEAL_TYPE_INTEREST = 12
    DEAL_TYPE_BUY_CANCELED = 13
    DEAL_TYPE_SELL_CANCELED = 14
    DEAL_DIVIDEND = 15
    DEAL_DIVIDEND_FRANKED = 16
    DEAL_TAX = 17


DEAL_TYPE_BUY: Final = ENUM_DEAL_TYPE.DEAL_TYPE_BUY
DEAL_TYPE_SELL: Final = ENUM_DEAL_TYPE.DEAL_TYPE_SELL
DEAL_TYPE_BALANCE: Final = ENUM_DEAL_TYPE.DEAL_TYPE_BALANCE
DEAL_TYPE_CREDIT: Final = ENUM_DEAL_TYPE.DEAL_TYPE_CREDIT
DEAL_TYPE_CHARGE: Final = ENUM_DEAL_TYPE.DEAL_TYPE_CHARGE
DEAL_TYPE_CORRECTION: Final = ENUM_DEAL_TYPE.DEAL_TYPE_CORRECTION
DEAL_TYPE_BONUS: Final = ENUM_DEAL_TYPE.DEAL_TYPE_BONUS
DEAL_TYPE_COMMISSION: Final = ENUM_DEAL_TYPE.DEAL_TYPE_COMMISSION
DEAL_TYPE_COMMISSION_DAILY: Final = ENUM_DEAL_TYPE.DEAL_TYPE_COMMISSION_DAILY
DEAL_TYPE_COMMISSION_MONTHLY: Final = ENUM_DEAL_TYPE.DEAL_TYPE_COMMISSION_MONTHLY
DEAL_TYPE_COMMISSION_AGENT_DAILY: Final = (
    ENUM_DEAL_TYPE.DEAL_TYPE_COMMISSION_AGENT_DAILY
)
DEAL_TYPE_COMMISSION_AGENT_MONTHLY: Final = (
    ENUM_DEAL_TYPE.DEAL_TYPE_COMMISSION_AGENT_MONTHLY
)
DEAL_TYPE_INTEREST: Final = ENUM_DEAL_TYPE.DEAL_TYPE_INTEREST
DEAL_TYPE_BUY_CANCELED: Final = ENUM_DEAL_TYPE.DEAL_TYPE_BUY_CANCELED
DEAL_TYPE_SELL_CANCELED: Final = ENUM_DEAL_TYPE.DEAL_TYPE_SELL_CANCELED
DEAL_DIVIDEND: Final = ENUM_DEAL_TYPE.DEAL_DIVIDEND
DEAL_DIVIDEND_FRANKED: Final = ENUM_DEAL_TYPE.DEAL_DIVIDEND_FRANKED
DEAL_TAX: Final = ENUM_DEAL_TYPE.DEAL_TAX


class ENUM_ORDER_PROPERTY_DOUBLE(IntEnum):
    """Defines the identifier set for order property double."""

    ORDER_VOLUME_INITIAL = 0
    ORDER_VOLUME_CURRENT = 1
    ORDER_PRICE_OPEN = 2
    ORDER_SL = 3
    ORDER_TP = 4
    ORDER_PRICE_CURRENT = 5
    ORDER_PRICE_STOPLIMIT = 6


ORDER_VOLUME_INITIAL: Final = ENUM_ORDER_PROPERTY_DOUBLE.ORDER_VOLUME_INITIAL
ORDER_VOLUME_CURRENT: Final = ENUM_ORDER_PROPERTY_DOUBLE.ORDER_VOLUME_CURRENT
ORDER_PRICE_OPEN: Final = ENUM_ORDER_PROPERTY_DOUBLE.ORDER_PRICE_OPEN
ORDER_SL: Final = ENUM_ORDER_PROPERTY_DOUBLE.ORDER_SL
ORDER_TP: Final = ENUM_ORDER_PROPERTY_DOUBLE.ORDER_TP
ORDER_PRICE_CURRENT: Final = ENUM_ORDER_PROPERTY_DOUBLE.ORDER_PRICE_CURRENT
ORDER_PRICE_STOPLIMIT: Final = ENUM_ORDER_PROPERTY_DOUBLE.ORDER_PRICE_STOPLIMIT


class ENUM_ORDER_PROPERTY_INTEGER(IntEnum):
    """Defines the identifier set for order property integer."""

    ORDER_TICKET = 0
    ORDER_TIME_SETUP = 1
    ORDER_TYPE = 2
    ORDER_STATE = 3
    ORDER_TIME_EXPIRATION = 4
    ORDER_TIME_DONE = 5
    ORDER_TIME_SETUP_MSC = 6
    ORDER_TIME_DONE_MSC = 7
    ORDER_TYPE_FILLING = 8
    ORDER_TYPE_TIME = 9
    ORDER_MAGIC = 10
    ORDER_REASON = 11
    ORDER_POSITION_ID = 12
    ORDER_POSITION_BY_ID = 13


ORDER_TICKET: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_TICKET
ORDER_TIME_SETUP: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_TIME_SETUP
ORDER_TYPE: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_TYPE
ORDER_STATE: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_STATE
ORDER_TIME_EXPIRATION: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_TIME_EXPIRATION
ORDER_TIME_DONE: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_TIME_DONE
ORDER_TIME_SETUP_MSC: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_TIME_SETUP_MSC
ORDER_TIME_DONE_MSC: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_TIME_DONE_MSC
ORDER_TYPE_FILLING: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_TYPE_FILLING
ORDER_TYPE_TIME: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_TYPE_TIME
ORDER_MAGIC: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_MAGIC
ORDER_REASON: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_REASON
ORDER_POSITION_ID: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_POSITION_ID
ORDER_POSITION_BY_ID: Final = ENUM_ORDER_PROPERTY_INTEGER.ORDER_POSITION_BY_ID


class ENUM_ORDER_PROPERTY_STRING(IntEnum):
    """Defines the identifier set for order property string."""

    ORDER_SYMBOL = 0
    ORDER_COMMENT = 1
    ORDER_EXTERNAL_ID = 2


ORDER_SYMBOL: Final = ENUM_ORDER_PROPERTY_STRING.ORDER_SYMBOL
ORDER_COMMENT: Final = ENUM_ORDER_PROPERTY_STRING.ORDER_COMMENT
ORDER_EXTERNAL_ID: Final = ENUM_ORDER_PROPERTY_STRING.ORDER_EXTERNAL_ID


class ENUM_ORDER_REASON(IntEnum):
    """Defines the identifier set for order reason."""

    ORDER_REASON_CLIENT = 0
    ORDER_REASON_MOBILE = 1
    ORDER_REASON_WEB = 2
    ORDER_REASON_AUTOMATION = 3
    ORDER_REASON_SL = 4
    ORDER_REASON_TP = 5
    ORDER_REASON_SO = 6


ORDER_REASON_CLIENT: Final = ENUM_ORDER_REASON.ORDER_REASON_CLIENT
ORDER_REASON_MOBILE: Final = ENUM_ORDER_REASON.ORDER_REASON_MOBILE
ORDER_REASON_WEB: Final = ENUM_ORDER_REASON.ORDER_REASON_WEB
ORDER_REASON_AUTOMATION: Final = ENUM_ORDER_REASON.ORDER_REASON_AUTOMATION
ORDER_REASON_SL: Final = ENUM_ORDER_REASON.ORDER_REASON_SL
ORDER_REASON_TP: Final = ENUM_ORDER_REASON.ORDER_REASON_TP
ORDER_REASON_SO: Final = ENUM_ORDER_REASON.ORDER_REASON_SO


class ENUM_ORDER_STATE(IntEnum):
    """Defines the identifier set for order state."""

    ORDER_STATE_STARTED = 0
    ORDER_STATE_PLACED = 1
    ORDER_STATE_CANCELED = 2
    ORDER_STATE_PARTIAL = 3
    ORDER_STATE_FILLED = 4
    ORDER_STATE_REJECTED = 5
    ORDER_STATE_EXPIRED = 6
    ORDER_STATE_REQUEST_ADD = 7
    ORDER_STATE_REQUEST_MODIFY = 8
    ORDER_STATE_REQUEST_CANCEL = 9


ORDER_STATE_STARTED: Final = ENUM_ORDER_STATE.ORDER_STATE_STARTED
ORDER_STATE_PLACED: Final = ENUM_ORDER_STATE.ORDER_STATE_PLACED
ORDER_STATE_CANCELED: Final = ENUM_ORDER_STATE.ORDER_STATE_CANCELED
ORDER_STATE_PARTIAL: Final = ENUM_ORDER_STATE.ORDER_STATE_PARTIAL
ORDER_STATE_FILLED: Final = ENUM_ORDER_STATE.ORDER_STATE_FILLED
ORDER_STATE_REJECTED: Final = ENUM_ORDER_STATE.ORDER_STATE_REJECTED
ORDER_STATE_EXPIRED: Final = ENUM_ORDER_STATE.ORDER_STATE_EXPIRED
ORDER_STATE_REQUEST_ADD: Final = ENUM_ORDER_STATE.ORDER_STATE_REQUEST_ADD
ORDER_STATE_REQUEST_MODIFY: Final = ENUM_ORDER_STATE.ORDER_STATE_REQUEST_MODIFY
ORDER_STATE_REQUEST_CANCEL: Final = ENUM_ORDER_STATE.ORDER_STATE_REQUEST_CANCEL


class ENUM_ORDER_TYPE(IntEnum):
    """Defines the identifier set for order type."""

    ORDER_TYPE_BUY = 0
    ORDER_TYPE_SELL = 1
    ORDER_TYPE_BUY_LIMIT = 2
    ORDER_TYPE_SELL_LIMIT = 3
    ORDER_TYPE_BUY_STOP = 4
    ORDER_TYPE_SELL_STOP = 5
    ORDER_TYPE_BUY_STOP_LIMIT = 6
    ORDER_TYPE_SELL_STOP_LIMIT = 7
    ORDER_TYPE_CLOSE_BY = 8


ORDER_TYPE_BUY: Final = ENUM_ORDER_TYPE.ORDER_TYPE_BUY
ORDER_TYPE_SELL: Final = ENUM_ORDER_TYPE.ORDER_TYPE_SELL
ORDER_TYPE_BUY_LIMIT: Final = ENUM_ORDER_TYPE.ORDER_TYPE_BUY_LIMIT
ORDER_TYPE_SELL_LIMIT: Final = ENUM_ORDER_TYPE.ORDER_TYPE_SELL_LIMIT
ORDER_TYPE_BUY_STOP: Final = ENUM_ORDER_TYPE.ORDER_TYPE_BUY_STOP
ORDER_TYPE_SELL_STOP: Final = ENUM_ORDER_TYPE.ORDER_TYPE_SELL_STOP
ORDER_TYPE_BUY_STOP_LIMIT: Final = ENUM_ORDER_TYPE.ORDER_TYPE_BUY_STOP_LIMIT
ORDER_TYPE_SELL_STOP_LIMIT: Final = ENUM_ORDER_TYPE.ORDER_TYPE_SELL_STOP_LIMIT
ORDER_TYPE_CLOSE_BY: Final = ENUM_ORDER_TYPE.ORDER_TYPE_CLOSE_BY


class ENUM_ORDER_TYPE_FILLING(IntEnum):
    """Defines the identifier set for order type filling."""

    ORDER_FILLING_FOK = 0
    ORDER_FILLING_IOC = 1
    ORDER_FILLING_BOC = 3
    ORDER_FILLING_RETURN = 2


ORDER_FILLING_FOK: Final = ENUM_ORDER_TYPE_FILLING.ORDER_FILLING_FOK
ORDER_FILLING_IOC: Final = ENUM_ORDER_TYPE_FILLING.ORDER_FILLING_IOC
ORDER_FILLING_BOC: Final = ENUM_ORDER_TYPE_FILLING.ORDER_FILLING_BOC
ORDER_FILLING_RETURN: Final = ENUM_ORDER_TYPE_FILLING.ORDER_FILLING_RETURN


class ENUM_ORDER_TYPE_TIME(IntEnum):
    """Defines the identifier set for order type time."""

    ORDER_TIME_GTC = 0
    ORDER_TIME_DAY = 1
    ORDER_TIME_SPECIFIED = 2
    ORDER_TIME_SPECIFIED_DAY = 3


ORDER_TIME_GTC: Final = ENUM_ORDER_TYPE_TIME.ORDER_TIME_GTC
ORDER_TIME_DAY: Final = ENUM_ORDER_TYPE_TIME.ORDER_TIME_DAY
ORDER_TIME_SPECIFIED: Final = ENUM_ORDER_TYPE_TIME.ORDER_TIME_SPECIFIED
ORDER_TIME_SPECIFIED_DAY: Final = ENUM_ORDER_TYPE_TIME.ORDER_TIME_SPECIFIED_DAY


class ENUM_POSITION_PROPERTY_DOUBLE(IntEnum):
    """Defines the identifier set for position property double."""

    POSITION_VOLUME = 0
    POSITION_PRICE_OPEN = 1
    POSITION_SL = 2
    POSITION_TP = 3
    POSITION_PRICE_CURRENT = 4
    POSITION_SWAP = 5
    POSITION_PROFIT = 6


POSITION_VOLUME: Final = ENUM_POSITION_PROPERTY_DOUBLE.POSITION_VOLUME
POSITION_PRICE_OPEN: Final = ENUM_POSITION_PROPERTY_DOUBLE.POSITION_PRICE_OPEN
POSITION_SL: Final = ENUM_POSITION_PROPERTY_DOUBLE.POSITION_SL
POSITION_TP: Final = ENUM_POSITION_PROPERTY_DOUBLE.POSITION_TP
POSITION_PRICE_CURRENT: Final = ENUM_POSITION_PROPERTY_DOUBLE.POSITION_PRICE_CURRENT
POSITION_SWAP: Final = ENUM_POSITION_PROPERTY_DOUBLE.POSITION_SWAP
POSITION_PROFIT: Final = ENUM_POSITION_PROPERTY_DOUBLE.POSITION_PROFIT


class ENUM_POSITION_PROPERTY_INTEGER(IntEnum):
    """Defines the identifier set for position property integer."""

    POSITION_TICKET = 0
    POSITION_TIME = 1
    POSITION_TIME_MSC = 2
    POSITION_TIME_UPDATE = 3
    POSITION_TIME_UPDATE_MSC = 4
    POSITION_TYPE = 5
    POSITION_MAGIC = 6
    POSITION_IDENTIFIER = 7
    POSITION_REASON = 8


POSITION_TICKET: Final = ENUM_POSITION_PROPERTY_INTEGER.POSITION_TICKET
POSITION_TIME: Final = ENUM_POSITION_PROPERTY_INTEGER.POSITION_TIME
POSITION_TIME_MSC: Final = ENUM_POSITION_PROPERTY_INTEGER.POSITION_TIME_MSC
POSITION_TIME_UPDATE: Final = ENUM_POSITION_PROPERTY_INTEGER.POSITION_TIME_UPDATE
POSITION_TIME_UPDATE_MSC: Final = (
    ENUM_POSITION_PROPERTY_INTEGER.POSITION_TIME_UPDATE_MSC
)
POSITION_TYPE: Final = ENUM_POSITION_PROPERTY_INTEGER.POSITION_TYPE
POSITION_MAGIC: Final = ENUM_POSITION_PROPERTY_INTEGER.POSITION_MAGIC
POSITION_IDENTIFIER: Final = ENUM_POSITION_PROPERTY_INTEGER.POSITION_IDENTIFIER
POSITION_REASON: Final = ENUM_POSITION_PROPERTY_INTEGER.POSITION_REASON


class ENUM_POSITION_PROPERTY_STRING(IntEnum):
    """Defines the identifier set for position property string."""

    POSITION_SYMBOL = 0
    POSITION_COMMENT = 1
    POSITION_EXTERNAL_ID = 2


POSITION_SYMBOL: Final = ENUM_POSITION_PROPERTY_STRING.POSITION_SYMBOL
POSITION_COMMENT: Final = ENUM_POSITION_PROPERTY_STRING.POSITION_COMMENT
POSITION_EXTERNAL_ID: Final = ENUM_POSITION_PROPERTY_STRING.POSITION_EXTERNAL_ID


class ENUM_POSITION_REASON(IntEnum):
    """Defines the identifier set for position reason."""

    POSITION_REASON_CLIENT = 0
    POSITION_REASON_MOBILE = 1
    POSITION_REASON_WEB = 2
    POSITION_REASON_AUTOMATION = 3


POSITION_REASON_CLIENT: Final = ENUM_POSITION_REASON.POSITION_REASON_CLIENT
POSITION_REASON_MOBILE: Final = ENUM_POSITION_REASON.POSITION_REASON_MOBILE
POSITION_REASON_WEB: Final = ENUM_POSITION_REASON.POSITION_REASON_WEB
POSITION_REASON_AUTOMATION: Final = ENUM_POSITION_REASON.POSITION_REASON_AUTOMATION


class ENUM_POSITION_TYPE(IntEnum):
    """Defines the identifier set for position type."""

    POSITION_TYPE_BUY = 0
    POSITION_TYPE_SELL = 1


POSITION_TYPE_BUY: Final = ENUM_POSITION_TYPE.POSITION_TYPE_BUY
POSITION_TYPE_SELL: Final = ENUM_POSITION_TYPE.POSITION_TYPE_SELL


class ENUM_TRADE_REQUEST_ACTIONS(IntEnum):
    """Defines the identifier set for trade request actions."""

    TRADE_ACTION_DEAL = 1
    TRADE_ACTION_PENDING = 5
    TRADE_ACTION_SLTP = 6
    TRADE_ACTION_MODIFY = 7
    TRADE_ACTION_REMOVE = 8
    TRADE_ACTION_CLOSE_BY = 10


TRADE_ACTION_DEAL: Final = ENUM_TRADE_REQUEST_ACTIONS.TRADE_ACTION_DEAL
TRADE_ACTION_PENDING: Final = ENUM_TRADE_REQUEST_ACTIONS.TRADE_ACTION_PENDING
TRADE_ACTION_SLTP: Final = ENUM_TRADE_REQUEST_ACTIONS.TRADE_ACTION_SLTP
TRADE_ACTION_MODIFY: Final = ENUM_TRADE_REQUEST_ACTIONS.TRADE_ACTION_MODIFY
TRADE_ACTION_REMOVE: Final = ENUM_TRADE_REQUEST_ACTIONS.TRADE_ACTION_REMOVE
TRADE_ACTION_CLOSE_BY: Final = ENUM_TRADE_REQUEST_ACTIONS.TRADE_ACTION_CLOSE_BY


class ENUM_TRADE_TRANSACTION_TYPE(IntEnum):
    """Defines the identifier set for trade transaction type."""

    TRADE_TRANSACTION_ORDER_ADD = 0
    TRADE_TRANSACTION_ORDER_UPDATE = 1
    TRADE_TRANSACTION_ORDER_DELETE = 2
    TRADE_TRANSACTION_DEAL_ADD = 3
    TRADE_TRANSACTION_DEAL_UPDATE = 4
    TRADE_TRANSACTION_DEAL_DELETE = 5
    TRADE_TRANSACTION_HISTORY_ADD = 6
    TRADE_TRANSACTION_HISTORY_UPDATE = 7
    TRADE_TRANSACTION_HISTORY_DELETE = 8
    TRADE_TRANSACTION_POSITION = 9
    TRADE_TRANSACTION_REQUEST = 10


TRADE_TRANSACTION_ORDER_ADD: Final = (
    ENUM_TRADE_TRANSACTION_TYPE.TRADE_TRANSACTION_ORDER_ADD
)
TRADE_TRANSACTION_ORDER_UPDATE: Final = (
    ENUM_TRADE_TRANSACTION_TYPE.TRADE_TRANSACTION_ORDER_UPDATE
)
TRADE_TRANSACTION_ORDER_DELETE: Final = (
    ENUM_TRADE_TRANSACTION_TYPE.TRADE_TRANSACTION_ORDER_DELETE
)
TRADE_TRANSACTION_DEAL_ADD: Final = (
    ENUM_TRADE_TRANSACTION_TYPE.TRADE_TRANSACTION_DEAL_ADD
)
TRADE_TRANSACTION_DEAL_UPDATE: Final = (
    ENUM_TRADE_TRANSACTION_TYPE.TRADE_TRANSACTION_DEAL_UPDATE
)
TRADE_TRANSACTION_DEAL_DELETE: Final = (
    ENUM_TRADE_TRANSACTION_TYPE.TRADE_TRANSACTION_DEAL_DELETE
)
TRADE_TRANSACTION_HISTORY_ADD: Final = (
    ENUM_TRADE_TRANSACTION_TYPE.TRADE_TRANSACTION_HISTORY_ADD
)
TRADE_TRANSACTION_HISTORY_UPDATE: Final = (
    ENUM_TRADE_TRANSACTION_TYPE.TRADE_TRANSACTION_HISTORY_UPDATE
)
TRADE_TRANSACTION_HISTORY_DELETE: Final = (
    ENUM_TRADE_TRANSACTION_TYPE.TRADE_TRANSACTION_HISTORY_DELETE
)
TRADE_TRANSACTION_POSITION: Final = (
    ENUM_TRADE_TRANSACTION_TYPE.TRADE_TRANSACTION_POSITION
)
TRADE_TRANSACTION_REQUEST: Final = ENUM_TRADE_TRANSACTION_TYPE.TRADE_TRANSACTION_REQUEST

__all__ = [
    "DEAL_COMMENT",
    "DEAL_COMMISSION",
    "DEAL_DIVIDEND",
    "DEAL_DIVIDEND_FRANKED",
    "DEAL_ENTRY",
    "DEAL_ENTRY_IN",
    "DEAL_ENTRY_INOUT",
    "DEAL_ENTRY_OUT",
    "DEAL_ENTRY_OUT_BY",
    "DEAL_EXTERNAL_ID",
    "DEAL_FEE",
    "DEAL_MAGIC",
    "DEAL_ORDER",
    "DEAL_POSITION_ID",
    "DEAL_PRICE",
    "DEAL_PROFIT",
    "DEAL_REASON",
    "DEAL_REASON_AUTOMATION",
    "DEAL_REASON_CLIENT",
    "DEAL_REASON_CORPORATE_ACTION",
    "DEAL_REASON_MOBILE",
    "DEAL_REASON_ROLLOVER",
    "DEAL_REASON_SL",
    "DEAL_REASON_SO",
    "DEAL_REASON_SPLIT",
    "DEAL_REASON_TP",
    "DEAL_REASON_VMARGIN",
    "DEAL_REASON_WEB",
    "DEAL_SL",
    "DEAL_SWAP",
    "DEAL_SYMBOL",
    "DEAL_TAX",
    "DEAL_TICKET",
    "DEAL_TIME",
    "DEAL_TIME_MSC",
    "DEAL_TP",
    "DEAL_TYPE",
    "DEAL_TYPE_BALANCE",
    "DEAL_TYPE_BONUS",
    "DEAL_TYPE_BUY",
    "DEAL_TYPE_BUY_CANCELED",
    "DEAL_TYPE_CHARGE",
    "DEAL_TYPE_COMMISSION",
    "DEAL_TYPE_COMMISSION_AGENT_DAILY",
    "DEAL_TYPE_COMMISSION_AGENT_MONTHLY",
    "DEAL_TYPE_COMMISSION_DAILY",
    "DEAL_TYPE_COMMISSION_MONTHLY",
    "DEAL_TYPE_CORRECTION",
    "DEAL_TYPE_CREDIT",
    "DEAL_TYPE_INTEREST",
    "DEAL_TYPE_SELL",
    "DEAL_TYPE_SELL_CANCELED",
    "DEAL_VOLUME",
    "ENUM_DEAL_ENTRY",
    "ENUM_DEAL_PROPERTY_DOUBLE",
    "ENUM_DEAL_PROPERTY_INTEGER",
    "ENUM_DEAL_PROPERTY_STRING",
    "ENUM_DEAL_REASON",
    "ENUM_DEAL_TYPE",
    "ENUM_ORDER_PROPERTY_DOUBLE",
    "ENUM_ORDER_PROPERTY_INTEGER",
    "ENUM_ORDER_PROPERTY_STRING",
    "ENUM_ORDER_REASON",
    "ENUM_ORDER_STATE",
    "ENUM_ORDER_TYPE",
    "ENUM_ORDER_TYPE_FILLING",
    "ENUM_ORDER_TYPE_TIME",
    "ENUM_POSITION_PROPERTY_DOUBLE",
    "ENUM_POSITION_PROPERTY_INTEGER",
    "ENUM_POSITION_PROPERTY_STRING",
    "ENUM_POSITION_REASON",
    "ENUM_POSITION_TYPE",
    "ENUM_TRADE_REQUEST_ACTIONS",
    "ENUM_TRADE_TRANSACTION_TYPE",
    "ORDER_COMMENT",
    "ORDER_EXTERNAL_ID",
    "ORDER_FILLING_BOC",
    "ORDER_FILLING_FOK",
    "ORDER_FILLING_IOC",
    "ORDER_FILLING_RETURN",
    "ORDER_MAGIC",
    "ORDER_POSITION_BY_ID",
    "ORDER_POSITION_ID",
    "ORDER_PRICE_CURRENT",
    "ORDER_PRICE_OPEN",
    "ORDER_PRICE_STOPLIMIT",
    "ORDER_REASON",
    "ORDER_REASON_AUTOMATION",
    "ORDER_REASON_CLIENT",
    "ORDER_REASON_MOBILE",
    "ORDER_REASON_SL",
    "ORDER_REASON_SO",
    "ORDER_REASON_TP",
    "ORDER_REASON_WEB",
    "ORDER_SL",
    "ORDER_STATE",
    "ORDER_STATE_CANCELED",
    "ORDER_STATE_EXPIRED",
    "ORDER_STATE_FILLED",
    "ORDER_STATE_PARTIAL",
    "ORDER_STATE_PLACED",
    "ORDER_STATE_REJECTED",
    "ORDER_STATE_REQUEST_ADD",
    "ORDER_STATE_REQUEST_CANCEL",
    "ORDER_STATE_REQUEST_MODIFY",
    "ORDER_STATE_STARTED",
    "ORDER_SYMBOL",
    "ORDER_TICKET",
    "ORDER_TIME_DAY",
    "ORDER_TIME_DONE",
    "ORDER_TIME_DONE_MSC",
    "ORDER_TIME_EXPIRATION",
    "ORDER_TIME_GTC",
    "ORDER_TIME_SETUP",
    "ORDER_TIME_SETUP_MSC",
    "ORDER_TIME_SPECIFIED",
    "ORDER_TIME_SPECIFIED_DAY",
    "ORDER_TP",
    "ORDER_TYPE",
    "ORDER_TYPE_BUY",
    "ORDER_TYPE_BUY_LIMIT",
    "ORDER_TYPE_BUY_STOP",
    "ORDER_TYPE_BUY_STOP_LIMIT",
    "ORDER_TYPE_CLOSE_BY",
    "ORDER_TYPE_FILLING",
    "ORDER_TYPE_SELL",
    "ORDER_TYPE_SELL_LIMIT",
    "ORDER_TYPE_SELL_STOP",
    "ORDER_TYPE_SELL_STOP_LIMIT",
    "ORDER_TYPE_TIME",
    "ORDER_VOLUME_CURRENT",
    "ORDER_VOLUME_INITIAL",
    "POSITION_COMMENT",
    "POSITION_EXTERNAL_ID",
    "POSITION_IDENTIFIER",
    "POSITION_MAGIC",
    "POSITION_PRICE_CURRENT",
    "POSITION_PRICE_OPEN",
    "POSITION_PROFIT",
    "POSITION_REASON",
    "POSITION_REASON_AUTOMATION",
    "POSITION_REASON_CLIENT",
    "POSITION_REASON_MOBILE",
    "POSITION_REASON_WEB",
    "POSITION_SL",
    "POSITION_SWAP",
    "POSITION_SYMBOL",
    "POSITION_TICKET",
    "POSITION_TIME",
    "POSITION_TIME_MSC",
    "POSITION_TIME_UPDATE",
    "POSITION_TIME_UPDATE_MSC",
    "POSITION_TP",
    "POSITION_TYPE",
    "POSITION_TYPE_BUY",
    "POSITION_TYPE_SELL",
    "POSITION_VOLUME",
    "TRADE_ACTION_CLOSE_BY",
    "TRADE_ACTION_DEAL",
    "TRADE_ACTION_MODIFY",
    "TRADE_ACTION_PENDING",
    "TRADE_ACTION_REMOVE",
    "TRADE_ACTION_SLTP",
    "TRADE_TRANSACTION_DEAL_ADD",
    "TRADE_TRANSACTION_DEAL_DELETE",
    "TRADE_TRANSACTION_DEAL_UPDATE",
    "TRADE_TRANSACTION_HISTORY_ADD",
    "TRADE_TRANSACTION_HISTORY_DELETE",
    "TRADE_TRANSACTION_HISTORY_UPDATE",
    "TRADE_TRANSACTION_ORDER_ADD",
    "TRADE_TRANSACTION_ORDER_DELETE",
    "TRADE_TRANSACTION_ORDER_UPDATE",
    "TRADE_TRANSACTION_POSITION",
    "TRADE_TRANSACTION_REQUEST",
]
