import type { RuleNode } from '../../host/types';

export interface StrategyTemplate {
  id: string;
  name: string;
  category: 'Trend Following' | 'Breakout' | 'Mean Reversion' | 'Trade Management';
  description: string;
  symbol: string;
  timeframe: string;
  executionModel: 'On Bar Open' | 'On Bar Close';
  variables: { name: string; value: number | string; optimize: boolean }[];
  rules: RuleNode[];
}

export const STRATEGY_TEMPLATES: StrategyTemplate[] = [
  {
    id: 'ema-cross',
    name: 'EMA Cross',
    category: 'Trend Following',
    description: 'Classic trend-following strategy entering market when faster EMA crosses above or below slower EMA with Stop Loss and Profit Target.',
    symbol: 'EURUSD',
    timeframe: 'H1',
    executionModel: 'On Bar Close',
    variables: [
      { name: 'FastPeriod', value: 20, optimize: true },
      { name: 'SlowPeriod', value: 50, optimize: true },
      { name: 'StopLoss', value: 60, optimize: true },
      { name: 'TakeProfit', value: 120, optimize: true },
    ],
    rules: [
      {
        id: 'r-le-group',
        depth: 0,
        kind: 'event',
        label: 'Long Entry Signal',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-le-if',
        depth: 1,
        kind: 'if',
        label: 'IF',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-le-c1',
        depth: 2,
        kind: 'condition',
        label: 'EMA(FastPeriod) crosses above EMA(SlowPeriod)',
        operator: 'AND',
        leftExpr: 'EMA(FastPeriod)',
        compOp: 'crosses above',
        rightExpr: 'EMA(SlowPeriod)',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-le-then',
        depth: 1,
        kind: 'then',
        label: 'THEN',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-le-a1',
        depth: 2,
        kind: 'action',
        label: 'Enter at Market (Long)',
        actionType: 'Enter at Market',
        actionParams: { direction: 'Long', lots: 0.1 },
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-le-a2',
        depth: 2,
        kind: 'action',
        label: 'Set Stop Loss: StopLoss pips',
        actionType: 'Set Stop Loss',
        actionParams: { pips: 60 },
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-le-a3',
        depth: 2,
        kind: 'action',
        label: 'Set Profit Target: TakeProfit pips',
        actionType: 'Set Profit Target',
        actionParams: { pips: 120 },
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-se-group',
        depth: 0,
        kind: 'event',
        label: 'Short Entry Signal',
        signalGroup: 'Short Entry',
      },
      {
        id: 'r-se-if',
        depth: 1,
        kind: 'if',
        label: 'IF',
        signalGroup: 'Short Entry',
      },
      {
        id: 'r-se-c1',
        depth: 2,
        kind: 'condition',
        label: 'EMA(FastPeriod) crosses below EMA(SlowPeriod)',
        operator: 'AND',
        leftExpr: 'EMA(FastPeriod)',
        compOp: 'crosses below',
        rightExpr: 'EMA(SlowPeriod)',
        signalGroup: 'Short Entry',
      },
      {
        id: 'r-se-then',
        depth: 1,
        kind: 'then',
        label: 'THEN',
        signalGroup: 'Short Entry',
      },
      {
        id: 'r-se-a1',
        depth: 2,
        kind: 'action',
        label: 'Enter at Market (Short)',
        actionType: 'Enter at Market',
        actionParams: { direction: 'Short', lots: 0.1 },
        signalGroup: 'Short Entry',
      },
      {
        id: 'r-se-a2',
        depth: 2,
        kind: 'action',
        label: 'Set Stop Loss: StopLoss pips',
        actionType: 'Set Stop Loss',
        actionParams: { pips: 60 },
        signalGroup: 'Short Entry',
      },
      {
        id: 'r-se-a3',
        depth: 2,
        kind: 'action',
        label: 'Set Profit Target: TakeProfit pips',
        actionType: 'Set Profit Target',
        actionParams: { pips: 120 },
        signalGroup: 'Short Entry',
      },
    ],
  },
  {
    id: 'inside-bar-breakout',
    name: 'Inside Bar Breakout',
    category: 'Breakout',
    description: 'High timeframe breakout strategy placing Stop orders above and below an inside bar with opposite boundary Stop Loss.',
    symbol: 'GBPUSD',
    timeframe: 'D1',
    executionModel: 'On Bar Open',
    variables: [
      { name: 'BreakoutOffsetPips', value: 5, optimize: true },
      { name: 'TrailAtrPeriod', value: 14, optimize: false },
    ],
    rules: [
      {
        id: 'r-ib-group',
        depth: 0,
        kind: 'event',
        label: 'Inside Bar Setup',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-ib-if',
        depth: 1,
        kind: 'if',
        label: 'IF',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-ib-c1',
        depth: 2,
        kind: 'condition',
        label: 'High[1] < High[2]',
        operator: 'AND',
        leftExpr: 'High[1]',
        compOp: '<',
        rightExpr: 'High[2]',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-ib-c2',
        depth: 2,
        kind: 'condition',
        label: 'Low[1] > Low[2]',
        operator: 'AND',
        leftExpr: 'Low[1]',
        compOp: '>',
        rightExpr: 'Low[2]',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-ib-then',
        depth: 1,
        kind: 'then',
        label: 'THEN',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-ib-a1',
        depth: 2,
        kind: 'action',
        label: 'Place Stop Order: High[1] + BreakoutOffsetPips',
        actionType: 'Place Stop Order',
        actionParams: { priceOffset: 5, direction: 'Long' },
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-ib-a2',
        depth: 2,
        kind: 'action',
        label: 'Set Stop Loss: Low[1]',
        actionType: 'Set Stop Loss',
        actionParams: { ref: 'Low[1]' },
        signalGroup: 'Long Entry',
      },
    ],
  },
  {
    id: 'range-breakout',
    name: 'Range Breakout',
    category: 'Breakout',
    description: 'Enters market when price breaks above or below the highest/lowest range of N bars with an ATR trailing stop.',
    symbol: 'USDJPY',
    timeframe: 'H4',
    executionModel: 'On Bar Close',
    variables: [
      { name: 'RangeBars', value: 24, optimize: true },
      { name: 'ATR_Period', value: 14, optimize: false },
      { name: 'ATR_Multiplier', value: 2.5, optimize: true },
    ],
    rules: [
      {
        id: 'r-rb-group',
        depth: 0,
        kind: 'event',
        label: 'Channel Breakout Long',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-rb-if',
        depth: 1,
        kind: 'if',
        label: 'IF',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-rb-c1',
        depth: 2,
        kind: 'condition',
        label: 'Close[0] > Highest(High, RangeBars)[1]',
        operator: 'AND',
        leftExpr: 'Close[0]',
        compOp: '>',
        rightExpr: 'Highest(High, RangeBars)[1]',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-rb-then',
        depth: 1,
        kind: 'then',
        label: 'THEN',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-rb-a1',
        depth: 2,
        kind: 'action',
        label: 'Enter at Market (Long)',
        actionType: 'Enter at Market',
        actionParams: { direction: 'Long', lots: 0.1 },
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-rb-a2',
        depth: 2,
        kind: 'action',
        label: 'Trailing Stop: ATR(ATR_Period) * ATR_Multiplier',
        actionType: 'Trailing Stop',
        actionParams: { atrMult: 2.5 },
        signalGroup: 'Long Entry',
      },
    ],
  },
  {
    id: 'mean-reversion',
    name: 'Mean Reversion',
    category: 'Mean Reversion',
    description: 'RSI oversold bounce from lower Bollinger Band aiming for middle band target.',
    symbol: 'EURUSD',
    timeframe: 'M15',
    executionModel: 'On Bar Close',
    variables: [
      { name: 'RSI_Period', value: 14, optimize: true },
      { name: 'RSI_Oversold', value: 30, optimize: true },
      { name: 'BB_Period', value: 20, optimize: false },
    ],
    rules: [
      {
        id: 'r-mr-group',
        depth: 0,
        kind: 'event',
        label: 'RSI Oversold Bounce',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-mr-if',
        depth: 1,
        kind: 'if',
        label: 'IF',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-mr-c1',
        depth: 2,
        kind: 'condition',
        label: 'RSI(RSI_Period) < RSI_Oversold',
        operator: 'AND',
        leftExpr: 'RSI(RSI_Period)',
        compOp: '<',
        rightExpr: 'RSI_Oversold',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-mr-c2',
        depth: 2,
        kind: 'condition',
        label: 'Close[0] <= BollingerLower(BB_Period, 2.0)',
        operator: 'AND',
        leftExpr: 'Close[0]',
        compOp: '<=',
        rightExpr: 'BollingerLower(BB_Period, 2.0)',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-mr-then',
        depth: 1,
        kind: 'then',
        label: 'THEN',
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-mr-a1',
        depth: 2,
        kind: 'action',
        label: 'Enter at Market (Long)',
        actionType: 'Enter at Market',
        actionParams: { direction: 'Long', lots: 0.1 },
        signalGroup: 'Long Entry',
      },
      {
        id: 'r-mr-a2',
        depth: 2,
        kind: 'action',
        label: 'Set Profit Target: BollingerMiddle(BB_Period)',
        actionType: 'Set Profit Target',
        actionParams: { target: 'BB_Middle' },
        signalGroup: 'Long Entry',
      },
    ],
  },
  {
    id: 'trail-stop-ea',
    name: 'Trail Stop by EA',
    category: 'Trade Management',
    description: 'Rule-based programmatic dynamic trailing stop updating Stop Loss to the lowest low of previous 5 bars.',
    symbol: 'XAUUSD',
    timeframe: 'H1',
    executionModel: 'On Bar Close',
    variables: [
      { name: 'LookbackBars', value: 5, optimize: true },
      { name: 'BufferPips', value: 10, optimize: false },
    ],
    rules: [
      {
        id: 'r-ts-group',
        depth: 0,
        kind: 'event',
        label: 'Trail Stop Event',
        signalGroup: 'Long Exit',
      },
      {
        id: 'r-ts-if',
        depth: 1,
        kind: 'if',
        label: 'IF',
        signalGroup: 'Long Exit',
      },
      {
        id: 'r-ts-c1',
        depth: 2,
        kind: 'condition',
        label: 'Lowest(Low, LookbackBars)[1] - BufferPips > PositionOpenPrice',
        operator: 'AND',
        leftExpr: 'Lowest(Low, LookbackBars)[1]',
        compOp: '>',
        rightExpr: 'PositionOpenPrice',
        signalGroup: 'Long Exit',
      },
      {
        id: 'r-ts-then',
        depth: 1,
        kind: 'then',
        label: 'THEN',
        signalGroup: 'Long Exit',
      },
      {
        id: 'r-ts-a1',
        depth: 2,
        kind: 'action',
        label: 'Move SL to Lowest(Low, LookbackBars)[1] - BufferPips',
        actionType: 'Trailing Stop',
        actionParams: { lookback: 5, buffer: 10 },
        signalGroup: 'Long Exit',
      },
    ],
  },
];
