"""Business-neutral shared infrastructure for HaruQuantAI domains."""

from app.utils.contracts import AuditEvent, AuthContext
from app.utils.errors import (
    ConfigurationError,
    ErrorMetadata,
    ErrorSink,
    ExternalServiceError,
    HaruQuantError,
    SecurityError,
    ValidationError,
    get_error_metadata,
    map_exception,
    normalize_error_code,
    route_error_event,
)
from app.utils.identity import derive_stable_id, generate_id, validate_id
from app.utils.logging import (
    BoundLogger,
    RedactingFilter,
    StructuredFormatter,
    configure_logging,
    flush_logging,
    get_logger,
    logger,
    shutdown_logging,
)
from app.utils.security import (
    RedactionPolicy,
    RedactionResult,
    SecretVersion,
    decrypt_text,
    encrypt_text,
    generate_fernet_key,
    hash_password,
    is_sensitive_key,
    redact_mapping_value,
    redact_text_value,
    select_active_secret_version,
    verify_password,
)
from app.utils.serialization import canonical_json, to_json_safe
from app.utils.settings import (
    AppSettings,
    LoggingSettings,
    RuntimeSettings,
    load_settings,
    resolve_secret_reference,
)
from app.utils.time import (
    Clock,
    SystemClock,
    age_seconds,
    format_utc_timestamp,
    is_fresh,
    parse_utc_timestamp,
    utc_now,
)

__all__ = (
    "AppSettings",
    "AuditEvent",
    "AuthContext",
    "BoundLogger",
    "Clock",
    "ConfigurationError",
    "ErrorMetadata",
    "ErrorSink",
    "ExternalServiceError",
    "HaruQuantError",
    "LoggingSettings",
    "RedactingFilter",
    "RedactionPolicy",
    "RedactionResult",
    "RuntimeSettings",
    "SecretVersion",
    "SecurityError",
    "StructuredFormatter",
    "SystemClock",
    "ValidationError",
    "age_seconds",
    "canonical_json",
    "configure_logging",
    "decrypt_text",
    "derive_stable_id",
    "encrypt_text",
    "flush_logging",
    "format_utc_timestamp",
    "generate_fernet_key",
    "generate_id",
    "get_error_metadata",
    "get_logger",
    "hash_password",
    "is_fresh",
    "is_sensitive_key",
    "load_settings",
    "logger",
    "map_exception",
    "normalize_error_code",
    "parse_utc_timestamp",
    "redact_mapping_value",
    "redact_text_value",
    "resolve_secret_reference",
    "route_error_event",
    "select_active_secret_version",
    "shutdown_logging",
    "to_json_safe",
    "utc_now",
    "validate_id",
    "verify_password",
)
