"""Deterministic limits engine package.

Runs pre-trade limits in a strict, sequential order, prioritizing hard-blocking
governance gates before execution feasibility and tail-risk exposure checks.
"""

from __future__ import annotations

from app.services.risk.limits.checks import (
    check_correlation_limit,
    check_currency_exposure_limit,
    check_daily_loss,
    check_daily_loss_limit,
    check_evidence_freshness,
    check_execution_limits,
    check_expected_shortfall_limit,
    check_exposure_limits,
    check_kill_switch,
    check_kill_switch_state,
    check_leverage_limit,
    check_margin_limit,
    check_max_drawdown_limit,
    check_news_blackout,
    check_pending_order_limit,
    check_portfolio_exposure_limit,
    check_rollover_blackout,
    check_slippage_limit,
    check_spread_limit,
    check_stale_evidence_limit,
    check_strategy_loss_limit,
    check_stress_loss_limit,
    check_symbol_exposure_limit,
    check_tail_risk_limits,
    check_total_drawdown,
    check_trade_frequency_limit,
    check_var_limit,
)
from app.services.risk.limits.contracts import (
    DEFAULT_LIMIT_PRECEDENCE,
    LimitAssessment,
    LimitCheck,
    LimitCheckFunction,
    LimitContext,
    LimitPrecedence,
    LimitResult,
)
from app.services.risk.limits.engine import (
    FUNCTION_TO_LIMIT_NAMES,
    ORDERED_LIMIT_CHECKS,
    REGISTERED_LIMIT_NAMES,
    LimitEngine,
    build_composite_breach_flags,
    check_risk_limits,
    evaluate_ordered_limits,
    run_limit_checks,
    select_primary_failure,
)

__all__ = [
    "DEFAULT_LIMIT_PRECEDENCE",
    "FUNCTION_TO_LIMIT_NAMES",
    "ORDERED_LIMIT_CHECKS",
    "REGISTERED_LIMIT_NAMES",
    "LimitAssessment",
    "LimitCheck",
    "LimitCheckFunction",
    "LimitContext",
    "LimitEngine",
    "LimitPrecedence",
    "LimitResult",
    "build_composite_breach_flags",
    "check_correlation_limit",
    "check_currency_exposure_limit",
    "check_daily_loss",
    "check_daily_loss_limit",
    "check_evidence_freshness",
    "check_execution_limits",
    "check_expected_shortfall_limit",
    "check_exposure_limits",
    "check_kill_switch",
    "check_kill_switch_state",
    "check_leverage_limit",
    "check_margin_limit",
    "check_max_drawdown_limit",
    "check_news_blackout",
    "check_pending_order_limit",
    "check_portfolio_exposure_limit",
    "check_risk_limits",
    "check_rollover_blackout",
    "check_slippage_limit",
    "check_spread_limit",
    "check_stale_evidence_limit",
    "check_strategy_loss_limit",
    "check_stress_loss_limit",
    "check_symbol_exposure_limit",
    "check_tail_risk_limits",
    "check_total_drawdown",
    "check_trade_frequency_limit",
    "check_var_limit",
    "evaluate_ordered_limits",
    "run_limit_checks",
    "select_primary_failure",
]
