# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from typing import Final

ERR_MARKET_UNKNOWN_SYMBOL: Final[int] = 4301
ERR_MARKET_NOT_SELECTED: Final[int] = 4302
ERR_MARKET_WRONG_PROPERTY: Final[int] = 4303
ERR_MARKET_LASTTIME_UNKNOWN: Final[int] = 4304
ERR_MARKET_SELECT_ERROR: Final[int] = 4305
ERR_MARKET_SELECT_LIMIT: Final[int] = 4306
ERR_MARKET_SESSION_INDEX: Final[int] = 4307
ERR_CUSTOM_SYMBOL_WRONG_NAME: Final[int] = 5301
ERR_CUSTOM_SYMBOL_NAME_LONG: Final[int] = 5302
ERR_CUSTOM_SYMBOL_PATH_LONG: Final[int] = 5303
ERR_CUSTOM_SYMBOL_EXIST: Final[int] = 5304
ERR_CUSTOM_SYMBOL_ERROR: Final[int] = 5305
ERR_CUSTOM_SYMBOL_SELECTED: Final[int] = 5306
ERR_CUSTOM_SYMBOL_PROPERTY_WRONG: Final[int] = 5307
ERR_CUSTOM_SYMBOL_PARAMETER_ERROR: Final[int] = 5308
ERR_CUSTOM_SYMBOL_PARAMETER_LONG: Final[int] = 5309

__all__ = [
    "ERR_CUSTOM_SYMBOL_ERROR",
    "ERR_CUSTOM_SYMBOL_EXIST",
    "ERR_CUSTOM_SYMBOL_NAME_LONG",
    "ERR_CUSTOM_SYMBOL_PARAMETER_ERROR",
    "ERR_CUSTOM_SYMBOL_PARAMETER_LONG",
    "ERR_CUSTOM_SYMBOL_PATH_LONG",
    "ERR_CUSTOM_SYMBOL_PROPERTY_WRONG",
    "ERR_CUSTOM_SYMBOL_SELECTED",
    "ERR_CUSTOM_SYMBOL_WRONG_NAME",
    "ERR_MARKET_LASTTIME_UNKNOWN",
    "ERR_MARKET_NOT_SELECTED",
    "ERR_MARKET_SELECT_ERROR",
    "ERR_MARKET_SELECT_LIMIT",
    "ERR_MARKET_SESSION_INDEX",
    "ERR_MARKET_UNKNOWN_SYMBOL",
    "ERR_MARKET_WRONG_PROPERTY",
]
