# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from enum import IntEnum
from typing import Final


class ENUM_DAY_OF_WEEK(IntEnum):
    """Defines the identifier set for day of week."""

    SUNDAY = 0
    MONDAY = 1
    TUESDAY = 2
    WEDNESDAY = 3
    THURSDAY = 4
    FRIDAY = 5
    SATURDAY = 6


SUNDAY: Final = ENUM_DAY_OF_WEEK.SUNDAY
MONDAY: Final = ENUM_DAY_OF_WEEK.MONDAY
TUESDAY: Final = ENUM_DAY_OF_WEEK.TUESDAY
WEDNESDAY: Final = ENUM_DAY_OF_WEEK.WEDNESDAY
THURSDAY: Final = ENUM_DAY_OF_WEEK.THURSDAY
FRIDAY: Final = ENUM_DAY_OF_WEEK.FRIDAY
SATURDAY: Final = ENUM_DAY_OF_WEEK.SATURDAY


class ENUM_SYMBOL_CALC_MODE(IntEnum):
    """Defines the identifier set for symbol calc mode."""

    SYMBOL_CALC_MODE_FOREX = 0
    SYMBOL_CALC_MODE_FOREX_NO_LEVERAGE = 5
    SYMBOL_CALC_MODE_FUTURES = 1
    SYMBOL_CALC_MODE_CFD = 2
    SYMBOL_CALC_MODE_CFDINDEX = 3
    SYMBOL_CALC_MODE_CFDLEVERAGE = 4
    SYMBOL_CALC_MODE_EXCH_STOCKS = 32
    SYMBOL_CALC_MODE_EXCH_FUTURES = 33
    SYMBOL_CALC_MODE_EXCH_FUTURES_FORTS = 8
    SYMBOL_CALC_MODE_EXCH_BONDS = 37
    SYMBOL_CALC_MODE_EXCH_STOCKS_MOEX = 38
    SYMBOL_CALC_MODE_EXCH_BONDS_MOEX = 39
    SYMBOL_CALC_MODE_SERV_COLLATERAL = 64


SYMBOL_CALC_MODE_FOREX: Final = ENUM_SYMBOL_CALC_MODE.SYMBOL_CALC_MODE_FOREX
SYMBOL_CALC_MODE_FOREX_NO_LEVERAGE: Final = (
    ENUM_SYMBOL_CALC_MODE.SYMBOL_CALC_MODE_FOREX_NO_LEVERAGE
)
SYMBOL_CALC_MODE_FUTURES: Final = ENUM_SYMBOL_CALC_MODE.SYMBOL_CALC_MODE_FUTURES
SYMBOL_CALC_MODE_CFD: Final = ENUM_SYMBOL_CALC_MODE.SYMBOL_CALC_MODE_CFD
SYMBOL_CALC_MODE_CFDINDEX: Final = ENUM_SYMBOL_CALC_MODE.SYMBOL_CALC_MODE_CFDINDEX
SYMBOL_CALC_MODE_CFDLEVERAGE: Final = ENUM_SYMBOL_CALC_MODE.SYMBOL_CALC_MODE_CFDLEVERAGE
SYMBOL_CALC_MODE_EXCH_STOCKS: Final = ENUM_SYMBOL_CALC_MODE.SYMBOL_CALC_MODE_EXCH_STOCKS
SYMBOL_CALC_MODE_EXCH_FUTURES: Final = (
    ENUM_SYMBOL_CALC_MODE.SYMBOL_CALC_MODE_EXCH_FUTURES
)
SYMBOL_CALC_MODE_EXCH_FUTURES_FORTS: Final = (
    ENUM_SYMBOL_CALC_MODE.SYMBOL_CALC_MODE_EXCH_FUTURES_FORTS
)
SYMBOL_CALC_MODE_EXCH_BONDS: Final = ENUM_SYMBOL_CALC_MODE.SYMBOL_CALC_MODE_EXCH_BONDS
SYMBOL_CALC_MODE_EXCH_STOCKS_MOEX: Final = (
    ENUM_SYMBOL_CALC_MODE.SYMBOL_CALC_MODE_EXCH_STOCKS_MOEX
)
SYMBOL_CALC_MODE_EXCH_BONDS_MOEX: Final = (
    ENUM_SYMBOL_CALC_MODE.SYMBOL_CALC_MODE_EXCH_BONDS_MOEX
)
SYMBOL_CALC_MODE_SERV_COLLATERAL: Final = (
    ENUM_SYMBOL_CALC_MODE.SYMBOL_CALC_MODE_SERV_COLLATERAL
)


class ENUM_SYMBOL_CHART_MODE(IntEnum):
    """Defines the identifier set for symbol chart mode."""

    SYMBOL_PATH = 0
    SYMBOL_CHART_MODE_BID = 0
    SYMBOL_CHART_MODE_LAST = 1


SYMBOL_PATH: Final = ENUM_SYMBOL_CHART_MODE.SYMBOL_PATH
SYMBOL_CHART_MODE_BID: Final = ENUM_SYMBOL_CHART_MODE.SYMBOL_CHART_MODE_BID
SYMBOL_CHART_MODE_LAST: Final = ENUM_SYMBOL_CHART_MODE.SYMBOL_CHART_MODE_LAST


class ENUM_SYMBOL_INDUSTRY(IntEnum):
    """Defines the identifier set for symbol industry."""

    INDUSTRY_UNDEFINED = 0
    INDUSTRY_AGRICULTURAL_INPUTS = 1
    INDUSTRY_ALUMINIUM = 2
    INDUSTRY_BUILDING_MATERIALS = 3
    INDUSTRY_CHEMICALS = 4
    INDUSTRY_COKING_COAL = 5
    INDUSTRY_COPPER = 6
    INDUSTRY_GOLD = 7
    INDUSTRY_LUMBER_WOOD = 8
    INDUSTRY_INDUSTRIAL_METALS = 9
    INDUSTRY_PRECIOUS_METALS = 10
    INDUSTRY_PAPER = 11
    INDUSTRY_SILVER = 12
    INDUSTRY_SPECIALTY_CHEMICALS = 13
    INDUSTRY_STEEL = 14
    INDUSTRY_ADVERTISING = 15
    INDUSTRY_BROADCASTING = 16
    INDUSTRY_GAMING_MULTIMEDIA = 17
    INDUSTRY_ENTERTAINMENT = 18
    INDUSTRY_INTERNET_CONTENT = 19
    INDUSTRY_PUBLISHING = 20
    INDUSTRY_TELECOM = 21
    INDUSTRY_APPAREL_MANUFACTURING = 22
    INDUSTRY_APPAREL_RETAIL = 23
    INDUSTRY_AUTO_MANUFACTURERS = 24
    INDUSTRY_AUTO_PARTS = 25
    INDUSTRY_AUTO_DEALERSHIP = 26
    INDUSTRY_DEPARTMENT_STORES = 27
    INDUSTRY_FOOTWEAR_ACCESSORIES = 28
    INDUSTRY_FURNISHINGS = 29
    INDUSTRY_GAMBLING = 30
    INDUSTRY_HOME_IMPROV_RETAIL = 31
    INDUSTRY_INTERNET_RETAIL = 32
    INDUSTRY_LEISURE = 33
    INDUSTRY_LODGING = 34
    INDUSTRY_LUXURY_GOODS = 35
    INDUSTRY_PACKAGING_CONTAINERS = 36
    INDUSTRY_PERSONAL_SERVICES = 37
    INDUSTRY_RECREATIONAL_VEHICLES = 38
    INDUSTRY_RESIDENT_CONSTRUCTION = 39
    INDUSTRY_RESORTS_CASINOS = 40
    INDUSTRY_RESTAURANTS = 41
    INDUSTRY_SPECIALTY_RETAIL = 42
    INDUSTRY_TEXTILE_MANUFACTURING = 43
    INDUSTRY_TRAVEL_SERVICES = 44
    INDUSTRY_BEVERAGES_BREWERS = 45
    INDUSTRY_BEVERAGES_NON_ALCO = 46
    INDUSTRY_BEVERAGES_WINERIES = 47
    INDUSTRY_CONFECTIONERS = 48
    INDUSTRY_DISCOUNT_STORES = 49
    INDUSTRY_EDUCATION_TRAINIG = 50
    INDUSTRY_FARM_PRODUCTS = 51
    INDUSTRY_FOOD_DISTRIBUTION = 52
    INDUSTRY_GROCERY_STORES = 53
    INDUSTRY_HOUSEHOLD_PRODUCTS = 54
    INDUSTRY_PACKAGED_FOODS = 55
    INDUSTRY_TOBACCO = 56
    INDUSTRY_OIL_GAS_DRILLING = 57
    INDUSTRY_OIL_GAS_EP = 58
    INDUSTRY_OIL_GAS_EQUIPMENT = 59
    INDUSTRY_OIL_GAS_INTEGRATED = 60
    INDUSTRY_OIL_GAS_MIDSTREAM = 61
    INDUSTRY_OIL_GAS_REFINING = 62
    INDUSTRY_THERMAL_COAL = 63
    INDUSTRY_URANIUM = 64
    INDUSTRY_EXCHANGE_TRADED_FUND = 65
    INDUSTRY_ASSETS_MANAGEMENT = 66
    INDUSTRY_BANKS_DIVERSIFIED = 67
    INDUSTRY_BANKS_REGIONAL = 68
    INDUSTRY_CAPITAL_MARKETS = 69
    INDUSTRY_CLOSE_END_FUND_DEBT = 70
    INDUSTRY_CLOSE_END_FUND_EQUITY = 71
    INDUSTRY_CLOSE_END_FUND_FOREIGN = 72
    INDUSTRY_CREDIT_SERVICES = 73
    INDUSTRY_FINANCIAL_CONGLOMERATE = 74
    INDUSTRY_FINANCIAL_DATA_EXCHANGE = 75
    INDUSTRY_INSURANCE_BROKERS = 76
    INDUSTRY_INSURANCE_DIVERSIFIED = 77
    INDUSTRY_INSURANCE_LIFE = 78
    INDUSTRY_INSURANCE_PROPERTY = 79
    INDUSTRY_INSURANCE_REINSURANCE = 80
    INDUSTRY_INSURANCE_SPECIALTY = 81
    INDUSTRY_MORTGAGE_FINANCE = 82
    INDUSTRY_SHELL_COMPANIES = 83
    INDUSTRY_BIOTECHNOLOGY = 84
    INDUSTRY_DIAGNOSTICS_RESEARCH = 85
    INDUSTRY_DRUGS_MANUFACTURERS = 86
    INDUSTRY_DRUGS_MANUFACTURERS_SPEC = 87
    INDUSTRY_HEALTHCARE_PLANS = 88
    INDUSTRY_HEALTH_INFORMATION = 89
    INDUSTRY_MEDICAL_FACILITIES = 90
    INDUSTRY_MEDICAL_DEVICES = 91
    INDUSTRY_MEDICAL_DISTRIBUTION = 92
    INDUSTRY_MEDICAL_INSTRUMENTS = 93
    INDUSTRY_PHARM_RETAILERS = 94
    INDUSTRY_AEROSPACE_DEFENSE = 95
    INDUSTRY_AIRLINES = 96
    INDUSTRY_AIRPORTS_SERVICES = 97
    INDUSTRY_BUILDING_PRODUCTS = 98
    INDUSTRY_BUSINESS_EQUIPMENT = 99
    INDUSTRY_CONGLOMERATES = 100
    INDUSTRY_CONSULTING_SERVICES = 101
    INDUSTRY_ELECTRICAL_EQUIPMENT = 102
    INDUSTRY_ENGINEERING_CONSTRUCTION = 103
    INDUSTRY_FARM_HEAVY_MACHINERY = 104
    INDUSTRY_INDUSTRIAL_DISTRIBUTION = 105
    INDUSTRY_INFRASTRUCTURE_OPERATIONS = 106
    INDUSTRY_FREIGHT_LOGISTICS = 107
    INDUSTRY_MARINE_SHIPPING = 108
    INDUSTRY_METAL_FABRICATION = 109
    INDUSTRY_POLLUTION_CONTROL = 110
    INDUSTRY_RAILROADS = 111
    INDUSTRY_RENTAL_LEASING = 112
    INDUSTRY_SECURITY_PROTECTION = 113
    INDUSTRY_SPEALITY_BUSINESS_SERVICES = 114
    INDUSTRY_SPEALITY_MACHINERY = 115
    INDUSTRY_STUFFING_EMPLOYMENT = 116
    INDUSTRY_TOOLS_ACCESSORIES = 117
    INDUSTRY_TRUCKING = 118
    INDUSTRY_WASTE_MANAGEMENT = 119
    INDUSTRY_REAL_ESTATE_DEVELOPMENT = 120
    INDUSTRY_REAL_ESTATE_DIVERSIFIED = 121
    INDUSTRY_REAL_ESTATE_SERVICES = 122
    INDUSTRY_REIT_DIVERSIFIED = 123
    INDUSTRY_REIT_HEALTCARE = 124
    INDUSTRY_REIT_HOTEL_MOTEL = 125
    INDUSTRY_REIT_INDUSTRIAL = 126
    INDUSTRY_REIT_MORTAGE = 127
    INDUSTRY_REIT_OFFICE = 128
    INDUSTRY_REIT_RESIDENTAL = 129
    INDUSTRY_REIT_RETAIL = 130
    INDUSTRY_REIT_SPECIALITY = 131
    INDUSTRY_COMMUNICATION_EQUIPMENT = 132
    INDUSTRY_COMPUTER_HARDWARE = 133
    INDUSTRY_CONSUMER_ELECTRONICS = 134
    INDUSTRY_ELECTRONIC_COMPONENTS = 135
    INDUSTRY_ELECTRONIC_DISTRIBUTION = 136
    INDUSTRY_IT_SERVICES = 137
    INDUSTRY_SCIENTIFIC_INSTRUMENTS = 138
    INDUSTRY_SEMICONDUCTOR_EQUIPMENT = 139
    INDUSTRY_SEMICONDUCTORS = 140
    INDUSTRY_SOFTWARE_APPLICATION = 141
    INDUSTRY_SOFTWARE_INFRASTRUCTURE = 142
    INDUSTRY_SOLAR = 143
    INDUSTRY_UTILITIES_DIVERSIFIED = 144
    INDUSTRY_UTILITIES_POWERPRODUCERS = 145
    INDUSTRY_UTILITIES_RENEWABLE = 146
    INDUSTRY_UTILITIES_REGULATED_ELECTRIC = 147
    INDUSTRY_UTILITIES_REGULATED_GAS = 148
    INDUSTRY_UTILITIES_REGULATED_WATER = 149
    INDUSTRY_UTILITIES_FIRST = 150
    INDUSTRY_UTILITIES_LAST = 151


INDUSTRY_UNDEFINED: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_UNDEFINED
INDUSTRY_AGRICULTURAL_INPUTS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_AGRICULTURAL_INPUTS
INDUSTRY_ALUMINIUM: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_ALUMINIUM
INDUSTRY_BUILDING_MATERIALS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_BUILDING_MATERIALS
INDUSTRY_CHEMICALS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_CHEMICALS
INDUSTRY_COKING_COAL: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_COKING_COAL
INDUSTRY_COPPER: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_COPPER
INDUSTRY_GOLD: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_GOLD
INDUSTRY_LUMBER_WOOD: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_LUMBER_WOOD
INDUSTRY_INDUSTRIAL_METALS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_INDUSTRIAL_METALS
INDUSTRY_PRECIOUS_METALS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_PRECIOUS_METALS
INDUSTRY_PAPER: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_PAPER
INDUSTRY_SILVER: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_SILVER
INDUSTRY_SPECIALTY_CHEMICALS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_SPECIALTY_CHEMICALS
INDUSTRY_STEEL: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_STEEL
INDUSTRY_ADVERTISING: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_ADVERTISING
INDUSTRY_BROADCASTING: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_BROADCASTING
INDUSTRY_GAMING_MULTIMEDIA: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_GAMING_MULTIMEDIA
INDUSTRY_ENTERTAINMENT: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_ENTERTAINMENT
INDUSTRY_INTERNET_CONTENT: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_INTERNET_CONTENT
INDUSTRY_PUBLISHING: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_PUBLISHING
INDUSTRY_TELECOM: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_TELECOM
INDUSTRY_APPAREL_MANUFACTURING: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_APPAREL_MANUFACTURING
)
INDUSTRY_APPAREL_RETAIL: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_APPAREL_RETAIL
INDUSTRY_AUTO_MANUFACTURERS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_AUTO_MANUFACTURERS
INDUSTRY_AUTO_PARTS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_AUTO_PARTS
INDUSTRY_AUTO_DEALERSHIP: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_AUTO_DEALERSHIP
INDUSTRY_DEPARTMENT_STORES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_DEPARTMENT_STORES
INDUSTRY_FOOTWEAR_ACCESSORIES: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_FOOTWEAR_ACCESSORIES
)
INDUSTRY_FURNISHINGS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_FURNISHINGS
INDUSTRY_GAMBLING: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_GAMBLING
INDUSTRY_HOME_IMPROV_RETAIL: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_HOME_IMPROV_RETAIL
INDUSTRY_INTERNET_RETAIL: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_INTERNET_RETAIL
INDUSTRY_LEISURE: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_LEISURE
INDUSTRY_LODGING: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_LODGING
INDUSTRY_LUXURY_GOODS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_LUXURY_GOODS
INDUSTRY_PACKAGING_CONTAINERS: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_PACKAGING_CONTAINERS
)
INDUSTRY_PERSONAL_SERVICES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_PERSONAL_SERVICES
INDUSTRY_RECREATIONAL_VEHICLES: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_RECREATIONAL_VEHICLES
)
INDUSTRY_RESIDENT_CONSTRUCTION: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_RESIDENT_CONSTRUCTION
)
INDUSTRY_RESORTS_CASINOS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_RESORTS_CASINOS
INDUSTRY_RESTAURANTS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_RESTAURANTS
INDUSTRY_SPECIALTY_RETAIL: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_SPECIALTY_RETAIL
INDUSTRY_TEXTILE_MANUFACTURING: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_TEXTILE_MANUFACTURING
)
INDUSTRY_TRAVEL_SERVICES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_TRAVEL_SERVICES
INDUSTRY_BEVERAGES_BREWERS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_BEVERAGES_BREWERS
INDUSTRY_BEVERAGES_NON_ALCO: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_BEVERAGES_NON_ALCO
INDUSTRY_BEVERAGES_WINERIES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_BEVERAGES_WINERIES
INDUSTRY_CONFECTIONERS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_CONFECTIONERS
INDUSTRY_DISCOUNT_STORES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_DISCOUNT_STORES
INDUSTRY_EDUCATION_TRAINIG: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_EDUCATION_TRAINIG
INDUSTRY_FARM_PRODUCTS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_FARM_PRODUCTS
INDUSTRY_FOOD_DISTRIBUTION: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_FOOD_DISTRIBUTION
INDUSTRY_GROCERY_STORES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_GROCERY_STORES
INDUSTRY_HOUSEHOLD_PRODUCTS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_HOUSEHOLD_PRODUCTS
INDUSTRY_PACKAGED_FOODS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_PACKAGED_FOODS
INDUSTRY_TOBACCO: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_TOBACCO
INDUSTRY_OIL_GAS_DRILLING: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_OIL_GAS_DRILLING
INDUSTRY_OIL_GAS_EP: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_OIL_GAS_EP
INDUSTRY_OIL_GAS_EQUIPMENT: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_OIL_GAS_EQUIPMENT
INDUSTRY_OIL_GAS_INTEGRATED: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_OIL_GAS_INTEGRATED
INDUSTRY_OIL_GAS_MIDSTREAM: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_OIL_GAS_MIDSTREAM
INDUSTRY_OIL_GAS_REFINING: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_OIL_GAS_REFINING
INDUSTRY_THERMAL_COAL: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_THERMAL_COAL
INDUSTRY_URANIUM: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_URANIUM
INDUSTRY_EXCHANGE_TRADED_FUND: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_EXCHANGE_TRADED_FUND
)
INDUSTRY_ASSETS_MANAGEMENT: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_ASSETS_MANAGEMENT
INDUSTRY_BANKS_DIVERSIFIED: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_BANKS_DIVERSIFIED
INDUSTRY_BANKS_REGIONAL: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_BANKS_REGIONAL
INDUSTRY_CAPITAL_MARKETS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_CAPITAL_MARKETS
INDUSTRY_CLOSE_END_FUND_DEBT: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_CLOSE_END_FUND_DEBT
INDUSTRY_CLOSE_END_FUND_EQUITY: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_CLOSE_END_FUND_EQUITY
)
INDUSTRY_CLOSE_END_FUND_FOREIGN: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_CLOSE_END_FUND_FOREIGN
)
INDUSTRY_CREDIT_SERVICES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_CREDIT_SERVICES
INDUSTRY_FINANCIAL_CONGLOMERATE: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_FINANCIAL_CONGLOMERATE
)
INDUSTRY_FINANCIAL_DATA_EXCHANGE: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_FINANCIAL_DATA_EXCHANGE
)
INDUSTRY_INSURANCE_BROKERS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_INSURANCE_BROKERS
INDUSTRY_INSURANCE_DIVERSIFIED: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_INSURANCE_DIVERSIFIED
)
INDUSTRY_INSURANCE_LIFE: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_INSURANCE_LIFE
INDUSTRY_INSURANCE_PROPERTY: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_INSURANCE_PROPERTY
INDUSTRY_INSURANCE_REINSURANCE: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_INSURANCE_REINSURANCE
)
INDUSTRY_INSURANCE_SPECIALTY: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_INSURANCE_SPECIALTY
INDUSTRY_MORTGAGE_FINANCE: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_MORTGAGE_FINANCE
INDUSTRY_SHELL_COMPANIES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_SHELL_COMPANIES
INDUSTRY_BIOTECHNOLOGY: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_BIOTECHNOLOGY
INDUSTRY_DIAGNOSTICS_RESEARCH: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_DIAGNOSTICS_RESEARCH
)
INDUSTRY_DRUGS_MANUFACTURERS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_DRUGS_MANUFACTURERS
INDUSTRY_DRUGS_MANUFACTURERS_SPEC: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_DRUGS_MANUFACTURERS_SPEC
)
INDUSTRY_HEALTHCARE_PLANS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_HEALTHCARE_PLANS
INDUSTRY_HEALTH_INFORMATION: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_HEALTH_INFORMATION
INDUSTRY_MEDICAL_FACILITIES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_MEDICAL_FACILITIES
INDUSTRY_MEDICAL_DEVICES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_MEDICAL_DEVICES
INDUSTRY_MEDICAL_DISTRIBUTION: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_MEDICAL_DISTRIBUTION
)
INDUSTRY_MEDICAL_INSTRUMENTS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_MEDICAL_INSTRUMENTS
INDUSTRY_PHARM_RETAILERS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_PHARM_RETAILERS
INDUSTRY_AEROSPACE_DEFENSE: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_AEROSPACE_DEFENSE
INDUSTRY_AIRLINES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_AIRLINES
INDUSTRY_AIRPORTS_SERVICES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_AIRPORTS_SERVICES
INDUSTRY_BUILDING_PRODUCTS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_BUILDING_PRODUCTS
INDUSTRY_BUSINESS_EQUIPMENT: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_BUSINESS_EQUIPMENT
INDUSTRY_CONGLOMERATES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_CONGLOMERATES
INDUSTRY_CONSULTING_SERVICES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_CONSULTING_SERVICES
INDUSTRY_ELECTRICAL_EQUIPMENT: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_ELECTRICAL_EQUIPMENT
)
INDUSTRY_ENGINEERING_CONSTRUCTION: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_ENGINEERING_CONSTRUCTION
)
INDUSTRY_FARM_HEAVY_MACHINERY: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_FARM_HEAVY_MACHINERY
)
INDUSTRY_INDUSTRIAL_DISTRIBUTION: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_INDUSTRIAL_DISTRIBUTION
)
INDUSTRY_INFRASTRUCTURE_OPERATIONS: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_INFRASTRUCTURE_OPERATIONS
)
INDUSTRY_FREIGHT_LOGISTICS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_FREIGHT_LOGISTICS
INDUSTRY_MARINE_SHIPPING: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_MARINE_SHIPPING
INDUSTRY_METAL_FABRICATION: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_METAL_FABRICATION
INDUSTRY_POLLUTION_CONTROL: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_POLLUTION_CONTROL
INDUSTRY_RAILROADS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_RAILROADS
INDUSTRY_RENTAL_LEASING: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_RENTAL_LEASING
INDUSTRY_SECURITY_PROTECTION: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_SECURITY_PROTECTION
INDUSTRY_SPEALITY_BUSINESS_SERVICES: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_SPEALITY_BUSINESS_SERVICES
)
INDUSTRY_SPEALITY_MACHINERY: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_SPEALITY_MACHINERY
INDUSTRY_STUFFING_EMPLOYMENT: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_STUFFING_EMPLOYMENT
INDUSTRY_TOOLS_ACCESSORIES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_TOOLS_ACCESSORIES
INDUSTRY_TRUCKING: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_TRUCKING
INDUSTRY_WASTE_MANAGEMENT: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_WASTE_MANAGEMENT
INDUSTRY_REAL_ESTATE_DEVELOPMENT: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_REAL_ESTATE_DEVELOPMENT
)
INDUSTRY_REAL_ESTATE_DIVERSIFIED: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_REAL_ESTATE_DIVERSIFIED
)
INDUSTRY_REAL_ESTATE_SERVICES: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_REAL_ESTATE_SERVICES
)
INDUSTRY_REIT_DIVERSIFIED: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_REIT_DIVERSIFIED
INDUSTRY_REIT_HEALTCARE: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_REIT_HEALTCARE
INDUSTRY_REIT_HOTEL_MOTEL: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_REIT_HOTEL_MOTEL
INDUSTRY_REIT_INDUSTRIAL: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_REIT_INDUSTRIAL
INDUSTRY_REIT_MORTAGE: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_REIT_MORTAGE
INDUSTRY_REIT_OFFICE: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_REIT_OFFICE
INDUSTRY_REIT_RESIDENTAL: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_REIT_RESIDENTAL
INDUSTRY_REIT_RETAIL: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_REIT_RETAIL
INDUSTRY_REIT_SPECIALITY: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_REIT_SPECIALITY
INDUSTRY_COMMUNICATION_EQUIPMENT: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_COMMUNICATION_EQUIPMENT
)
INDUSTRY_COMPUTER_HARDWARE: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_COMPUTER_HARDWARE
INDUSTRY_CONSUMER_ELECTRONICS: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_CONSUMER_ELECTRONICS
)
INDUSTRY_ELECTRONIC_COMPONENTS: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_ELECTRONIC_COMPONENTS
)
INDUSTRY_ELECTRONIC_DISTRIBUTION: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_ELECTRONIC_DISTRIBUTION
)
INDUSTRY_IT_SERVICES: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_IT_SERVICES
INDUSTRY_SCIENTIFIC_INSTRUMENTS: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_SCIENTIFIC_INSTRUMENTS
)
INDUSTRY_SEMICONDUCTOR_EQUIPMENT: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_SEMICONDUCTOR_EQUIPMENT
)
INDUSTRY_SEMICONDUCTORS: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_SEMICONDUCTORS
INDUSTRY_SOFTWARE_APPLICATION: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_SOFTWARE_APPLICATION
)
INDUSTRY_SOFTWARE_INFRASTRUCTURE: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_SOFTWARE_INFRASTRUCTURE
)
INDUSTRY_SOLAR: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_SOLAR
INDUSTRY_UTILITIES_DIVERSIFIED: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_UTILITIES_DIVERSIFIED
)
INDUSTRY_UTILITIES_POWERPRODUCERS: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_UTILITIES_POWERPRODUCERS
)
INDUSTRY_UTILITIES_RENEWABLE: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_UTILITIES_RENEWABLE
INDUSTRY_UTILITIES_REGULATED_ELECTRIC: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_UTILITIES_REGULATED_ELECTRIC
)
INDUSTRY_UTILITIES_REGULATED_GAS: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_UTILITIES_REGULATED_GAS
)
INDUSTRY_UTILITIES_REGULATED_WATER: Final = (
    ENUM_SYMBOL_INDUSTRY.INDUSTRY_UTILITIES_REGULATED_WATER
)
INDUSTRY_UTILITIES_FIRST: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_UTILITIES_FIRST
INDUSTRY_UTILITIES_LAST: Final = ENUM_SYMBOL_INDUSTRY.INDUSTRY_UTILITIES_LAST


class ENUM_SYMBOL_INFO_DOUBLE(IntEnum):
    """Defines the identifier set for symbol info double."""

    SYMBOL_OPTION_MODE = 0
    SYMBOL_OPTION_RIGHT = 1
    SYMBOL_BID = 2
    SYMBOL_BIDHIGH = 3
    SYMBOL_BIDLOW = 4
    SYMBOL_ASK = 5
    SYMBOL_ASKHIGH = 6
    SYMBOL_ASKLOW = 7
    SYMBOL_LAST = 8
    SYMBOL_LASTHIGH = 9
    SYMBOL_LASTLOW = 10
    SYMBOL_VOLUME_REAL = 11
    SYMBOL_VOLUMEHIGH_REAL = 12
    SYMBOL_VOLUMELOW_REAL = 13
    SYMBOL_OPTION_STRIKE = 14
    SYMBOL_POINT = 15
    SYMBOL_TRADE_TICK_VALUE = 16
    SYMBOL_TRADE_TICK_VALUE_PROFIT = 17
    SYMBOL_TRADE_TICK_VALUE_LOSS = 18
    SYMBOL_TRADE_TICK_SIZE = 19
    SYMBOL_TRADE_CONTRACT_SIZE = 20
    SYMBOL_TRADE_ACCRUED_INTEREST = 21
    SYMBOL_TRADE_FACE_VALUE = 22
    SYMBOL_TRADE_LIQUIDITY_RATE = 23
    SYMBOL_VOLUME_MIN = 24
    SYMBOL_VOLUME_MAX = 25
    SYMBOL_VOLUME_STEP = 26
    SYMBOL_VOLUME_LIMIT = 27
    SYMBOL_SWAP_LONG = 28
    SYMBOL_SWAP_SHORT = 29
    SYMBOL_SWAP_SUNDAY = 30
    SYMBOL_SWAP_MONDAY = 31
    SYMBOL_SWAP_TUESDAY = 32
    SYMBOL_SWAP_WEDNESDAY = 33
    SYMBOL_SWAP_THURSDAY = 34
    SYMBOL_SWAP_FRIDAY = 35
    SYMBOL_SWAP_SATURDAY = 36
    SYMBOL_MARGIN_INITIAL = 37
    SYMBOL_MARGIN_MAINTENANCE = 38
    SYMBOL_SESSION_VOLUME = 39
    SYMBOL_SESSION_TURNOVER = 40
    SYMBOL_SESSION_INTEREST = 41
    SYMBOL_SESSION_BUY_ORDERS_VOLUME = 42
    SYMBOL_SESSION_SELL_ORDERS_VOLUME = 43
    SYMBOL_SESSION_OPEN = 44
    SYMBOL_SESSION_CLOSE = 45
    SYMBOL_SESSION_AW = 46
    SYMBOL_SESSION_PRICE_SETTLEMENT = 47
    SYMBOL_SESSION_PRICE_LIMIT_MIN = 48
    SYMBOL_SESSION_PRICE_LIMIT_MAX = 49
    SYMBOL_MARGIN_HEDGED = 50
    SYMBOL_PRICE_CHANGE = 51
    SYMBOL_PRICE_VOLATILITY = 52
    SYMBOL_PRICE_THEORETICAL = 53
    SYMBOL_PRICE_DELTA = 54
    SYMBOL_PRICE_THETA = 55
    SYMBOL_PRICE_GAMMA = 56
    SYMBOL_PRICE_VEGA = 57
    SYMBOL_PRICE_RHO = 58
    SYMBOL_PRICE_OMEGA = 59
    SYMBOL_PRICE_SENSITIVITY = 60


SYMBOL_OPTION_MODE: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_OPTION_MODE
SYMBOL_OPTION_RIGHT: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_OPTION_RIGHT
SYMBOL_BID: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_BID
SYMBOL_BIDHIGH: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_BIDHIGH
SYMBOL_BIDLOW: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_BIDLOW
SYMBOL_ASK: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_ASK
SYMBOL_ASKHIGH: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_ASKHIGH
SYMBOL_ASKLOW: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_ASKLOW
SYMBOL_LAST: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_LAST
SYMBOL_LASTHIGH: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_LASTHIGH
SYMBOL_LASTLOW: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_LASTLOW
SYMBOL_VOLUME_REAL: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_VOLUME_REAL
SYMBOL_VOLUMEHIGH_REAL: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_VOLUMEHIGH_REAL
SYMBOL_VOLUMELOW_REAL: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_VOLUMELOW_REAL
SYMBOL_OPTION_STRIKE: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_OPTION_STRIKE
SYMBOL_POINT: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_POINT
SYMBOL_TRADE_TICK_VALUE: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_TRADE_TICK_VALUE
SYMBOL_TRADE_TICK_VALUE_PROFIT: Final = (
    ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_TRADE_TICK_VALUE_PROFIT
)
SYMBOL_TRADE_TICK_VALUE_LOSS: Final = (
    ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_TRADE_TICK_VALUE_LOSS
)
SYMBOL_TRADE_TICK_SIZE: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_TRADE_TICK_SIZE
SYMBOL_TRADE_CONTRACT_SIZE: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_TRADE_CONTRACT_SIZE
SYMBOL_TRADE_ACCRUED_INTEREST: Final = (
    ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_TRADE_ACCRUED_INTEREST
)
SYMBOL_TRADE_FACE_VALUE: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_TRADE_FACE_VALUE
SYMBOL_TRADE_LIQUIDITY_RATE: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_TRADE_LIQUIDITY_RATE
SYMBOL_VOLUME_MIN: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_VOLUME_MIN
SYMBOL_VOLUME_MAX: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_VOLUME_MAX
SYMBOL_VOLUME_STEP: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_VOLUME_STEP
SYMBOL_VOLUME_LIMIT: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_VOLUME_LIMIT
SYMBOL_SWAP_LONG: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SWAP_LONG
SYMBOL_SWAP_SHORT: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SWAP_SHORT
SYMBOL_SWAP_SUNDAY: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SWAP_SUNDAY
SYMBOL_SWAP_MONDAY: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SWAP_MONDAY
SYMBOL_SWAP_TUESDAY: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SWAP_TUESDAY
SYMBOL_SWAP_WEDNESDAY: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SWAP_WEDNESDAY
SYMBOL_SWAP_THURSDAY: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SWAP_THURSDAY
SYMBOL_SWAP_FRIDAY: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SWAP_FRIDAY
SYMBOL_SWAP_SATURDAY: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SWAP_SATURDAY
SYMBOL_MARGIN_INITIAL: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_MARGIN_INITIAL
SYMBOL_MARGIN_MAINTENANCE: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_MARGIN_MAINTENANCE
SYMBOL_SESSION_VOLUME: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SESSION_VOLUME
SYMBOL_SESSION_TURNOVER: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SESSION_TURNOVER
SYMBOL_SESSION_INTEREST: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SESSION_INTEREST
SYMBOL_SESSION_BUY_ORDERS_VOLUME: Final = (
    ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SESSION_BUY_ORDERS_VOLUME
)
SYMBOL_SESSION_SELL_ORDERS_VOLUME: Final = (
    ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SESSION_SELL_ORDERS_VOLUME
)
SYMBOL_SESSION_OPEN: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SESSION_OPEN
SYMBOL_SESSION_CLOSE: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SESSION_CLOSE
SYMBOL_SESSION_AW: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SESSION_AW
SYMBOL_SESSION_PRICE_SETTLEMENT: Final = (
    ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SESSION_PRICE_SETTLEMENT
)
SYMBOL_SESSION_PRICE_LIMIT_MIN: Final = (
    ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SESSION_PRICE_LIMIT_MIN
)
SYMBOL_SESSION_PRICE_LIMIT_MAX: Final = (
    ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_SESSION_PRICE_LIMIT_MAX
)
SYMBOL_MARGIN_HEDGED: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_MARGIN_HEDGED
SYMBOL_PRICE_CHANGE: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_PRICE_CHANGE
SYMBOL_PRICE_VOLATILITY: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_PRICE_VOLATILITY
SYMBOL_PRICE_THEORETICAL: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_PRICE_THEORETICAL
SYMBOL_PRICE_DELTA: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_PRICE_DELTA
SYMBOL_PRICE_THETA: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_PRICE_THETA
SYMBOL_PRICE_GAMMA: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_PRICE_GAMMA
SYMBOL_PRICE_VEGA: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_PRICE_VEGA
SYMBOL_PRICE_RHO: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_PRICE_RHO
SYMBOL_PRICE_OMEGA: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_PRICE_OMEGA
SYMBOL_PRICE_SENSITIVITY: Final = ENUM_SYMBOL_INFO_DOUBLE.SYMBOL_PRICE_SENSITIVITY


class ENUM_SYMBOL_INFO_INTEGER(IntEnum):
    """Defines the identifier set for symbol info integer."""

    SYMBOL_SUBSCRIPTION_DELAY = 0
    SYMBOL_SECTOR = 1
    SYMBOL_INDUSTRY = 2
    SYMBOL_CUSTOM = 3
    SYMBOL_BACKGROUND_COLOR = 4
    SYMBOL_CHART_MODE = 5
    SYMBOL_EXIST = 6
    SYMBOL_SELECT = 7
    SYMBOL_VISIBLE = 8
    SYMBOL_SESSION_DEALS = 9
    SYMBOL_SESSION_BUY_ORDERS = 10
    SYMBOL_SESSION_SELL_ORDERS = 11
    SYMBOL_VOLUME = 12
    SYMBOL_VOLUMEHIGH = 13
    SYMBOL_VOLUMELOW = 14
    SYMBOL_TIME = 15
    SYMBOL_TIME_MSC = 16
    SYMBOL_DIGITS = 17
    SYMBOL_SPREAD_FLOAT = 18
    SYMBOL_SPREAD = 19
    SYMBOL_TICKS_BOOKDEPTH = 20
    SYMBOL_TRADE_CALC_MODE = 21
    SYMBOL_TRADE_MODE = 22
    SYMBOL_START_TIME = 23
    SYMBOL_EXPIRATION_TIME = 24
    SYMBOL_TRADE_STOPS_LEVEL = 25
    SYMBOL_TRADE_FREEZE_LEVEL = 26
    SYMBOL_TRADE_EXEMODE = 27
    SYMBOL_SWAP_MODE = 28
    SYMBOL_SWAP_ROLLOVER3DAYS = 29
    SYMBOL_MARGIN_HEDGED_USE_LEG = 30
    SYMBOL_EXPIRATION_MODE = 31
    SYMBOL_FILLING_MODE = 32
    SYMBOL_ORDER_MODE = 33
    SYMBOL_ORDER_GTC_MODE = 34


SYMBOL_SUBSCRIPTION_DELAY: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_SUBSCRIPTION_DELAY
SYMBOL_SECTOR: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_SECTOR
SYMBOL_INDUSTRY: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_INDUSTRY
SYMBOL_CUSTOM: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_CUSTOM
SYMBOL_BACKGROUND_COLOR: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_BACKGROUND_COLOR
SYMBOL_CHART_MODE: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_CHART_MODE
SYMBOL_EXIST: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_EXIST
SYMBOL_SELECT: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_SELECT
SYMBOL_VISIBLE: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_VISIBLE
SYMBOL_SESSION_DEALS: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_SESSION_DEALS
SYMBOL_SESSION_BUY_ORDERS: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_SESSION_BUY_ORDERS
SYMBOL_SESSION_SELL_ORDERS: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_SESSION_SELL_ORDERS
SYMBOL_VOLUME: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_VOLUME
SYMBOL_VOLUMEHIGH: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_VOLUMEHIGH
SYMBOL_VOLUMELOW: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_VOLUMELOW
SYMBOL_TIME: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_TIME
SYMBOL_TIME_MSC: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_TIME_MSC
SYMBOL_DIGITS: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_DIGITS
SYMBOL_SPREAD_FLOAT: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_SPREAD_FLOAT
SYMBOL_SPREAD: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_SPREAD
SYMBOL_TICKS_BOOKDEPTH: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_TICKS_BOOKDEPTH
SYMBOL_TRADE_CALC_MODE: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_TRADE_CALC_MODE
SYMBOL_TRADE_MODE: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_TRADE_MODE
SYMBOL_START_TIME: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_START_TIME
SYMBOL_EXPIRATION_TIME: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_EXPIRATION_TIME
SYMBOL_TRADE_STOPS_LEVEL: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_TRADE_STOPS_LEVEL
SYMBOL_TRADE_FREEZE_LEVEL: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_TRADE_FREEZE_LEVEL
SYMBOL_TRADE_EXEMODE: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_TRADE_EXEMODE
SYMBOL_SWAP_MODE: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_SWAP_MODE
SYMBOL_SWAP_ROLLOVER3DAYS: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_SWAP_ROLLOVER3DAYS
SYMBOL_MARGIN_HEDGED_USE_LEG: Final = (
    ENUM_SYMBOL_INFO_INTEGER.SYMBOL_MARGIN_HEDGED_USE_LEG
)
SYMBOL_EXPIRATION_MODE: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_EXPIRATION_MODE
SYMBOL_FILLING_MODE: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_FILLING_MODE
SYMBOL_ORDER_MODE: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_ORDER_MODE
SYMBOL_ORDER_GTC_MODE: Final = ENUM_SYMBOL_INFO_INTEGER.SYMBOL_ORDER_GTC_MODE


class ENUM_SYMBOL_INFO_STRING(IntEnum):
    """Defines the identifier set for symbol info string."""

    SYMBOL_BASIS = 0
    SYMBOL_CATEGORY = 1
    SYMBOL_COUNTRY = 2
    SYMBOL_SECTOR_NAME = 3
    SYMBOL_INDUSTRY_NAME = 4
    SYMBOL_CURRENCY_BASE = 5
    SYMBOL_CURRENCY_PROFIT = 6
    SYMBOL_CURRENCY_MARGIN = 7
    SYMBOL_BANK = 8
    SYMBOL_DESCRIPTION = 9
    SYMBOL_EXCHANGE = 10
    SYMBOL_FORMULA = 11
    SYMBOL_ISIN = 12
    SYMBOL_PAGE = 13


SYMBOL_BASIS: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_BASIS
SYMBOL_CATEGORY: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_CATEGORY
SYMBOL_COUNTRY: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_COUNTRY
SYMBOL_SECTOR_NAME: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_SECTOR_NAME
SYMBOL_INDUSTRY_NAME: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_INDUSTRY_NAME
SYMBOL_CURRENCY_BASE: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_CURRENCY_BASE
SYMBOL_CURRENCY_PROFIT: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_CURRENCY_PROFIT
SYMBOL_CURRENCY_MARGIN: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_CURRENCY_MARGIN
SYMBOL_BANK: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_BANK
SYMBOL_DESCRIPTION: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_DESCRIPTION
SYMBOL_EXCHANGE: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_EXCHANGE
SYMBOL_FORMULA: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_FORMULA
SYMBOL_ISIN: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_ISIN
SYMBOL_PAGE: Final = ENUM_SYMBOL_INFO_STRING.SYMBOL_PAGE


class ENUM_SYMBOL_OPTION_MODE(IntEnum):
    """Defines the identifier set for symbol option mode."""

    SYMBOL_OPTION_MODE_EUROPEAN = 0
    SYMBOL_OPTION_MODE_AMERICAN = 1


SYMBOL_OPTION_MODE_EUROPEAN: Final = ENUM_SYMBOL_OPTION_MODE.SYMBOL_OPTION_MODE_EUROPEAN
SYMBOL_OPTION_MODE_AMERICAN: Final = ENUM_SYMBOL_OPTION_MODE.SYMBOL_OPTION_MODE_AMERICAN


class ENUM_SYMBOL_OPTION_RIGHT(IntEnum):
    """Defines the identifier set for symbol option right."""

    SYMBOL_OPTION_RIGHT_CALL = 0
    SYMBOL_OPTION_RIGHT_PUT = 1


SYMBOL_OPTION_RIGHT_CALL: Final = ENUM_SYMBOL_OPTION_RIGHT.SYMBOL_OPTION_RIGHT_CALL
SYMBOL_OPTION_RIGHT_PUT: Final = ENUM_SYMBOL_OPTION_RIGHT.SYMBOL_OPTION_RIGHT_PUT


class ENUM_SYMBOL_ORDER_GTC_MODE(IntEnum):
    """Defines the identifier set for symbol order GTC mode."""

    SYMBOL_ORDERS_GTC = 0
    SYMBOL_ORDERS_DAILY = 1
    SYMBOL_ORDERS_DAILY_EXCLUDING_STOPS = 2


SYMBOL_ORDERS_GTC: Final = ENUM_SYMBOL_ORDER_GTC_MODE.SYMBOL_ORDERS_GTC
SYMBOL_ORDERS_DAILY: Final = ENUM_SYMBOL_ORDER_GTC_MODE.SYMBOL_ORDERS_DAILY
SYMBOL_ORDERS_DAILY_EXCLUDING_STOPS: Final = (
    ENUM_SYMBOL_ORDER_GTC_MODE.SYMBOL_ORDERS_DAILY_EXCLUDING_STOPS
)


class ENUM_SYMBOL_SECTOR(IntEnum):
    """Defines the identifier set for symbol sector."""

    SECTOR_UNDEFINED = 0
    SECTOR_BASIC_MATERIALS = 1
    SECTOR_COMMUNICATION_SERVICES = 2
    SECTOR_CONSUMER_CYCLICAL = 3
    SECTOR_CONSUMER_DEFENSIVE = 4
    SECTOR_CURRENCY = 5
    SECTOR_CURRENCY_CRYPTO = 6
    SECTOR_ENERGY = 7
    SECTOR_FINANCIAL = 8
    SECTOR_HEALTHCARE = 9
    SECTOR_INDUSTRIALS = 10
    SECTOR_REAL_ESTATE = 11
    SECTOR_TECHNOLOGY = 12
    SECTOR_UTILITIES = 13


SECTOR_UNDEFINED: Final = ENUM_SYMBOL_SECTOR.SECTOR_UNDEFINED
SECTOR_BASIC_MATERIALS: Final = ENUM_SYMBOL_SECTOR.SECTOR_BASIC_MATERIALS
SECTOR_COMMUNICATION_SERVICES: Final = ENUM_SYMBOL_SECTOR.SECTOR_COMMUNICATION_SERVICES
SECTOR_CONSUMER_CYCLICAL: Final = ENUM_SYMBOL_SECTOR.SECTOR_CONSUMER_CYCLICAL
SECTOR_CONSUMER_DEFENSIVE: Final = ENUM_SYMBOL_SECTOR.SECTOR_CONSUMER_DEFENSIVE
SECTOR_CURRENCY: Final = ENUM_SYMBOL_SECTOR.SECTOR_CURRENCY
SECTOR_CURRENCY_CRYPTO: Final = ENUM_SYMBOL_SECTOR.SECTOR_CURRENCY_CRYPTO
SECTOR_ENERGY: Final = ENUM_SYMBOL_SECTOR.SECTOR_ENERGY
SECTOR_FINANCIAL: Final = ENUM_SYMBOL_SECTOR.SECTOR_FINANCIAL
SECTOR_HEALTHCARE: Final = ENUM_SYMBOL_SECTOR.SECTOR_HEALTHCARE
SECTOR_INDUSTRIALS: Final = ENUM_SYMBOL_SECTOR.SECTOR_INDUSTRIALS
SECTOR_REAL_ESTATE: Final = ENUM_SYMBOL_SECTOR.SECTOR_REAL_ESTATE
SECTOR_TECHNOLOGY: Final = ENUM_SYMBOL_SECTOR.SECTOR_TECHNOLOGY
SECTOR_UTILITIES: Final = ENUM_SYMBOL_SECTOR.SECTOR_UTILITIES


class ENUM_SYMBOL_SWAP_MODE(IntEnum):
    """Defines the identifier set for symbol swap mode."""

    SYMBOL_SWAP_MODE_DISABLED = 0
    SYMBOL_SWAP_MODE_POINTS = 1
    SYMBOL_SWAP_MODE_CURRENCY_SYMBOL = 2
    SYMBOL_SWAP_MODE_CURRENCY_MARGIN = 3
    SYMBOL_SWAP_MODE_CURRENCY_DEPOSIT = 4
    SYMBOL_SWAP_MODE_CURRENCY_PROFIT = 5
    SYMBOL_SWAP_MODE_INTEREST_CURRENT = 5
    SYMBOL_SWAP_MODE_INTEREST_OPEN = 6
    SYMBOL_SWAP_MODE_REOPEN_CURRENT = 7
    SYMBOL_SWAP_MODE_REOPEN_BID = 8


SYMBOL_SWAP_MODE_DISABLED: Final = ENUM_SYMBOL_SWAP_MODE.SYMBOL_SWAP_MODE_DISABLED
SYMBOL_SWAP_MODE_POINTS: Final = ENUM_SYMBOL_SWAP_MODE.SYMBOL_SWAP_MODE_POINTS
SYMBOL_SWAP_MODE_CURRENCY_SYMBOL: Final = (
    ENUM_SYMBOL_SWAP_MODE.SYMBOL_SWAP_MODE_CURRENCY_SYMBOL
)
SYMBOL_SWAP_MODE_CURRENCY_MARGIN: Final = (
    ENUM_SYMBOL_SWAP_MODE.SYMBOL_SWAP_MODE_CURRENCY_MARGIN
)
SYMBOL_SWAP_MODE_CURRENCY_DEPOSIT: Final = (
    ENUM_SYMBOL_SWAP_MODE.SYMBOL_SWAP_MODE_CURRENCY_DEPOSIT
)
SYMBOL_SWAP_MODE_CURRENCY_PROFIT: Final = (
    ENUM_SYMBOL_SWAP_MODE.SYMBOL_SWAP_MODE_CURRENCY_PROFIT
)
SYMBOL_SWAP_MODE_INTEREST_CURRENT: Final = (
    ENUM_SYMBOL_SWAP_MODE.SYMBOL_SWAP_MODE_INTEREST_CURRENT
)
SYMBOL_SWAP_MODE_INTEREST_OPEN: Final = (
    ENUM_SYMBOL_SWAP_MODE.SYMBOL_SWAP_MODE_INTEREST_OPEN
)
SYMBOL_SWAP_MODE_REOPEN_CURRENT: Final = (
    ENUM_SYMBOL_SWAP_MODE.SYMBOL_SWAP_MODE_REOPEN_CURRENT
)
SYMBOL_SWAP_MODE_REOPEN_BID: Final = ENUM_SYMBOL_SWAP_MODE.SYMBOL_SWAP_MODE_REOPEN_BID


class ENUM_SYMBOL_TRADE_EXECUTION(IntEnum):
    """Defines the identifier set for symbol trade execution."""

    SYMBOL_TRADE_EXECUTION_REQUEST = 0
    SYMBOL_TRADE_EXECUTION_INSTANT = 1
    SYMBOL_TRADE_EXECUTION_MARKET = 2
    SYMBOL_TRADE_EXECUTION_EXCHANGE = 3


SYMBOL_TRADE_EXECUTION_REQUEST: Final = (
    ENUM_SYMBOL_TRADE_EXECUTION.SYMBOL_TRADE_EXECUTION_REQUEST
)
SYMBOL_TRADE_EXECUTION_INSTANT: Final = (
    ENUM_SYMBOL_TRADE_EXECUTION.SYMBOL_TRADE_EXECUTION_INSTANT
)
SYMBOL_TRADE_EXECUTION_MARKET: Final = (
    ENUM_SYMBOL_TRADE_EXECUTION.SYMBOL_TRADE_EXECUTION_MARKET
)
SYMBOL_TRADE_EXECUTION_EXCHANGE: Final = (
    ENUM_SYMBOL_TRADE_EXECUTION.SYMBOL_TRADE_EXECUTION_EXCHANGE
)


class ENUM_SYMBOL_TRADE_MODE(IntEnum):
    """Defines the identifier set for symbol trade mode."""

    SYMBOL_TRADE_MODE_DISABLED = 0
    SYMBOL_TRADE_MODE_LONGONLY = 1
    SYMBOL_TRADE_MODE_SHORTONLY = 2
    SYMBOL_TRADE_MODE_CLOSEONLY = 3
    SYMBOL_TRADE_MODE_FULL = 4


SYMBOL_TRADE_MODE_DISABLED: Final = ENUM_SYMBOL_TRADE_MODE.SYMBOL_TRADE_MODE_DISABLED
SYMBOL_TRADE_MODE_LONGONLY: Final = ENUM_SYMBOL_TRADE_MODE.SYMBOL_TRADE_MODE_LONGONLY
SYMBOL_TRADE_MODE_SHORTONLY: Final = ENUM_SYMBOL_TRADE_MODE.SYMBOL_TRADE_MODE_SHORTONLY
SYMBOL_TRADE_MODE_CLOSEONLY: Final = ENUM_SYMBOL_TRADE_MODE.SYMBOL_TRADE_MODE_CLOSEONLY
SYMBOL_TRADE_MODE_FULL: Final = ENUM_SYMBOL_TRADE_MODE.SYMBOL_TRADE_MODE_FULL

SYMBOL_EXPIRATION_GTC: Final[int] = 1
SYMBOL_EXPIRATION_DAY: Final[int] = 2
SYMBOL_EXPIRATION_SPECIFIED: Final[int] = 4
SYMBOL_EXPIRATION_SPECIFIED_DAY: Final[int] = 8
SYMBOL_FILLING_FOK: Final[int] = 1
SYMBOL_FILLING_IOC: Final[int] = 2
SYMBOL_FILLING_BOC: Final[int] = 4
SYMBOL_ORDER_MARKET: Final[int] = 1
SYMBOL_ORDER_LIMIT: Final[int] = 2
SYMBOL_ORDER_STOP: Final[int] = 4
SYMBOL_ORDER_STOP_LIMIT: Final[int] = 8
SYMBOL_ORDER_SL: Final[int] = 16
SYMBOL_ORDER_TP: Final[int] = 32
SYMBOL_ORDER_CLOSEBY: Final[int] = 64

__all__ = [
    "ENUM_DAY_OF_WEEK",
    "ENUM_SYMBOL_CALC_MODE",
    "ENUM_SYMBOL_CHART_MODE",
    "ENUM_SYMBOL_INDUSTRY",
    "ENUM_SYMBOL_INFO_DOUBLE",
    "ENUM_SYMBOL_INFO_INTEGER",
    "ENUM_SYMBOL_INFO_STRING",
    "ENUM_SYMBOL_OPTION_MODE",
    "ENUM_SYMBOL_OPTION_RIGHT",
    "ENUM_SYMBOL_ORDER_GTC_MODE",
    "ENUM_SYMBOL_SECTOR",
    "ENUM_SYMBOL_SWAP_MODE",
    "ENUM_SYMBOL_TRADE_EXECUTION",
    "ENUM_SYMBOL_TRADE_MODE",
    "FRIDAY",
    "INDUSTRY_ADVERTISING",
    "INDUSTRY_AEROSPACE_DEFENSE",
    "INDUSTRY_AGRICULTURAL_INPUTS",
    "INDUSTRY_AIRLINES",
    "INDUSTRY_AIRPORTS_SERVICES",
    "INDUSTRY_ALUMINIUM",
    "INDUSTRY_APPAREL_MANUFACTURING",
    "INDUSTRY_APPAREL_RETAIL",
    "INDUSTRY_ASSETS_MANAGEMENT",
    "INDUSTRY_AUTO_DEALERSHIP",
    "INDUSTRY_AUTO_MANUFACTURERS",
    "INDUSTRY_AUTO_PARTS",
    "INDUSTRY_BANKS_DIVERSIFIED",
    "INDUSTRY_BANKS_REGIONAL",
    "INDUSTRY_BEVERAGES_BREWERS",
    "INDUSTRY_BEVERAGES_NON_ALCO",
    "INDUSTRY_BEVERAGES_WINERIES",
    "INDUSTRY_BIOTECHNOLOGY",
    "INDUSTRY_BROADCASTING",
    "INDUSTRY_BUILDING_MATERIALS",
    "INDUSTRY_BUILDING_PRODUCTS",
    "INDUSTRY_BUSINESS_EQUIPMENT",
    "INDUSTRY_CAPITAL_MARKETS",
    "INDUSTRY_CHEMICALS",
    "INDUSTRY_CLOSE_END_FUND_DEBT",
    "INDUSTRY_CLOSE_END_FUND_EQUITY",
    "INDUSTRY_CLOSE_END_FUND_FOREIGN",
    "INDUSTRY_COKING_COAL",
    "INDUSTRY_COMMUNICATION_EQUIPMENT",
    "INDUSTRY_COMPUTER_HARDWARE",
    "INDUSTRY_CONFECTIONERS",
    "INDUSTRY_CONGLOMERATES",
    "INDUSTRY_CONSULTING_SERVICES",
    "INDUSTRY_CONSUMER_ELECTRONICS",
    "INDUSTRY_COPPER",
    "INDUSTRY_CREDIT_SERVICES",
    "INDUSTRY_DEPARTMENT_STORES",
    "INDUSTRY_DIAGNOSTICS_RESEARCH",
    "INDUSTRY_DISCOUNT_STORES",
    "INDUSTRY_DRUGS_MANUFACTURERS",
    "INDUSTRY_DRUGS_MANUFACTURERS_SPEC",
    "INDUSTRY_EDUCATION_TRAINIG",
    "INDUSTRY_ELECTRICAL_EQUIPMENT",
    "INDUSTRY_ELECTRONIC_COMPONENTS",
    "INDUSTRY_ELECTRONIC_DISTRIBUTION",
    "INDUSTRY_ENGINEERING_CONSTRUCTION",
    "INDUSTRY_ENTERTAINMENT",
    "INDUSTRY_EXCHANGE_TRADED_FUND",
    "INDUSTRY_FARM_HEAVY_MACHINERY",
    "INDUSTRY_FARM_PRODUCTS",
    "INDUSTRY_FINANCIAL_CONGLOMERATE",
    "INDUSTRY_FINANCIAL_DATA_EXCHANGE",
    "INDUSTRY_FOOD_DISTRIBUTION",
    "INDUSTRY_FOOTWEAR_ACCESSORIES",
    "INDUSTRY_FREIGHT_LOGISTICS",
    "INDUSTRY_FURNISHINGS",
    "INDUSTRY_GAMBLING",
    "INDUSTRY_GAMING_MULTIMEDIA",
    "INDUSTRY_GOLD",
    "INDUSTRY_GROCERY_STORES",
    "INDUSTRY_HEALTH_INFORMATION",
    "INDUSTRY_HEALTHCARE_PLANS",
    "INDUSTRY_HOME_IMPROV_RETAIL",
    "INDUSTRY_HOUSEHOLD_PRODUCTS",
    "INDUSTRY_INDUSTRIAL_DISTRIBUTION",
    "INDUSTRY_INDUSTRIAL_METALS",
    "INDUSTRY_INFRASTRUCTURE_OPERATIONS",
    "INDUSTRY_INSURANCE_BROKERS",
    "INDUSTRY_INSURANCE_DIVERSIFIED",
    "INDUSTRY_INSURANCE_LIFE",
    "INDUSTRY_INSURANCE_PROPERTY",
    "INDUSTRY_INSURANCE_REINSURANCE",
    "INDUSTRY_INSURANCE_SPECIALTY",
    "INDUSTRY_INTERNET_CONTENT",
    "INDUSTRY_INTERNET_RETAIL",
    "INDUSTRY_IT_SERVICES",
    "INDUSTRY_LEISURE",
    "INDUSTRY_LODGING",
    "INDUSTRY_LUMBER_WOOD",
    "INDUSTRY_LUXURY_GOODS",
    "INDUSTRY_MARINE_SHIPPING",
    "INDUSTRY_MEDICAL_DEVICES",
    "INDUSTRY_MEDICAL_DISTRIBUTION",
    "INDUSTRY_MEDICAL_FACILITIES",
    "INDUSTRY_MEDICAL_INSTRUMENTS",
    "INDUSTRY_METAL_FABRICATION",
    "INDUSTRY_MORTGAGE_FINANCE",
    "INDUSTRY_OIL_GAS_DRILLING",
    "INDUSTRY_OIL_GAS_EP",
    "INDUSTRY_OIL_GAS_EQUIPMENT",
    "INDUSTRY_OIL_GAS_INTEGRATED",
    "INDUSTRY_OIL_GAS_MIDSTREAM",
    "INDUSTRY_OIL_GAS_REFINING",
    "INDUSTRY_PACKAGED_FOODS",
    "INDUSTRY_PACKAGING_CONTAINERS",
    "INDUSTRY_PAPER",
    "INDUSTRY_PERSONAL_SERVICES",
    "INDUSTRY_PHARM_RETAILERS",
    "INDUSTRY_POLLUTION_CONTROL",
    "INDUSTRY_PRECIOUS_METALS",
    "INDUSTRY_PUBLISHING",
    "INDUSTRY_RAILROADS",
    "INDUSTRY_REAL_ESTATE_DEVELOPMENT",
    "INDUSTRY_REAL_ESTATE_DIVERSIFIED",
    "INDUSTRY_REAL_ESTATE_SERVICES",
    "INDUSTRY_RECREATIONAL_VEHICLES",
    "INDUSTRY_REIT_DIVERSIFIED",
    "INDUSTRY_REIT_HEALTCARE",
    "INDUSTRY_REIT_HOTEL_MOTEL",
    "INDUSTRY_REIT_INDUSTRIAL",
    "INDUSTRY_REIT_MORTAGE",
    "INDUSTRY_REIT_OFFICE",
    "INDUSTRY_REIT_RESIDENTAL",
    "INDUSTRY_REIT_RETAIL",
    "INDUSTRY_REIT_SPECIALITY",
    "INDUSTRY_RENTAL_LEASING",
    "INDUSTRY_RESIDENT_CONSTRUCTION",
    "INDUSTRY_RESORTS_CASINOS",
    "INDUSTRY_RESTAURANTS",
    "INDUSTRY_SCIENTIFIC_INSTRUMENTS",
    "INDUSTRY_SECURITY_PROTECTION",
    "INDUSTRY_SEMICONDUCTOR_EQUIPMENT",
    "INDUSTRY_SEMICONDUCTORS",
    "INDUSTRY_SHELL_COMPANIES",
    "INDUSTRY_SILVER",
    "INDUSTRY_SOFTWARE_APPLICATION",
    "INDUSTRY_SOFTWARE_INFRASTRUCTURE",
    "INDUSTRY_SOLAR",
    "INDUSTRY_SPEALITY_BUSINESS_SERVICES",
    "INDUSTRY_SPEALITY_MACHINERY",
    "INDUSTRY_SPECIALTY_CHEMICALS",
    "INDUSTRY_SPECIALTY_RETAIL",
    "INDUSTRY_STEEL",
    "INDUSTRY_STUFFING_EMPLOYMENT",
    "INDUSTRY_TELECOM",
    "INDUSTRY_TEXTILE_MANUFACTURING",
    "INDUSTRY_THERMAL_COAL",
    "INDUSTRY_TOBACCO",
    "INDUSTRY_TOOLS_ACCESSORIES",
    "INDUSTRY_TRAVEL_SERVICES",
    "INDUSTRY_TRUCKING",
    "INDUSTRY_UNDEFINED",
    "INDUSTRY_URANIUM",
    "INDUSTRY_UTILITIES_DIVERSIFIED",
    "INDUSTRY_UTILITIES_FIRST",
    "INDUSTRY_UTILITIES_LAST",
    "INDUSTRY_UTILITIES_POWERPRODUCERS",
    "INDUSTRY_UTILITIES_REGULATED_ELECTRIC",
    "INDUSTRY_UTILITIES_REGULATED_GAS",
    "INDUSTRY_UTILITIES_REGULATED_WATER",
    "INDUSTRY_UTILITIES_RENEWABLE",
    "INDUSTRY_WASTE_MANAGEMENT",
    "MONDAY",
    "SATURDAY",
    "SECTOR_BASIC_MATERIALS",
    "SECTOR_COMMUNICATION_SERVICES",
    "SECTOR_CONSUMER_CYCLICAL",
    "SECTOR_CONSUMER_DEFENSIVE",
    "SECTOR_CURRENCY",
    "SECTOR_CURRENCY_CRYPTO",
    "SECTOR_ENERGY",
    "SECTOR_FINANCIAL",
    "SECTOR_HEALTHCARE",
    "SECTOR_INDUSTRIALS",
    "SECTOR_REAL_ESTATE",
    "SECTOR_TECHNOLOGY",
    "SECTOR_UNDEFINED",
    "SECTOR_UTILITIES",
    "SUNDAY",
    "SYMBOL_ASK",
    "SYMBOL_ASKHIGH",
    "SYMBOL_ASKLOW",
    "SYMBOL_BACKGROUND_COLOR",
    "SYMBOL_BANK",
    "SYMBOL_BASIS",
    "SYMBOL_BID",
    "SYMBOL_BIDHIGH",
    "SYMBOL_BIDLOW",
    "SYMBOL_CALC_MODE_CFD",
    "SYMBOL_CALC_MODE_CFDINDEX",
    "SYMBOL_CALC_MODE_CFDLEVERAGE",
    "SYMBOL_CALC_MODE_EXCH_BONDS",
    "SYMBOL_CALC_MODE_EXCH_BONDS_MOEX",
    "SYMBOL_CALC_MODE_EXCH_FUTURES",
    "SYMBOL_CALC_MODE_EXCH_FUTURES_FORTS",
    "SYMBOL_CALC_MODE_EXCH_STOCKS",
    "SYMBOL_CALC_MODE_EXCH_STOCKS_MOEX",
    "SYMBOL_CALC_MODE_FOREX",
    "SYMBOL_CALC_MODE_FOREX_NO_LEVERAGE",
    "SYMBOL_CALC_MODE_FUTURES",
    "SYMBOL_CALC_MODE_SERV_COLLATERAL",
    "SYMBOL_CATEGORY",
    "SYMBOL_CHART_MODE",
    "SYMBOL_CHART_MODE_BID",
    "SYMBOL_CHART_MODE_LAST",
    "SYMBOL_COUNTRY",
    "SYMBOL_CURRENCY_BASE",
    "SYMBOL_CURRENCY_MARGIN",
    "SYMBOL_CURRENCY_PROFIT",
    "SYMBOL_CUSTOM",
    "SYMBOL_DESCRIPTION",
    "SYMBOL_DIGITS",
    "SYMBOL_EXCHANGE",
    "SYMBOL_EXIST",
    "SYMBOL_EXPIRATION_DAY",
    "SYMBOL_EXPIRATION_GTC",
    "SYMBOL_EXPIRATION_MODE",
    "SYMBOL_EXPIRATION_SPECIFIED",
    "SYMBOL_EXPIRATION_SPECIFIED_DAY",
    "SYMBOL_EXPIRATION_TIME",
    "SYMBOL_FILLING_BOC",
    "SYMBOL_FILLING_FOK",
    "SYMBOL_FILLING_IOC",
    "SYMBOL_FILLING_MODE",
    "SYMBOL_FORMULA",
    "SYMBOL_INDUSTRY",
    "SYMBOL_INDUSTRY_NAME",
    "SYMBOL_ISIN",
    "SYMBOL_LAST",
    "SYMBOL_LASTHIGH",
    "SYMBOL_LASTLOW",
    "SYMBOL_MARGIN_HEDGED",
    "SYMBOL_MARGIN_HEDGED_USE_LEG",
    "SYMBOL_MARGIN_INITIAL",
    "SYMBOL_MARGIN_MAINTENANCE",
    "SYMBOL_OPTION_MODE",
    "SYMBOL_OPTION_MODE_AMERICAN",
    "SYMBOL_OPTION_MODE_EUROPEAN",
    "SYMBOL_OPTION_RIGHT",
    "SYMBOL_OPTION_RIGHT_CALL",
    "SYMBOL_OPTION_RIGHT_PUT",
    "SYMBOL_OPTION_STRIKE",
    "SYMBOL_ORDER_CLOSEBY",
    "SYMBOL_ORDER_GTC_MODE",
    "SYMBOL_ORDER_LIMIT",
    "SYMBOL_ORDER_MARKET",
    "SYMBOL_ORDER_MODE",
    "SYMBOL_ORDER_SL",
    "SYMBOL_ORDER_STOP",
    "SYMBOL_ORDER_STOP_LIMIT",
    "SYMBOL_ORDER_TP",
    "SYMBOL_ORDERS_DAILY",
    "SYMBOL_ORDERS_DAILY_EXCLUDING_STOPS",
    "SYMBOL_ORDERS_GTC",
    "SYMBOL_PAGE",
    "SYMBOL_PATH",
    "SYMBOL_POINT",
    "SYMBOL_PRICE_CHANGE",
    "SYMBOL_PRICE_DELTA",
    "SYMBOL_PRICE_GAMMA",
    "SYMBOL_PRICE_OMEGA",
    "SYMBOL_PRICE_RHO",
    "SYMBOL_PRICE_SENSITIVITY",
    "SYMBOL_PRICE_THEORETICAL",
    "SYMBOL_PRICE_THETA",
    "SYMBOL_PRICE_VEGA",
    "SYMBOL_PRICE_VOLATILITY",
    "SYMBOL_SECTOR",
    "SYMBOL_SECTOR_NAME",
    "SYMBOL_SELECT",
    "SYMBOL_SESSION_AW",
    "SYMBOL_SESSION_BUY_ORDERS",
    "SYMBOL_SESSION_BUY_ORDERS_VOLUME",
    "SYMBOL_SESSION_CLOSE",
    "SYMBOL_SESSION_DEALS",
    "SYMBOL_SESSION_INTEREST",
    "SYMBOL_SESSION_OPEN",
    "SYMBOL_SESSION_PRICE_LIMIT_MAX",
    "SYMBOL_SESSION_PRICE_LIMIT_MIN",
    "SYMBOL_SESSION_PRICE_SETTLEMENT",
    "SYMBOL_SESSION_SELL_ORDERS",
    "SYMBOL_SESSION_SELL_ORDERS_VOLUME",
    "SYMBOL_SESSION_TURNOVER",
    "SYMBOL_SESSION_VOLUME",
    "SYMBOL_SPREAD",
    "SYMBOL_SPREAD_FLOAT",
    "SYMBOL_START_TIME",
    "SYMBOL_SUBSCRIPTION_DELAY",
    "SYMBOL_SWAP_FRIDAY",
    "SYMBOL_SWAP_LONG",
    "SYMBOL_SWAP_MODE",
    "SYMBOL_SWAP_MODE_CURRENCY_DEPOSIT",
    "SYMBOL_SWAP_MODE_CURRENCY_MARGIN",
    "SYMBOL_SWAP_MODE_CURRENCY_PROFIT",
    "SYMBOL_SWAP_MODE_CURRENCY_SYMBOL",
    "SYMBOL_SWAP_MODE_DISABLED",
    "SYMBOL_SWAP_MODE_INTEREST_CURRENT",
    "SYMBOL_SWAP_MODE_INTEREST_OPEN",
    "SYMBOL_SWAP_MODE_POINTS",
    "SYMBOL_SWAP_MODE_REOPEN_BID",
    "SYMBOL_SWAP_MODE_REOPEN_CURRENT",
    "SYMBOL_SWAP_MONDAY",
    "SYMBOL_SWAP_ROLLOVER3DAYS",
    "SYMBOL_SWAP_SATURDAY",
    "SYMBOL_SWAP_SHORT",
    "SYMBOL_SWAP_SUNDAY",
    "SYMBOL_SWAP_THURSDAY",
    "SYMBOL_SWAP_TUESDAY",
    "SYMBOL_SWAP_WEDNESDAY",
    "SYMBOL_TICKS_BOOKDEPTH",
    "SYMBOL_TIME",
    "SYMBOL_TIME_MSC",
    "SYMBOL_TRADE_ACCRUED_INTEREST",
    "SYMBOL_TRADE_CALC_MODE",
    "SYMBOL_TRADE_CONTRACT_SIZE",
    "SYMBOL_TRADE_EXECUTION_EXCHANGE",
    "SYMBOL_TRADE_EXECUTION_INSTANT",
    "SYMBOL_TRADE_EXECUTION_MARKET",
    "SYMBOL_TRADE_EXECUTION_REQUEST",
    "SYMBOL_TRADE_EXEMODE",
    "SYMBOL_TRADE_FACE_VALUE",
    "SYMBOL_TRADE_FREEZE_LEVEL",
    "SYMBOL_TRADE_LIQUIDITY_RATE",
    "SYMBOL_TRADE_MODE",
    "SYMBOL_TRADE_MODE_CLOSEONLY",
    "SYMBOL_TRADE_MODE_DISABLED",
    "SYMBOL_TRADE_MODE_FULL",
    "SYMBOL_TRADE_MODE_LONGONLY",
    "SYMBOL_TRADE_MODE_SHORTONLY",
    "SYMBOL_TRADE_STOPS_LEVEL",
    "SYMBOL_TRADE_TICK_SIZE",
    "SYMBOL_TRADE_TICK_VALUE",
    "SYMBOL_TRADE_TICK_VALUE_LOSS",
    "SYMBOL_TRADE_TICK_VALUE_PROFIT",
    "SYMBOL_VISIBLE",
    "SYMBOL_VOLUME",
    "SYMBOL_VOLUME_LIMIT",
    "SYMBOL_VOLUME_MAX",
    "SYMBOL_VOLUME_MIN",
    "SYMBOL_VOLUME_REAL",
    "SYMBOL_VOLUME_STEP",
    "SYMBOL_VOLUMEHIGH",
    "SYMBOL_VOLUMEHIGH_REAL",
    "SYMBOL_VOLUMELOW",
    "SYMBOL_VOLUMELOW_REAL",
    "THURSDAY",
    "TUESDAY",
    "WEDNESDAY",
]
