"""Governance-specific review modules package.

Supports non-trade workflows and special governance states: capital
allocation review, strategy lifecycle promotion, and safety kill switches.
Never allocates capital, activates a strategy, or mutates broker state.
"""

from __future__ import annotations

from app.services.risk.governance.allocation import (
    AllocatableRisk,
    AllocationAssessment,
    AllocationMethod,
    AllocationPlan,
    AllocationReviewRequest,
    AllocationReviewResult,
    RiskAllocator,
    apply_drawdown_adjustment,
    apply_regime_and_drawdown_adjustments,
    apply_regime_weighting,
    calculate_correlation_adjusted_allocation,
    calculate_correlation_adjusted_budget,
    calculate_equal_risk_allocation,
    calculate_equal_risk_budget,
    calculate_regime_weighted_budget,
    calculate_volatility_parity_allocation,
    calculate_volatility_parity_budget,
    correlation_adjusted_risk_parity_allocation,
    equal_risk_allocation,
    review_allocation_proposal,
    verify_allocation_limits,
    volatility_parity_allocation,
)
from app.services.risk.governance.kill_switch import (
    ApprovalContext,
    KillSwitchAssessment,
    KillSwitchManager,
    KillSwitchResumeRequest,
    KillSwitchScope,
    KillSwitchService,
    KillSwitchState,
    KillSwitchTriggerRequest,
    PortfolioKillSwitch,
    RiskKillSwitch,
    StrategyKillSwitch,
    check_risk_kill_switch,
    clear_kill_switch_after_approval,
    get_kill_switch_manager,
    request_kill_switch_trigger,
    resume_after_kill_switch,
    trigger_kill_switch,
    validate_resume_request,
)
from app.services.risk.governance.lifecycle import (
    STAGE_SEQUENCE,
    LifecycleAssessment,
    LifecycleEvidence,
    LiveReadinessRequest,
    LiveReadinessReview,
    ModePromotionReview,
    RiskLifecycleGate,
    RiskLifecycleState,
    StrategyAdmissionReview,
    StrategyLifecycleState,
    evaluate_lifecycle_promotion,
    evaluate_live_readiness,
    requires_lifecycle_approval,
    review_live_readiness,
    review_mode_promotion,
    review_strategy_admission,
    validate_lifecycle_transition,
)

__all__ = [
    "STAGE_SEQUENCE",
    "AllocatableRisk",
    "AllocationAssessment",
    "AllocationMethod",
    "AllocationPlan",
    "AllocationReviewRequest",
    "AllocationReviewResult",
    "ApprovalContext",
    "KillSwitchAssessment",
    "KillSwitchManager",
    "KillSwitchResumeRequest",
    "KillSwitchScope",
    "KillSwitchService",
    "KillSwitchState",
    "KillSwitchTriggerRequest",
    "LifecycleAssessment",
    "LifecycleEvidence",
    "LiveReadinessRequest",
    "LiveReadinessReview",
    "ModePromotionReview",
    "PortfolioKillSwitch",
    "RiskAllocator",
    "RiskKillSwitch",
    "RiskLifecycleGate",
    "RiskLifecycleState",
    "StrategyAdmissionReview",
    "StrategyKillSwitch",
    "StrategyLifecycleState",
    "apply_drawdown_adjustment",
    "apply_regime_and_drawdown_adjustments",
    "apply_regime_weighting",
    "calculate_correlation_adjusted_allocation",
    "calculate_correlation_adjusted_budget",
    "calculate_equal_risk_allocation",
    "calculate_equal_risk_budget",
    "calculate_regime_weighted_budget",
    "calculate_volatility_parity_allocation",
    "calculate_volatility_parity_budget",
    "check_risk_kill_switch",
    "clear_kill_switch_after_approval",
    "correlation_adjusted_risk_parity_allocation",
    "equal_risk_allocation",
    "evaluate_lifecycle_promotion",
    "evaluate_live_readiness",
    "get_kill_switch_manager",
    "request_kill_switch_trigger",
    "requires_lifecycle_approval",
    "resume_after_kill_switch",
    "review_allocation_proposal",
    "review_live_readiness",
    "review_mode_promotion",
    "review_strategy_admission",
    "trigger_kill_switch",
    "validate_lifecycle_transition",
    "validate_resume_request",
    "verify_allocation_limits",
    "volatility_parity_allocation",
]
