#!/usr/bin/env python3
"""Interactive configuration picker for the HaruQuantAI agent workflow.

Flow: orchestration mode first; every later menu depends on the previous
answer. For each role (planner, executor, reviewer) the user selects:

    vendor -> model (list depends on vendor) -> reasoning effort

Mode semantics:
    solo           No further questions; the chat performs all roles itself.
    delegate       ONE vendor for all roles (same brand), then per-role
                   model + effort.
    multi-delegate Per-role vendor + model + effort; also regenerates the
                   three .agents/<role>.toml files with correct per-vendor
                   CLI flags so orchestrator.py picks up the choices.
    manual         No further questions; separate chats relayed by the user.

Writes .agents/run-config.toml. Run: python .agents/configure.py
"""

from __future__ import annotations

import datetime as _dt
import sys
from pathlib import Path

AGENTS_DIR = Path(__file__).resolve().parent
CONFIG_PATH = AGENTS_DIR / "run-config.toml"

MODES = (
    ("solo", "One chat plans, implements, tests, and self-reviews (no subagents)"),
    ("delegate", "Same-brand subagents, one per role, spawned by this chat"),
    ("multi-delegate", "Cross-vendor headless CLIs (codex / agy / cline / ...)"),
    ("manual", "Separate chats per role; the user relays by hand"),
)

ROLES = ("planner", "executor", "reviewer")

# Vendor order for menus. Verified suggestions only; custom values are always
# accepted (the CLIs evolve faster than any list here).
VENDORS = ("zai", "codex", "agy", "cline", "claude", "gemini", "qwen")

VENDOR_MODELS: dict[str, tuple[str, ...]] = {
    "zai": ("sol", "luna", "terra", "glm-5.3", "glm-5.2"),
    "codex": ("gpt-5.6-sol",),
    "agy": ("gemini-3.7-flash-high", "gemini-3.6-flash-high"),
    "cline": ("glm-5.3", "glm-5.2"),
    "claude": ("sonnet", "opus"),
    "gemini": ("gemini-3.6-flash-high",),
    "qwen": (),
}

VENDOR_EFFORTS: dict[str, tuple[str, ...]] = {
    "agy": ("low", "medium", "high"),
    "cline": ("none", "low", "medium", "high", "xhigh"),
}

DEFAULT_EFFORTS = ("low", "medium", "high", "xhigh")

# Headless CLI command layouts per vendor. Placeholders: {model} {effort}
# {provider}. Only verified flag layouts are generated; gemini/qwen get an
# unverified stub the user should check with the CLI's --help.
ROLE_TOML_TEMPLATES: dict[str, str] = {
    "codex": """\
# {role} agent — generated by .agents/configure.py (vendor: codex).
brand = "codex"
command = ["codex", "exec", "-s", "danger-full-access"]
model_args = ["-m", "{model}", "-c", "model_reasoning_effort={effort}"]
prompt_delivery = "file"
template = ".agents/templates/{role}.md"
""",
    "agy": """\
# {role} agent — generated by .agents/configure.py (vendor: agy).
# NOTE: agy's -p takes the next token as its prompt, so it must stay LAST.
brand = "agy"
command = [
  "agy",
  "--dangerously-skip-permissions",
  "--model", "{model}",
  "--effort", "{effort}",
  "--print-timeout", "110m",
  "-p",
]
prompt_delivery = "file"
template = ".agents/templates/{role}.md"
""",
    "cline": """\
# {role} agent — generated by .agents/configure.py (vendor: cline).
# WARNING: cline's -p flag is PLAN mode; this role needs act mode, so it is
# never added here. Provider id comes from your Cline setup (~/.cline).
brand = "cline"
command = ["cline", "-P", "{provider}", "-m", "{model}", "--thinking", "{effort}"]
prompt_delivery = "file"
template = ".agents/templates/{role}.md"
""",
    "zai": """\
# {role} agent — generated by .agents/configure.py (vendor: zai via Cline).
# z.ai models are driven headlessly through the Cline CLI provider.
brand = "cline"
command = ["cline", "-P", "zai-coding-plan", "-m", "{model}", "--thinking", "{effort}"]
prompt_delivery = "file"
template = ".agents/templates/{role}.md"
""",
    "claude": """\
# {role} agent — generated by .agents/configure.py (vendor: claude).
brand = "claude"
command = ["claude", "-p", "--dangerously-skip-permissions"]
model_args = ["--model", "{model}"]
prompt_delivery = "file"
template = ".agents/templates/{role}.md"
""",
    "gemini": """\
# {role} agent — generated by .agents/configure.py (vendor: gemini).
# NOTE: verify the gemini CLI's headless flags with `gemini --help` before
# running; the command below is an unverified placeholder.
brand = "gemini"
command = ["gemini", "-p"]
model_args = ["--model", "{model}"]
prompt_delivery = "file"
template = ".agents/templates/{role}.md"
""",
    "qwen": """\
# {role} agent — generated by .agents/configure.py (vendor: qwen).
# NOTE: verify the qwen CLI's headless flags with `qwen --help` before
# running; the command below is an unverified placeholder.
brand = "qwen"
command = ["qwen"]
model_args = ["--model", "{model}"]
prompt_delivery = "file"
template = ".agents/templates/{role}.md"
""",
}


def _ask(prompt: str) -> str:
    try:
        return input(prompt).strip()
    except EOFError:
        sys.exit(
            "\n[abort] no input available; run from an interactive terminal "
            "or pipe answers via stdin."
        )


def _pick(label: str, options: tuple[str, ...], allow_custom: bool = False) -> str:
    print(f"\n{label}:")
    if options:
        for idx, option in enumerate(options, start=1):
            print(f"  {idx}) {option}")
        hint = f"select 1-{len(options)}"
    else:
        hint = "no suggestions"
    if allow_custom:
        hint += " (or type a custom value)"
    while True:
        answer = _ask(f"{hint}: ")
        if options and answer.isdigit() and 1 <= int(answer) <= len(options):
            return options[int(answer) - 1]
        if allow_custom and answer:
            return answer
        if not options and answer:
            return answer
        print("Invalid selection; try again.")


def _ask_role(role: str, vendor: str) -> dict[str, str]:
    model = _pick(
        f"[{role}] model (vendor: {vendor})",
        VENDOR_MODELS.get(vendor, ()),
        allow_custom=True,
    )
    effort = _pick(
        f"[{role}] reasoning effort (vendor: {vendor})",
        VENDOR_EFFORTS.get(vendor, DEFAULT_EFFORTS),
        allow_custom=True,
    )
    return {"vendor": vendor, "model": model, "effort": effort}


def _write_role_tomls(roles: dict[str, dict[str, str]], provider: str) -> None:
    for role, spec in roles.items():
        template = ROLE_TOML_TEMPLATES[spec["vendor"]]
        body = template.format(
            role=role, model=spec["model"], effort=spec["effort"], provider=provider
        )
        path = AGENTS_DIR / f"{role}.toml"
        path.write_text(body, encoding="utf-8")
        print(
            f"[ok] regenerated {path} "
            f"({spec['vendor']}: {spec['model']} / {spec['effort']})"
        )


def main() -> int:
    """Run the interactive configuration CLI.

    Returns:
        Exit code indicating success (0).
    """
    print("=" * 62)
    print(" HaruQuantAI agent workflow configuration")
    print("=" * 62)

    mode = _pick(
        "1. Orchestration mode", tuple(f"{name} — {desc}" for name, desc in MODES)
    )
    mode_name = mode.split(" — ")[0]

    lines = [
        "# Generated by .agents/configure.py — read by the chat orchestrator",
        "# (.agents/ORCHESTRATOR.md). Re-run configure.py to change.",
        f"# generated: {_dt.datetime.now(tz=_dt.UTC).isoformat(timespec='seconds')}",
        f'mode = "{mode_name}"',
    ]
    roles: dict[str, dict[str, str]] = {}
    provider = "zai-coding-plan"

    if mode_name in ("delegate", "multi-delegate"):
        if mode_name == "delegate":
            print("\nDelegate mode: one vendor (brand) for ALL roles.")
            vendor = _pick("2. Vendor (single brand)", VENDORS)
            for role in ROLES:
                spec = _ask_role(role, vendor)
                roles[role] = spec
            lines += ["", f'vendor = "{vendor}"']
        else:
            for role in ROLES:
                print(f"\nMulti-delegate mode: configure the {role} role.")
                vendor = _pick(f"[{role}] 2. Vendor", VENDORS)
                roles[role] = _ask_role(role, vendor)
        for role in ROLES:
            spec = roles[role]
            lines += [
                "",
                f"[roles.{role}]",
                f'vendor = "{spec["vendor"]}"',
                f'model = "{spec["model"]}"',
                f'effort = "{spec["effort"]}"',
            ]

    CONFIG_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n[ok] wrote {CONFIG_PATH}")

    if mode_name == "multi-delegate":
        if any(spec["vendor"] == "cline" for spec in roles.values()):
            answer = _ask("\nCline provider id [press Enter for zai-coding-plan]: ")
            provider = answer or "zai-coding-plan"
        _write_role_tomls(roles, provider)
        print("\nNext steps: python .agents/orchestrator.py doctor, then")
        print("  python .agents/orchestrator.py start --task-file <task.toml>")
    elif mode_name == "delegate":
        print("\nNext steps: in your orchestrating chat, read")
        print("  .agents/ORCHESTRATOR.md section 3 and start the task.")
    elif mode_name == "solo":
        print("\nNext steps: in your orchestrating chat, read")
        print("  .agents/ORCHESTRATOR.md section 2 and start the task.")
    else:
        print("\nNext steps: read .agents/ORCHESTRATOR.md section 5 (manual relay).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
