#!/usr/bin/env python3
"""Interactive configuration picker for HaruQuantAI agent orchestration."""

from __future__ import annotations

import datetime as dt
import json
import sys
from pathlib import Path

AGENTS_DIR = Path(__file__).resolve().parent
RUN_CONFIG = AGENTS_DIR / "run-config.toml"
ROLES = ("planner", "executor", "reviewer")
MODES = (
    ("solo", "One chat performs sequential roles with soft cross-role isolation"),
    ("delegate", "One persistent same-brand delegate session per role"),
    ("multi-delegate", "One persistent cross-vendor CLI conversation per role"),
    ("manual", "One orchestrator chat plus three persistent role chats"),
)
VENDORS = ("zai", "codex", "agy", "cline", "claude")
SESSION_CLI_VENDORS = frozenset({"zai", "codex", "agy", "cline"})
MODELS: dict[str, tuple[str, ...]] = {
    "zai": ("sol", "luna", "terra", "glm-5.3", "glm-5.2"),
    "codex": ("gpt-5.6-sol",),
    "agy": ("gemini-3.7-flash-high", "gemini-3.6-flash-high"),
    "cline": ("glm-5.3", "glm-5.2"),
    "claude": ("sonnet", "opus"),
}
EFFORTS = ("low", "medium", "high", "xhigh")

ROLE_TEMPLATE = {
    "planner": "docs/templates/prompt/planner.md",
    "executor": "docs/templates/prompt/executor.md",
    "reviewer": "docs/templates/prompt/reviewer.md",
}


def _ask(prompt: str) -> str:
    try:
        return input(prompt).strip()
    except EOFError:
        sys.exit("No interactive input available.")


def _pick(label: str, options: tuple[str, ...], *, custom: bool = False) -> str:
    print(f"\n{label}")
    for index, option in enumerate(options, start=1):
        print(f"  {index}) {option}")
    while True:
        answer = _ask("Selection: ")
        if answer.isdigit() and 1 <= int(answer) <= len(options):
            return options[int(answer) - 1]
        if custom and answer:
            return answer
        print("Invalid selection.")


def _session_command(
    role: str,
    *,
    brand: str,
    model: str,
    effort: str,
    provider: str = "",
) -> list[str]:
    command = [
        "python",
        ".agents/session_runner.py",
        "--brand",
        brand,
        "--role",
        role,
        "--model",
        model,
        "--effort",
        effort,
    ]
    if provider:
        command.extend(["--provider", provider])
    if brand == "agy":
        command.extend(["--print-timeout", "110m"])
    command.append("{prompt}")
    return command


def _role_toml(role: str, vendor: str, model: str, effort: str, provider: str) -> str:
    if vendor not in SESSION_CLI_VENDORS:
        raise ValueError(
            f"Vendor {vendor!r} has no verified native session adapter for "
            "multi-delegate mode. Choose codex, agy, cline, or zai."
        )
    template = ROLE_TEMPLATE[role]
    brand = "cline" if vendor in {"cline", "zai"} else vendor
    if vendor == "zai":
        chosen_provider = "zai-coding-plan"
    elif brand == "cline":
        chosen_provider = provider
    else:
        chosen_provider = ""
    command = _session_command(
        role,
        brand=brand,
        model=model,
        effort=effort,
        provider=chosen_provider,
    )
    lines = [
        f"# {role} agent — generated by .agents/configure.py (vendor: {vendor}).",
        f"brand = {json.dumps(brand)}",
        f"session_adapter = {json.dumps(brand)}",
        'session_continuity = "required"',
    ]
    if chosen_provider:
        lines.append(f"provider = {json.dumps(chosen_provider)}")
    lines.extend(
        [
            f"model = {json.dumps(model, ensure_ascii=False)}",
            f"effort = {json.dumps(effort, ensure_ascii=False)}",
            f"command = {json.dumps(command, ensure_ascii=False)}",
            'prompt_delivery = "file"',
            f"template = {json.dumps(template, ensure_ascii=False)}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    print("HaruQuantAI agent workflow configuration")
    mode_display = _pick(
        "Orchestration mode",
        tuple(f"{name} — {description}" for name, description in MODES),
    )
    mode = mode_display.split(" — ", maxsplit=1)[0]
    lines = [
        "# Generated by .agents/configure.py; runtime-only and gitignored.",
        f"# generated: {dt.datetime.now(tz=dt.UTC).isoformat(timespec='seconds')}",
        f"mode = {json.dumps(mode)}",
    ]
    role_specs: dict[str, tuple[str, str, str]] = {}
    if mode in {"delegate", "multi-delegate"}:
        vendor_options = (
            VENDORS
            if mode == "delegate"
            else tuple(vendor for vendor in VENDORS if vendor in SESSION_CLI_VENDORS)
        )
        shared_vendor = (
            _pick("Vendor for all roles", vendor_options) if mode == "delegate" else ""
        )
        for role in ROLES:
            vendor = shared_vendor or _pick(f"[{role}] vendor", vendor_options)
            model = _pick(f"[{role}] model", MODELS.get(vendor, ()), custom=True)
            effort = _pick(f"[{role}] reasoning effort", EFFORTS, custom=True)
            role_specs[role] = (vendor, model, effort)
            lines.extend(
                [
                    "",
                    f"[roles.{role}]",
                    f"vendor = {json.dumps(vendor)}",
                    f"model = {json.dumps(model)}",
                    f"effort = {json.dumps(effort)}",
                    'session_continuity = "same-role"',
                ]
            )
    RUN_CONFIG.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[ok] wrote {RUN_CONFIG}")
    if mode == "multi-delegate":
        provider = _ask("Cline provider id [zai-coding-plan]: ") or "zai-coding-plan"
        for role, (vendor, model, effort) in role_specs.items():
            path = AGENTS_DIR / f"{role}.toml"
            path.write_text(
                _role_toml(role, vendor, model, effort, provider), encoding="utf-8"
            )
            print(f"[ok] regenerated {path}")
    print("Next role prompt is always .agents/task/next-agent.md.")
    print("Same-role conversation context is preserved for this workflow run only.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
