#!/usr/bin/env python3
"""Interactive configuration picker for HaruQuantAI agent orchestration."""

from __future__ import annotations

import datetime as dt
import json
import sys
from pathlib import Path

AGENTS_DIR = Path(__file__).resolve().parent
RUN_CONFIG = AGENTS_DIR / "run-config.toml"
ROLES = ("planner", "executor", "reviewer")
MODES = (
    ("solo", "One chat performs all roles with soft context isolation"),
    ("delegate", "Fresh same-brand subagent per role"),
    ("multi-delegate", "Fresh cross-vendor CLI process per role"),
    ("manual", "Fresh user-relayed chat per role"),
)
VENDORS = ("zai", "codex", "agy", "cline", "claude")
MODELS: dict[str, tuple[str, ...]] = {
    "zai": ("sol", "luna", "terra", "glm-5.3", "glm-5.2"),
    "codex": ("gpt-5.6-sol",),
    "agy": ("gemini-3.7-flash-high", "gemini-3.6-flash-high"),
    "cline": ("glm-5.3", "glm-5.2"),
    "claude": ("sonnet", "opus"),
}
EFFORTS = ("low", "medium", "high", "xhigh")

ROLE_TEMPLATE = {
    "planner": "docs/templates/prompt/planner.md",
    "executor": "docs/templates/prompt/executor.md",
    "reviewer": "docs/templates/prompt/reviewer.md",
}


def _ask(prompt: str) -> str:
    try:
        return input(prompt).strip()
    except EOFError:
        sys.exit("No interactive input available.")


def _pick(label: str, options: tuple[str, ...], *, custom: bool = False) -> str:
    print(f"\n{label}")
    for index, option in enumerate(options, start=1):
        print(f"  {index}) {option}")
    while True:
        answer = _ask("Selection: ")
        if answer.isdigit() and 1 <= int(answer) <= len(options):
            return options[int(answer) - 1]
        if custom and answer:
            return answer
        print("Invalid selection.")


def _role_toml(role: str, vendor: str, model: str, effort: str, provider: str) -> str:
    template = ROLE_TEMPLATE[role]
    model_q = json.dumps(model, ensure_ascii=False)
    effort_q = json.dumps(effort, ensure_ascii=False)
    template_q = json.dumps(template, ensure_ascii=False)
    if vendor == "codex":
        return (
            f"# {role} agent — generated by .agents/configure.py (vendor: codex).\n"
            'brand = "codex"\n'
            'command = ["codex", "exec", "-s", "danger-full-access"]\n'
            f'model_args = ["-m", {model_q}, "-c", '
            f"{json.dumps(f'model_reasoning_effort={effort}')}]\n"
            'prompt_delivery = "file"\n'
            f"template = {template_q}\n"
        )
    if vendor == "agy":
        return (
            f"# {role} agent — generated by .agents/configure.py (vendor: agy).\n"
            'brand = "agy"\n'
            'command = ["agy", "--dangerously-skip-permissions", '
            f'"--model", {model_q}, "--effort", {effort_q}, '
            '"--print-timeout", "110m", "-p"]\n'
            'prompt_delivery = "file"\n'
            f"template = {template_q}\n"
        )
    if vendor in {"cline", "zai"}:
        chosen_provider = "zai-coding-plan" if vendor == "zai" else provider
        return (
            f"# {role} agent — generated by .agents/configure.py (vendor: {vendor}).\n"
            'brand = "cline"\n'
            f'command = ["cline", "-P", '
            f'{json.dumps(chosen_provider, ensure_ascii=False)}, "-m", {model_q}, '
            f'"--thinking", {effort_q}]\n'
            'prompt_delivery = "file"\n'
            f"template = {template_q}\n"
        )
    if vendor == "claude":
        return (
            f"# {role} agent — generated by .agents/configure.py (vendor: claude).\n"
            'brand = "claude"\n'
            'command = ["claude", "-p", "--dangerously-skip-permissions"]\n'
            f'model_args = ["--model", {model_q}]\n'
            'prompt_delivery = "file"\n'
            f"template = {template_q}\n"
        )
    raise ValueError(f"Unsupported workflow adapter: {vendor}")


def main() -> int:
    print("HaruQuantAI agent workflow configuration")
    mode_display = _pick(
        "Orchestration mode",
        tuple(f"{name} — {description}" for name, description in MODES),
    )
    mode = mode_display.split(" — ", maxsplit=1)[0]
    lines = [
        "# Generated by .agents/configure.py; runtime-only and gitignored.",
        f"# generated: {dt.datetime.now(tz=dt.UTC).isoformat(timespec='seconds')}",
        f"mode = {json.dumps(mode)}",
    ]
    role_specs: dict[str, tuple[str, str, str]] = {}
    if mode in {"delegate", "multi-delegate"}:
        shared_vendor = (
            _pick("Vendor for all roles", VENDORS) if mode == "delegate" else ""
        )
        for role in ROLES:
            vendor = shared_vendor or _pick(f"[{role}] vendor", VENDORS)
            model = _pick(f"[{role}] model", MODELS.get(vendor, ()), custom=True)
            effort = _pick(f"[{role}] reasoning effort", EFFORTS, custom=True)
            role_specs[role] = (vendor, model, effort)
            lines.extend(
                [
                    "",
                    f"[roles.{role}]",
                    f"vendor = {json.dumps(vendor)}",
                    f"model = {json.dumps(model)}",
                    f"effort = {json.dumps(effort)}",
                ]
            )
    RUN_CONFIG.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[ok] wrote {RUN_CONFIG}")
    if mode == "multi-delegate":
        provider = _ask("Cline provider id [zai-coding-plan]: ") or "zai-coding-plan"
        for role, (vendor, model, effort) in role_specs.items():
            path = AGENTS_DIR / f"{role}.toml"
            path.write_text(
                _role_toml(role, vendor, model, effort, provider), encoding="utf-8"
            )
            print(f"[ok] regenerated {path}")
    print("Next role prompt is always .agents/task/next-agent.md.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
