#!/usr/bin/env python3
"""Generate .agents/task.toml from an implementation-order entry.

Parses the `##### 1.1 [ ] FEAT-...` feature headings and their `FR-*`
checkboxes, then writes a ready-to-run task spec wired to the tracker entry.

Usage:
    python .agents/make_task.py --list              # show open entries
    python .agents/make_task.py 1.1                 # write .agents/task.toml
    python .agents/make_task.py 2.8 --out other.toml
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

AGENTS_DIR = Path(__file__).resolve().parent
REPO = AGENTS_DIR.parent

ENTRY_RE = re.compile(
    r"^#####\s+(\d+\.\d+)\s+(?P<partial>Partial\s+—\s+)?(?:\[(?P<mark>[ xX])\]\s*)?"
    r"`?(?P<feature>FEAT-[A-Z0-9_-]+)`?"
)
FR_RE = re.compile(r"^\d+\.\s+\[?([ xX])\]?\s*`?(FR-[A-Z0-9_-]+)`?")


def parse_entries(path: Path) -> dict[str, dict]:
    """Return {entry_id: {feature, done, partial, frs: [(id, done)]}}."""
    entries: dict[str, dict] = {}
    current: dict | None = None
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        match = ENTRY_RE.match(line)
        if match:
            mark = match.group("mark")
            current = {
                "feature": match.group("feature"),
                "done": mark.lower() == "x" if mark else False,
                "partial": bool(match.group("partial")),
                "frs": [],
            }
            entries[match.group(1)] = current
            continue
        fr = FR_RE.match(line)
        if fr and current is not None:
            current["frs"].append((fr.group(2), fr.group(1).lower() == "x"))
        elif line.startswith("#"):
            current = None
    return entries


def main() -> int:
    """Parse CLI arguments and generate the task spec file.

    Returns:
        Process exit code (0 on success).
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("entry", nargs="?", help="entry id, e.g. 1.1")
    parser.add_argument(
        "--file",
        default="docs/dev/IMPLEMENTATION_ORDER.md",
        help="implementation tracker (default: docs/dev/IMPLEMENTATION_ORDER.md)",
    )
    parser.add_argument(
        "--out",
        default=str(AGENTS_DIR / "task.toml"),
        help="output path (default: .agents/task.toml)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="generate even if the entry is already complete",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="list open entries and exit",
    )
    args = parser.parse_args()

    tracker = (REPO / args.file).resolve()
    if not tracker.exists():
        print(f"[FAIL] tracker not found: {tracker}")
        return 1
    entries = parse_entries(tracker)

    if args.list or not args.entry:
        open_entries = [
            (eid, e)
            for eid, e in sorted(entries.items())
            if not e["done"] and not all(done for _, done in e["frs"])
        ]
        for eid, e in open_entries[:20]:
            state = "Partial" if e["partial"] else ""
            print(f"  {eid:5} [{len(e['frs'])} FRs] {state:8} {e['feature']}")
        print(f"({len(open_entries)} open entries in {args.file})")
        return 0

    entry = entries.get(args.entry)
    if entry is None:
        print(f"[FAIL] entry {args.entry!r} not found in {tracker}; use --list")
        return 1
    if entry["done"] and not args.force:
        print(
            f"[FAIL] entry {args.entry} ({entry['feature']}) is already complete; "
            "use --force to regenerate anyway."
        )
        return 1

    feature = entry["feature"]
    name_part = feature.split("-", 2)[-1]  # MANAGE_WORKSPACES
    task_slug = name_part.lower().replace("_", "-")
    task_name = name_part.replace("_", " ").title()
    fr_ids = [fr for fr, _ in entry["frs"]]
    partial_note = (
        "This is a Partial slice: implement ONLY the listed requirement slice."
        if entry["partial"]
        else ""
    )
    task_request = (
        f"Implement entry {args.entry} {feature} from {args.file}: "
        + ", ".join(fr_ids)
        + ". Follow the owning README as the sole feature/FR registry and AGENTS.md"
        " for all workflow rules. Mark the tracker entry complete with evidence"
        " when every gate passes." + (f" {partial_note}" if partial_note else "")
    )

    body = f"""\
# Generated by .agents/make_task.py from {args.file} entry {args.entry}.
# Edit freely before running; this file is scratch (gitignored).

task_kind = "feature"
task_id = "{feature}"
task_slug = "{task_slug}"
task_name = "{task_name}"
task_request = "{task_request}"
additional_context = "Owning README is the acceptance authority."
exclusions = "No unrelated features; no scope beyond the listed requirements."
owner_execution_notes = "None"
review_focus = "None"
implementation_file = "{args.file}"
implementation_entry = "{args.entry}"
"""
    out_path = Path(args.out)
    out_path.write_text(body, encoding="utf-8")
    print(f"[ok] wrote {out_path} for {args.entry} {feature}")
    print(f"     FRs: {', '.join(fr_ids) if fr_ids else '(none parsed)'}")
    print(f"     start with: read .agents/ORCHESTRATOR.md and run task {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
