#!/usr/bin/env python3
"""Generate .agents/goal.toml for deterministic multi-Task Goal orchestration."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

AGENTS_DIR = Path(__file__).resolve().parent
REPO = AGENTS_DIR.parent
sys.path.insert(0, str(AGENTS_DIR))

from goal_engine import resolve_goal_entries  # noqa: E402
from make_task import parse_entries  # noqa: E402


def _q(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _slug(value: str) -> str:
    result = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return result or "goal"


def _build_spec(args: argparse.Namespace) -> dict[str, Any]:
    if args.entries:
        selection_type = "entries"
        selection_value: Any = list(args.entries)
        default_name = "Complete Selected Implementation Entries"
        default_id = "GOAL-SELECTED-ENTRIES"
    elif args.phase:
        selection_type = "phase"
        selection_value = str(args.phase)
        default_name = f"Complete Implementation Phase {args.phase}"
        default_id = f"GOAL-PHASE-{args.phase}"
    else:
        selection_type = "all_open"
        selection_value = None
        default_name = "Complete All Open Implementation Entries"
        default_id = "GOAL-ALL-OPEN"
    name = args.goal_name or default_name
    goal_id = args.goal_id or default_id
    spec: dict[str, Any] = {
        "goal_id": goal_id,
        "goal_slug": args.goal_slug or _slug(name),
        "goal_name": name,
        "goal_request": args.goal_request
        or f"Execute {name} through independent HaruQuantAI child Task workflows.",
        "implementation_file": args.file,
        "selection_type": selection_type,
        "execution_order": "listed"
        if args.entries and args.listed_order
        else "tracker",
        "skip_completed": True,
        "stop_on_blocked": True,
    }
    if selection_type == "entries":
        spec["entries"] = selection_value
    elif selection_type == "phase":
        spec["selection"] = selection_value
    return spec


def _render(spec: dict[str, Any]) -> str:
    lines = [
        "# Generated by .agents/make_goal.py; runtime-only and gitignored.",
        f"goal_id = {_q(str(spec['goal_id']))}",
        f"goal_slug = {_q(str(spec['goal_slug']))}",
        f"goal_name = {_q(str(spec['goal_name']))}",
        f"goal_request = {_q(str(spec['goal_request']))}",
        f"implementation_file = {_q(str(spec['implementation_file']))}",
        f"selection_type = {_q(str(spec['selection_type']))}",
    ]
    if spec["selection_type"] == "entries":
        entries = ", ".join(_q(str(value)) for value in spec["entries"])
        lines.append(f"entries = [{entries}]")
    elif spec["selection_type"] == "phase":
        lines.append(f"selection = {_q(str(spec['selection']))}")
    lines.extend(
        [
            f"execution_order = {_q(str(spec['execution_order']))}",
            "skip_completed = true",
            "stop_on_blocked = true",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    selection = parser.add_mutually_exclusive_group(required=True)
    selection.add_argument("--entries", nargs="+")
    selection.add_argument("--phase")
    selection.add_argument("--all-open", action="store_true")
    parser.add_argument("--file", default="docs/dev/IMPLEMENTATION_ORDER.md")
    parser.add_argument("--out", default=str(AGENTS_DIR / "goal.toml"))
    parser.add_argument("--goal-id")
    parser.add_argument("--goal-slug")
    parser.add_argument("--goal-name")
    parser.add_argument("--goal-request")
    parser.add_argument(
        "--listed-order",
        action="store_true",
        help="Preserve explicit --entries order instead of tracker order.",
    )
    args = parser.parse_args()
    tracker = (REPO / args.file).resolve()
    if not tracker.exists():
        print(f"[FAIL] tracker not found: {tracker}")
        return 1
    spec = _build_spec(args)
    try:
        resolved = resolve_goal_entries(spec, parse_entries(tracker))
    except RuntimeError as exc:
        print(f"[FAIL] {exc}")
        return 1
    out = Path(args.out)
    out.write_text(_render(spec), encoding="utf-8")
    print(f"[ok] wrote {out}")
    print(f"     Goal: {spec['goal_name']}")
    print(f"     Child Tasks ({len(resolved)}): {', '.join(resolved)}")
    print(f"     next: uv run .agents/orchestrator.py goal-start --goal-file {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
