# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from enum import IntEnum
from typing import Final


class ENUM_PROGRAM_INFO_INTEGER(IntEnum):
    """Defines the identifier set for MQL info integer."""

    PROGRAM_HANDLES_USED = 0
    PROGRAM_MEMORY_LIMIT = 1
    PROGRAM_MEMORY_USED = 2
    PROGRAM_PROGRAM_TYPE = 3
    PROGRAM_DLLS_ALLOWED = 4
    PROGRAM_TRADE_ALLOWED = 5
    PROGRAM_SIGNALS_ALLOWED = 6
    PROGRAM_DEBUG = 7
    PROGRAM_PROFILER = 8
    PROGRAM_TESTER = 9
    PROGRAM_FORWARD = 10
    PROGRAM_OPTIMIZATION = 11
    PROGRAM_VISUAL_MODE = 12
    PROGRAM_FRAME_MODE = 13
    PROGRAM_LICENSE_TYPE = 14
    PROGRAM_STARTED_FROM_CONFIG = 15


PROGRAM_HANDLES_USED: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_HANDLES_USED
PROGRAM_MEMORY_LIMIT: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_MEMORY_LIMIT
PROGRAM_MEMORY_USED: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_MEMORY_USED
PROGRAM_PROGRAM_TYPE: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_PROGRAM_TYPE
PROGRAM_DLLS_ALLOWED: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_DLLS_ALLOWED
PROGRAM_TRADE_ALLOWED: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_TRADE_ALLOWED
PROGRAM_SIGNALS_ALLOWED: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_SIGNALS_ALLOWED
PROGRAM_DEBUG: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_DEBUG
PROGRAM_PROFILER: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_PROFILER
PROGRAM_TESTER: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_TESTER
PROGRAM_FORWARD: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_FORWARD
PROGRAM_OPTIMIZATION: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_OPTIMIZATION
PROGRAM_VISUAL_MODE: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_VISUAL_MODE
PROGRAM_FRAME_MODE: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_FRAME_MODE
PROGRAM_LICENSE_TYPE: Final = ENUM_PROGRAM_INFO_INTEGER.PROGRAM_LICENSE_TYPE
PROGRAM_STARTED_FROM_CONFIG: Final = (
    ENUM_PROGRAM_INFO_INTEGER.PROGRAM_STARTED_FROM_CONFIG
)


class ENUM_PROGRAM_INFO_STRING(IntEnum):
    """Defines the identifier set for MQL info string."""

    PROGRAM_PROGRAM_NAME = 0
    PROGRAM_PROGRAM_PATH = 1


PROGRAM_PROGRAM_NAME: Final = ENUM_PROGRAM_INFO_STRING.PROGRAM_PROGRAM_NAME
PROGRAM_PROGRAM_PATH: Final = ENUM_PROGRAM_INFO_STRING.PROGRAM_PROGRAM_PATH


class ENUM_PROGRAM_TYPE(IntEnum):
    """Defines the identifier set for program type."""

    PROGRAM_SCRIPT = 0
    PROGRAM_EXPERT = 1
    PROGRAM_INDICATOR = 2
    PROGRAM_SERVICE = 3


PROGRAM_SCRIPT: Final = ENUM_PROGRAM_TYPE.PROGRAM_SCRIPT
PROGRAM_EXPERT: Final = ENUM_PROGRAM_TYPE.PROGRAM_EXPERT
PROGRAM_INDICATOR: Final = ENUM_PROGRAM_TYPE.PROGRAM_INDICATOR
PROGRAM_SERVICE: Final = ENUM_PROGRAM_TYPE.PROGRAM_SERVICE


class ENUM_RUNTIME_INFO_DOUBLE(IntEnum):
    """Defines the identifier set for terminal info double."""

    RUNTIME_RETRANSMISSION = 1


RUNTIME_RETRANSMISSION: Final = ENUM_RUNTIME_INFO_DOUBLE.RUNTIME_RETRANSMISSION


class ENUM_RUNTIME_INFO_INTEGER(IntEnum):
    """Defines the identifier set for terminal info integer."""

    RUNTIME_BUILD = 0
    RUNTIME_CONNECTED = 3
    RUNTIME_DLLS_ALLOWED = 4
    RUNTIME_TRADE_ALLOWED = 5
    RUNTIME_EMAIL_ENABLED = 6
    RUNTIME_NOTIFICATIONS_ENABLED = 8
    RUNTIME_MAXBARS = 9
    RUNTIME_CODEPAGE = 11
    RUNTIME_CPU_CORES = 12
    RUNTIME_DISK_SPACE = 13
    RUNTIME_MEMORY_PHYSICAL = 14
    RUNTIME_MEMORY_TOTAL = 15
    RUNTIME_MEMORY_AVAILABLE = 16
    RUNTIME_MEMORY_USED = 17
    RUNTIME_X64 = 18
    RUNTIME_OPENCL_SUPPORT = 19
    RUNTIME_SCREEN_DPI = 20
    RUNTIME_SCREEN_LEFT = 21
    RUNTIME_SCREEN_TOP = 22
    RUNTIME_SCREEN_WIDTH = 23
    RUNTIME_SCREEN_HEIGHT = 24
    RUNTIME_LEFT = 25
    RUNTIME_TOP = 26
    RUNTIME_RIGHT = 27
    RUNTIME_BOTTOM = 28
    RUNTIME_PING_LAST = 29
    RUNTIME_VPS = 30
    RUNTIME_KEYSTATE_LEFT = 31
    RUNTIME_KEYSTATE_UP = 32
    RUNTIME_KEYSTATE_RIGHT = 33
    RUNTIME_KEYSTATE_DOWN = 34
    RUNTIME_KEYSTATE_SHIFT = 35
    RUNTIME_KEYSTATE_CONTROL = 36
    RUNTIME_KEYSTATE_MENU = 37
    RUNTIME_KEYSTATE_CAPSLOCK = 38
    RUNTIME_KEYSTATE_NUMLOCK = 39
    RUNTIME_KEYSTATE_SCRLOCK = 40
    RUNTIME_KEYSTATE_ENTER = 41
    RUNTIME_KEYSTATE_INSERT = 42
    RUNTIME_KEYSTATE_DELETE = 43
    RUNTIME_KEYSTATE_HOME = 44
    RUNTIME_KEYSTATE_END = 45
    RUNTIME_KEYSTATE_TAB = 46
    RUNTIME_KEYSTATE_PAGEUP = 47
    RUNTIME_KEYSTATE_PAGEDOWN = 48
    RUNTIME_KEYSTATE_ESCAPE = 49


RUNTIME_BUILD: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_BUILD
RUNTIME_CONNECTED: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_CONNECTED
RUNTIME_DLLS_ALLOWED: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_DLLS_ALLOWED
RUNTIME_TRADE_ALLOWED: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_TRADE_ALLOWED
RUNTIME_EMAIL_ENABLED: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_EMAIL_ENABLED
RUNTIME_NOTIFICATIONS_ENABLED: Final = (
    ENUM_RUNTIME_INFO_INTEGER.RUNTIME_NOTIFICATIONS_ENABLED
)
RUNTIME_MAXBARS: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_MAXBARS
RUNTIME_CODEPAGE: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_CODEPAGE
RUNTIME_CPU_CORES: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_CPU_CORES
RUNTIME_DISK_SPACE: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_DISK_SPACE
RUNTIME_MEMORY_PHYSICAL: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_MEMORY_PHYSICAL
RUNTIME_MEMORY_TOTAL: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_MEMORY_TOTAL
RUNTIME_MEMORY_AVAILABLE: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_MEMORY_AVAILABLE
RUNTIME_MEMORY_USED: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_MEMORY_USED
RUNTIME_X64: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_X64
RUNTIME_OPENCL_SUPPORT: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_OPENCL_SUPPORT
RUNTIME_SCREEN_DPI: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_SCREEN_DPI
RUNTIME_SCREEN_LEFT: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_SCREEN_LEFT
RUNTIME_SCREEN_TOP: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_SCREEN_TOP
RUNTIME_SCREEN_WIDTH: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_SCREEN_WIDTH
RUNTIME_SCREEN_HEIGHT: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_SCREEN_HEIGHT
RUNTIME_LEFT: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_LEFT
RUNTIME_TOP: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_TOP
RUNTIME_RIGHT: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_RIGHT
RUNTIME_BOTTOM: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_BOTTOM
RUNTIME_PING_LAST: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_PING_LAST
RUNTIME_VPS: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_VPS
RUNTIME_KEYSTATE_LEFT: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_LEFT
RUNTIME_KEYSTATE_UP: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_UP
RUNTIME_KEYSTATE_RIGHT: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_RIGHT
RUNTIME_KEYSTATE_DOWN: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_DOWN
RUNTIME_KEYSTATE_SHIFT: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_SHIFT
RUNTIME_KEYSTATE_CONTROL: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_CONTROL
RUNTIME_KEYSTATE_MENU: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_MENU
RUNTIME_KEYSTATE_CAPSLOCK: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_CAPSLOCK
RUNTIME_KEYSTATE_NUMLOCK: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_NUMLOCK
RUNTIME_KEYSTATE_SCRLOCK: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_SCRLOCK
RUNTIME_KEYSTATE_ENTER: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_ENTER
RUNTIME_KEYSTATE_INSERT: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_INSERT
RUNTIME_KEYSTATE_DELETE: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_DELETE
RUNTIME_KEYSTATE_HOME: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_HOME
RUNTIME_KEYSTATE_END: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_END
RUNTIME_KEYSTATE_TAB: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_TAB
RUNTIME_KEYSTATE_PAGEUP: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_PAGEUP
RUNTIME_KEYSTATE_PAGEDOWN: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_PAGEDOWN
RUNTIME_KEYSTATE_ESCAPE: Final = ENUM_RUNTIME_INFO_INTEGER.RUNTIME_KEYSTATE_ESCAPE


class ENUM_RUNTIME_INFO_STRING(IntEnum):
    """Defines the identifier set for terminal info string."""

    RUNTIME_LANGUAGE = 0
    RUNTIME_COMPANY = 1
    RUNTIME_NAME = 2
    RUNTIME_PATH = 3
    RUNTIME_DATA_PATH = 4
    RUNTIME_COMMONDATA_PATH = 5
    RUNTIME_CPU_NAME = 6
    RUNTIME_CPU_ARCHITECTURE = 7
    RUNTIME_OS_VERSION = 8
    RUNTIME_COLORTHEME_NAME = 9


RUNTIME_LANGUAGE: Final = ENUM_RUNTIME_INFO_STRING.RUNTIME_LANGUAGE
RUNTIME_COMPANY: Final = ENUM_RUNTIME_INFO_STRING.RUNTIME_COMPANY
RUNTIME_NAME: Final = ENUM_RUNTIME_INFO_STRING.RUNTIME_NAME
RUNTIME_PATH: Final = ENUM_RUNTIME_INFO_STRING.RUNTIME_PATH
RUNTIME_DATA_PATH: Final = ENUM_RUNTIME_INFO_STRING.RUNTIME_DATA_PATH
RUNTIME_COMMONDATA_PATH: Final = ENUM_RUNTIME_INFO_STRING.RUNTIME_COMMONDATA_PATH
RUNTIME_CPU_NAME: Final = ENUM_RUNTIME_INFO_STRING.RUNTIME_CPU_NAME
RUNTIME_CPU_ARCHITECTURE: Final = ENUM_RUNTIME_INFO_STRING.RUNTIME_CPU_ARCHITECTURE
RUNTIME_OS_VERSION: Final = ENUM_RUNTIME_INFO_STRING.RUNTIME_OS_VERSION
RUNTIME_COLORTHEME_NAME: Final = ENUM_RUNTIME_INFO_STRING.RUNTIME_COLORTHEME_NAME

__all__ = [
    "ENUM_PROGRAM_INFO_INTEGER",
    "ENUM_PROGRAM_INFO_STRING",
    "ENUM_PROGRAM_TYPE",
    "ENUM_RUNTIME_INFO_DOUBLE",
    "ENUM_RUNTIME_INFO_INTEGER",
    "ENUM_RUNTIME_INFO_STRING",
    "PROGRAM_DEBUG",
    "PROGRAM_DLLS_ALLOWED",
    "PROGRAM_EXPERT",
    "PROGRAM_FORWARD",
    "PROGRAM_FRAME_MODE",
    "PROGRAM_HANDLES_USED",
    "PROGRAM_INDICATOR",
    "PROGRAM_LICENSE_TYPE",
    "PROGRAM_MEMORY_LIMIT",
    "PROGRAM_MEMORY_USED",
    "PROGRAM_OPTIMIZATION",
    "PROGRAM_PROFILER",
    "PROGRAM_PROGRAM_NAME",
    "PROGRAM_PROGRAM_PATH",
    "PROGRAM_PROGRAM_TYPE",
    "PROGRAM_SCRIPT",
    "PROGRAM_SERVICE",
    "PROGRAM_SIGNALS_ALLOWED",
    "PROGRAM_STARTED_FROM_CONFIG",
    "PROGRAM_TESTER",
    "PROGRAM_TRADE_ALLOWED",
    "PROGRAM_VISUAL_MODE",
    "RUNTIME_BOTTOM",
    "RUNTIME_BUILD",
    "RUNTIME_CODEPAGE",
    "RUNTIME_COLORTHEME_NAME",
    "RUNTIME_COMMONDATA_PATH",
    "RUNTIME_COMPANY",
    "RUNTIME_CONNECTED",
    "RUNTIME_CPU_ARCHITECTURE",
    "RUNTIME_CPU_CORES",
    "RUNTIME_CPU_NAME",
    "RUNTIME_DATA_PATH",
    "RUNTIME_DISK_SPACE",
    "RUNTIME_DLLS_ALLOWED",
    "RUNTIME_EMAIL_ENABLED",
    "RUNTIME_KEYSTATE_CAPSLOCK",
    "RUNTIME_KEYSTATE_CONTROL",
    "RUNTIME_KEYSTATE_DELETE",
    "RUNTIME_KEYSTATE_DOWN",
    "RUNTIME_KEYSTATE_END",
    "RUNTIME_KEYSTATE_ENTER",
    "RUNTIME_KEYSTATE_ESCAPE",
    "RUNTIME_KEYSTATE_HOME",
    "RUNTIME_KEYSTATE_INSERT",
    "RUNTIME_KEYSTATE_LEFT",
    "RUNTIME_KEYSTATE_MENU",
    "RUNTIME_KEYSTATE_NUMLOCK",
    "RUNTIME_KEYSTATE_PAGEDOWN",
    "RUNTIME_KEYSTATE_PAGEUP",
    "RUNTIME_KEYSTATE_RIGHT",
    "RUNTIME_KEYSTATE_SCRLOCK",
    "RUNTIME_KEYSTATE_SHIFT",
    "RUNTIME_KEYSTATE_TAB",
    "RUNTIME_KEYSTATE_UP",
    "RUNTIME_LANGUAGE",
    "RUNTIME_LEFT",
    "RUNTIME_MAXBARS",
    "RUNTIME_MEMORY_AVAILABLE",
    "RUNTIME_MEMORY_PHYSICAL",
    "RUNTIME_MEMORY_TOTAL",
    "RUNTIME_MEMORY_USED",
    "RUNTIME_NAME",
    "RUNTIME_NOTIFICATIONS_ENABLED",
    "RUNTIME_OPENCL_SUPPORT",
    "RUNTIME_OS_VERSION",
    "RUNTIME_PATH",
    "RUNTIME_PING_LAST",
    "RUNTIME_RETRANSMISSION",
    "RUNTIME_RIGHT",
    "RUNTIME_SCREEN_DPI",
    "RUNTIME_SCREEN_HEIGHT",
    "RUNTIME_SCREEN_LEFT",
    "RUNTIME_SCREEN_TOP",
    "RUNTIME_SCREEN_WIDTH",
    "RUNTIME_TOP",
    "RUNTIME_TRADE_ALLOWED",
    "RUNTIME_VPS",
    "RUNTIME_X64",
]
