"""Simulation contracts module.

Defines BacktestConfig and BacktestResult contracts.
"""

from __future__ import annotations

import hashlib
from datetime import UTC, datetime
from typing import Any

from app.services.simulator.errors import SimulationError as ValidationError
from app.utils.standard import SENSITIVE_KEY_PATTERN, canonical_json
from pydantic import BaseModel, Field, field_validator, model_validator

_SCHEMA_VERSION_MIN_PARTS = 2

_TRACE_FIELDS: frozenset[str] = frozenset(
    {"created_at", "request_id", "workflow_id", "correlation_id"}
)


class Contract(BaseModel):
    """Local base model for simulator contracts."""

    schema_version: str = Field(default="1.0.0")
    created_at: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())
    request_id: str | None = None
    workflow_id: str | None = None
    correlation_id: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("metadata")
    @classmethod
    def validate_metadata_structure(cls, value: dict[str, Any]) -> dict[str, Any]:
        """Validate metadata namespacing and secret safety."""
        for key in value:
            if not isinstance(key, str):
                raise TypeError("Metadata keys must be strings.")
            if "." not in key and ":" not in key:
                raise ValueError("Metadata keys must be namespaced.")
            if SENSITIVE_KEY_PATTERN.search(key):
                raise ValueError("Metadata key matches sensitive key pattern.")
        try:
            canonical_json(value)
        except (TypeError, ValueError) as exc:
            msg = f"Metadata is not deterministically serializable: {exc}"
            raise ValueError(msg) from exc
        return value

    @model_validator(mode="after")
    def validate_trace_identifiers(self) -> Contract:
        """Validate trace identifier fields."""
        for name in ("request_id", "workflow_id", "correlation_id"):
            value = getattr(self, name)
            if value is not None and (not isinstance(value, str) or not value.strip()):
                msg = f"{name} must be a non-empty string or None."
                raise ValueError(msg)
        return self

    def to_json(self) -> str:
        """Serialize this contract to deterministic canonical JSON."""
        try:
            return canonical_json(self.model_dump())
        except (TypeError, ValueError) as exc:
            msg = f"Failed to serialize contract: {exc}"
            raise ValidationError(msg) from exc

    def content_hash(self) -> str:
        """Calculate a stable SHA256 hash over business-data fields only."""
        payload = {
            key: value
            for key, value in self.model_dump().items()
            if key not in _TRACE_FIELDS
        }
        try:
            serialized = canonical_json(payload)
        except (TypeError, ValueError) as exc:
            msg = f"Failed to compute content hash: {exc}"
            raise ValidationError(msg) from exc
        return hashlib.sha256(serialized.encode("utf-8")).hexdigest()

    def contract_hash(self) -> str:
        """Calculate SHA256 hash over the full serialized contract."""
        return hashlib.sha256(self.to_json().encode("utf-8")).hexdigest()

    def check_compatibility(self, target_version: str) -> bool:
        """Check whether this contract version is compatible with a target."""
        try:
            current_parts = [int(part) for part in self.schema_version.split(".")]
            target_parts = [int(part) for part in target_version.split(".")]
            return (
                len(current_parts) >= _SCHEMA_VERSION_MIN_PARTS
                and len(target_parts) >= _SCHEMA_VERSION_MIN_PARTS
                and current_parts[0] == target_parts[0]
                and current_parts[1] >= target_parts[1]
            )
        except ValueError:
            return False


class BacktestConfig(Contract):
    """Configuration constraints for running a simulator backtest."""

    dataset_refs: list[str] = Field(
        default_factory=list,
        description="References to historical datasets used.",
    )
    strategy_refs: list[str] = Field(
        default_factory=list,
        description="References to strategy models and configs tested.",
    )
    cost_model: str = Field(
        ..., description="Cost model rules mapping (e.g. standard_commission)."
    )
    fill_model: str = Field(
        ..., description="Order execution fill model style (e.g. bar_close)."
    )
    calendar: str = Field(..., description="Session calendar identifier.")
    split_policy: str = Field(
        ..., description="Data splits validation model (e.g. train_test_split)."
    )
    reproducibility_seed: int | None = Field(
        default=None, description="Random seed value for deterministic runs."
    )


class BacktestResult(Contract):
    """The canonical outcomes generated by a simulator run."""

    run_id: str = Field(..., description="Unique backtest Run ID.")
    config_hash: str = Field(
        ..., description="SHA256 fingerprint hash of BacktestConfig."
    )
    journal_ref: str = Field(
        ..., description="Reference link/URI to Persisted ExecutionJournal."
    )
    equity_curve_ref: str = Field(
        ..., description="Reference link/URI to computed equity curve dataset."
    )
    metrics_ref: str = Field(
        ..., description="Reference link/URI to analytics metrics summary."
    )
    evidence_metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Evidence validation files and checksums metadata.",
    )
