# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from typing import Final

ERR_MATRIX_INTERNAL: Final[int] = 5700
ERR_MATRIX_NOT_INITIALIZED: Final[int] = 5701
ERR_MATRIX_INCONSISTENT: Final[int] = 5702
ERR_MATRIX_INVALID_SIZE: Final[int] = 5703
ERR_MATRIX_INVALID_TYPE: Final[int] = 5704
ERR_MATRIX_FUNC_NOT_ALLOWED: Final[int] = 5705
ERR_MATRIX_CONTAINS_NAN: Final[int] = 5706
ERR_ONNX_INTERNAL: Final[int] = 5800
ERR_ONNX_NOT_INITIALIZED: Final[int] = 5801
ERR_ONNX_NOT_SUPPORTED: Final[int] = 5802
ERR_ONNX_RUN_FAILED: Final[int] = 5803
ERR_ONNX_INVALID_PARAMETERS_COUNT: Final[int] = 5804
ERR_ONNX_INVALID_PARAMETER: Final[int] = 5805
ERR_ONNX_INVALID_PARAMETER_TYPE: Final[int] = 5806
ERR_ONNX_INVALID_PARAMETER_SIZE: Final[int] = 5807
ERR_ONNX_WRONG_DIMENSION: Final[int] = 5808

__all__ = [
    "ERR_MATRIX_CONTAINS_NAN",
    "ERR_MATRIX_FUNC_NOT_ALLOWED",
    "ERR_MATRIX_INCONSISTENT",
    "ERR_MATRIX_INTERNAL",
    "ERR_MATRIX_INVALID_SIZE",
    "ERR_MATRIX_INVALID_TYPE",
    "ERR_MATRIX_NOT_INITIALIZED",
    "ERR_ONNX_INTERNAL",
    "ERR_ONNX_INVALID_PARAMETER",
    "ERR_ONNX_INVALID_PARAMETER_SIZE",
    "ERR_ONNX_INVALID_PARAMETER_TYPE",
    "ERR_ONNX_INVALID_PARAMETERS_COUNT",
    "ERR_ONNX_NOT_INITIALIZED",
    "ERR_ONNX_NOT_SUPPORTED",
    "ERR_ONNX_RUN_FAILED",
    "ERR_ONNX_WRONG_DIMENSION",
]
