"""Stable enumerations for the Risk domain."""

from enum import StrEnum


class DecisionState(StrEnum):
    """Canonical Risk decision states."""

    APPROVE = "approve"
    WARN = "warn"
    NEEDS_APPROVAL = "needs_approval"
    NEEDS_MORE_EVIDENCE = "needs_more_evidence"
    REJECT = "reject"
    BLOCK = "block"
    ERROR = "error"


class LimitStatus(StrEnum):
    """Canonical ordered-limit states."""

    PASS = "pass"  # noqa: S105 - stable policy state, not a credential
    WARN = "warn"
    NEEDS_MORE_EVIDENCE = "needs_more_evidence"
    FAIL = "fail"
    BLOCKED = "blocked"


class RiskErrorCode(StrEnum):
    """Exhaustive deterministic Risk error catalog."""

    INVALID_INPUT = "INVALID_INPUT"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    INVALID_PORTFOLIO_STATE = "INVALID_PORTFOLIO_STATE"
    INVALID_RISK_CONFIG = "INVALID_RISK_CONFIG"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    STALE_EVIDENCE = "STALE_EVIDENCE"
    LIMIT_FAILED = "LIMIT_FAILED"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    KILL_SWITCH_UNKNOWN = "KILL_SWITCH_UNKNOWN"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_TOKEN_INVALID = "APPROVAL_TOKEN_INVALID"  # noqa: S105
    APPROVAL_TOKEN_EXPIRED = "APPROVAL_TOKEN_EXPIRED"  # noqa: S105
    APPROVAL_TOKEN_REVOKED = "APPROVAL_TOKEN_REVOKED"  # noqa: S105
    APPROVAL_TOKEN_CONSUMED = "APPROVAL_TOKEN_CONSUMED"  # noqa: S105
    CONFIG_VERSION_MISMATCH = "CONFIG_VERSION_MISMATCH"
    PENDING_APPROVAL_DOUBLE_SPEND_BLOCKED = "PENDING_APPROVAL_DOUBLE_SPEND_BLOCKED"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    MISSING_STOP_LOSS = "MISSING_STOP_LOSS"
    INSUFFICIENT_VOLATILITY_EVIDENCE = "INSUFFICIENT_VOLATILITY_EVIDENCE"
    INSUFFICIENT_K_EVIDENCE = "INSUFFICIENT_K_EVIDENCE"
    LIVE_STATE_STALE = "LIVE_STATE_STALE"
    IN_FLIGHT_TOLERANCE_EXCEEDED = "IN_FLIGHT_TOLERANCE_EXCEEDED"
    IN_FLIGHT_RECONCILIATION_EXPIRED = "IN_FLIGHT_RECONCILIATION_EXPIRED"
    AUDIT_CHAIN_TAMPER_DETECTED = "AUDIT_CHAIN_TAMPER_DETECTED"
    CALCULATION_FAILED = "CALCULATION_FAILED"
    SNAPSHOT_BUILD_FAILED = "SNAPSHOT_BUILD_FAILED"
    GOVERNOR_DECISION_FAILED = "GOVERNOR_DECISION_FAILED"
    REPORT_GENERATION_FAILED = "REPORT_GENERATION_FAILED"
    STORAGE_ERROR = "STORAGE_ERROR"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"


__all__ = ["DecisionState", "LimitStatus", "RiskErrorCode"]
