import { useState } from 'react';
import { Check, Copy, Download, FileCode } from 'lucide-react';
import type { RuleNode } from './documents';
import { Button, Modal } from '../../components/ui';

interface Props {
  onClose: () => void;
  rules: RuleNode[];
  strategyName: string;
  symbol: string;
  timeframe: string;
  variables: { name: string; value: number | string; optimize: boolean }[];
}

export function generateMql5Code(
  rules: RuleNode[],
  variables: { name: string; value: number | string }[],
  strategyName: string,
  symbol: string,
  timeframe: string
): string {
  const inputs = variables.map(v => `input double ${v.name} = ${v.value};`).join('\n');
  const conditions = rules.filter(r => r.kind === 'condition').map(r => `   // Condition: ${r.label}\n   bool cond_${r.id.replace(/-/g, '_')} = (${r.leftExpr || 'Close[0]'} ${r.compOp || '>'} ${r.rightExpr || 'Open[0]'});`).join('\n\n');
  const actions = rules.filter(r => r.kind === 'action').map(r => `   // Action: ${r.label}\n   if(PositionsTotal() == 0) {\n      trade.PositionOpen(_Symbol, ORDER_TYPE_BUY, 0.10, Ask, Ask - 50 * _Point, Ask + 100 * _Point, "${strategyName}");\n   }`).join('\n\n');

  return `//+------------------------------------------------------------------+
//|                                     ${strategyName.replace(/\s+/g, '_')}.mq5 |
//|                                  Generated by HaruQuantAI AlgoWizard |
//+------------------------------------------------------------------+
#property copyright "HaruQuantAI Strategy Engine"
#property link      "https://haruquant.internal"
#property version   "1.00"
#property strict

#include <Trade\\Trade.mqh>
CTrade trade;

//--- Strategy Parameters & Inputs
${inputs}

//--- Execution Settings
string StrategySymbol = "${symbol}";
ENUM_TIMEFRAMES StrategyTF = PERIOD_${timeframe};

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   trade.SetExpertMagicNumber(102030);
   Print("${strategyName} initialized successfully on ", _Symbol);
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // Check bar open condition
   static datetime lastBar;
   datetime curBar = iTime(_Symbol, _Period, 0);
   if(curBar == lastBar) return;
   lastBar = curBar;

   //--- Evaluated Conditions from Rule Tree
${conditions || '   // No custom conditions defined'}

   //--- Evaluated Order Actions
${actions || '   // No custom actions defined'}
  }
`;
}

export function generateEasyLanguageCode(
  rules: RuleNode[],
  variables: { name: string; value: number | string }[],
  strategyName: string
): string {
  const inputs = variables.map(v => `    ${v.name}(${v.value})`).join(',\n');
  const conditions = rules.filter(r => r.kind === 'condition').map(r => `// ${r.label}\nCondition1 = ${r.leftExpr || 'Close'} ${r.compOp || '>'} ${r.rightExpr || 'Open'};`).join('\n\n');

  return `// Strategy: ${strategyName}
// Generated by HaruQuantAI AlgoWizard

Inputs:
${inputs || '    StopLoss(60),\n    TakeProfit(120)'};

Variables:
    Condition1(false),
    Condition2(false);

${conditions || '// No conditions'}

If Condition1 then begin
    Buy ("LE") next bar at market;
    SetStopLoss(StopLoss);
    SetProfitTarget(TakeProfit);
end;
`;
}

export function generatePythonCode(
  rules: RuleNode[],
  variables: { name: string; value: number | string }[],
  strategyName: string,
  symbol: string,
  timeframe: string
): string {
  const params = variables.map(v => `    ${v.name} = ${v.value}`).join('\n');
  const conds = rules.filter(r => r.kind === 'condition').map(r => `        # ${r.label}\n        long_condition = (df['close'] > df['open'])`).join('\n');

  return `"""
Strategy: ${strategyName}
Generated by HaruQuantAI AlgoWizard
Market: ${symbol} | Timeframe: ${timeframe}
"""

import pandas as pd
import numpy as np

class ${strategyName.replace(/[^a-zA-Z0-9]/g, '')}Strategy:
    """AlgoWizard synthesized vectorized strategy."""
${params || '    pass'}

    def __init__(self, df: pd.DataFrame):
        self.df = df.copy()

    def generate_signals(self) -> pd.DataFrame:
        df = self.df
        df['signal'] = 0

${conds || '        long_condition = df["close"] > df["close"].shift(1)'}

        # Apply Long Entry Signals
        df.loc[long_condition, 'signal'] = 1

        # Calculate strategy returns
        df['returns'] = df['close'].pct_change()
        df['strategy_returns'] = df['signal'].shift(1) * df['returns']
        df['equity'] = (1.0 + df['strategy_returns'].fillna(0)).cumprod()

        return df
`;
}

export function StrategyCodeExportModal({
  onClose,
  rules,
  strategyName,
  symbol,
  timeframe,
  variables,
}: Props) {
  const [lang, setLang] = useState<'mql5' | 'easylanguage' | 'python'>('mql5');
  const [copied, setCopied] = useState(false);

  const code =
    lang === 'mql5'
      ? generateMql5Code(rules, variables, strategyName, symbol, timeframe)
      : lang === 'easylanguage'
      ? generateEasyLanguageCode(rules, variables, strategyName)
      : generatePythonCode(rules, variables, strategyName, symbol, timeframe);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const ext = lang === 'mql5' ? 'mq5' : lang === 'easylanguage' ? 'eld' : 'py';
    const blob = new Blob([code], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${strategyName.replace(/\s+/g, '_')}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Modal
      title="Export Strategy Source Code"
      onClose={onClose}
      footer={
        <div style={{ display: 'flex', justifyContent: 'space-between', width: '100%', alignItems: 'center' }}>
          <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
            Synthesized from {rules.length} rule nodes and {variables.length} parameters.
          </span>
          <div style={{ display: 'flex', gap: '0.5rem' }}>
            <Button onClick={onClose}>Close</Button>
            <Button onClick={handleDownload}>
              <Download size={14} /> Download File
            </Button>
            <Button className="primary" onClick={handleCopy}>
              {copied ? <Check size={14} /> : <Copy size={14} />}
              {copied ? 'Copied to Clipboard!' : 'Copy Code'}
            </Button>
          </div>
        </div>
      }
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', minWidth: '720px' }}>
        {/* Language Tabs */}
        <div style={{ display: 'flex', gap: '0.5rem', borderBottom: '1px solid var(--border)', paddingBottom: '0.5rem' }}>
          <button
            className={`btn-tab ${lang === 'mql5' ? 'active' : ''}`}
            onClick={() => setLang('mql5')}
            style={{
              padding: '0.35rem 0.85rem',
              border: 'none',
              background: lang === 'mql5' ? 'var(--primary)' : 'var(--bg-card)',
              color: lang === 'mql5' ? '#fff' : 'inherit',
              borderRadius: '4px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
            }}
          >
            <FileCode size={14} /> MetaTrader 5 (MQL5)
          </button>
          <button
            className={`btn-tab ${lang === 'easylanguage' ? 'active' : ''}`}
            onClick={() => setLang('easylanguage')}
            style={{
              padding: '0.35rem 0.85rem',
              border: 'none',
              background: lang === 'easylanguage' ? 'var(--primary)' : 'var(--bg-card)',
              color: lang === 'easylanguage' ? '#fff' : 'inherit',
              borderRadius: '4px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
            }}
          >
            <FileCode size={14} /> EasyLanguage / TradeStation
          </button>
          <button
            className={`btn-tab ${lang === 'python' ? 'active' : ''}`}
            onClick={() => setLang('python')}
            style={{
              padding: '0.35rem 0.85rem',
              border: 'none',
              background: lang === 'python' ? 'var(--primary)' : 'var(--bg-card)',
              color: lang === 'python' ? '#fff' : 'inherit',
              borderRadius: '4px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
            }}
          >
            <FileCode size={14} /> Python (HaruQuantAI / Pandas)
          </button>
        </div>

        {/* Code Block */}
        <div
          style={{
            maxHeight: '420px',
            overflowY: 'auto',
            background: '#0a0f1d',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '1rem',
            fontFamily: 'Consolas, Monaco, "Courier New", monospace',
            fontSize: '0.82rem',
            lineHeight: 1.5,
            color: '#e2e8f0',
            whiteSpace: 'pre',
          }}
        >
          {code}
        </div>
      </div>
    </Modal>
  );
}
