# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from enum import IntEnum
from typing import Final


class ENUM_ACCOUNT_INFO_DOUBLE(IntEnum):
    """Defines the identifier set for account info double."""

    ACCOUNT_HEDGE_ALLOWED = 0
    ACCOUNT_BALANCE = 1
    ACCOUNT_CREDIT = 2
    ACCOUNT_PROFIT = 3
    ACCOUNT_EQUITY = 4
    ACCOUNT_MARGIN = 5
    ACCOUNT_MARGIN_FREE = 6
    ACCOUNT_MARGIN_LEVEL = 7
    ACCOUNT_MARGIN_SO_CALL = 8
    ACCOUNT_MARGIN_SO_SO = 9
    ACCOUNT_MARGIN_INITIAL = 10
    ACCOUNT_MARGIN_MAINTENANCE = 11


ACCOUNT_HEDGE_ALLOWED: Final = ENUM_ACCOUNT_INFO_DOUBLE.ACCOUNT_HEDGE_ALLOWED
ACCOUNT_BALANCE: Final = ENUM_ACCOUNT_INFO_DOUBLE.ACCOUNT_BALANCE
ACCOUNT_CREDIT: Final = ENUM_ACCOUNT_INFO_DOUBLE.ACCOUNT_CREDIT
ACCOUNT_PROFIT: Final = ENUM_ACCOUNT_INFO_DOUBLE.ACCOUNT_PROFIT
ACCOUNT_EQUITY: Final = ENUM_ACCOUNT_INFO_DOUBLE.ACCOUNT_EQUITY
ACCOUNT_MARGIN: Final = ENUM_ACCOUNT_INFO_DOUBLE.ACCOUNT_MARGIN
ACCOUNT_MARGIN_FREE: Final = ENUM_ACCOUNT_INFO_DOUBLE.ACCOUNT_MARGIN_FREE
ACCOUNT_MARGIN_LEVEL: Final = ENUM_ACCOUNT_INFO_DOUBLE.ACCOUNT_MARGIN_LEVEL
ACCOUNT_MARGIN_SO_CALL: Final = ENUM_ACCOUNT_INFO_DOUBLE.ACCOUNT_MARGIN_SO_CALL
ACCOUNT_MARGIN_SO_SO: Final = ENUM_ACCOUNT_INFO_DOUBLE.ACCOUNT_MARGIN_SO_SO
ACCOUNT_MARGIN_INITIAL: Final = ENUM_ACCOUNT_INFO_DOUBLE.ACCOUNT_MARGIN_INITIAL
ACCOUNT_MARGIN_MAINTENANCE: Final = ENUM_ACCOUNT_INFO_DOUBLE.ACCOUNT_MARGIN_MAINTENANCE


class ENUM_ACCOUNT_INFO_INTEGER(IntEnum):
    """Defines the identifier set for account info integer."""

    ACCOUNT_LOGIN = 0
    ACCOUNT_TRADE_MODE = 1
    ACCOUNT_LEVERAGE = 2
    ACCOUNT_LIMIT_ORDERS = 3
    ACCOUNT_MARGIN_SO_MODE = 4
    ACCOUNT_TRADE_ALLOWED = 5
    ACCOUNT_TRADE_EXPERT = 6
    ACCOUNT_MARGIN_MODE = 7
    ACCOUNT_CURRENCY_DIGITS = 8
    ACCOUNT_FIFO_CLOSE = 9


ACCOUNT_LOGIN: Final = ENUM_ACCOUNT_INFO_INTEGER.ACCOUNT_LOGIN
ACCOUNT_TRADE_MODE: Final = ENUM_ACCOUNT_INFO_INTEGER.ACCOUNT_TRADE_MODE
ACCOUNT_LEVERAGE: Final = ENUM_ACCOUNT_INFO_INTEGER.ACCOUNT_LEVERAGE
ACCOUNT_LIMIT_ORDERS: Final = ENUM_ACCOUNT_INFO_INTEGER.ACCOUNT_LIMIT_ORDERS
ACCOUNT_MARGIN_SO_MODE: Final = ENUM_ACCOUNT_INFO_INTEGER.ACCOUNT_MARGIN_SO_MODE
ACCOUNT_TRADE_ALLOWED: Final = ENUM_ACCOUNT_INFO_INTEGER.ACCOUNT_TRADE_ALLOWED
ACCOUNT_TRADE_EXPERT: Final = ENUM_ACCOUNT_INFO_INTEGER.ACCOUNT_TRADE_EXPERT
ACCOUNT_MARGIN_MODE: Final = ENUM_ACCOUNT_INFO_INTEGER.ACCOUNT_MARGIN_MODE
ACCOUNT_CURRENCY_DIGITS: Final = ENUM_ACCOUNT_INFO_INTEGER.ACCOUNT_CURRENCY_DIGITS
ACCOUNT_FIFO_CLOSE: Final = ENUM_ACCOUNT_INFO_INTEGER.ACCOUNT_FIFO_CLOSE


class ENUM_ACCOUNT_INFO_STRING(IntEnum):
    """Defines the identifier set for account info string."""

    ACCOUNT_ASSETS = 0
    ACCOUNT_LIABILITIES = 1
    ACCOUNT_COMMISSION_BLOCKED = 2
    ACCOUNT_NAME = 3
    ACCOUNT_SERVER = 4
    ACCOUNT_CURRENCY = 5
    ACCOUNT_COMPANY = 6


ACCOUNT_ASSETS: Final = ENUM_ACCOUNT_INFO_STRING.ACCOUNT_ASSETS
ACCOUNT_LIABILITIES: Final = ENUM_ACCOUNT_INFO_STRING.ACCOUNT_LIABILITIES
ACCOUNT_COMMISSION_BLOCKED: Final = ENUM_ACCOUNT_INFO_STRING.ACCOUNT_COMMISSION_BLOCKED
ACCOUNT_NAME: Final = ENUM_ACCOUNT_INFO_STRING.ACCOUNT_NAME
ACCOUNT_SERVER: Final = ENUM_ACCOUNT_INFO_STRING.ACCOUNT_SERVER
ACCOUNT_CURRENCY: Final = ENUM_ACCOUNT_INFO_STRING.ACCOUNT_CURRENCY
ACCOUNT_COMPANY: Final = ENUM_ACCOUNT_INFO_STRING.ACCOUNT_COMPANY


class ENUM_ACCOUNT_MARGIN_MODE(IntEnum):
    """Defines the identifier set for account margin mode."""

    ACCOUNT_MARGIN_MODE_RETAIL_NETTING = 0
    ACCOUNT_MARGIN_MODE_EXCHANGE = 1
    ACCOUNT_MARGIN_MODE_RETAIL_HEDGING = 2


ACCOUNT_MARGIN_MODE_RETAIL_NETTING: Final = (
    ENUM_ACCOUNT_MARGIN_MODE.ACCOUNT_MARGIN_MODE_RETAIL_NETTING
)
ACCOUNT_MARGIN_MODE_EXCHANGE: Final = (
    ENUM_ACCOUNT_MARGIN_MODE.ACCOUNT_MARGIN_MODE_EXCHANGE
)
ACCOUNT_MARGIN_MODE_RETAIL_HEDGING: Final = (
    ENUM_ACCOUNT_MARGIN_MODE.ACCOUNT_MARGIN_MODE_RETAIL_HEDGING
)


class ENUM_ACCOUNT_STOPOUT_MODE(IntEnum):
    """Defines the identifier set for account stopout mode."""

    ACCOUNT_STOPOUT_MODE_PERCENT = 0
    ACCOUNT_STOPOUT_MODE_MONEY = 1


ACCOUNT_STOPOUT_MODE_PERCENT: Final = (
    ENUM_ACCOUNT_STOPOUT_MODE.ACCOUNT_STOPOUT_MODE_PERCENT
)
ACCOUNT_STOPOUT_MODE_MONEY: Final = ENUM_ACCOUNT_STOPOUT_MODE.ACCOUNT_STOPOUT_MODE_MONEY


class ENUM_ACCOUNT_TRADE_MODE(IntEnum):
    """Defines the identifier set for account trade mode."""

    ACCOUNT_TRADE_MODE_DEMO = 0
    ACCOUNT_TRADE_MODE_CONTEST = 1
    ACCOUNT_TRADE_MODE_REAL = 2


ACCOUNT_TRADE_MODE_DEMO: Final = ENUM_ACCOUNT_TRADE_MODE.ACCOUNT_TRADE_MODE_DEMO
ACCOUNT_TRADE_MODE_CONTEST: Final = ENUM_ACCOUNT_TRADE_MODE.ACCOUNT_TRADE_MODE_CONTEST
ACCOUNT_TRADE_MODE_REAL: Final = ENUM_ACCOUNT_TRADE_MODE.ACCOUNT_TRADE_MODE_REAL

__all__ = [
    "ACCOUNT_ASSETS",
    "ACCOUNT_BALANCE",
    "ACCOUNT_COMMISSION_BLOCKED",
    "ACCOUNT_COMPANY",
    "ACCOUNT_CREDIT",
    "ACCOUNT_CURRENCY",
    "ACCOUNT_CURRENCY_DIGITS",
    "ACCOUNT_EQUITY",
    "ACCOUNT_FIFO_CLOSE",
    "ACCOUNT_HEDGE_ALLOWED",
    "ACCOUNT_LEVERAGE",
    "ACCOUNT_LIABILITIES",
    "ACCOUNT_LIMIT_ORDERS",
    "ACCOUNT_LOGIN",
    "ACCOUNT_MARGIN",
    "ACCOUNT_MARGIN_FREE",
    "ACCOUNT_MARGIN_INITIAL",
    "ACCOUNT_MARGIN_LEVEL",
    "ACCOUNT_MARGIN_MAINTENANCE",
    "ACCOUNT_MARGIN_MODE",
    "ACCOUNT_MARGIN_MODE_EXCHANGE",
    "ACCOUNT_MARGIN_MODE_RETAIL_HEDGING",
    "ACCOUNT_MARGIN_MODE_RETAIL_NETTING",
    "ACCOUNT_MARGIN_SO_CALL",
    "ACCOUNT_MARGIN_SO_MODE",
    "ACCOUNT_MARGIN_SO_SO",
    "ACCOUNT_NAME",
    "ACCOUNT_PROFIT",
    "ACCOUNT_SERVER",
    "ACCOUNT_STOPOUT_MODE_MONEY",
    "ACCOUNT_STOPOUT_MODE_PERCENT",
    "ACCOUNT_TRADE_ALLOWED",
    "ACCOUNT_TRADE_EXPERT",
    "ACCOUNT_TRADE_MODE",
    "ACCOUNT_TRADE_MODE_CONTEST",
    "ACCOUNT_TRADE_MODE_DEMO",
    "ACCOUNT_TRADE_MODE_REAL",
    "ENUM_ACCOUNT_INFO_DOUBLE",
    "ENUM_ACCOUNT_INFO_INTEGER",
    "ENUM_ACCOUNT_INFO_STRING",
    "ENUM_ACCOUNT_MARGIN_MODE",
    "ENUM_ACCOUNT_STOPOUT_MODE",
    "ENUM_ACCOUNT_TRADE_MODE",
]
