# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from typing import Final

ERR_ACCOUNT_WRONG_PROPERTY: Final[int] = 4701
ERR_TRADE_WRONG_PROPERTY: Final[int] = 4751
ERR_TRADE_DISABLED: Final[int] = 4752
ERR_TRADE_POSITION_NOT_FOUND: Final[int] = 4753
ERR_TRADE_ORDER_NOT_FOUND: Final[int] = 4754
ERR_TRADE_DEAL_NOT_FOUND: Final[int] = 4755
ERR_TRADE_SEND_FAILED: Final[int] = 4756
ERR_TRADE_CALC_FAILED: Final[int] = 4758
ERR_BOOKS_CANNOT_ADD: Final[int] = 4901
ERR_BOOKS_CANNOT_DELETE: Final[int] = 4902
ERR_BOOKS_CANNOT_GET: Final[int] = 4903
ERR_BOOKS_CANNOT_SUBSCRIBE: Final[int] = 4904

__all__ = [
    "ERR_ACCOUNT_WRONG_PROPERTY",
    "ERR_BOOKS_CANNOT_ADD",
    "ERR_BOOKS_CANNOT_DELETE",
    "ERR_BOOKS_CANNOT_GET",
    "ERR_BOOKS_CANNOT_SUBSCRIBE",
    "ERR_TRADE_CALC_FAILED",
    "ERR_TRADE_DEAL_NOT_FOUND",
    "ERR_TRADE_DISABLED",
    "ERR_TRADE_ORDER_NOT_FOUND",
    "ERR_TRADE_POSITION_NOT_FOUND",
    "ERR_TRADE_SEND_FAILED",
    "ERR_TRADE_WRONG_PROPERTY",
]
