# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from typing import Final

TRADE_RETCODE_REQUOTE: Final[int] = 10004
TRADE_RETCODE_REJECT: Final[int] = 10006
TRADE_RETCODE_CANCEL: Final[int] = 10007
TRADE_RETCODE_PLACED: Final[int] = 10008
TRADE_RETCODE_DONE: Final[int] = 10009
TRADE_RETCODE_DONE_PARTIAL: Final[int] = 10010
TRADE_RETCODE_ERROR: Final[int] = 10011
TRADE_RETCODE_TIMEOUT: Final[int] = 10012
TRADE_RETCODE_INVALID: Final[int] = 10013
TRADE_RETCODE_INVALID_VOLUME: Final[int] = 10014
TRADE_RETCODE_INVALID_PRICE: Final[int] = 10015
TRADE_RETCODE_INVALID_STOPS: Final[int] = 10016
TRADE_RETCODE_TRADE_DISABLED: Final[int] = 10017
TRADE_RETCODE_MARKET_CLOSED: Final[int] = 10018
TRADE_RETCODE_NO_MONEY: Final[int] = 10019
TRADE_RETCODE_PRICE_CHANGED: Final[int] = 10020
TRADE_RETCODE_PRICE_OFF: Final[int] = 10021
TRADE_RETCODE_INVALID_EXPIRATION: Final[int] = 10022
TRADE_RETCODE_ORDER_CHANGED: Final[int] = 10023
TRADE_RETCODE_TOO_MANY_REQUESTS: Final[int] = 10024
TRADE_RETCODE_NO_CHANGES: Final[int] = 10025
TRADE_RETCODE_SERVER_DISABLES_AT: Final[int] = 10026
TRADE_RETCODE_CLIENT_DISABLES_AT: Final[int] = 10027
TRADE_RETCODE_LOCKED: Final[int] = 10028
TRADE_RETCODE_FROZEN: Final[int] = 10029
TRADE_RETCODE_INVALID_FILL: Final[int] = 10030
TRADE_RETCODE_CONNECTION: Final[int] = 10031
TRADE_RETCODE_ONLY_REAL: Final[int] = 10032
TRADE_RETCODE_LIMIT_ORDERS: Final[int] = 10033
TRADE_RETCODE_LIMIT_VOLUME: Final[int] = 10034
TRADE_RETCODE_INVALID_ORDER: Final[int] = 10035
TRADE_RETCODE_POSITION_CLOSED: Final[int] = 10036
TRADE_RETCODE_INVALID_CLOSE_VOLUME: Final[int] = 10038
TRADE_RETCODE_CLOSE_ORDER_EXIST: Final[int] = 10039
TRADE_RETCODE_LIMIT_POSITIONS: Final[int] = 10040
TRADE_RETCODE_REJECT_CANCEL: Final[int] = 10041
TRADE_RETCODE_LONG_ONLY: Final[int] = 10042
TRADE_RETCODE_SHORT_ONLY: Final[int] = 10043
TRADE_RETCODE_CLOSE_ONLY: Final[int] = 10044
TRADE_RETCODE_FIFO_CLOSE: Final[int] = 10045
TRADE_RETCODE_HEDGE_PROHIBITED: Final[int] = 10046

__all__ = [
    "TRADE_RETCODE_CANCEL",
    "TRADE_RETCODE_CLIENT_DISABLES_AT",
    "TRADE_RETCODE_CLOSE_ONLY",
    "TRADE_RETCODE_CLOSE_ORDER_EXIST",
    "TRADE_RETCODE_CONNECTION",
    "TRADE_RETCODE_DONE",
    "TRADE_RETCODE_DONE_PARTIAL",
    "TRADE_RETCODE_ERROR",
    "TRADE_RETCODE_FIFO_CLOSE",
    "TRADE_RETCODE_FROZEN",
    "TRADE_RETCODE_HEDGE_PROHIBITED",
    "TRADE_RETCODE_INVALID",
    "TRADE_RETCODE_INVALID_CLOSE_VOLUME",
    "TRADE_RETCODE_INVALID_EXPIRATION",
    "TRADE_RETCODE_INVALID_FILL",
    "TRADE_RETCODE_INVALID_ORDER",
    "TRADE_RETCODE_INVALID_PRICE",
    "TRADE_RETCODE_INVALID_STOPS",
    "TRADE_RETCODE_INVALID_VOLUME",
    "TRADE_RETCODE_LIMIT_ORDERS",
    "TRADE_RETCODE_LIMIT_POSITIONS",
    "TRADE_RETCODE_LIMIT_VOLUME",
    "TRADE_RETCODE_LOCKED",
    "TRADE_RETCODE_LONG_ONLY",
    "TRADE_RETCODE_MARKET_CLOSED",
    "TRADE_RETCODE_NO_CHANGES",
    "TRADE_RETCODE_NO_MONEY",
    "TRADE_RETCODE_ONLY_REAL",
    "TRADE_RETCODE_ORDER_CHANGED",
    "TRADE_RETCODE_PLACED",
    "TRADE_RETCODE_POSITION_CLOSED",
    "TRADE_RETCODE_PRICE_CHANGED",
    "TRADE_RETCODE_PRICE_OFF",
    "TRADE_RETCODE_REJECT",
    "TRADE_RETCODE_REJECT_CANCEL",
    "TRADE_RETCODE_REQUOTE",
    "TRADE_RETCODE_SERVER_DISABLES_AT",
    "TRADE_RETCODE_SHORT_ONLY",
    "TRADE_RETCODE_TIMEOUT",
    "TRADE_RETCODE_TOO_MANY_REQUESTS",
    "TRADE_RETCODE_TRADE_DISABLED",
]
