"""Promotion evidence packets, lifecycle records, and the transition machine.

`PromotionEvidencePacket` makes the ordered evidence complete
(`FR-AGENTIC-052`): every required piece is its own non-defaulted field, so a
packet assembled without a critique, without a sweep, or without an approving
principal is not a weaker packet but an unconstructable one. The packet carries
a digest over the whole assembly, so evidence appended after approval yields a
different packet.

`LifecycleRecord` makes transitions append-only and version-specific
(`FR-AGENTIC-054`). Records are keyed on the **artefact digest**, not the
artefact identity: change one generated byte and the digest changes, so the
altered artefact begins at `staged` with no history to inherit. `_PREDECESSORS`
states which state may follow which, so a skipped step is unrepresentable and
demotion from `registered` is always available.

`research_only` is terminal (`FR-AGENTIC-053`). Nothing leaves it. An artefact
that leaked, reused holdout, exhausted its search budget, arrived without
provenance, or was never approved does not get a second run at the gate under a
freshly assembled packet.
"""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType
from typing import Literal, Protocol, Self, runtime_checkable

from pydantic import (
    BaseModel,
    ConfigDict,
    field_serializer,
    field_validator,
    model_validator,
)

# These are pydantic field types, so they must resolve at runtime; a
# type-checking block would leave the models unbuildable.
from app.agentic.agents.engineering.coder.schemas import CodeArtifact  # noqa: TC001
from app.agentic.agents.experimentation.experiment_designer.schemas import (  # noqa: TC001
    ExperimentVerdict,
)
from app.agentic.agents.experimentation.optimization_coordinator.schemas import (  # noqa: TC001
    SweepVerdict,
)
from app.agentic.agents.operations.evaluation_manager.schemas import (  # noqa: TC001
    CritiqueMemo,
)
from app.composition.logging import get_logger
from app.kernel.serialization import canonical_digest

logger = get_logger(__name__)

_MAX_TEXT = 2_000
_MAX_SHORT_TEXT = 200
_MAX_ITEMS = 32

# The permission an approving human must hold. Deny-by-default: a principal
# without it cannot approve, and no agent message can grant it.
PROMOTION_PERMISSION = "agentic:approve_promotion"

type ArtifactState = Literal[
    "staged",
    "evaluated",
    "approved",
    "registered",
    "research_only",
    "demoted",
]

type TerminationReason = Literal[
    "leakage_detected",
    "holdout_reused",
    "search_budget_exhausted",
    "provenance_incomplete",
    "approval_absent",
]

# States from which nothing may follow. `research_only` is a judgement about
# the artefact itself, so re-assembling a packet does not reopen it; `demoted`
# ends a registered artefact's standing and a replacement is a new digest.
TERMINAL_STATES: frozenset[str] = frozenset({"research_only", "demoted"})

# Which state may follow which. A state absent from a predecessor set cannot be
# reached from it, so `staged -> registered` is not a shortcut but an error.
_PREDECESSORS: Mapping[str, frozenset[str]] = MappingProxyType(
    {
        "staged": frozenset(),
        "evaluated": frozenset({"staged"}),
        "approved": frozenset({"evaluated"}),
        "registered": frozenset({"approved"}),
        # Termination is reachable from any non-terminal state: evidence can
        # fail a gate at assembly time or at approval time.
        "research_only": frozenset({"staged", "evaluated", "approved"}),
        # Demotion applies to something already registered. Automatic demotion
        # is the point: nothing needs approval to withdraw an artefact.
        "demoted": frozenset({"registered"}),
    },
)

# Provenance fields an artefact must carry for its authorship to be traceable.
# Each is a digest or identity the coder recorded at authoring time.
REQUIRED_PROVENANCE: tuple[str, ...] = (
    "artifact_hash",
    "base_prompt_hash",
    "composite_instruction_hash",
    "model_profile_id",
)


@runtime_checkable
class ApprovingPrincipal(Protocol):
    """The authenticated identity a promotion approval must carry.

    Utils exposes `create_auth_context` but not the `AuthContext` class, so
    this structural Protocol names only the fields approval reads. A real
    `utils.auth_context.v1` satisfies it without a deep import.

    Attributes:
        principal_id: Authenticated identity.
        principal_type: Whether the principal is a user or a service account.
        permissions: Fine-grained permissions the principal holds.
        tenant_or_environment: Environment the context was issued for.
    """

    principal_id: str
    principal_type: str
    permissions: tuple[str, ...]
    tenant_or_environment: str


def _text(value: str, field: str, *, limit: int = _MAX_TEXT) -> str:
    """Validate bounded non-empty trimmed text.

    Args:
        value: Candidate text.
        field: Safe field label for validation.
        limit: Maximum permitted character count.

    Returns:
        Validated text.

    Raises:
        ValueError: If the text is empty, untrimmed, or oversized.
    """
    if not value or value != value.strip():
        message = f"{field} must be non-empty trimmed text"
        raise ValueError(message)
    if len(value) > limit:
        message = f"{field} must not exceed {limit} characters"
        raise ValueError(message)
    return value


def _entries(value: tuple[str, ...], field: str) -> tuple[str, ...]:
    """Validate one bounded optional tuple of statements.

    Args:
        value: Candidate entries.
        field: Safe field label for validation.

    Returns:
        Validated entries.

    Raises:
        ValueError: If the tuple is oversized.
    """
    if len(value) > _MAX_ITEMS:
        message = f"{field} must not exceed {_MAX_ITEMS} entries"
        raise ValueError(message)
    return tuple(_text(item, field) for item in value)


def permitted_next_states(current: str) -> tuple[str, ...]:
    """Return the states one artefact state may legally advance to.

    Args:
        current: Current recorded state.

    Returns:
        Ordered permitted next states, empty for a terminal state.
    """
    return tuple(
        sorted(state for state, prior in _PREDECESSORS.items() if current in prior)
    )


def is_terminal_state(state: str) -> bool:
    """Report whether a state admits no further transition.

    Args:
        state: Candidate artefact state.

    Returns:
        True when nothing may follow the state.
    """
    return state in TERMINAL_STATES


def validate_transition(current: str | None, requested: str) -> str | None:
    """Validate one requested artefact transition.

    A `None` current state means the artefact has no history, which is the only
    condition under which `staged` may be recorded. Every other state requires
    its declared predecessor, so a skipped step fails rather than fast-tracks.

    Args:
        current: Current recorded state, or None when unrecorded.
        requested: State the caller wants to record.

    Returns:
        A refusal message, or None when the transition is permitted.
    """
    permitted = _PREDECESSORS.get(requested)
    if permitted is None:
        return f"{requested!r} is not a recognized artefact state"
    if current is None:
        return (
            None
            if requested == "staged"
            else f"an unrecorded artefact must enter at 'staged', not {requested!r}"
        )
    if is_terminal_state(current):
        return f"{current!r} is terminal; no transition may follow it"
    if current == requested:
        return f"the artefact is already {requested!r}"
    if current not in permitted:
        allowed = ", ".join(sorted(permitted)) or "nothing"
        return f"{requested!r} may only follow {allowed}; the artefact is {current!r}"
    return None


def missing_provenance(artifact: CodeArtifact) -> tuple[str, ...]:
    """Return the provenance fields an artefact does not carry.

    Args:
        artifact: Staged artefact under assessment.

    Returns:
        Ordered missing provenance field names.
    """
    return tuple(
        name
        for name in REQUIRED_PROVENANCE
        if not str(getattr(artifact, name, "")).strip()
    )


class PromotionEvidencePacket(BaseModel):
    """The complete ordered evidence one promotion decision rests on.

    Every evidence field is required. A packet is not a container that happens
    to hold what was available; it is the assertion that the whole record
    exists, and the absence of any part makes the assertion unconstructable.

    Attributes:
        packet_id: Stable packet identity.
        task_id: Owning task identity.
        artifact: Staged artefact this packet promotes.
        experiment_verdict: Pre-registered experiment outcome.
        sweep_verdict: Bounded search outcome.
        critique: Adversarial critique of the candidate.
        simulation_manifest_ref: Receiver-returned simulation evidence identity.
        lifetime_trial_ceiling: Declared cumulative search budget for the thesis.
        approver_id: Authenticated human who approved the promotion.
        approval_environment: Environment the approval was issued for.
        assembled_at: Assembly time, as an ISO-8601 UTC instant.
        packet_hash: Derived digest over the whole assembly.
    """

    model_config = ConfigDict(
        allow_inf_nan=False,
        extra="forbid",
        frozen=True,
        strict=True,
    )

    packet_id: str
    task_id: str
    artifact: CodeArtifact
    experiment_verdict: ExperimentVerdict
    sweep_verdict: SweepVerdict
    critique: CritiqueMemo
    simulation_manifest_ref: str
    lifetime_trial_ceiling: int
    approver_id: str
    approval_environment: str
    assembled_at: str
    packet_hash: str

    @field_validator(
        "packet_id",
        "task_id",
        "simulation_manifest_ref",
        "approver_id",
        "approval_environment",
        "assembled_at",
        "packet_hash",
    )
    @classmethod
    def _validate_reference(cls, value: str) -> str:
        """Validate one required packet reference.

        Args:
            value: Candidate reference.

        Returns:
            Validated reference.
        """
        return _text(value, "packet reference", limit=_MAX_SHORT_TEXT)

    @field_validator("lifetime_trial_ceiling")
    @classmethod
    def _validate_ceiling(cls, value: int) -> int:
        """Validate the declared cumulative search ceiling.

        Args:
            value: Candidate ceiling.

        Returns:
            Validated ceiling.

        Raises:
            ValueError: If the ceiling is not positive.
        """
        if value <= 0:
            message = "the lifetime trial ceiling must be positive"
            raise ValueError(message)
        return value


class LifecycleRecord(BaseModel):
    """One append-only entry in an artefact's transition history.

    The record is keyed on `artifact_hash` rather than on an artefact
    identifier, which is what makes `FR-AGENTIC-054`'s non-inheritance
    structural: a materially changed artefact has a different digest and
    therefore an empty history.

    Attributes:
        record_id: Stable record identity.
        artifact_hash: Digest of the exact artefact this record concerns.
        artifact_id: Artefact identity, carried for operator readability only.
        sequence: Position in the append-only history, starting at one.
        previous_state: State this transition left, or None for the first.
        state: State this transition entered.
        packet_hash: Packet that justified this transition, when one applies.
        termination_reason: Why promotion terminated, for `research_only`.
        actor_id: Principal or process that recorded the transition.
        rationale: Why the transition was recorded.
        recorded_at: Record time, as an ISO-8601 UTC instant.
    """

    model_config = ConfigDict(
        allow_inf_nan=False,
        extra="forbid",
        frozen=True,
        strict=True,
    )

    record_id: str
    artifact_hash: str
    artifact_id: str
    sequence: int
    previous_state: ArtifactState | None
    state: ArtifactState
    actor_id: str
    rationale: str
    recorded_at: str
    packet_hash: str | None = None
    termination_reason: TerminationReason | None = None
    unresolved_concerns: tuple[str, ...] = ()

    @field_validator(
        "record_id",
        "artifact_hash",
        "artifact_id",
        "actor_id",
        "recorded_at",
    )
    @classmethod
    def _validate_reference(cls, value: str) -> str:
        """Validate one required record reference.

        Args:
            value: Candidate reference.

        Returns:
            Validated reference.
        """
        return _text(value, "lifecycle reference", limit=_MAX_SHORT_TEXT)

    @field_validator("packet_hash")
    @classmethod
    def _validate_packet(cls, value: str | None) -> str | None:
        """Validate the optional justifying packet digest.

        Args:
            value: Candidate digest.

        Returns:
            Validated digest, or None.
        """
        if value is None:
            return None
        return _text(value, "packet digest", limit=_MAX_SHORT_TEXT)

    @field_validator("rationale")
    @classmethod
    def _validate_rationale(cls, value: str) -> str:
        """Validate the transition rationale.

        Args:
            value: Candidate rationale.

        Returns:
            Validated rationale.
        """
        return _text(value, "transition rationale")

    @field_validator("unresolved_concerns")
    @classmethod
    def _validate_concerns(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        """Validate the preserved unresolved concerns.

        Args:
            value: Candidate concerns.

        Returns:
            Validated concerns.
        """
        return _entries(value, "unresolved concern")

    @field_validator("sequence")
    @classmethod
    def _validate_sequence(cls, value: int) -> int:
        """Validate the append-only sequence position.

        Args:
            value: Candidate position.

        Returns:
            Validated position.

        Raises:
            ValueError: If the position is not positive.
        """
        if value <= 0:
            message = "a lifecycle sequence starts at one"
            raise ValueError(message)
        return value

    @field_serializer("previous_state", "state", "termination_reason", mode="plain")
    def _serialize_optional(self, value: str | None) -> str | None:
        """Serialize one enumerated field deterministically.

        Args:
            value: Enumerated value or None.

        Returns:
            The plain value.
        """
        return value

    @model_validator(mode="after")
    def _validate_record(self) -> Self:
        """Validate the record against the transition machine.

        Returns:
            The validated record.

        Raises:
            ValueError: If the recorded transition is not permitted, or the
                termination reason and state disagree.
        """
        failure = validate_transition(self.previous_state, self.state)
        if failure is not None:
            raise ValueError(failure)
        if self.sequence == 1 and self.previous_state is not None:
            message = "the first lifecycle record has no previous state"
            raise ValueError(message)
        if self.sequence > 1 and self.previous_state is None:
            message = "only the first lifecycle record may omit a previous state"
            raise ValueError(message)
        if self.state == "research_only" and self.termination_reason is None:
            message = "a research_only record must state why promotion terminated"
            raise ValueError(message)
        if self.state != "research_only" and self.termination_reason is not None:
            message = (
                f"a termination reason belongs to research_only, not {self.state!r}"
            )
            raise ValueError(message)
        return self


class PromotionAssessment(BaseModel):
    """What the deterministic gates concluded about one packet.

    Attributes:
        assessment_id: Stable assessment identity.
        task_id: Owning task identity.
        artifact_hash: Digest of the artefact assessed.
        packet_hash: Digest of the packet assessed, when one was assembled.
        promotable: Whether every gate passed.
        termination_reason: The first gate that terminated promotion.
        failed_gates: Every gate that failed, in a stable order.
        unresolved_concerns: Blocking concerns the critique preserved.
        assessed_at: Assessment time, as an ISO-8601 UTC instant.
    """

    model_config = ConfigDict(
        allow_inf_nan=False,
        extra="forbid",
        frozen=True,
        strict=True,
    )

    assessment_id: str
    task_id: str
    artifact_hash: str
    promotable: bool
    failed_gates: tuple[str, ...]
    unresolved_concerns: tuple[str, ...]
    assessed_at: str
    packet_hash: str | None = None
    termination_reason: TerminationReason | None = None

    @field_validator("assessment_id", "task_id", "artifact_hash", "assessed_at")
    @classmethod
    def _validate_reference(cls, value: str) -> str:
        """Validate one required assessment reference.

        Args:
            value: Candidate reference.

        Returns:
            Validated reference.
        """
        return _text(value, "assessment reference", limit=_MAX_SHORT_TEXT)

    @field_validator("failed_gates", "unresolved_concerns")
    @classmethod
    def _validate_entries(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        """Validate one bounded assessment tuple.

        Args:
            value: Candidate entries.

        Returns:
            Validated entries.
        """
        return _entries(value, "assessment entry")

    @field_serializer("termination_reason", mode="plain")
    def _serialize_reason(self, value: str | None) -> str | None:
        """Serialize the optional termination reason.

        Args:
            value: Enumerated reason or None.

        Returns:
            The plain value.
        """
        return value

    @model_validator(mode="after")
    def _validate_verdict(self) -> Self:
        """Validate that the verdict and its reasons agree.

        Returns:
            The validated assessment.

        Raises:
            ValueError: If promotability disagrees with the recorded gates.
        """
        if self.promotable and self.failed_gates:
            message = (
                "an assessment cannot be promotable while gates failed: "
                f"{', '.join(self.failed_gates)}"
            )
            raise ValueError(message)
        if self.promotable and self.termination_reason is not None:
            message = "a promotable assessment carries no termination reason"
            raise ValueError(message)
        if not self.promotable and self.termination_reason is None:
            message = "a terminated assessment must state its termination reason"
            raise ValueError(message)
        return self


def derive_packet_hash(fields: Mapping[str, object]) -> str:
    """Derive the assembly digest of one promotion evidence packet.

    Args:
        fields: Packet fields excluding the derived digest.

    Returns:
        The canonical content digest.
    """
    payload = {
        key: value.model_dump(mode="json") if isinstance(value, BaseModel) else value
        for key, value in sorted(fields.items())
        if key != "packet_hash"
    }
    return canonical_digest(payload)


def build_promotion_evidence_packet(
    fields: Mapping[str, object],
) -> PromotionEvidencePacket:
    """Build one complete promotion evidence packet.

    Args:
        fields: Complete packet fields excluding the derived digest.

    Returns:
        A validated immutable packet carrying its assembly digest.
    """
    logger.debug("Building a promotion evidence packet")
    return PromotionEvidencePacket.model_validate(
        {**fields, "packet_hash": derive_packet_hash(fields)},
    )


def build_lifecycle_record(fields: Mapping[str, object]) -> LifecycleRecord:
    """Build one append-only lifecycle record.

    Args:
        fields: Complete record fields.

    Returns:
        A validated immutable record.
    """
    logger.debug("Building a lifecycle record")
    return LifecycleRecord.model_validate(fields)


def build_promotion_assessment(fields: Mapping[str, object]) -> PromotionAssessment:
    """Build one deterministic promotion assessment.

    Args:
        fields: Complete assessment fields.

    Returns:
        A validated immutable assessment.
    """
    logger.debug("Building a promotion assessment")
    return PromotionAssessment.model_validate(fields)


def approval_refusal(
    principal: ApprovingPrincipal | None,
    environment: str,
) -> str | None:
    """Report why one principal may not approve a promotion.

    Args:
        principal: Candidate approving principal, or None when absent.
        environment: Environment the promotion targets.

    Returns:
        A refusal message, or None when the principal may approve.
    """
    if principal is None:
        return "promotion requires an authenticated human approval"
    if principal.principal_type != "USER":
        return (
            "promotion approval requires a human principal; "
            f"{principal.principal_type!r} cannot approve"
        )
    if PROMOTION_PERMISSION not in principal.permissions:
        return f"the approving principal does not hold {PROMOTION_PERMISSION}"
    if principal.tenant_or_environment != environment:
        return (
            f"the approval was issued for {principal.tenant_or_environment!r}, "
            f"not for {environment!r}"
        )
    return None


class _StateHolder(Protocol):
    """Minimal structural view of something carrying a recorded state."""

    state: ArtifactState


def latest_state(records: tuple[_StateHolder, ...]) -> ArtifactState | None:
    """Return the current state implied by an ordered history.

    Args:
        records: Ordered lifecycle history, oldest first.

    Returns:
        The most recent state, or None when there is no history.
    """
    if not records:
        return None
    return records[-1].state
