import { useRef, useState, type InputHTMLAttributes } from 'react';
import { Button, Field, Modal, Select, TextInput } from '../../../components/ui';
import { useAppStore } from '../../../app/store';
import { defaultMt4Properties, exportPreset, exportRange, exportTimezones, mt4Manifest, parseMt4Properties, type ExportTarget } from './dataExport';
import { useDataExports } from './dataExportStore';
import type { Preset } from '../Dukascopy/dukascopyDownload';
import './dataExport.css';

const presets: [Preset, string][] = [['sinceLast', 'Since last date'], ['sixMonths', 'Last 6 months'], ['year', 'Last year'], ['fiveYears', 'Last 5 years'], ['tenYears', 'Last 10 years'], ['allTime', 'All time']];

export function Mt4ExportDialog({ target, externalActive, onClose, onStarted }: { target: ExportTarget; externalActive: boolean; onClose: () => void; onStarted: () => void }) {
  const store = useDataExports(); const notify = useAppStore(state => state.notify); const range = exportRange([target]);
  const installPicker = useRef<HTMLInputElement>(null); const dataPicker = useRef<HTMLInputElement>(null); const specPicker = useRef<HTMLInputElement>(null);
  const [from, setFrom] = useState(range.from); const [to, setTo] = useState(range.to); const [preset, setPreset] = useState<Preset>('allTime');
  const [installation, setInstallation] = useState(String(store.settings.mt4Installation ?? 'Mock MT4 installation'));
  const [dataFolder, setDataFolder] = useState(String(store.settings.mt4DataFolder ?? 'Browser downloads / MT4'));
  const [server, setServer] = useState(String(store.settings.mt4Server ?? 'Mock-Demo'));
  const [properties, setProperties] = useState<Record<string, string>>({ ...defaultMt4Properties, SYMBOL: target.instrument || target.symbol });
  const [specificationSymbol, setSpecificationSymbol] = useState(target.instrument || target.symbol); const [mt4Name, setMt4Name] = useState(target.symbol);
  const [timeframe, setTimeframe] = useState('All'); const [timezone, setTimezone] = useState('original'); const [encoding, setEncoding] = useState('windows-1252'); const [mode, setMode] = useState<'all' | 'hst' | 'fxt'>('all'); const [error, setError] = useState('');
  function choose(value: Preset): void { const next = exportPreset(value, range, from, to); setFrom(next.from); setTo(next.to); setPreset(value); setError(''); }
  function folderName(files: FileList): string { return files[0]?.webkitRelativePath.split('/')[0] || files[0]?.name || 'Selected folder'; }
  async function loadSpec(file?: File): Promise<void> { if (!file) return; try { if (!/\.properties$/i.test(file.name)) throw new Error('Choose an MT4 .properties specification file.'); const next = parseMt4Properties(await file.text()); setProperties(next); const symbol = next.SYMBOL || target.instrument; setSpecificationSymbol(symbol); setMt4Name(symbol); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load MT4 specification.'); } }
  function start(): void { try { const artifact = mt4Manifest({ target, from, to, installation, dataFolder, server, specificationSymbol, mt4Name, timeframe, timezone, encoding, mode, properties }); store.start('mt4', 'MT4 mock export', [target.id], [artifact], { mt4Installation: installation, mt4DataFolder: dataFolder, mt4Server: server }, externalActive); onStarted(); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to start MT4 export.'); } }
  return <div className="data-export-flow"><Modal title={`Export to MetaTrader 4 FXT and HST for '${target.symbol}'`} width={800} onClose={onClose} footer={<><button className="export-help" onClick={() => notify('MT4 export help is not configured for this HaruQuantAI workspace')}>Help</button><Button onClick={onClose}>Close</Button><Button className="primary" onClick={start}>Start export</Button></>}>
    {(error || store.storageError) && <p className="export-error" role="alert">{error || store.storageError}</p>}
    <fieldset><legend>Choose data range to export</legend><div className="export-date-grid"><label>From <TextInput aria-label="MT4 date from" type="date" min={range.from} max={to} value={from} onChange={event => { setFrom(event.target.value); setPreset('custom'); }}/></label>{presets.slice(0, 3).map(([id,label]) => <Button key={id} aria-pressed={preset === id} className={preset === id ? 'primary' : ''} onClick={() => choose(id)}>{label}</Button>)}<label>To <TextInput aria-label="MT4 date to" type="date" min={from} max={range.to} value={to} onChange={event => { setTo(event.target.value); setPreset('custom'); }}/></label>{presets.slice(3).map(([id,label]) => <Button key={id} aria-pressed={preset === id} className={preset === id ? 'primary' : ''} onClick={() => choose(id)}>{label}</Button>)}</div><p className="export-muted">Note: exported files cannot exceed 4 GB in the native HaruQuantAI workflow.</p></fieldset>
    <fieldset><legend>Output folder</legend><div className="export-folder-row"><Field label="MT4 Installation"><TextInput value={installation} readOnly/></Field><Button onClick={() => installPicker.current?.click()}>Select</Button><input ref={installPicker} hidden type="file" aria-label="Select MT4 installation folder" {...({ webkitdirectory: '', directory: '' } as InputHTMLAttributes<HTMLInputElement>)} onChange={event => { if (event.target.files?.length) setInstallation(folderName(event.target.files)); event.target.value = ''; }}/><Field label="MT4 Data Folder"><TextInput value={dataFolder} readOnly/></Field><Button onClick={() => dataPicker.current?.click()}>Select</Button><input ref={dataPicker} hidden type="file" aria-label="Select MT4 data folder" {...({ webkitdirectory: '', directory: '' } as InputHTMLAttributes<HTMLInputElement>)} onChange={event => { if (event.target.files?.length) setDataFolder(folderName(event.target.files)); event.target.value = ''; }}/><Field label="Server name"><Select value={server} onChange={setServer}><option>Mock-Demo</option><option>Mock-Live</option><option>Selected server</option></Select></Field></div></fieldset>
    <fieldset><legend>MT4 data specification and properties</legend><div className="export-grid three"><Field label="Symbol"><Select value={specificationSymbol} onChange={value => { setSpecificationSymbol(value); setMt4Name(value); }}>{[...new Set([specificationSymbol, target.symbol])].map(item => <option key={item}>{item}</option>)}</Select></Field><Field label="Name in MT4"><TextInput aria-label="Name in MT4" value={mt4Name} onChange={event => setMt4Name(event.target.value)}/></Field><Field label="Timeframe"><Select value={timeframe} onChange={setTimeframe}>{['All','M1','M5','M15','M30','H1','H4','D1'].map(item => <option key={item}>{item}</option>)}</Select></Field><Field label="Target timezone" hint="Choose Original to keep timestamps unchanged."><Select value={timezone} onChange={setTimezone}>{exportTimezones.map(([id,label]) => <option value={id} key={id}>{label}</option>)}</Select></Field><Field label="Encoding" hint="Leave empty to use the system default."><TextInput list="mt4-encodings" value={encoding} onChange={event => setEncoding(event.target.value)}/><datalist id="mt4-encodings"><option value="windows-1250"/><option value="windows-1252"/><option value="ISO-8859-1"/><option value="ISO-8859-2"/></datalist></Field><Field label="Export mode"><Select value={mode} onChange={value => setMode(value as typeof mode)}><option value="all">All (FXT and HST)</option><option value="hst">HST only</option><option value="fxt">FXT only</option></Select></Field></div>
      <Button onClick={() => specPicker.current?.click()}>Load other MT4 data specification file</Button><input ref={specPicker} hidden type="file" accept=".properties,text/plain" aria-label="Load MT4 specification file" onChange={event => { void loadSpec(event.target.files?.[0]); event.target.value = ''; }}/>
      <div className="mt4-properties" aria-label="MT4 property summary">{Object.entries(properties).slice(0, 18).map(([key,value]) => <span key={key}><strong>{key}</strong> {value}</span>)}</div>
      <p className="export-warning">MetaTrader 4 Build 8xx and newer can ignore FXT spread values and use the spread configured in Strategy Tester.</p><p className="export-mock-note">This browser workflow creates a JSON manifest describing the requested files. It does not claim native FXT/HST compatibility.</p>
    </fieldset>
  </Modal></div>;
}
