import {SqdModal,SqdFieldset} from '../../plugins/project/ProjectWorkbench';
import type {MasterDraft} from './portfolioMasterModel';
export function PortfolioMasterDialogs({kind,draft,onChange,onClose}:{kind:'genetic'|'correlation';draft:MasterDraft;onChange:(v:MasterDraft)=>void;onClose:()=>void}) {
 const patch=(v:Partial<MasterDraft>)=>onChange({...draft,...v});
 const number=(label:string,key:'population'|'generations'|'stagnation',min=10)=><label className="pf-row"><span>{label}</span><input aria-label={label} type="number" min={min} value={draft[key]} onChange={e=>patch({[key]:Number(e.target.value)})}/></label>;
 const corr=(v:Partial<MasterDraft['correlation']>)=>patch({correlation:{...draft.correlation,...v}});
 return <SqdModal title={kind==='genetic'?'Genetic settings':'Correlation settings'} width={kind==='genetic'?600:800} onClose={onClose} footer={<button className="sqd-btn" onClick={onClose}>Close</button>}>
 {kind==='genetic'?<><div className="pf-two">{number('Population size','population')}{number('Generations','generations')}</div><label className="pf-check"><input type="checkbox" checked={draft.restart} onChange={e=>patch({restart:e.target.checked})}/>Restart if fitness of In Sample stagnates for</label>{number('Stagnation generations','stagnation')}<label className="pf-check"><input type="checkbox" checked={draft.continuous} onChange={e=>patch({continuous:e.target.checked})}/>Run continually (start again when finished, runs until stopped)</label><p className="pf-hint">Preview runs remain bounded to one cycle.</p></>:<><SqdFieldset legend="Correlation computation settings">{([['Correlation by','period',['Day','Week','Month']],['of','type',['Profit / Loss','Equity']],['computed on','sample',['Full','In Sample','Out of Sample']]] as const).map(([label,key,options])=><label key={key} className="pf-row"><span>{label}</span><select aria-label={label} value={draft.correlation[key]} onChange={e=>corr({[key]:e.target.value})}>{options.map(o=><option key={o}>{o}</option>)}</select></label>)}<label className="pf-check"><input type="checkbox" checked={draft.correlation.empty} onChange={e=>corr({empty:e.target.checked})}/>Add empty periods</label></SqdFieldset><SqdFieldset legend="Filter"><label className="pf-row"><span>Max allowed correlation of any two strategies in portfolio</span><input aria-label="Maximum correlation" type="number" min={0} max={1} step={0.1} value={draft.correlation.max} onChange={e=>corr({max:Number(e.target.value)})}/></label><label className="pf-check"><input type="checkbox" checked={draft.correlation.negative} onChange={e=>corr({negative:e.target.checked})}/>Allow negative correlation</label></SqdFieldset></>}
 </SqdModal>;
}
