# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from enum import IntEnum
from typing import Final


class ENUM_APPLIED_PRICE(IntEnum):
    """Defines the identifier set for applied price."""

    PRICE_CLOSE = 0
    PRICE_OPEN = 1
    PRICE_HIGH = 2
    PRICE_LOW = 3
    PRICE_MEDIAN = 4
    PRICE_TYPICAL = 5
    PRICE_WEIGHTED = 6


PRICE_CLOSE: Final = ENUM_APPLIED_PRICE.PRICE_CLOSE
PRICE_OPEN: Final = ENUM_APPLIED_PRICE.PRICE_OPEN
PRICE_HIGH: Final = ENUM_APPLIED_PRICE.PRICE_HIGH
PRICE_LOW: Final = ENUM_APPLIED_PRICE.PRICE_LOW
PRICE_MEDIAN: Final = ENUM_APPLIED_PRICE.PRICE_MEDIAN
PRICE_TYPICAL: Final = ENUM_APPLIED_PRICE.PRICE_TYPICAL
PRICE_WEIGHTED: Final = ENUM_APPLIED_PRICE.PRICE_WEIGHTED


class ENUM_APPLIED_VOLUME(IntEnum):
    """Defines the identifier set for applied volume."""

    VOLUME_TICK = 0
    VOLUME_REAL = 1


VOLUME_TICK: Final = ENUM_APPLIED_VOLUME.VOLUME_TICK
VOLUME_REAL: Final = ENUM_APPLIED_VOLUME.VOLUME_REAL


class ENUM_CUSTOMIND_PROPERTY_DOUBLE(IntEnum):
    """Defines the identifier set for customind property double."""

    INDICATOR_MINIMUM = 0
    INDICATOR_MAXIMUM = 1
    INDICATOR_LEVELVALUE = 2


INDICATOR_MINIMUM: Final = ENUM_CUSTOMIND_PROPERTY_DOUBLE.INDICATOR_MINIMUM
INDICATOR_MAXIMUM: Final = ENUM_CUSTOMIND_PROPERTY_DOUBLE.INDICATOR_MAXIMUM
INDICATOR_LEVELVALUE: Final = ENUM_CUSTOMIND_PROPERTY_DOUBLE.INDICATOR_LEVELVALUE


class ENUM_CUSTOMIND_PROPERTY_INTEGER(IntEnum):
    """Defines the identifier set for customind property integer."""

    INDICATOR_DIGITS = 0
    INDICATOR_HEIGHT = 1
    INDICATOR_LEVELS = 2
    INDICATOR_LEVELCOLOR = 3
    INDICATOR_LEVELSTYLE = 4
    INDICATOR_LEVELWIDTH = 5
    INDICATOR_FIXED_MINIMUM = 6
    INDICATOR_FIXED_MAXIMUM = 7


INDICATOR_DIGITS: Final = ENUM_CUSTOMIND_PROPERTY_INTEGER.INDICATOR_DIGITS
INDICATOR_HEIGHT: Final = ENUM_CUSTOMIND_PROPERTY_INTEGER.INDICATOR_HEIGHT
INDICATOR_LEVELS: Final = ENUM_CUSTOMIND_PROPERTY_INTEGER.INDICATOR_LEVELS
INDICATOR_LEVELCOLOR: Final = ENUM_CUSTOMIND_PROPERTY_INTEGER.INDICATOR_LEVELCOLOR
INDICATOR_LEVELSTYLE: Final = ENUM_CUSTOMIND_PROPERTY_INTEGER.INDICATOR_LEVELSTYLE
INDICATOR_LEVELWIDTH: Final = ENUM_CUSTOMIND_PROPERTY_INTEGER.INDICATOR_LEVELWIDTH
INDICATOR_FIXED_MINIMUM: Final = ENUM_CUSTOMIND_PROPERTY_INTEGER.INDICATOR_FIXED_MINIMUM
INDICATOR_FIXED_MAXIMUM: Final = ENUM_CUSTOMIND_PROPERTY_INTEGER.INDICATOR_FIXED_MAXIMUM


class ENUM_CUSTOMIND_PROPERTY_STRING(IntEnum):
    """Defines the identifier set for customind property string."""

    INDICATOR_SHORTNAME = 0
    INDICATOR_LEVELTEXT = 1


INDICATOR_SHORTNAME: Final = ENUM_CUSTOMIND_PROPERTY_STRING.INDICATOR_SHORTNAME
INDICATOR_LEVELTEXT: Final = ENUM_CUSTOMIND_PROPERTY_STRING.INDICATOR_LEVELTEXT


class ENUM_DATATYPE(IntEnum):
    """Defines the identifier set for datatype."""

    TYPE_BOOL = 0
    TYPE_CHAR = 1
    TYPE_UCHAR = 2
    TYPE_SHORT = 3
    TYPE_USHORT = 4
    TYPE_COLOR = 5
    TYPE_INT = 6
    TYPE_UINT = 7
    TYPE_DATETIME = 8
    TYPE_LONG = 9
    TYPE_ULONG = 10
    TYPE_FLOAT = 11
    TYPE_DOUBLE = 12
    TYPE_STRING = 13


TYPE_BOOL: Final = ENUM_DATATYPE.TYPE_BOOL
TYPE_CHAR: Final = ENUM_DATATYPE.TYPE_CHAR
TYPE_UCHAR: Final = ENUM_DATATYPE.TYPE_UCHAR
TYPE_SHORT: Final = ENUM_DATATYPE.TYPE_SHORT
TYPE_USHORT: Final = ENUM_DATATYPE.TYPE_USHORT
TYPE_COLOR: Final = ENUM_DATATYPE.TYPE_COLOR
TYPE_INT: Final = ENUM_DATATYPE.TYPE_INT
TYPE_UINT: Final = ENUM_DATATYPE.TYPE_UINT
TYPE_DATETIME: Final = ENUM_DATATYPE.TYPE_DATETIME
TYPE_LONG: Final = ENUM_DATATYPE.TYPE_LONG
TYPE_ULONG: Final = ENUM_DATATYPE.TYPE_ULONG
TYPE_FLOAT: Final = ENUM_DATATYPE.TYPE_FLOAT
TYPE_DOUBLE: Final = ENUM_DATATYPE.TYPE_DOUBLE
TYPE_STRING: Final = ENUM_DATATYPE.TYPE_STRING


class ENUM_DRAW_TYPE(IntEnum):
    """Defines the identifier set for draw type."""

    DRAW_NONE = 0
    DRAW_LINE = 1
    DRAW_SECTION = 2
    DRAW_HISTOGRAM = 3
    DRAW_HISTOGRAM2 = 4
    DRAW_ARROW = 5
    DRAW_ZIGZAG = 6
    DRAW_FILLING = 7
    DRAW_BARS = 8
    DRAW_CANDLES = 9
    DRAW_COLOR_LINE = 10
    DRAW_COLOR_SECTION = 11
    DRAW_COLOR_HISTOGRAM = 12
    DRAW_COLOR_HISTOGRAM2 = 13
    DRAW_COLOR_ARROW = 14
    DRAW_COLOR_ZIGZAG = 15
    DRAW_COLOR_BARS = 16
    DRAW_COLOR_CANDLES = 17


DRAW_NONE: Final = ENUM_DRAW_TYPE.DRAW_NONE
DRAW_LINE: Final = ENUM_DRAW_TYPE.DRAW_LINE
DRAW_SECTION: Final = ENUM_DRAW_TYPE.DRAW_SECTION
DRAW_HISTOGRAM: Final = ENUM_DRAW_TYPE.DRAW_HISTOGRAM
DRAW_HISTOGRAM2: Final = ENUM_DRAW_TYPE.DRAW_HISTOGRAM2
DRAW_ARROW: Final = ENUM_DRAW_TYPE.DRAW_ARROW
DRAW_ZIGZAG: Final = ENUM_DRAW_TYPE.DRAW_ZIGZAG
DRAW_FILLING: Final = ENUM_DRAW_TYPE.DRAW_FILLING
DRAW_BARS: Final = ENUM_DRAW_TYPE.DRAW_BARS
DRAW_CANDLES: Final = ENUM_DRAW_TYPE.DRAW_CANDLES
DRAW_COLOR_LINE: Final = ENUM_DRAW_TYPE.DRAW_COLOR_LINE
DRAW_COLOR_SECTION: Final = ENUM_DRAW_TYPE.DRAW_COLOR_SECTION
DRAW_COLOR_HISTOGRAM: Final = ENUM_DRAW_TYPE.DRAW_COLOR_HISTOGRAM
DRAW_COLOR_HISTOGRAM2: Final = ENUM_DRAW_TYPE.DRAW_COLOR_HISTOGRAM2
DRAW_COLOR_ARROW: Final = ENUM_DRAW_TYPE.DRAW_COLOR_ARROW
DRAW_COLOR_ZIGZAG: Final = ENUM_DRAW_TYPE.DRAW_COLOR_ZIGZAG
DRAW_COLOR_BARS: Final = ENUM_DRAW_TYPE.DRAW_COLOR_BARS
DRAW_COLOR_CANDLES: Final = ENUM_DRAW_TYPE.DRAW_COLOR_CANDLES


class ENUM_INDEXBUFFER_TYPE(IntEnum):
    """Defines the identifier set for indexbuffer type."""

    INDICATOR_DATA = 0
    INDICATOR_COLOR_INDEX = 1
    INDICATOR_CALCULATIONS = 2


INDICATOR_DATA: Final = ENUM_INDEXBUFFER_TYPE.INDICATOR_DATA
INDICATOR_COLOR_INDEX: Final = ENUM_INDEXBUFFER_TYPE.INDICATOR_COLOR_INDEX
INDICATOR_CALCULATIONS: Final = ENUM_INDEXBUFFER_TYPE.INDICATOR_CALCULATIONS


class ENUM_INDICATOR(IntEnum):
    """Defines the identifier set for indicator."""

    IND_AC = 0
    IND_AD = 1
    IND_ADX = 2
    IND_ADXW = 3
    IND_ALLIGATOR = 4
    IND_AMA = 5
    IND_AO = 6
    IND_ATR = 7
    IND_BANDS = 8
    IND_BEARS = 9
    IND_BULLS = 10
    IND_BWMFI = 11
    IND_CCI = 12
    IND_CHAIKIN = 13
    IND_CUSTOM = 14
    IND_DEMA = 15
    IND_DEMARKER = 16
    IND_ENVELOPES = 17
    IND_FORCE = 18
    IND_FRACTALS = 19
    IND_FRAMA = 20
    IND_GATOR = 21
    IND_ICHIMOKU = 22
    IND_MA = 23
    IND_MACD = 24
    IND_MFI = 25
    IND_MOMENTUM = 26
    IND_OBV = 27
    IND_OSMA = 28
    IND_RSI = 29
    IND_RVI = 30
    IND_SAR = 31
    IND_STDDEV = 32
    IND_STOCHASTIC = 33
    IND_TEMA = 34
    IND_TRIX = 35
    IND_VIDYA = 36
    IND_VOLUMES = 37
    IND_WPR = 38


IND_AC: Final = ENUM_INDICATOR.IND_AC
IND_AD: Final = ENUM_INDICATOR.IND_AD
IND_ADX: Final = ENUM_INDICATOR.IND_ADX
IND_ADXW: Final = ENUM_INDICATOR.IND_ADXW
IND_ALLIGATOR: Final = ENUM_INDICATOR.IND_ALLIGATOR
IND_AMA: Final = ENUM_INDICATOR.IND_AMA
IND_AO: Final = ENUM_INDICATOR.IND_AO
IND_ATR: Final = ENUM_INDICATOR.IND_ATR
IND_BANDS: Final = ENUM_INDICATOR.IND_BANDS
IND_BEARS: Final = ENUM_INDICATOR.IND_BEARS
IND_BULLS: Final = ENUM_INDICATOR.IND_BULLS
IND_BWMFI: Final = ENUM_INDICATOR.IND_BWMFI
IND_CCI: Final = ENUM_INDICATOR.IND_CCI
IND_CHAIKIN: Final = ENUM_INDICATOR.IND_CHAIKIN
IND_CUSTOM: Final = ENUM_INDICATOR.IND_CUSTOM
IND_DEMA: Final = ENUM_INDICATOR.IND_DEMA
IND_DEMARKER: Final = ENUM_INDICATOR.IND_DEMARKER
IND_ENVELOPES: Final = ENUM_INDICATOR.IND_ENVELOPES
IND_FORCE: Final = ENUM_INDICATOR.IND_FORCE
IND_FRACTALS: Final = ENUM_INDICATOR.IND_FRACTALS
IND_FRAMA: Final = ENUM_INDICATOR.IND_FRAMA
IND_GATOR: Final = ENUM_INDICATOR.IND_GATOR
IND_ICHIMOKU: Final = ENUM_INDICATOR.IND_ICHIMOKU
IND_MA: Final = ENUM_INDICATOR.IND_MA
IND_MACD: Final = ENUM_INDICATOR.IND_MACD
IND_MFI: Final = ENUM_INDICATOR.IND_MFI
IND_MOMENTUM: Final = ENUM_INDICATOR.IND_MOMENTUM
IND_OBV: Final = ENUM_INDICATOR.IND_OBV
IND_OSMA: Final = ENUM_INDICATOR.IND_OSMA
IND_RSI: Final = ENUM_INDICATOR.IND_RSI
IND_RVI: Final = ENUM_INDICATOR.IND_RVI
IND_SAR: Final = ENUM_INDICATOR.IND_SAR
IND_STDDEV: Final = ENUM_INDICATOR.IND_STDDEV
IND_STOCHASTIC: Final = ENUM_INDICATOR.IND_STOCHASTIC
IND_TEMA: Final = ENUM_INDICATOR.IND_TEMA
IND_TRIX: Final = ENUM_INDICATOR.IND_TRIX
IND_VIDYA: Final = ENUM_INDICATOR.IND_VIDYA
IND_VOLUMES: Final = ENUM_INDICATOR.IND_VOLUMES
IND_WPR: Final = ENUM_INDICATOR.IND_WPR


class ENUM_LINE_STYLE(IntEnum):
    """Defines the identifier set for line style."""

    STYLE_SOLID = 0
    STYLE_DASH = 1
    STYLE_DOT = 2
    STYLE_DASHDOT = 3
    STYLE_DASHDOTDOT = 4


STYLE_SOLID: Final = ENUM_LINE_STYLE.STYLE_SOLID
STYLE_DASH: Final = ENUM_LINE_STYLE.STYLE_DASH
STYLE_DOT: Final = ENUM_LINE_STYLE.STYLE_DOT
STYLE_DASHDOT: Final = ENUM_LINE_STYLE.STYLE_DASHDOT
STYLE_DASHDOTDOT: Final = ENUM_LINE_STYLE.STYLE_DASHDOTDOT


class ENUM_MA_METHOD(IntEnum):
    """Defines the identifier set for ma method."""

    MODE_SMA = 0
    MODE_EMA = 1
    MODE_SMMA = 2
    MODE_LWMA = 3


MODE_SMA: Final = ENUM_MA_METHOD.MODE_SMA
MODE_EMA: Final = ENUM_MA_METHOD.MODE_EMA
MODE_SMMA: Final = ENUM_MA_METHOD.MODE_SMMA
MODE_LWMA: Final = ENUM_MA_METHOD.MODE_LWMA


class ENUM_PLOT_PROPERTY_DOUBLE(IntEnum):
    """Defines the identifier set for plot property double."""

    PLOT_EMPTY_VALUE = 0


PLOT_EMPTY_VALUE: Final = ENUM_PLOT_PROPERTY_DOUBLE.PLOT_EMPTY_VALUE


class ENUM_PLOT_PROPERTY_INTEGER(IntEnum):
    """Defines the identifier set for plot property integer."""

    PLOT_ARROW = 0
    PLOT_ARROW_SHIFT = 1
    PLOT_DRAW_BEGIN = 2
    PLOT_DRAW_TYPE = 3
    PLOT_SHOW_DATA = 4
    PLOT_SHIFT = 5
    PLOT_LINE_STYLE = 6
    PLOT_LINE_WIDTH = 7
    PLOT_COLOR_INDEXES = 8
    PLOT_LINE_COLOR = 9


PLOT_ARROW: Final = ENUM_PLOT_PROPERTY_INTEGER.PLOT_ARROW
PLOT_ARROW_SHIFT: Final = ENUM_PLOT_PROPERTY_INTEGER.PLOT_ARROW_SHIFT
PLOT_DRAW_BEGIN: Final = ENUM_PLOT_PROPERTY_INTEGER.PLOT_DRAW_BEGIN
PLOT_DRAW_TYPE: Final = ENUM_PLOT_PROPERTY_INTEGER.PLOT_DRAW_TYPE
PLOT_SHOW_DATA: Final = ENUM_PLOT_PROPERTY_INTEGER.PLOT_SHOW_DATA
PLOT_SHIFT: Final = ENUM_PLOT_PROPERTY_INTEGER.PLOT_SHIFT
PLOT_LINE_STYLE: Final = ENUM_PLOT_PROPERTY_INTEGER.PLOT_LINE_STYLE
PLOT_LINE_WIDTH: Final = ENUM_PLOT_PROPERTY_INTEGER.PLOT_LINE_WIDTH
PLOT_COLOR_INDEXES: Final = ENUM_PLOT_PROPERTY_INTEGER.PLOT_COLOR_INDEXES
PLOT_LINE_COLOR: Final = ENUM_PLOT_PROPERTY_INTEGER.PLOT_LINE_COLOR


class ENUM_PLOT_PROPERTY_STRING(IntEnum):
    """Defines the identifier set for plot property string."""

    PLOT_LABEL = 0


PLOT_LABEL: Final = ENUM_PLOT_PROPERTY_STRING.PLOT_LABEL


class ENUM_STO_PRICE(IntEnum):
    """Defines the identifier set for sto price."""

    STO_LOWHIGH = 0
    STO_CLOSECLOSE = 1


STO_LOWHIGH: Final = ENUM_STO_PRICE.STO_LOWHIGH
STO_CLOSECLOSE: Final = ENUM_STO_PRICE.STO_CLOSECLOSE

MAIN_LINE: Final[int] = 0
PLUSDI_LINE: Final[int] = 1
MINUSDI_LINE: Final[int] = 2
BASE_LINE: Final[int] = 0
UPPER_BAND: Final[int] = 1
LOWER_BAND: Final[int] = 2
UPPER_LINE: Final[int] = 0
LOWER_LINE: Final[int] = 1
UPPER_HISTOGRAM: Final[int] = 0
LOWER_HISTOGRAM: Final[int] = 2
GATORJAW_LINE: Final[int] = 0
GATORTEETH_LINE: Final[int] = 1
GATORLIPS_LINE: Final[int] = 2
TENKANSEN_LINE: Final[int] = 0
KIJUNSEN_LINE: Final[int] = 1
SENKOUSPANA_LINE: Final[int] = 2
SENKOUSPANB_LINE: Final[int] = 3
CHIKOUSPAN_LINE: Final[int] = 4

__all__ = [
    "BASE_LINE",
    "CHIKOUSPAN_LINE",
    "DRAW_ARROW",
    "DRAW_BARS",
    "DRAW_CANDLES",
    "DRAW_COLOR_ARROW",
    "DRAW_COLOR_BARS",
    "DRAW_COLOR_CANDLES",
    "DRAW_COLOR_HISTOGRAM",
    "DRAW_COLOR_HISTOGRAM2",
    "DRAW_COLOR_LINE",
    "DRAW_COLOR_SECTION",
    "DRAW_COLOR_ZIGZAG",
    "DRAW_FILLING",
    "DRAW_HISTOGRAM",
    "DRAW_HISTOGRAM2",
    "DRAW_LINE",
    "DRAW_NONE",
    "DRAW_SECTION",
    "DRAW_ZIGZAG",
    "ENUM_APPLIED_PRICE",
    "ENUM_APPLIED_VOLUME",
    "ENUM_CUSTOMIND_PROPERTY_DOUBLE",
    "ENUM_CUSTOMIND_PROPERTY_INTEGER",
    "ENUM_CUSTOMIND_PROPERTY_STRING",
    "ENUM_DATATYPE",
    "ENUM_DRAW_TYPE",
    "ENUM_INDEXBUFFER_TYPE",
    "ENUM_INDICATOR",
    "ENUM_LINE_STYLE",
    "ENUM_MA_METHOD",
    "ENUM_PLOT_PROPERTY_DOUBLE",
    "ENUM_PLOT_PROPERTY_INTEGER",
    "ENUM_PLOT_PROPERTY_STRING",
    "ENUM_STO_PRICE",
    "GATORJAW_LINE",
    "GATORLIPS_LINE",
    "GATORTEETH_LINE",
    "IND_AC",
    "IND_AD",
    "IND_ADX",
    "IND_ADXW",
    "IND_ALLIGATOR",
    "IND_AMA",
    "IND_AO",
    "IND_ATR",
    "IND_BANDS",
    "IND_BEARS",
    "IND_BULLS",
    "IND_BWMFI",
    "IND_CCI",
    "IND_CHAIKIN",
    "IND_CUSTOM",
    "IND_DEMA",
    "IND_DEMARKER",
    "IND_ENVELOPES",
    "IND_FORCE",
    "IND_FRACTALS",
    "IND_FRAMA",
    "IND_GATOR",
    "IND_ICHIMOKU",
    "IND_MA",
    "IND_MACD",
    "IND_MFI",
    "IND_MOMENTUM",
    "IND_OBV",
    "IND_OSMA",
    "IND_RSI",
    "IND_RVI",
    "IND_SAR",
    "IND_STDDEV",
    "IND_STOCHASTIC",
    "IND_TEMA",
    "IND_TRIX",
    "IND_VIDYA",
    "IND_VOLUMES",
    "IND_WPR",
    "INDICATOR_CALCULATIONS",
    "INDICATOR_COLOR_INDEX",
    "INDICATOR_DATA",
    "INDICATOR_DIGITS",
    "INDICATOR_FIXED_MAXIMUM",
    "INDICATOR_FIXED_MINIMUM",
    "INDICATOR_HEIGHT",
    "INDICATOR_LEVELCOLOR",
    "INDICATOR_LEVELS",
    "INDICATOR_LEVELSTYLE",
    "INDICATOR_LEVELTEXT",
    "INDICATOR_LEVELVALUE",
    "INDICATOR_LEVELWIDTH",
    "INDICATOR_MAXIMUM",
    "INDICATOR_MINIMUM",
    "INDICATOR_SHORTNAME",
    "KIJUNSEN_LINE",
    "LOWER_BAND",
    "LOWER_HISTOGRAM",
    "LOWER_LINE",
    "MAIN_LINE",
    "MINUSDI_LINE",
    "MODE_EMA",
    "MODE_LWMA",
    "MODE_SMA",
    "MODE_SMMA",
    "PLOT_ARROW",
    "PLOT_ARROW_SHIFT",
    "PLOT_COLOR_INDEXES",
    "PLOT_DRAW_BEGIN",
    "PLOT_DRAW_TYPE",
    "PLOT_EMPTY_VALUE",
    "PLOT_LABEL",
    "PLOT_LINE_COLOR",
    "PLOT_LINE_STYLE",
    "PLOT_LINE_WIDTH",
    "PLOT_SHIFT",
    "PLOT_SHOW_DATA",
    "PLUSDI_LINE",
    "PRICE_CLOSE",
    "PRICE_HIGH",
    "PRICE_LOW",
    "PRICE_MEDIAN",
    "PRICE_OPEN",
    "PRICE_TYPICAL",
    "PRICE_WEIGHTED",
    "SENKOUSPANA_LINE",
    "SENKOUSPANB_LINE",
    "STO_CLOSECLOSE",
    "STO_LOWHIGH",
    "STYLE_DASH",
    "STYLE_DASHDOT",
    "STYLE_DASHDOTDOT",
    "STYLE_DOT",
    "STYLE_SOLID",
    "TENKANSEN_LINE",
    "TYPE_BOOL",
    "TYPE_CHAR",
    "TYPE_COLOR",
    "TYPE_DATETIME",
    "TYPE_DOUBLE",
    "TYPE_FLOAT",
    "TYPE_INT",
    "TYPE_LONG",
    "TYPE_SHORT",
    "TYPE_STRING",
    "TYPE_UCHAR",
    "TYPE_UINT",
    "TYPE_ULONG",
    "TYPE_USHORT",
    "UPPER_BAND",
    "UPPER_HISTOGRAM",
    "UPPER_LINE",
    "VOLUME_REAL",
    "VOLUME_TICK",
]
