# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from typing import Final

ERR_BUFFERS_NO_MEMORY: Final[int] = 4601
ERR_BUFFERS_WRONG_INDEX: Final[int] = 4602
ERR_INDICATOR_UNKNOWN_SYMBOL: Final[int] = 4801
ERR_INDICATOR_CANNOT_CREATE: Final[int] = 4802
ERR_INDICATOR_NO_MEMORY: Final[int] = 4803
ERR_INDICATOR_CANNOT_APPLY: Final[int] = 4804
ERR_INDICATOR_CANNOT_ADD: Final[int] = 4805
ERR_INDICATOR_DATA_NOT_FOUND: Final[int] = 4806
ERR_INDICATOR_WRONG_HANDLE: Final[int] = 4807
ERR_INDICATOR_WRONG_PARAMETERS: Final[int] = 4808
ERR_INDICATOR_PARAMETERS_MISSING: Final[int] = 4809
ERR_INDICATOR_CUSTOM_NAME: Final[int] = 4810
ERR_INDICATOR_PARAMETER_TYPE: Final[int] = 4811
ERR_INDICATOR_WRONG_INDEX: Final[int] = 4812

__all__ = [
    "ERR_BUFFERS_NO_MEMORY",
    "ERR_BUFFERS_WRONG_INDEX",
    "ERR_INDICATOR_CANNOT_ADD",
    "ERR_INDICATOR_CANNOT_APPLY",
    "ERR_INDICATOR_CANNOT_CREATE",
    "ERR_INDICATOR_CUSTOM_NAME",
    "ERR_INDICATOR_DATA_NOT_FOUND",
    "ERR_INDICATOR_NO_MEMORY",
    "ERR_INDICATOR_PARAMETER_TYPE",
    "ERR_INDICATOR_PARAMETERS_MISSING",
    "ERR_INDICATOR_UNKNOWN_SYMBOL",
    "ERR_INDICATOR_WRONG_HANDLE",
    "ERR_INDICATOR_WRONG_INDEX",
    "ERR_INDICATOR_WRONG_PARAMETERS",
]
