"""Feasibility gates package.

Evaluates margin, drawdown, and execution feasibility after portfolio risk
and before final decision. Never performs broker account queries or order
mutation.
"""

from __future__ import annotations

from app.services.risk.feasibility.drawdown import (
    DrawdownGovernor,
    DrawdownThrottlingState,
    RiskStepDownState,
    apply_drawdown_throttle,
    calculate_daily_drawdown,
    calculate_drawdown_multiplier,
    calculate_strategy_drawdown,
    calculate_total_drawdown,
    check_revenge_trading,
    determine_drawdown_state,
    determine_drawdown_throttling,
    persist_drawdown_state,
    restore_drawdown_state,
    verify_drawdown_limits,
)
from app.services.risk.feasibility.execution_gate import (
    BrokerConstraintSnapshot,
    ExecutionFeasibilityResult,
    ExecutionRiskGate,
    SlippagePolicy,
    SpreadPolicy,
    assess_execution_feasibility,
    check_execution_feasibility,
    check_holding_time_limit,
    check_lot_step_validity,
    check_slippage_limit,
    check_slippage_to_sigma,
    check_spread_limit,
    check_spread_to_sigma,
    check_stop_distance_validity,
    check_stop_freeze_level,
    check_trade_frequency,
    check_trade_frequency_limit,
    check_volume_feasibility,
    evaluate_execution_feasibility,
    validate_micro_scalping_costs,
    validate_stop_and_freeze_levels,
    verify_execution_limits,
)
from app.services.risk.feasibility.margin import (
    LeverageSnapshot,
    LiquiditySnapshot,
    MarginRequirement,
    MarginRiskEngine,
    calculate_current_margin_usage,
    calculate_free_margin_after_reservations,
    calculate_free_margin_after_trade,
    calculate_margin_requirement,
    calculate_projected_margin,
    calculate_projected_margin_usage,
    check_exit_liquidity,
    check_leverage_limit,
    check_margin_limits,
    check_margin_usage,
    evaluate_margin_governance,
    exit_liquidity_stress_check,
    verify_margin_limits,
)

__all__ = [
    "BrokerConstraintSnapshot",
    "DrawdownGovernor",
    "DrawdownThrottlingState",
    "ExecutionFeasibilityResult",
    "ExecutionRiskGate",
    "LeverageSnapshot",
    "LiquiditySnapshot",
    "MarginRequirement",
    "MarginRiskEngine",
    "RiskStepDownState",
    "SlippagePolicy",
    "SpreadPolicy",
    "apply_drawdown_throttle",
    "assess_execution_feasibility",
    "calculate_current_margin_usage",
    "calculate_daily_drawdown",
    "calculate_drawdown_multiplier",
    "calculate_free_margin_after_reservations",
    "calculate_free_margin_after_trade",
    "calculate_margin_requirement",
    "calculate_projected_margin",
    "calculate_projected_margin_usage",
    "calculate_strategy_drawdown",
    "calculate_total_drawdown",
    "check_execution_feasibility",
    "check_exit_liquidity",
    "check_holding_time_limit",
    "check_leverage_limit",
    "check_lot_step_validity",
    "check_margin_limits",
    "check_margin_usage",
    "check_revenge_trading",
    "check_slippage_limit",
    "check_slippage_to_sigma",
    "check_spread_limit",
    "check_spread_to_sigma",
    "check_stop_distance_validity",
    "check_stop_freeze_level",
    "check_trade_frequency",
    "check_trade_frequency_limit",
    "check_volume_feasibility",
    "determine_drawdown_state",
    "determine_drawdown_throttling",
    "evaluate_execution_feasibility",
    "evaluate_margin_governance",
    "exit_liquidity_stress_check",
    "persist_drawdown_state",
    "restore_drawdown_state",
    "validate_micro_scalping_costs",
    "validate_stop_and_freeze_levels",
    "verify_drawdown_limits",
    "verify_execution_limits",
    "verify_margin_limits",
]
