import { useMemo, useState } from 'react';
import { Copy, Download, Filter, FolderInput, MoreHorizontal, Search, Settings2, Trash2 } from 'lucide-react';
import { useAppStore } from '../app/store';
import { Button, IconButton, Modal, TextInput } from './ui';
import { StrategyTable } from './StrategyTable';

export function DatabankPanel() {
  const store = useAppStore(); const [query, setQuery] = useState(''); const [dialog, setDialog] = useState<'move' | 'rename' | 'delete' | null>(null); const [target, setTarget] = useState('retest'); const [copy, setCopy] = useState(true); const [name, setName] = useState(''); const [note, setNote] = useState('');
  const bank = store.databanks.find(b => b.id === store.selectedBankId)!; const data = useMemo(() => store.strategies.filter(s => bank.strategyIds.includes(s.id) && `${s.name} ${s.symbol}`.toLowerCase().includes(query.toLowerCase())), [store.strategies, bank, query]); const current = store.strategies.find(s => s.id === store.selectedStrategyId);
  const openRename = () => { if (!current) return; setName(current.name); setNote(current.note); setDialog('rename'); };
  return <div className="databank-panel"><div className="bank-tabs">{store.databanks.map(b => <button key={b.id} className={b.id === bank.id ? 'active' : ''} onClick={() => store.setBank(b.id)}>{b.name}<small>{b.strategyIds.length}</small></button>)}<button className="add-bank" onClick={() => store.notify('New databank created in mock workspace')}>＋</button></div><div className="bank-toolbar"><div className="search"><Search size={14}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search strategies"/></div><Button disabled={!store.selectedRows.length} onClick={() => setDialog('move')}><FolderInput size={14}/> Move / copy</Button><Button disabled={!current} onClick={openRename}><Settings2 size={14}/> Rename & notes</Button><IconButton title="Filters"><Filter size={15}/></IconButton><IconButton title="Export selected" onClick={() => store.notify(`${store.selectedRows.length || 1} strategy artifact prepared for download`)}><Download size={15}/></IconButton><IconButton title="Delete" disabled={!store.selectedRows.length} onClick={() => setDialog('delete')}><Trash2 size={15}/></IconButton><IconButton title="More databank actions"><MoreHorizontal size={16}/></IconButton><span className="row-count">{data.length} strategies · {store.selectedRows.length} selected</span></div><StrategyTable data={data} selectedId={store.selectedStrategyId} selectedRows={store.selectedRows} onSelect={store.selectStrategy} onRows={store.setRows}/>
  {dialog === 'move' && <Modal title="Move or copy strategies" onClose={() => setDialog(null)} footer={<><Button onClick={() => setDialog(null)}>Cancel</Button><Button className="primary" onClick={() => { store.moveStrategies(store.selectedRows, target, copy); store.notify(`${copy ? 'Copied' : 'Moved'} strategies to ${store.databanks.find(b => b.id === target)?.name}`); setDialog(null); }}>{copy ? <Copy size={14}/> : <FolderInput size={14}/>} {copy ? 'Copy' : 'Move'}</Button></>}><p className="dialog-note">The selected {store.selectedRows.length} strategies will {copy ? 'remain in the source databank.' : 'be removed from the source databank.'}</p><label className="field"><span>Target databank</span><select className="text-input" value={target} onChange={e => setTarget(e.target.value)}>{store.databanks.filter(b => b.id !== bank.id).map(b => <option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label className="check"><input type="radio" checked={copy} onChange={() => setCopy(true)}/> Copy strategies</label><label className="check"><input type="radio" checked={!copy} onChange={() => setCopy(false)}/> Move strategies</label></Modal>}
  {dialog === 'rename' && current && <Modal title="Strategy name and notes" onClose={() => setDialog(null)} footer={<><Button onClick={() => setDialog(null)}>Cancel</Button><Button className="primary" disabled={!name.trim()} onClick={() => { store.renameStrategy(current.id, name.trim(), note); setDialog(null); }}>Save</Button></>}><label className="field"><span>Name</span><TextInput value={name} onChange={e => setName(e.target.value)} autoFocus/></label><label className="field"><span>Notes</span><textarea className="text-input textarea" value={note} onChange={e => setNote(e.target.value)}/></label></Modal>}
  {dialog === 'delete' && <Modal title="Delete selected strategies?" onClose={() => setDialog(null)} footer={<><Button onClick={() => setDialog(null)}>Cancel</Button><Button className="danger" onClick={() => { store.deleteStrategies(store.selectedRows); setDialog(null); }}>Delete permanently</Button></>}><p>This removes {store.selectedRows.length} selected strategies from every databank in this mock workspace. This action cannot be undone.</p></Modal>}</div>;
}
