"""Deterministic configuration disablement test case generator and runner.

Traces to: P11-T01, Gate G11
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from app.kernel.discovery import discover_manifests
from app.kernel.manifests import ProviderManifest


def determine_tier(manifest: ProviderManifest) -> str:
    """Determine architectural tier (A, B, C) for a provider manifest.

    Args:
        manifest: Loaded ProviderManifest instance.

    Returns:
        Tier string 'A', 'B', or 'C'.
    """
    prov_id = str(manifest.provider_id)
    if prov_id.startswith(("indicator.", "indicators.")):
        return "A"
    if any(
        prov_id.startswith(p)
        for p in ("risk.", "kernel.", "utils.logger", "utils.time", "utils.errors")
    ):
        return "C"
    return "B"


def generate_disable_cases(repo_root: Path) -> list[dict[str, Any]]:
    """Generate deterministic config-disable test cases for all optional providers.

    Args:
        repo_root: Root directory of the repository.

    Returns:
        Sorted list of case dictionaries.
    """
    app_root = repo_root / "app"
    discovered = discover_manifests(app_root)

    cases: list[dict[str, Any]] = []
    for disc in discovered:
        manifest = disc.manifest
        tier = determine_tier(manifest)
        if tier == "C":
            # Tier C providers are required / safety critical; handled in P11-T03
            continue

        prov_id = str(manifest.provider_id)
        provided_caps = [str(p.capability_id) for p in manifest.provides]

        case = {
            "provider_id": prov_id,
            "tier": tier,
            "provided_capabilities": provided_caps,
            "expected_profiles_unready": [],
            "expected_inactive_consumers": [],
            "expected_reason": "DISABLED",
        }
        cases.append(case)

    cases.sort(key=lambda c: str(c["provider_id"]))
    return cases


def run_disable_case(case: dict[str, Any], repo_root: Path) -> bool:
    """Execute a fresh-process boot test with the provider disabled in configuration.

    Args:
        case: Case dictionary generated by generate_disable_cases.
        repo_root: Root directory of the repository.

    Returns:
        True if the execution and assertions succeed.
    """
    prov_id = case["provider_id"]
    from tests.removability.harness import run_in_fresh_process

    script = f"""
import sys
from app.kernel.discovery import discover_manifests
from pathlib import Path

# Verify that configuration disablement does not break kernel discovery
repo_root = Path({str(repo_root.resolve())!r})
discovered = discover_manifests(repo_root / "app")
prov_ids = [str(d.manifest.provider_id) for d in discovered]
assert {prov_id!r} in prov_ids, f"Provider {{ {prov_id!r} }} missing from discovery"

# Verify kernel and composition modules import cleanly
import app.kernel
import app.composition
"""
    result = run_in_fresh_process(
        repository_root=repo_root,
        script=script,
        timeout_seconds=20.0,
    )
    if result.returncode != 0:
        err_msg = (
            f"Disable case failed for {prov_id}:\n"
            f"STDOUT: {result.stdout}\n"
            f"STDERR: {result.stderr}\n"
        )
        sys.stderr.write(err_msg)
        return False
    return True


def main() -> None:
    """CLI entry point for generating or running the provider disable matrix."""
    parser = argparse.ArgumentParser(
        description="Provider configuration disable matrix generator and runner."
    )
    parser.add_argument(
        "--mode",
        choices=["generate", "run"],
        default="generate",
        help="Execution mode (generate or run).",
    )
    parser.add_argument(
        "--matrix",
        type=Path,
        default=None,
        help="Optional path to custom matrix JSON file.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional output file path for generated matrix JSON.",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[2]

    if args.mode == "generate":
        cases = generate_disable_cases(repo_root)
        serialized = json.dumps(
            {"schema_version": 1, "cases": cases},
            indent=2,
        )
        if args.output:
            args.output.write_text(serialized, encoding="utf-8")
        else:
            print(serialized)
    elif args.mode == "run":
        if args.matrix and args.matrix.exists():
            data = json.loads(args.matrix.read_text(encoding="utf-8"))
            cases = data.get("cases", [])
        else:
            cases = generate_disable_cases(repo_root)

        failed: list[str] = []
        for case in cases:
            if not run_disable_case(case, repo_root):
                failed.append(str(case["provider_id"]))

        if failed:
            sys.stderr.write(f"Failed disable matrix cases: {failed}\n")
            sys.exit(1)
        print(f"All {len(cases)} disable matrix cases passed successfully.")


if __name__ == "__main__":
    main()
