import { expect, test, type Page } from '@playwright/test';

async function launch(page: Page): Promise<void> { await page.goto('/'); await page.getByRole('button', { name: 'Data Manager', exact: true }).click(); await page.getByRole('button', { name: 'External indicators', exact: true }).click(); }
function row(page: Page, name: string) { return page.getByRole('table', { name: 'External indicators', exact: true }).getByRole('row').filter({ has: page.getByRole('checkbox', { name: `Select indicator ${name}`, exact: true }) }); }
async function add(page: Page, name = 'Sentiment'): Promise<void> { const actions = page.getByLabel('External indicator operations'); await actions.getByRole('button', { name: 'Add new', exact: true }).click(); const dialog = page.getByRole('dialog', { name: 'Add external indicators', exact: true }); await dialog.getByLabel('Name', { exact: true }).fill(name); await dialog.getByLabel('Value 1 name').fill('Score'); await dialog.getByLabel('Value 1 MT4 code').fill('iCustom(...)'); await dialog.getByRole('button', { name: 'Save', exact: true }).click(); await expect(row(page, name)).toBeVisible(); }

test('add, edit, import, pause/reload/resume, view, clear, and delete', async ({ page }) => {
  await launch(page); const actions = page.getByLabel('External indicator operations');
  await actions.getByRole('button', { name: 'Import indicator data', exact: true }).click(); await expect(page.getByLabel('Data Manager progress')).toContainText('at least one indicator');
  await add(page); let indicator = row(page, 'Sentiment'); await indicator.dblclick(); let dialog = page.getByRole('dialog', { name: 'Edit external indicators', exact: true }); await expect(dialog.getByLabel('Name', { exact: true })).toBeDisabled(); await dialog.getByLabel('Value 1 EL code').fill('Sentiment[0]'); await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  indicator = row(page, 'Sentiment'); await indicator.getByRole('checkbox').check(); await actions.getByRole('button', { name: 'Import indicator data', exact: true }).click(); dialog = page.getByRole('dialog', { name: "Custom data import for 'Sentiment'", exact: true });
  const csv = 'Date,Score\n2026-09-20 10:00:00,1.5\n2026-09-20 10:01:00,2.5\n2026-09-20 10:02:00,3.5'; await dialog.getByLabel('Data file').setInputFiles({ name: 'sentiment.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) }); await expect(dialog.getByRole('table', { name: 'Indicator import preview' })).toContainText('1.5'); await page.screenshot({ path: 'test-results/external-import-dark.png' }); await dialog.getByRole('button', { name: 'Start Import', exact: true }).click();
  await page.getByRole('button', { name: 'Pause all', exact: true }).click(); await page.reload(); await page.getByRole('button', { name: 'External indicators', exact: true }).click(); await expect(page.getByLabel('Data Manager progress')).toContainText('paused'); await page.getByRole('button', { name: 'Resume all', exact: true }).click(); await expect(page.getByLabel('Status for Sentiment')).toHaveText('Completed', { timeout: 8000 });
  await row(page, 'Sentiment').getByRole('checkbox').check(); await actions.getByRole('button', { name: 'View & Analyze', exact: true }).click(); dialog = page.getByRole('dialog', { name: "View custom data for 'Sentiment'", exact: true }); await expect(dialog.getByRole('table')).toContainText('3.5'); await dialog.getByRole('button', { name: 'Close', exact: true }).last().click();
  await row(page, 'Sentiment').getByRole('button', { name: 'Delete indicator Sentiment' }).click(); dialog = page.getByRole('dialog', { name: 'Delete custom data' }); await dialog.getByRole('button', { name: 'Clear data' }).click(); await expect(row(page, 'Sentiment').getByRole('cell').nth(8)).toHaveText('0'); await row(page, 'Sentiment').getByRole('button', { name: 'Delete indicator Sentiment' }).click(); await page.getByRole('dialog', { name: 'Delete custom data' }).getByRole('button', { name: 'Delete' }).click(); await expect(row(page, 'Sentiment')).toHaveCount(0);
});

test('recognize MQ4 and save/load JSON with overwrite conflict', async ({ page }) => {
  await launch(page); const actions = page.getByLabel('External indicator operations'); await actions.getByRole('button', { name: 'Recognize from file', exact: true }).click(); let dialog = page.getByRole('dialog', { name: 'Recognize from file', exact: true });
  const mq4 = '#property indicator_buffers 2\n#property indicator_label1 "Upper"\n#property indicator_label2 "Lower"\nSetIndexBuffer(0,UpperBuffer);\nSetIndexBuffer(1,LowerBuffer);'; await dialog.getByLabel('MQ4 file').setInputFiles({ name: 'Bands.mq4', mimeType: 'text/plain', buffer: Buffer.from(mq4) }); await expect(dialog.getByLabel('Output lines')).toHaveValue('Upper, Lower'); await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await row(page, 'Bands').getByRole('checkbox').check(); const download = page.waitForEvent('download'); await actions.getByRole('button', { name: 'Save', exact: true }).click(); dialog = page.getByRole('dialog', { name: 'Save external indicators' }); await dialog.getByRole('button', { name: 'Download JSON' }).click(); expect((await download).suggestedFilename()).toBe('ExternalIndicators.json');
  await actions.getByRole('button', { name: 'Load', exact: true }).click(); dialog = page.getByRole('dialog', { name: 'Load external indicators' }); const json = JSON.stringify({version:1,kind:'external-indicators',indicators:[{name:'Bands',type:10,values:[{name:'Signal',mt4:'',mt5:'',el:''},{name:'',mt4:'',mt5:'',el:''},{name:'',mt4:'',mt5:'',el:''}]}]}); await dialog.getByLabel('ExternalIndicators JSON file').setInputFiles({ name: 'ExternalIndicators.json', mimeType: 'application/json', buffer: Buffer.from(json) }); await dialog.getByRole('button', { name: 'Validate and load' }).click(); dialog = page.getByRole('dialog', { name: 'Overwrite confirm' }); await expect(dialog).toContainText("Indicator 'Bands' already exists"); await dialog.getByRole('button', { name: 'Overwrite' }).click(); await expect(row(page, 'Bands')).toContainText('Signal - 0 means false');
  await page.getByLabel('Filter external indicators').fill('missing'); await expect(page.getByText('No External indicators defined.')).toBeVisible(); await page.getByLabel('Filter external indicators').fill(''); await page.getByLabel('External indicator data type').selectOption('10'); await expect(row(page, 'Bands')).toBeVisible();
});

test('validation and corrupt storage fail closed', async ({ page }) => {
  await launch(page); await page.getByLabel('External indicator operations').getByRole('button', { name: 'Add new' }).click(); let dialog = page.getByRole('dialog', { name: 'Add external indicators' }); await dialog.getByLabel('Name', { exact: true }).fill('Bad'); await dialog.getByLabel('Value 1 name').fill('bad value'); await dialog.getByRole('button', { name: 'Save' }).click(); await expect(dialog.getByRole('alert')).toContainText('special characters');
  await page.evaluate(() => localStorage.setItem('haru-external-indicators-v1', '{bad')); await page.reload(); await page.getByRole('button', { name: 'External indicators', exact: true }).click(); await page.getByLabel('External indicator operations').getByRole('button', { name: 'Add new' }).click(); await expect(page.getByRole('dialog', { name: 'Add external indicators' }).getByRole('alert')).toContainText('could not be read');
});
