import { expect, test, type Page } from '@playwright/test';
import { selectLightSkin } from './shellTestUtils';
async function open(page: Page) {
  await page.goto('/');
  await page.getByRole('button', { name: 'Data Manager', exact: true }).click();
  await page.getByRole('button', { name: 'Dukascopy data', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Add new Dukascopy symbol', exact: true }).click();
  return page.getByRole('dialog', { name: 'Add Dukascopy data', exact: true });
}
test('catalogue controls, validation, save and reload remain offline', async ({ page }) => {
  await page.route('**/*', route => ['127.0.0.1', 'localhost'].includes(new URL(route.request().url()).hostname) ? route.continue() : route.abort());
  const dialog = await open(page);
  await expect(dialog.getByRole('checkbox', { name: /^Select symbol / })).toHaveCount(725);
  await expect(dialog.getByRole('radio', { name: 'Tick data', exact: true })).toBeChecked();
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(dialog.getByRole('alert')).toHaveText('No symbols selected');
  await page.screenshot({ path: 'test-results/dukascopy-popup.png' });
  await dialog.getByLabel('Show types').selectOption('Forex - Majors');
  await dialog.getByRole('checkbox', { name: 'Select Forex - Majors', exact: true }).check();
  await expect(dialog.getByRole('checkbox', { name: 'Select all available symbols' })).toBeChecked();
  await dialog.getByLabel('Filter available symbols').fill('AUD');
  await expect(dialog.getByRole('checkbox', { name: /^Select symbol / })).toHaveCount(1);
  await dialog.getByRole('checkbox', { name: 'Select symbol AUDUSD', exact: true }).check();
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('I confirm');
  await dialog.getByRole('switch').check();
  await dialog.getByRole('radio', { name: 'M1 data', exact: true }).check();
  await dialog.getByLabel('Data postfix').fill('_TEST');
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  let row = page.getByRole('table', { name: 'Historical data' }).getByRole('row').filter({ hasText: 'AUDUSD_TEST' });
  await expect(row).toContainText('Default');
  await expect(row).toContainText('M1');
  await expect(row.getByRole('cell').nth(10)).toHaveText('0');
  await page.reload();
  row = page.getByRole('table', { name: 'Historical data' }).getByRole('row').filter({ hasText: 'AUDUSD_TEST' });
  await expect(row).toHaveCount(1);
  await page.getByRole('button', { name: 'Dukascopy data', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Add new Dukascopy symbol', exact: true }).click();
  await expect(dialog.getByRole('switch')).not.toBeChecked();
  await dialog.getByLabel('Filter available symbols').fill('no-such-symbol');
  await expect(dialog.getByText('No Dukascopy symbols available.')).toBeVisible();
  await dialog.getByRole('button', { name: 'Close', exact: true }).last().click();
  await expect(page.getByRole('button', { name: 'Dukascopy data', exact: true })).toBeFocused();
});
test('broker mapping validates unresolved and skipped symbols', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('sqx-data-manager-v1', JSON.stringify({ version: 1, definitions: [], brokers: [{ id: 'test', name: 'Test broker', postfix: '_B', timezone: 'Europe/Prague', mtUse: true, instruments: [] }] })));
  const dialog = await open(page);
  await dialog.getByLabel('Filter available symbols').fill('AUDUSD');
  await dialog.getByRole('checkbox', { name: 'Select symbol AUDUSD', exact: true }).check();
  await dialog.getByLabel('Broker profile *', { exact: true }).selectOption('test');
  await expect(dialog.getByLabel('Data postfix')).toHaveValue('_B');
  await dialog.getByRole('switch').check();
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  const mapping = page.getByRole('dialog', { name: 'Add Dukascopy data - identify instruments', exact: true });
  await mapping.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(mapping.getByRole('alert')).toContainText('Select proper instrument');
  await mapping.getByRole('button', { name: 'Skip adding the symbol', exact: true }).click();
  await mapping.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(mapping.getByRole('alert')).toHaveText('No symbols selected');
  await mapping.getByLabel('Instrument for AUDUSD').selectOption('-1');
  await mapping.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('table', { name: 'Historical data' })).toContainText('AUDUSD_B');
});
test('duplicate and storage failures retain the dialog without additions', async ({ page }) => {
  const dialog = await open(page);
  await dialog.getByLabel('Filter available symbols').fill('EURUSD');
  await dialog.getByRole('checkbox', { name: 'Select symbol EURUSD', exact: true }).check();
  await dialog.getByRole('switch').check();
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('already exists');
  await dialog.getByLabel('Data postfix').fill('_FAIL');
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new Error('quota'); }; });
  await dialog.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('No symbols were added');
  await dialog.getByRole('button', { name: 'Close', exact: true }).first().click();
  await expect(page.getByRole('table', { name: 'Historical data' })).not.toContainText('EURUSD_FAIL');
});
test('popup layout fits desktop and smaller viewports with keyboard closure', async ({ page }) => {
  await page.setViewportSize({ width: 1569, height: 1000 });
  const dialog = await open(page);
  await page.screenshot({ path: 'test-results/dukascopy-desktop.png' });
  await expect(dialog.getByRole('button', { name: 'Close', exact: true }).first()).toBeFocused();
  await page.keyboard.press('Shift+Tab');
  await expect(dialog.getByRole('button', { name: 'Save', exact: true })).toBeFocused();
  await page.setViewportSize({ width: 740, height: 650 });
  await expect(dialog.getByRole('button', { name: 'Save', exact: true })).toBeInViewport();
  await expect(dialog.getByRole('switch')).toBeInViewport();
  await page.screenshot({ path: 'test-results/dukascopy-small.png' });
  await page.keyboard.press('Escape');
  await expect(dialog).toHaveCount(0);
});
test('popup follows HaruQuantAI dark and light themes', async ({ page }) => {
  const dialog = await open(page);
  const font = await page.locator('.app-shell').evaluate(node => getComputedStyle(node).fontFamily);
  await expect(dialog).toHaveCSS('font-family', font);
  const darkBackground = await dialog.evaluate(node => getComputedStyle(node).backgroundColor);
  await expect(dialog).toHaveCSS('background-color', 'rgb(32, 37, 45)');
  await dialog.getByRole('button', { name: 'Close', exact: true }).first().click();
  await selectLightSkin(page);
  await page.getByRole('button', { name: 'Dukascopy data', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Add new Dukascopy symbol', exact: true }).click();
  await expect(dialog).toHaveCSS('background-color', 'rgb(255, 255, 255)');
  expect(await dialog.evaluate(node => getComputedStyle(node).backgroundColor)).not.toBe(darkBackground);
  await expect(dialog).toHaveCSS('font-family', font);
  await page.screenshot({ path: 'test-results/dukascopy-light.png' });
});
