import {expect,test,type Page} from '@playwright/test';
async function launch(page:Page){await page.goto('/');await page.getByRole('button',{name:'Data Manager',exact:true}).click();await page.getByRole('button',{name:'Broker profiles',exact:true}).click();}
function brokerRow(page:Page,name:string){return page.getByRole('table',{name:'Broker profiles',exact:true}).getByRole('row').filter({has:page.getByRole('checkbox',{name:`Select broker ${name}`,exact:true})});}

test('adds, edits stocks, updates, persists, exports and removes a broker',async({page})=>{test.setTimeout(45_000);await launch(page);const actions=page.getByLabel('Broker profile operations');await actions.getByRole('button',{name:'Edit stocks',exact:true}).click();await expect(page.getByLabel('Data Manager progress')).toContainText('You have to select some broker.');
  await actions.getByRole('button',{name:'Add new',exact:true}).click();let dialog=page.getByRole('dialog',{name:'Add Broker profile',exact:true});const description=dialog.getByLabel('Broker description');const timezone=dialog.getByLabel('Broker timezone');const nameBox=await dialog.getByLabel('Broker profile name').boundingBox();const descriptionBox=await description.boundingBox();expect(nameBox).not.toBeNull();expect(descriptionBox).not.toBeNull();expect(descriptionBox!.width).toBeGreaterThanOrEqual(nameBox!.width-2);const dialogBackground=await dialog.evaluate(element=>getComputedStyle(element).backgroundColor);const descriptionBackground=await description.evaluate(element=>getComputedStyle(element).backgroundColor);const timezoneBackground=await timezone.evaluate(element=>getComputedStyle(element).backgroundColor);const optionBackground=await timezone.locator('option').first().evaluate(element=>getComputedStyle(element).backgroundColor);expect(descriptionBackground).not.toBe(dialogBackground);expect(timezoneBackground).toBe(descriptionBackground);expect(optionBackground).toBe(descriptionBackground);await dialog.getByLabel('Broker profile name').fill('Demo');await description.fill('Demo broker');await dialog.getByLabel('Instrument data postfix').fill('_demo');await dialog.getByRole('button',{name:'Save',exact:true}).click();let row=brokerRow(page,'[Demo]');await expect(row).toContainText('Demo broker');await row.getByRole('checkbox').check();
  await actions.getByRole('button',{name:'Edit stocks',exact:true}).click();dialog=page.getByRole('dialog',{name:'Edit stocks [Demo]',exact:true});await dialog.getByRole('textbox',{name:'Broker stocks',exact:true}).fill('AAPL\nTSLA;ignored');await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(row).toContainText('2');
  await actions.getByRole('button',{name:'Update data for broker (automatic)',exact:true}).click();await expect(page.getByLabel('Data Manager progress')).toContainText('Broker data update running');await page.getByLabel('Data Manager progress').getByRole('button',{name:'Pause all',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Broker profiles',exact:true}).click();await expect(page.getByLabel('Data Manager progress')).toContainText('paused');await page.getByLabel('Data Manager progress').getByRole('button',{name:'Resume all',exact:true}).click();await expect(page.getByLabel('Data Manager progress')).toContainText('completed 100%',{timeout:15_000});
  row=brokerRow(page,'[Demo]');await row.getByRole('checkbox').check();const download=page.waitForEvent('download');await actions.getByRole('button',{name:'Save',exact:true}).click();expect((await download).suggestedFilename()).toBe('Brokers.json');await actions.getByRole('button',{name:'Mass delete',exact:true}).click();dialog=page.getByRole('dialog',{name:'Remove broker',exact:true});await expect(dialog).toContainText('selected brokers (1)');await dialog.getByRole('button',{name:'Yes',exact:true}).click();await expect(row).toHaveCount(0);
});

test('loads brokers with overwrite confirmation and imports selected sessions',async({page})=>{await launch(page);const actions=page.getByLabel('Broker profile operations');await actions.getByRole('button',{name:'Load',exact:true}).click();let dialog=page.getByRole('dialog',{name:'Load brokers',exact:true});const json=JSON.stringify({version:1,kind:'brokers',brokers:[{name:'[Imported]',desc:'Loaded',postfix:'_x',timezone:'UTC',mtUse:true,stockPickerUse:true,stocks:['AAPL']}]});await dialog.getByLabel('Brokers JSON file').setInputFiles({name:'Brokers.json',mimeType:'application/json',buffer:Buffer.from(json)});await dialog.getByRole('button',{name:'Validate and load',exact:true}).click();const row=brokerRow(page,'[Imported]');await expect(row).toContainText('Loaded');
  await actions.getByRole('button',{name:'Load',exact:true}).click();dialog=page.getByRole('dialog',{name:'Load brokers',exact:true});await dialog.getByLabel('Brokers JSON file').setInputFiles({name:'Brokers.json',mimeType:'application/json',buffer:Buffer.from(json.replace('Loaded','Overwritten'))});await dialog.getByRole('button',{name:'Validate and load',exact:true}).click();let confirm=page.getByRole('dialog',{name:'Overwrite confirm',exact:true});await expect(confirm).toContainText("Broker '[Imported]' already exists");await confirm.getByRole('button',{name:'Overwrite',exact:true}).click();await expect(row).toContainText('Overwritten');
  await actions.getByRole('button',{name:'Import broker sessions from JSON',exact:true}).click();dialog=page.getByRole('dialog',{name:'Session import from JSON',exact:true});const sessions=JSON.stringify({version:1,kind:'sessions',sessions:[{name:'Week',broker:'-1',brokerName:'Default',elements:[{dayFrom:'Mon',timeFrom:'00:00',dayTo:'Tue',timeTo:'00:00',eod:true}]}]});await dialog.getByLabel('session JSON file').setInputFiles({name:'Sessions.json',mimeType:'application/json',buffer:Buffer.from(sessions)});await dialog.getByRole('checkbox',{name:'Select Week',exact:true}).check();await dialog.getByLabel('Import broker profile').selectOption({label:'[Imported]'});await dialog.getByRole('button',{name:'Start Import',exact:true}).click();await page.getByRole('button',{name:'Sessions',exact:true}).click();await expect(page.getByRole('table',{name:'Sessions',exact:true})).toContainText('Week_x');
  await page.getByRole('button',{name:'Broker profiles',exact:true}).click();await actions.getByRole('button',{name:'Import broker instruments from JSON',exact:true}).click();dialog=page.getByRole('dialog',{name:'Instruments import from JSON',exact:true});const instrument=JSON.stringify({version:1,kind:'instruments',brokers:[],instruments:[{symbol:'TEST',name:'Test instrument',broker:'-1',brokerName:'Default',type:'Forex',pointValue:100000,tickSize:.0001,tickStep:.00001,spread:1,slippage:0,minDistance:0,multiplier:1,sizeStep:1,timezone:'UTC',commission:{model:'None',value:0,unit:'share',min:.35,minUnit:'money',max:1,maxUnit:'equity'},swap:{use:false,type:'money',long:0,short:0,tripleSwapOn:'WEDNESDAY',rolloutHour:'23:00'}}]});await dialog.getByLabel('instrument JSON file').setInputFiles({name:'Instruments.json',mimeType:'application/json',buffer:Buffer.from(instrument)});await dialog.getByRole('checkbox',{name:'Select TEST',exact:true}).check();await dialog.getByLabel('Import broker profile').selectOption({label:'[Imported]'});await dialog.getByRole('button',{name:'Start Import',exact:true}).click();await page.getByRole('button',{name:'Instruments',exact:true}).click();await expect(page.getByRole('table',{name:'Instruments',exact:true})).toContainText('TEST_x');await page.getByRole('button',{name:'Broker profiles',exact:true}).click();await brokerRow(page,'[Imported]').getByRole('checkbox').check();await actions.getByRole('button',{name:'Mass delete',exact:true}).click();await expect(page.getByLabel('Data Manager progress')).toContainText('not used by any instrument or session');
});
