import { expect, test, type Page } from '@playwright/test';
import { selectLightSkin, setFeatureProfileFixture } from './shellTestUtils';
async function open(page: Page, provider: 'Equity' | 'Futures') {
  await page.getByRole('button', { name: `${provider} data`, exact: true }).click();
  await page.getByRole('menuitem', { name: `Find and add ${provider.toLowerCase()} data`, exact: true }).click();
  return page.getByRole('dialog', { name: `Add ${provider} Data`, exact: true });
}
test.beforeEach(async ({ page }) => { await page.goto('/'); await page.getByRole('button', { name: 'Data Manager', exact: true }).click(); });
test('equity search, conditions, validation, add, pause/reload/resume and row status', async ({ page }) => {
  const dialog = await open(page, 'Equity');
  await expect(dialog.getByRole('button', { name: 'Add', exact: true })).toHaveCount(0);
  await dialog.getByRole('textbox', { name: 'Search text' }).fill('AAPL;Microsoft');
  await dialog.getByRole('button', { name: 'Lookup', exact: true }).click();
  await expect(dialog.getByRole('status')).toHaveText('Found: 2, selected: 0');
  await dialog.getByRole('button', { name: 'Add', exact: true }).click(); await expect(dialog.getByRole('alert')).toContainText('agree');
  await dialog.getByRole('button', { name: 'HaruQuantAI Data Usage Conditions', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'HaruQuantAI Data Usage Conditions' }).first()).toBeVisible();
  await page.keyboard.press('Escape'); await expect(dialog.getByRole('button', { name: 'HaruQuantAI Data Usage Conditions', exact: true })).toBeFocused();
  await dialog.getByRole('checkbox', { name: 'I confirm' }).check();
  await dialog.getByRole('checkbox', { name: 'Select all available tickers' }).check();
  await dialog.getByRole('textbox', { name: 'Name postfix' }).fill('_sq');
  await dialog.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Pause all', exact: true }).click(); await page.reload();
  await expect(page.getByRole('button', { name: 'Resume all', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Resume all', exact: true }).click();
  await expect(page.getByLabel('Status for AAPL_sq', { exact: true })).toHaveText('Completed', { timeout: 10000 });
  await expect(page.getByLabel('Status for MSFT_sq', { exact: true })).toHaveText('Completed');
  const row = page.getByRole('row').filter({ has: page.getByRole('checkbox', { name: 'Select AAPL_sq', exact: true }) });
  await expect(row).toContainText('End of bar'); await expect(row).toContainText('America/New_York');
  await page.reload(); await expect(page.getByLabel('Status for AAPL_sq', { exact: true })).toHaveText('Completed');
});
test('futures continuous filter, duplicate rejection, fixed shift and cancellation', async ({ page }) => {
  const dialog = await open(page, 'Futures');
  await dialog.getByRole('textbox', { name: 'Search text' }).fill('NQ');
  await dialog.getByRole('checkbox', { name: 'Only continuous futures' }).uncheck();
  await dialog.getByRole('button', { name: 'Lookup', exact: true }).click();
  await expect(dialog.getByRole('status')).toHaveText('Found: 2, selected: 0');
  await dialog.getByRole('checkbox', { name: 'Select ticker NQ', exact: true }).check();
  await dialog.getByRole('checkbox', { name: 'I confirm' }).check();
  await dialog.getByRole('button', { name: 'Add', exact: true }).click(); await expect(dialog.getByRole('alert')).toContainText('exists');
  await dialog.getByRole('textbox', { name: 'Name postfix' }).fill('_sq');
  await dialog.getByRole('radio', { name: 'add fixed shift' }).check();
  await dialog.getByRole('spinbutton', { name: 'Fixed shift hours' }).fill('24');
  await dialog.getByRole('button', { name: 'Add', exact: true }).click(); await expect(dialog.getByRole('alert')).toContainText('integer');
  await dialog.getByRole('spinbutton', { name: 'Fixed shift hours' }).fill('-2');
  await dialog.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Stop all', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: 'Select NQ_sq', exact: true })).toHaveCount(0);
});
test('empty results, disabled exact field and search again preserve draft', async ({ page }) => {
  const dialog = await open(page, 'Equity');
  await dialog.getByRole('checkbox', { name: 'Search in ticker', exact: true }).uncheck();
  await expect(dialog.getByRole('checkbox', { name: 'Exact match' })).toBeDisabled();
  await dialog.getByRole('textbox', { name: 'Search text' }).fill('not-a-symbol');
  await dialog.getByRole('button', { name: 'Lookup', exact: true }).click();
  await expect(dialog.getByText('No tickers found.')).toBeVisible();
  await expect(dialog.getByRole('button', { name: 'Add', exact: true })).toHaveCount(0);
  await dialog.getByRole('button', { name: '< Search again' }).click();
  await expect(dialog.getByRole('textbox', { name: 'Search text' })).toHaveValue('not-a-symbol');
});
test('Starter eligibility, theme, narrow layout and keyboard focus', async ({ page }) => {
  await setFeatureProfileFixture(page, 'Starter');
  await selectLightSkin(page);
  const dialog = await open(page, 'Equity');
  await expect(dialog.getByText('Data available without subscription:', { exact: false })).toBeVisible();
  await dialog.getByRole('textbox', { name: 'Search text' }).fill('AAPL,AMZN');
  await dialog.getByRole('button', { name: 'Lookup', exact: true }).click();
  await expect(dialog.getByRole('checkbox', { name: 'Select ticker AMZN' })).toBeDisabled();
  await dialog.getByRole('checkbox', { name: 'Select all available tickers' }).check();
  await expect(dialog.getByRole('status')).toHaveText('Found: 2, selected: 1');
  await dialog.getByRole('radio', { name: 'choose timezone' }).check();
  await dialog.getByRole('combobox', { name: 'Data timezone' }).selectOption('UTC');
  await page.screenshot({ path: 'test-results/sq-equity-light.png' });
  await page.setViewportSize({ width: 520, height: 700 });
  const bounds = await dialog.boundingBox(); expect(bounds!.x).toBeGreaterThanOrEqual(0); expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(520);
  await expect(dialog.getByRole('button', { name: 'Add', exact: true })).toBeInViewport();
  await dialog.getByRole('button', { name: 'Add', exact: true }).focus(); await page.keyboard.press('Tab');
  await expect(dialog.getByRole('button', { name: 'Close', exact: true }).first()).toBeFocused();
  await page.screenshot({ path: 'test-results/sq-equity-narrow.png' });
});
test('futures adds timezone metadata, guards other jobs and stays offline', async ({ page }) => {
  const requests: string[] = []; page.on('request', request => { if (!request.url().startsWith('http://127.0.0.1:4173') && new URL(request.url()).hostname !== 'gc.kis.v2.scr.kaspersky-labs.com') requests.push(request.url()); });
  const dialog = await open(page, 'Futures');
  await dialog.getByRole('textbox', { name: 'Search text' }).fill('ES,6E');
  await dialog.getByRole('button', { name: 'Lookup', exact: true }).click();
  await dialog.getByRole('button', { name: /^Ticker/ }).click();
  await expect(dialog.getByRole('columnheader', { name: /^Ticker/ })).toHaveAttribute('aria-sort', 'descending');
  await dialog.getByRole('checkbox', { name: 'Select ticker ES', exact: true }).check();
  await dialog.getByRole('radio', { name: /^Timestamp is start/ }).check();
  await dialog.getByRole('radio', { name: 'choose timezone' }).check();
  await dialog.getByRole('combobox', { name: 'Data timezone' }).selectOption('UTC');
  await dialog.getByRole('checkbox', { name: 'I confirm' }).check();
  await dialog.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Pause all', exact: true }).click();
  await page.getByRole('button', { name: 'Equity data', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Find and add equity data', exact: true }).click();
  await expect(page.getByRole('status', { name: 'Data Manager progress' })).toContainText('Finish or stop');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'Resume all', exact: true }).click();
  await expect(page.getByLabel('Status for ES', { exact: true })).toHaveText('Completed', { timeout: 10000 });
  const row = page.getByRole('row').filter({ has: page.getByRole('checkbox', { name: 'Select ES', exact: true }) });
  await expect(row).toContainText('UTC'); await expect(row).toContainText('Start of bar');
  expect(requests).toEqual([]);
});
