"""Python code generator plugin consuming universal semantic IR.

Cohesive single-file plugin: the exporter's behavior, schema, bounds,
and presentation metadata live in this file. Stable identity:
``exporter.python@1.0.0``. The zero-argument ``plugin()`` factory is
pure and side-effect free — no I/O, no tasks or threads, no environment
reads, no registration — and the plugin is discovered through the host
catalog, never imported by name by the host or other plugins.

The exporter consumes a validated ``SemanticProgram`` (IR schema
version 1) and emits deterministic, formatted Python source plus an
immutable ``FrozenObject`` manifest carrying the target identity, IR
schema version, entry point, input/output keys, and the SHA-256 hash of
the generated source. It knows only the universal ``std.*``
primitives: any unknown operator or unsupported recurrence method is
rejected with a ValueError naming the offending primitive. It has no
knowledge of RSI or any other concrete plugin. Executing the generated
code is a test-only concern.
"""

from __future__ import annotations

import hashlib
from collections.abc import Mapping
from typing import Any, override

from app.plugins.lowering import (
    OP_STD_ABS,
    OP_STD_ADD,
    OP_STD_COND,
    OP_STD_DELTA,
    OP_STD_DIV,
    OP_STD_EQ,
    OP_STD_GT,
    OP_STD_GTE,
    OP_STD_LT,
    OP_STD_LTE,
    OP_STD_MAX,
    OP_STD_MIN,
    OP_STD_MUL,
    OP_STD_NEQ,
    OP_STD_RECURRENCE,
    OP_STD_SUB,
    IRArgument,
    IRNode,
    LoweringContext,
    LoweringResult,
    LoweringTarget,
    SemanticProgram,
    ValueRef,
)
from app.plugins.schema import (
    FrozenObject,
    ParameterBindingResult,
    ParameterSchema,
    PortSpec,
    Unit,
    ValueKind,
)
from app.plugins.spec import (
    CURRENT_METAMODEL_MAJOR,
    OperationBindings,
    OperationContribution,
    OperationImplementation,
    OperationSpec,
    PluginContribution,
    PluginRef,
    PluginSpec,
)

PLUGIN_REF = PluginRef(id="exporter.python", version=(1, 0, 0))
OPERATION_ID = "export"
TARGET_PYTHON = LoweringTarget(target_id="python", version=(1, 0, 0))

INPUT_PROGRAM = PortSpec(
    key="program",
    kind=ValueKind.OBJECT,
    unit=Unit.NONE,
    label="Semantic Program",
    description="Universal SemanticProgram IR to be lowered into Python code",
)

OUTPUT_SOURCE = PortSpec(
    key="source",
    kind=ValueKind.TEXT,
    unit=Unit.NONE,
    label="Python Source",
    description="Generated deterministic Python source code",
)

OUTPUT_MANIFEST = PortSpec(
    key="manifest",
    kind=ValueKind.OBJECT,
    unit=Unit.NONE,
    label="Export Manifest",
    description="Immutable export metadata manifest",
)

EXPORTER_SCHEMA = ParameterSchema()


def _format_literal(val: Any) -> str:
    """Format a literal value as Python source text (repr-based)."""
    if val is None:
        return "None"
    if isinstance(val, bool):
        return "True" if val else "False"
    if isinstance(val, (int, float)):
        return repr(val)
    if isinstance(val, str):
        return repr(val)
    return repr(val)


class PythonCodeGenerator:
    """Deterministic Python code generator for universal SemanticProgram IR.

    The same program always yields byte-identical source: nodes are
    emitted in program order with their stable IR node IDs, and each
    ``std.*`` primitive maps to one fixed code template. Generated
    semantics follow the IR contracts: missing samples propagate
    (resetting state for delta and recurrence nodes), and division by a
    zero denominator yields 0.0.
    """

    def __init__(self, program: SemanticProgram) -> None:
        """Store the validated program to generate code from."""
        self.program = program

    def generate(self) -> tuple[str, FrozenObject]:
        """Generate formatted Python script and export manifest.

        The generated module exposes an ``execute`` entry point that
        takes an inputs mapping and returns the program outputs as
        tuples, embedding its own MissingValue sentinel.

        Returns:
            Tuple of the generated source text and an immutable manifest
            (target id/version, IR schema version, entry point, input
            keys, output keys, and the SHA-256 ``source_hash`` of the
            UTF-8 source).

        Raises:
            ValueError: If a node uses an operator or recurrence method
                this exporter does not support.
        """
        lines: list[str] = [
            '"""Generated by HaruQuantAI Python Exporter."""',
            "",
            "from __future__ import annotations",
            "",
            "import math",
            "from collections.abc import Mapping, Sequence",
            "from typing import Any",
            "",
            "",
            "class MissingValue:",
            '    """Sentinel representing a missing data value."""',
            "",
            '    __slots__ = ("reason",)',
            "",
            '    def __init__(self, reason: str = "MISSING") -> None:',
            "        self.reason = reason",
            "",
            "    def __repr__(self) -> str:",
            '        return f"MissingValue({self.reason!r})"',
            "",
            "    def __eq__(self, other: Any) -> bool:",
            "        return (",
            (
                "            isinstance(other, MissingValue) "
                "and self.reason == other.reason"
            ),
            "        )",
            "",
            "",
            "def _is_missing(val: Any) -> bool:",
            '    return val is None or type(val).__name__ == "MissingValue"',
            "",
            "",
            "def execute(inputs: Mapping[str, Any]) -> dict[str, Any]:",
            '    """Execute the quantitative workflow against provided inputs."""',
            "    # Determine series length from first available input series",
            "    n_samples = 0",
        ]

        # Scan input lengths
        for inp in self.program.inputs:
            lines.append(f'    raw_{inp.key} = inputs.get("{inp.key}", ())')
            lines.append(f"    if raw_{inp.key} is not None:")
            lines.append(f"        n_samples = max(n_samples, len(raw_{inp.key}))")

        lines.extend(
            [
                "    if n_samples == 0:",
                "        return {",
            ]
        )
        lines.extend(f'            "{out.key}": (),' for out in self.program.outputs)
        lines.extend(
            [
                "        }",
                "",
            ]
        )

        # Generate code for each IR node
        for node in self.program.nodes:
            self._emit_node(node, lines)

        # Build output dictionary
        lines.append("    return {")
        for out in self.program.outputs:
            source_var = f"{out.source.node_id}_{out.source.output_key}"
            lines.append(f'        "{out.key}": tuple({source_var}),')
        lines.append("    }")
        lines.append("")

        source_code = "\n".join(lines)
        source_hash = hashlib.sha256(source_code.encode("utf-8")).hexdigest()

        manifest_data: dict[str, Any] = {
            "target_id": "python",
            "target_version": "1.0.0",
            "ir_schema_version": self.program.ir_schema_version,
            "entry_point": "execute",
            "inputs": tuple(inp.key for inp in self.program.inputs),
            "outputs": tuple(out.key for out in self.program.outputs),
            "source_hash": source_hash,
        }
        manifest = FrozenObject.from_mapping(manifest_data)
        return source_code, manifest

    def _arg_ref(self, arg: IRArgument) -> str:
        """Return the Python expression for one IR argument or input."""
        if isinstance(arg, ValueRef):
            # Check if it references a program input
            for inp in self.program.inputs:
                if arg.node_id == inp.key:
                    return f"raw_{inp.key}"
            return f"{arg.node_id}_{arg.output_key}"
        return _format_literal(arg.value)

    def _emit_delta_node(self, node: IRNode, out_var: str, lines: list[str]) -> None:
        """Emit first-difference code with gap reset and warm-up markers."""
        inp_ref = self._arg_ref(node.inputs[0])
        lines.extend(
            [
                f"    # {node.id}: delta of {inp_ref}",
                f"    {out_var} = []",
                f"    _prev_{node.id} = None",
                f"    for _v in {inp_ref}:",
                "        if _is_missing(_v):",
                f'            {out_var}.append(MissingValue("GAP"))',
                f"            _prev_{node.id} = None",
                f"        elif _prev_{node.id} is None:",
                f'            {out_var}.append(MissingValue("WARMUP"))',
                f"            _prev_{node.id} = float(_v)",
                "        else:",
                f"            {out_var}.append(float(_v) - _prev_{node.id})",
                f"            _prev_{node.id} = float(_v)",
                "",
            ]
        )

    def _emit_recurrence_node(
        self, node: IRNode, out_var: str, lines: list[str]
    ) -> None:
        """Emit Wilder recurrence code; reject any other recurrence method."""
        inp_ref = self._arg_ref(node.inputs[0])
        method = node.parameters.get("method", "wilder_smoothing")
        period_val = node.parameters.get("period", 14)
        period = int(period_val) if isinstance(period_val, (int, float, str)) else 14
        if method != "wilder_smoothing":
            raise ValueError(f"Unsupported recurrence method: {method!r}")
        lines.extend(
            [
                f"    # {node.id}: Wilder recurrence (period={period})",
                f"    {out_var} = []",
                f"    _accum_{node.id} = None",
                f"    _seed_buf_{node.id} = []",
                f"    for _v in {inp_ref}:",
                "        if _is_missing(_v):",
                f'            {out_var}.append(MissingValue("GAP"))',
                f"            _accum_{node.id} = None",
                f"            _seed_buf_{node.id}.clear()",
                "        else:",
                "            _val = float(_v)",
                f"            if _accum_{node.id} is None:",
                f"                _seed_buf_{node.id}.append(_val)",
                f"                if len(_seed_buf_{node.id}) < {period}:",
                f'                    {out_var}.append(MissingValue("WARMUP"))',
                "                else:",
                f"                    _accum_{node.id} = (",
                f"                        sum(_seed_buf_{node.id}) / {period}",
                "                    )",
                f"                    {out_var}.append(_accum_{node.id})",
                "            else:",
                f"                _accum_{node.id} = (",
                f"                    _accum_{node.id} * ({period} - 1) + _val",
                f"                ) / {period}",
                f"                {out_var}.append(_accum_{node.id})",
                "",
            ]
        )

    def _emit_binary_node(self, node: IRNode, out_var: str, lines: list[str]) -> None:
        """Emit elementwise binary code; a zero divisor yields 0.0."""
        arg1_ref = self._arg_ref(node.inputs[0])
        arg2_ref = self._arg_ref(node.inputs[1])
        is_arg1_series = isinstance(node.inputs[0], ValueRef)
        is_arg2_series = isinstance(node.inputs[1], ValueRef)

        a_expr = f"{arg1_ref}[_i]" if is_arg1_series else arg1_ref
        b_expr = f"{arg2_ref}[_i]" if is_arg2_series else arg2_ref

        lines.extend(
            [
                f"    # {node.id}: {node.operator}({arg1_ref}, {arg2_ref})",
                f"    {out_var} = []",
                "    for _i in range(n_samples):",
                f"        _a = {a_expr}",
                f"        _b = {b_expr}",
                "        if _is_missing(_a) or _is_missing(_b):",
                f'            {out_var}.append(MissingValue("PROPAGATED"))',
                "        else:",
            ]
        )

        op_map = {
            OP_STD_MAX: f"            {out_var}.append(max(float(_a), float(_b)))",
            OP_STD_MIN: f"            {out_var}.append(min(float(_a), float(_b)))",
            OP_STD_ADD: f"            {out_var}.append(float(_a) + float(_b))",
            OP_STD_SUB: f"            {out_var}.append(float(_a) - float(_b))",
            OP_STD_MUL: f"            {out_var}.append(float(_a) * float(_b))",
            OP_STD_GT: f"            {out_var}.append(bool(float(_a) > float(_b)))",
            OP_STD_LT: f"            {out_var}.append(bool(float(_a) < float(_b)))",
            OP_STD_GTE: f"            {out_var}.append(bool(float(_a) >= float(_b)))",
            OP_STD_LTE: f"            {out_var}.append(bool(float(_a) <= float(_b)))",
            OP_STD_EQ: f"            {out_var}.append(bool(float(_a) == float(_b)))",
            OP_STD_NEQ: f"            {out_var}.append(bool(float(_a) != float(_b)))",
        }
        if node.operator == OP_STD_DIV:
            lines.extend(
                [
                    "            if float(_b) == 0.0:",
                    f"                {out_var}.append(0.0)",
                    "            else:",
                    f"                {out_var}.append(float(_a) / float(_b))",
                ]
            )
        elif node.operator in op_map:
            lines.append(op_map[node.operator])
        lines.append("")

    def _emit_cond_node(self, node: IRNode, out_var: str, lines: list[str]) -> None:
        """Emit conditional-select code propagating a missing condition."""
        c_ref = self._arg_ref(node.inputs[0])
        t_ref = self._arg_ref(node.inputs[1])
        e_ref = self._arg_ref(node.inputs[2])
        is_c_series = isinstance(node.inputs[0], ValueRef)
        is_t_series = isinstance(node.inputs[1], ValueRef)
        is_e_series = isinstance(node.inputs[2], ValueRef)

        c_expr = f"{c_ref}[_i]" if is_c_series else c_ref
        t_expr = f"{t_ref}[_i]" if is_t_series else t_ref
        e_expr = f"{e_ref}[_i]" if is_e_series else e_ref

        lines.extend(
            [
                f"    # {node.id}: cond({c_ref}, {t_ref}, {e_ref})",
                f"    {out_var} = []",
                "    for _i in range(n_samples):",
                f"        _c = {c_expr}",
                f"        _t = {t_expr}",
                f"        _e = {e_expr}",
                "        if _is_missing(_c):",
                f'            {out_var}.append(MissingValue("PROPAGATED"))',
                "        else:",
                f"            {out_var}.append(_t if bool(_c) else _e)",
                "",
            ]
        )

    def _emit_abs_node(self, node: IRNode, out_var: str, lines: list[str]) -> None:
        """Emit elementwise absolute-value code with missing propagation."""
        inp_ref = self._arg_ref(node.inputs[0])
        lines.extend(
            [
                f"    # {node.id}: abs({inp_ref})",
                f"    {out_var} = []",
                f"    for _v in {inp_ref}:",
                "        if _is_missing(_v):",
                f'            {out_var}.append(MissingValue("PROPAGATED"))',
                "        else:",
                f"            {out_var}.append(abs(float(_v)))",
                "",
            ]
        )

    def _emit_node(self, node: IRNode, lines: list[str]) -> None:
        """Dispatch one IR node to its code template.

        Raises:
            ValueError: If the node's operator has no template in this
                exporter.
        """
        out_var = f"{node.id}_{node.outputs[0]}"

        if node.operator == OP_STD_DELTA:
            self._emit_delta_node(node, out_var, lines)
        elif node.operator == OP_STD_RECURRENCE:
            self._emit_recurrence_node(node, out_var, lines)
        elif node.operator in (
            OP_STD_MAX,
            OP_STD_MIN,
            OP_STD_ADD,
            OP_STD_SUB,
            OP_STD_MUL,
            OP_STD_DIV,
            OP_STD_GT,
            OP_STD_LT,
            OP_STD_GTE,
            OP_STD_LTE,
            OP_STD_EQ,
            OP_STD_NEQ,
        ):
            self._emit_binary_node(node, out_var, lines)
        elif node.operator == OP_STD_COND:
            self._emit_cond_node(node, out_var, lines)
        elif node.operator == OP_STD_ABS:
            self._emit_abs_node(node, out_var, lines)
        else:
            raise ValueError(
                f"Unsupported universal semantic operator: {node.operator!r}"
            )


class PythonExporterOperation(OperationImplementation):
    """Operation implementation for lowering SemanticProgram to Python code.

    Consumes an in-memory ``SemanticProgram`` object (not wire data) and
    returns the generated source and manifest. Semantic lowering is
    refused: exporters are terminal targets and do not lower
    recursively.
    """

    @override
    def validate_parameters(self, values: FrozenObject) -> ParameterBindingResult:
        """Validate parameter values against the empty exporter schema.

        Args:
            values: Parameter values mapping.

        Returns:
            Binding result; the exporter declares no parameters.
        """
        return EXPORTER_SCHEMA.validate_bindings(values)

    @override
    def warmup_samples(self, values: FrozenObject) -> int:
        """Return zero; exporting consumes no series samples.

        Args:
            values: Bound parameter values (unused).

        Returns:
            Always zero.
        """
        return 0

    @override
    def execute(
        self,
        inputs: Mapping[str, Any],
        parameters: FrozenObject,
        bindings: OperationBindings,
    ) -> Mapping[str, Any]:
        """Generate Python source and manifest from a SemanticProgram.

        Args:
            inputs: Mapping whose ``program`` value is a
                SemanticProgram.
            parameters: Unused; the exporter declares no parameters.
            bindings: Unused; the exporter requires no capabilities.

        Returns:
            Mapping with the generated ``source`` text and the immutable
            ``manifest``.

        Raises:
            TypeError: If ``program`` is not a SemanticProgram.
            ValueError: If the program contains an unsupported
                primitive.
        """
        program = inputs.get("program")
        if not isinstance(program, SemanticProgram):
            actual_type = type(program).__name__
            raise TypeError(
                f"Input 'program' must be a SemanticProgram, got {actual_type}"
            )
        generator = PythonCodeGenerator(program)
        source, manifest = generator.generate()
        return {"source": source, "manifest": manifest}

    @override
    def lower(
        self,
        context: LoweringContext,
        parameters: FrozenObject,
    ) -> LoweringResult:
        """Refuse semantic lowering for the exporter operation.

        Args:
            context: Unused lowering context.
            parameters: Unused parameter bindings.

        Returns:
            Always a failing LoweringResult with code
            ``CANNOT_LOWER_EXPORTER``.
        """
        from app.plugins.lowering import LoweringIssue

        return LoweringResult(
            success=False,
            issues=(
                LoweringIssue(
                    code="CANNOT_LOWER_EXPORTER",
                    message="Exporters do not support recursive semantic lowering",
                ),
            ),
        )


def plugin() -> PluginContribution:
    """Return the zero-argument pure plugin contribution for exporter.python.

    Builds the self-describing PluginSpec — identity exporter.python
    version 1.0.0, kind ``exporter``, one ``export`` operation — and its
    implementation. Performs no I/O and no registration; discovery
    happens through the host catalog.

    Returns:
        Immutable PluginContribution for exporter.python@1.0.0.
    """
    op_spec = OperationSpec(
        operation_id=OPERATION_ID,
        title="Export Python Source",
        description=(
            "Emit deterministic Python source code and manifest from SemanticProgram"
        ),
        parameters=EXPORTER_SCHEMA,
        inputs=(INPUT_PROGRAM,),
        outputs=(OUTPUT_SOURCE, OUTPUT_MANIFEST),
        determinism=True,
        effects=("pure",),
    )
    plugin_spec = PluginSpec(
        ref=PLUGIN_REF,
        kind="exporter",
        title="Python Exporter",
        description=(
            "Generates deterministic, executable Python source from SemanticProgram"
        ),
        metamodel_major=CURRENT_METAMODEL_MAJOR,
        operations=(op_spec,),
    )
    return PluginContribution(
        spec=plugin_spec,
        operations=(OperationContribution(OPERATION_ID, PythonExporterOperation()),),
    )
