import type { BuildingBlockItem } from '../../app/types';

export const BUILDING_BLOCKS_CATALOG: BuildingBlockItem[] = [
  // Signals (Predefined Conditions)
  {
    id: 'sig_ma_cross',
    name: 'Price Crosses MA',
    category: 'signals',
    description: 'Entry when price crosses above (Long) or below (Short) a Moving Average.',
    enabled: true,
    defaultParams: { period: 20, type: 'EMA' },
  },
  {
    id: 'sig_rsi_bounds',
    name: 'RSI Oversold / Overbought',
    category: 'signals',
    description: 'Signals trigger when RSI crosses below 30 or above 70 threshold.',
    enabled: true,
    defaultParams: { period: 14, lower: 30, upper: 70 },
  },
  {
    id: 'sig_macd_zero',
    name: 'MACD Zero Line Cross',
    category: 'signals',
    description: 'MACD histogram or main line crosses above / below zero level.',
    enabled: true,
    defaultParams: { fast: 12, slow: 26, signal: 9 },
  },
  {
    id: 'sig_bollinger_break',
    name: 'Bollinger Bands Breakout',
    category: 'signals',
    description: 'Price breaks outside the outer Bollinger Band bands.',
    enabled: true,
    defaultParams: { period: 20, deviation: 2.0 },
  },
  {
    id: 'sig_stoch_cross',
    name: 'Stochastic %K Crosses %D',
    category: 'signals',
    description: 'Fast %K crosses Slow %D in oversold / overbought zones.',
    enabled: true,
    defaultParams: { kPeriod: 14, dPeriod: 3, slowing: 3 },
  },
  {
    id: 'sig_channel_break',
    name: 'Highest / Lowest Channel Breakout',
    category: 'signals',
    description: 'Close is higher than Highest High (N) or lower than Lowest Low (N).',
    enabled: true,
    defaultParams: { bars: 20 },
  },
  {
    id: 'sig_atr_breakout',
    name: 'ATR Volatility Expansion',
    category: 'signals',
    description: 'Current bar range exceeds N multiples of Average True Range.',
    enabled: false,
    defaultParams: { period: 14, multiplier: 1.5 },
  },
  {
    id: 'sig_cci_threshold',
    name: 'CCI Crosses +/- 100',
    category: 'signals',
    description: 'Commodity Channel Index crosses above -100 or below +100.',
    enabled: false,
    defaultParams: { period: 14 },
  },

  // Indicators
  {
    id: 'ind_sma',
    name: 'Simple Moving Average (SMA)',
    category: 'indicators',
    description: 'Arithmetic mean of closing prices over N periods.',
    enabled: true,
    defaultParams: { period: 50 },
  },
  {
    id: 'ind_ema',
    name: 'Exponential Moving Average (EMA)',
    category: 'indicators',
    description: 'Weighted moving average giving higher priority to recent prices.',
    enabled: true,
    defaultParams: { period: 20 },
  },
  {
    id: 'ind_smma',
    name: 'Smoothed Moving Average (SMMA)',
    category: 'indicators',
    description: 'Blended exponential smoothing over longer lookback periods.',
    enabled: true,
    defaultParams: { period: 30 },
  },
  {
    id: 'ind_lwma',
    name: 'Linear Weighted MA (LWMA)',
    category: 'indicators',
    description: 'Linear weights scaling linearly with candle index.',
    enabled: false,
    defaultParams: { period: 25 },
  },
  {
    id: 'ind_rsi',
    name: 'Relative Strength Index (RSI)',
    category: 'indicators',
    description: 'Momentum oscillator measuring velocity and magnitude of price changes.',
    enabled: true,
    defaultParams: { period: 14 },
  },
  {
    id: 'ind_cci',
    name: 'Commodity Channel Index (CCI)',
    category: 'indicators',
    description: 'Measures variation from statistical mean price.',
    enabled: true,
    defaultParams: { period: 20 },
  },
  {
    id: 'ind_atr',
    name: 'Average True Range (ATR)',
    category: 'indicators',
    description: 'Volatility indicator derived from highest of H-L, H-Cp, L-Cp.',
    enabled: true,
    defaultParams: { period: 14 },
  },
  {
    id: 'ind_bollinger',
    name: 'Bollinger Bands',
    category: 'indicators',
    description: 'Volatility envelope centered around SMA with standard deviations.',
    enabled: true,
    defaultParams: { period: 20, deviation: 2.0 },
  },
  {
    id: 'ind_stoch',
    name: 'Stochastic Oscillator',
    category: 'indicators',
    description: 'Location of close relative to high-low range over lookback window.',
    enabled: true,
    defaultParams: { k: 14, d: 3 },
  },
  {
    id: 'ind_macd',
    name: 'MACD',
    category: 'indicators',
    description: 'Moving Average Convergence / Divergence trend following indicator.',
    enabled: true,
    defaultParams: { fast: 12, slow: 26, signal: 9 },
  },
  {
    id: 'ind_momentum',
    name: 'Momentum',
    category: 'indicators',
    description: 'Rate of acceleration of price movement over N bars.',
    enabled: true,
    defaultParams: { period: 14 },
  },
  {
    id: 'ind_williams_r',
    name: 'Williams %R',
    category: 'indicators',
    description: 'Negative scale momentum oscillator measuring overbought levels.',
    enabled: false,
    defaultParams: { period: 14 },
  },
  {
    id: 'ind_parabolic_sar',
    name: 'Parabolic SAR',
    category: 'indicators',
    description: 'Stop and reverse tracking trailing stop level.',
    enabled: false,
    defaultParams: { step: 0.02, max: 0.2 },
  },
  {
    id: 'ind_adx',
    name: 'ADX (Average Directional Index)',
    category: 'indicators',
    description: 'Trend strength indicator without regard to direction.',
    enabled: true,
    defaultParams: { period: 14 },
  },

  // Candlestick Patterns
  {
    id: 'cnd_hammer',
    name: 'Hammer & Inverted Hammer',
    category: 'candles',
    description: 'Single bar reversal formation with long lower shadow.',
    enabled: true,
  },
  {
    id: 'cnd_engulfing',
    name: 'Bullish & Bearish Engulfing',
    category: 'candles',
    description: 'Two-candle pattern where body completely engulfs prior candle.',
    enabled: true,
  },
  {
    id: 'cnd_morning_star',
    name: 'Morning & Evening Star',
    category: 'candles',
    description: 'Three-candle reversal pattern marking trend exhaustion.',
    enabled: false,
  },
  {
    id: 'cnd_shooting_star',
    name: 'Shooting Star',
    category: 'candles',
    description: 'Bearish reversal candle with long upper shadow following rally.',
    enabled: true,
  },
  {
    id: 'cnd_doji',
    name: 'Doji / Neutral Candlestick',
    category: 'candles',
    description: 'Indecision bar where open and close are virtually identical.',
    enabled: false,
  },

  // Time & Session Filters
  {
    id: 'time_day_of_week',
    name: 'Day of Week Filter',
    category: 'time',
    description: 'Restricts trading to designated weekdays (Mon - Fri).',
    enabled: true,
  },
  {
    id: 'time_session_hours',
    name: 'Session Time Range',
    category: 'time',
    description: 'Restricts trade entries to specific hours of day (e.g. 08:00 - 17:00).',
    enabled: true,
  },
  {
    id: 'time_month_filter',
    name: 'Month of Year Filter',
    category: 'time',
    description: 'Allows or blocks trades during specific calendar months.',
    enabled: false,
  },
  {
    id: 'time_bar_of_day',
    name: 'Bar Index of Day',
    category: 'time',
    description: 'Enters trades only during first N or last N bars of day.',
    enabled: false,
  },

  // Order Types
  {
    id: 'ord_market',
    name: 'Market Order',
    category: 'orders',
    description: 'Enters immediately at current market open/close price.',
    enabled: true,
  },
  {
    id: 'ord_stop',
    name: 'Stop Order',
    category: 'orders',
    description: 'Enters on breakout above/below specified trigger price.',
    enabled: true,
  },
  {
    id: 'ord_limit',
    name: 'Limit Order',
    category: 'orders',
    description: 'Enters on pullback at or better than specified limit price.',
    enabled: true,
  },

  // Exit Rules
  {
    id: 'exit_stop_loss',
    name: 'Stop Loss',
    category: 'exits',
    description: 'Mandatory protective stop order (Fixed pips, ATR multiple, or %).',
    enabled: true,
  },
  {
    id: 'exit_profit_target',
    name: 'Profit Target',
    category: 'exits',
    description: 'Take-profit order locking in gains at designated target.',
    enabled: true,
  },
  {
    id: 'exit_trailing_stop',
    name: 'Trailing Stop',
    category: 'exits',
    description: 'Dynamic stop following favorable price movement.',
    enabled: true,
  },
  {
    id: 'exit_break_even',
    name: 'Move SL to Break-Even',
    category: 'exits',
    description: 'Advances stop loss to entry price after specified profit threshold.',
    enabled: true,
  },
  {
    id: 'exit_n_bars',
    name: 'Exit After N Bars',
    category: 'exits',
    description: 'Closes trade unconditionally if holding exceeds N periods.',
    enabled: false,
  },
  {
    id: 'exit_reverse_signal',
    name: 'Exit on Reverse Signal',
    category: 'exits',
    description: 'Exits current position when an opposite directional signal fires.',
    enabled: true,
  },
  {
    id: 'exit_friday_close',
    name: 'Friday End-of-Week Close',
    category: 'exits',
    description: 'Closes all open positions before weekend market closure.',
    enabled: true,
  },
];
