"""FX currency exposure package."""

from app.services.risk.exposure.aggregation import (
    ClusterExposureEngine,
    CurrencyExposureEngine,
    ExposureSnapshotBuilder,
    SymbolExposureEngine,
    _resolve_base_quote,
    _resolve_conversion_rate,
    aggregate_currency_legs,
    calculate_currency_exposure,
    calculate_currency_leg_exposure,
    calculate_gross_and_net_exposure,
    calculate_net_currency_exposure,
    calculate_projected_exposure,
    calculate_symbol_exposure,
    decompose_position,
    detect_hidden_concentration,
    enforce_currency_rounding,
)
from app.services.risk.exposure.fx_legs import (
    ContractSpecification,
    FxPair,
    decompose_fx_trade,
    parse_fx_symbol,
    validate_currency_conversion_requirements,
)

__all__ = [
    "ClusterExposureEngine",
    "ContractSpecification",
    "CurrencyExposureEngine",
    "ExposureSnapshotBuilder",
    "FxPair",
    "SymbolExposureEngine",
    "_resolve_base_quote",
    "_resolve_conversion_rate",
    "aggregate_currency_legs",
    "calculate_currency_exposure",
    "calculate_currency_leg_exposure",
    "calculate_gross_and_net_exposure",
    "calculate_net_currency_exposure",
    "calculate_projected_exposure",
    "calculate_symbol_exposure",
    "decompose_fx_trade",
    "decompose_position",
    "detect_hidden_concentration",
    "enforce_currency_rounding",
    "parse_fx_symbol",
    "validate_currency_conversion_requirements",
]
