"""
Utility helpers and approved utility tools exposed by the HaruQuant utils package.

This package intentionally exposes both:
    - normal production utility helpers, such as ``logger`` and result builders;
    - approved AI-callable utility tools, such as multiprocessing logger tools.

Official AI Tools:
    - init_worker_logger
    - configure_multiprocess_listener
    - load_runtime_settings
    - load_runtime_settings_from_mapping
    - inject_runtime_settings

Utility Helpers:
    - configuration loading
    - logger
    - Logger
    - StructlogAdapter
    - success_result
    - error_result
    - blocked_result
    - needs_approval_result
    - needs_clarification_result
    - shared exception and error taxonomy helpers
    - trace ID generation and validation helpers
"""

# config.py utility helpers
from tools.utils.config import (
    DEFAULT_APP_NAME,
    DEFAULT_ENV_DIR,
    DEFAULT_ENV_FILE,
    DEFAULT_ENV_PREFIX,
    DEFAULT_ENVIRONMENT,
    DEFAULT_LOG_LEVEL,
    DEFAULT_RUNTIME_ENVIRONMENT,
    VALID_ENVIRONMENTS,
    VALID_LOG_LEVELS,
    RuntimeSettings,
    Settings,
    SettingsError,
    collect_prefixed_values,
    get_environment,
    get_settings,
    inject_runtime_settings,
    is_production,
    is_test,
    load_runtime_settings,
    load_runtime_settings_from_mapping,
    normalize_environment,
    normalize_log_level,
    normalize_mapping,
    parse_env_file,
)

# errors.py utility helpers
from tools.utils.errors import (
    MT5_MESSAGES,
    RETCODE_EXCEPTION_TYPES,
    RETCODE_INFO,
    SUCCESS_RETCODES,
    UNKNOWN_ERROR_CODE,
    BrokerError,
    ConfigurationError,
    DescriptorDict,
    DomainError,
    ErrorContext,
    ErrorDescriptor,
    ErrorEnvelope,
    ErrorInfo,
    ErrorPayload,
    HaruError,
    HaruQuantError,
    InfrastructureError,
    InvalidPriceError,
    InvalidRequestError,
    InvalidStopsError,
    InvalidVolumeError,
    MarketClosedError,
    NoMoneyError,
    NoQuotesError,
    PolicyError,
    TradeDisabledError,
    TradeError,
    ValidationError,
    descriptor_from_payload,
    descriptor_to_dict,
    error_from_retcode,
    error_info_to_dict,
    error_name,
    exception_from_descriptor,
    is_success_retcode,
    message_for,
    raise_for_retcode,
)

# ids.py utility helpers
from tools.utils.ids import (
    ID_SEPARATOR,
    REQUEST_ID_PREFIX,
    RUN_ID_PREFIX,
    TOOL_CALL_ID_PREFIX,
    UUID_HEX_LENGTH,
    VALID_ID_PREFIXES,
    WORKFLOW_ID_PREFIX,
    is_request_id,
    is_run_id,
    is_tool_call_id,
    is_valid_prefixed_id,
    is_workflow_id,
    new_request_id,
    new_run_id,
    new_tool_call_id,
    new_workflow_id,
)

# logger.py utilities and AI tools
from tools.utils.logger import (
    CRITICAL,
    DEBUG,
    DEFAULT_LEVELS,
    ERROR,
    INFO,
    SUCCESS,
    TRACE,
    WARNING,
    CompatRecord,
    Logger,
    StructlogAdapter,
    configure_default_file_sinks,
    configure_multiprocess_listener,
    init_worker_logger,
    logger,
)

# normalization.py utility helpers and AI tools
from tools.utils.normalization import (
    BOARD_BASELINE_TTL_POLICY,
    BoardBaselineArtifactWindow,
    BoardBaselineFreshnessEvaluation,
    FixedClock,
    FreshnessWindow,
    SystemClock,
    board_baseline_evaluation_to_dict,
    board_baseline_window_to_dict,
    ensure_dir,
    ensure_parent_dir,
    evaluate_board_baseline_freshness,
    evaluate_freshness,
    format_timestamp_z,
    freshness_window_to_dict,
    is_stale,
    normalize_path,
    normalize_timestamp,
    normalize_timezone_for_series,
    parse_datetime_value,
    to_naive_utc_datetime,
    to_utc,
    to_utc_datetime,
)

# result.py utility helpers
from tools.utils.result import (
    ERROR_APPROVAL_REQUIRED,
    ERROR_INVALID_INPUT,
    ERROR_MISSING_INPUT,
    ERROR_POLICY_BLOCKED,
    ERROR_UNKNOWN,
    ERROR_VALIDATION_FAILED,
    STATUS_BLOCKED,
    STATUS_ERROR,
    STATUS_NEEDS_APPROVAL,
    STATUS_NEEDS_CLARIFICATION,
    STATUS_SUCCESS,
    VALID_RESULT_STATUSES,
    blocked_result,
    error_result,
    needs_approval_result,
    needs_clarification_result,
    success_result,
)

# security.py utility helpers and AI tools
from tools.utils.security import (
    REDACTED,
    REDACTED_VALUE,
    SENSITIVE_KEYWORDS,
    SecretRef,
    SecretRotationPolicy,
    decrypt_data_value,
    encrypt_data_value,
    generate_encryption_key,
    hash_password_value,
    is_sensitive_key,
    redact_mapping,
    redact_scalar_value,
    redact_text,
    rotation_policy_to_dict,
    secret_ref_to_dict,
    select_active_secret_version,
    verify_password_value,
)

# validators.py utility helpers and AI tools
from tools.utils.validators import (
    ACTIVATOR_COLUMN_DEFAULTS,
    REQUIRED_OHLC_COLUMNS,
    SIGNAL_COLUMN_DEFAULTS,
    apply_warmup_policy,
    assert_dataframe,
    assert_ohlc_dataframe,
    ensure_dataframe,
    ensure_no_signal_columns,
    ensure_signal_columns,
    prepare_ohlcv_data,
    require_columns,
    require_known_warmup_policy,
    require_positive_float,
    require_positive_int,
    serialize_dataframe,
    validate_approval_packet,
    validate_artifact_reference,
    validate_blocked_actions,
    validate_data_freshness,
    validate_environment_mode,
    validate_evidence_pack,
    validate_handoff_payload,
    validate_input_schema,
    validate_output_schema,
    validate_registry_entry,
    validate_required_fields,
    validate_strategy_actions,
    validate_strategy_dataframe,
    validate_trade_action_object,
    validate_trade_actions,
)

__all__ = [
    # config.py utilities
    "DEFAULT_APP_NAME",
    "DEFAULT_ENV_DIR",
    "DEFAULT_ENV_FILE",
    "DEFAULT_ENV_PREFIX",
    "DEFAULT_ENVIRONMENT",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_RUNTIME_ENVIRONMENT",
    "RuntimeSettings",
    "Settings",
    "SettingsError",
    "VALID_ENVIRONMENTS",
    "VALID_LOG_LEVELS",
    "collect_prefixed_values",
    "get_environment",
    "get_settings",
    "inject_runtime_settings",
    "is_production",
    "is_test",
    "load_runtime_settings",
    "load_runtime_settings_from_mapping",
    "normalize_environment",
    "normalize_log_level",
    "normalize_mapping",
    "parse_env_file",
    # errors.py utilities
    "BrokerError",
    "ConfigurationError",
    "DescriptorDict",
    "DomainError",
    "ErrorContext",
    "ErrorDescriptor",
    "ErrorEnvelope",
    "ErrorInfo",
    "ErrorPayload",
    "HaruError",
    "HaruQuantError",
    "InfrastructureError",
    "InvalidPriceError",
    "InvalidRequestError",
    "InvalidStopsError",
    "InvalidVolumeError",
    "MarketClosedError",
    "MT5_MESSAGES",
    "NoMoneyError",
    "NoQuotesError",
    "PolicyError",
    "RETCODE_EXCEPTION_TYPES",
    "RETCODE_INFO",
    "SUCCESS_RETCODES",
    "TradeDisabledError",
    "TradeError",
    "UNKNOWN_ERROR_CODE",
    "ValidationError",
    "descriptor_from_payload",
    "descriptor_to_dict",
    "error_from_retcode",
    "error_info_to_dict",
    "error_name",
    "exception_from_descriptor",
    "is_success_retcode",
    "message_for",
    "raise_for_retcode",
    # ids.py utilities
    "ID_SEPARATOR",
    "REQUEST_ID_PREFIX",
    "RUN_ID_PREFIX",
    "TOOL_CALL_ID_PREFIX",
    "UUID_HEX_LENGTH",
    "VALID_ID_PREFIXES",
    "WORKFLOW_ID_PREFIX",
    "is_request_id",
    "is_run_id",
    "is_tool_call_id",
    "is_valid_prefixed_id",
    "is_workflow_id",
    "new_request_id",
    "new_run_id",
    "new_tool_call_id",
    "new_workflow_id",
    # logger.py utilities
    "CRITICAL",
    "DEBUG",
    "DEFAULT_LEVELS",
    "ERROR",
    "INFO",
    "SUCCESS",
    "TRACE",
    "WARNING",
    "CompatRecord",
    "Logger",
    "StructlogAdapter",
    "configure_default_file_sinks",
    "logger",
    # logger.py official AI tools
    "configure_multiprocess_listener",
    "init_worker_logger",
    # normalization.py helpers and official AI tools
    "BOARD_BASELINE_TTL_POLICY",
    "BoardBaselineArtifactWindow",
    "BoardBaselineFreshnessEvaluation",
    "FixedClock",
    "FreshnessWindow",
    "SystemClock",
    "board_baseline_evaluation_to_dict",
    "board_baseline_window_to_dict",
    "ensure_dir",
    "ensure_parent_dir",
    "evaluate_board_baseline_freshness",
    "evaluate_freshness",
    "format_timestamp_z",
    "freshness_window_to_dict",
    "is_stale",
    "normalize_path",
    "normalize_timestamp",
    "normalize_timezone_for_series",
    "parse_datetime_value",
    "to_naive_utc_datetime",
    "to_utc",
    "to_utc_datetime",
    # result.py constants
    "ERROR_APPROVAL_REQUIRED",
    "ERROR_INVALID_INPUT",
    "ERROR_MISSING_INPUT",
    "ERROR_POLICY_BLOCKED",
    "ERROR_UNKNOWN",
    "ERROR_VALIDATION_FAILED",
    "STATUS_BLOCKED",
    "STATUS_ERROR",
    "STATUS_NEEDS_APPROVAL",
    "STATUS_NEEDS_CLARIFICATION",
    "STATUS_SUCCESS",
    "VALID_RESULT_STATUSES",
    # result.py utility helpers
    "blocked_result",
    "error_result",
    "needs_approval_result",
    "needs_clarification_result",
    "success_result",
    # security.py helpers and official AI tools
    "REDACTED",
    "REDACTED_VALUE",
    "SENSITIVE_KEYWORDS",
    "SecretRef",
    "SecretRotationPolicy",
    "decrypt_data_value",
    "encrypt_data_value",
    "generate_encryption_key",
    "hash_password_value",
    "is_sensitive_key",
    "redact_mapping",
    "redact_scalar_value",
    "redact_text",
    "rotation_policy_to_dict",
    "secret_ref_to_dict",
    "select_active_secret_version",
    "verify_password_value",
    # validators.py helpers and official AI tools
    "ACTIVATOR_COLUMN_DEFAULTS",
    "REQUIRED_OHLC_COLUMNS",
    "SIGNAL_COLUMN_DEFAULTS",
    "apply_warmup_policy",
    "assert_dataframe",
    "assert_ohlc_dataframe",
    "ensure_dataframe",
    "ensure_no_signal_columns",
    "ensure_signal_columns",
    "prepare_ohlcv_data",
    "require_columns",
    "require_known_warmup_policy",
    "require_positive_float",
    "require_positive_int",
    "serialize_dataframe",
    "validate_approval_packet",
    "validate_artifact_reference",
    "validate_blocked_actions",
    "validate_data_freshness",
    "validate_environment_mode",
    "validate_evidence_pack",
    "validate_handoff_payload",
    "validate_input_schema",
    "validate_output_schema",
    "validate_registry_entry",
    "validate_required_fields",
    "validate_strategy_actions",
    "validate_strategy_dataframe",
    "validate_trade_action_object",
    "validate_trade_actions",
]
