"""Public Analytics domain port.

All cross-domain consumers and standalone usage programs import Analytics
capabilities through this package root.
"""

from app.services.analytics.adapters import (
    adapt_trading_result,
    build_closed_trade_equity_curve,
)
from app.services.analytics.contracts import (
    ANALYTICS_SCHEMA_VERSION,
    CONTRACT_COMPATIBILITY_MATRIX,
    EVIDENCE_CATALOG,
    METRIC_DEFINITION_CATALOG,
    AnalyticsError,
    AnalyticsRunConfig,
    AnalyticsValidationError,
    AnalyticsWarning,
    ClosedTrade,
    DashboardPayload,
    Lineage,
    MetricEvidence,
    PerformanceReport,
    PortfolioAllocationEvidence,
    PortfolioPerformanceReport,
    PortfolioRebalanceMeasurementEvidence,
    PortfolioRebalanceMeasurementRequest,
    QualityFlag,
    ReproducibilityHashes,
    RiskFreeRateEvidence,
    SectionEvidence,
    StatisticalValidationConfig,
    TradingResult,
    build_quality_flag,
    build_warning,
    to_analytics_error_payload,
    to_report_json_safe,
    validate_contract_version,
    validate_metric_catalog,
)
from app.services.analytics.dashboards import (
    build_dashboard_payload,
    truncate_series,
)
from app.services.analytics.metrics import (
    ANNUALIZATION_POLICY,
    BREAKEVEN_EPSILON,
    MIN_METRIC_SAMPLES,
    align_benchmark_series,
    calculate_benchmark_evidence,
    calculate_cost_efficiency_evidence,
    calculate_distribution_evidence,
    calculate_drawdown_evidence,
    calculate_grouped_evidence,
    calculate_ratio_evidence,
    calculate_return_evidence,
    calculate_risk_evidence,
    calculate_trade_evidence,
    run_statistical_validation,
)
from app.services.analytics.reports import (
    build_performance_report,
    build_portfolio_allocation_evidence,
    build_portfolio_performance_report,
    compare_performance_reports,
    compute_reproducibility_hashes,
    serialize_report,
)
from app.services.analytics.reports.allocation import (
    build_portfolio_rebalance_measurement,
)

__all__: tuple[str, ...] = (
    "ANALYTICS_SCHEMA_VERSION",
    "ANNUALIZATION_POLICY",
    "BREAKEVEN_EPSILON",
    "CONTRACT_COMPATIBILITY_MATRIX",
    "EVIDENCE_CATALOG",
    "METRIC_DEFINITION_CATALOG",
    "MIN_METRIC_SAMPLES",
    "AnalyticsError",
    "AnalyticsRunConfig",
    "AnalyticsValidationError",
    "AnalyticsWarning",
    "ClosedTrade",
    "DashboardPayload",
    "Lineage",
    "MetricEvidence",
    "PerformanceReport",
    "PortfolioAllocationEvidence",
    "PortfolioPerformanceReport",
    "PortfolioRebalanceMeasurementEvidence",
    "PortfolioRebalanceMeasurementRequest",
    "QualityFlag",
    "ReproducibilityHashes",
    "RiskFreeRateEvidence",
    "SectionEvidence",
    "StatisticalValidationConfig",
    "TradingResult",
    "adapt_trading_result",
    "align_benchmark_series",
    "build_closed_trade_equity_curve",
    "build_dashboard_payload",
    "build_performance_report",
    "build_portfolio_allocation_evidence",
    "build_portfolio_performance_report",
    "build_portfolio_rebalance_measurement",
    "build_quality_flag",
    "build_warning",
    "calculate_benchmark_evidence",
    "calculate_cost_efficiency_evidence",
    "calculate_distribution_evidence",
    "calculate_drawdown_evidence",
    "calculate_grouped_evidence",
    "calculate_ratio_evidence",
    "calculate_return_evidence",
    "calculate_risk_evidence",
    "calculate_trade_evidence",
    "compare_performance_reports",
    "compute_reproducibility_hashes",
    "run_statistical_validation",
    "serialize_report",
    "to_analytics_error_payload",
    "to_report_json_safe",
    "truncate_series",
    "validate_contract_version",
    "validate_metric_catalog",
)
