import type { CustomProject, WorkflowTask } from './documents';

export const workflowTasks: WorkflowTask[] = [
  { id: 'w1', type: 'ClearDatabanks', name: 'Clear temporary candidates', enabled: true, status: 'idle', input: 'Temporary', output: 'Temporary' },
  { id: 'w2', type: 'Build', name: 'Generate H1 candidates', enabled: true, status: 'idle', input: 'EURUSD H1', output: 'Generated' },
  { id: 'w3', type: 'Retest', name: 'Higher precision retest', enabled: true, status: 'idle', input: 'Generated', output: 'Precise' },
  { id: 'w4', type: 'Filtering', name: 'OOS ranking filter', enabled: true, status: 'idle', input: 'Precise', output: 'Accepted' },
  { id: 'w5', type: 'AutomaticPortfolioBuilder', name: 'Build uncorrelated portfolio', enabled: true, status: 'idle', input: 'Accepted', output: 'Portfolio' },
  { id: 'w6', type: 'SaveToFiles', name: 'Export selected strategies', enabled: false, status: 'idle', input: 'Portfolio', output: 'Mock filesystem' },
];

export const customProjects: CustomProject[] = [
  {
    id: 'proj-1',
    name: 'FX Trend-Following Research Pipeline',
    description: 'Autonomous multi-stage generation, walk-forward retest, correlation filtering and portfolio assembly for Forex majors.',
    status: 'idle',
    tasks: [
      {
        id: 'w1',
        type: 'ClearDatabanks',
        name: 'Clear temporary candidate databanks',
        enabled: true,
        status: 'idle',
        input: 'Temporary',
        output: 'Temporary',
        config: { targetBank: 'Temporary', keepPinned: true },
      },
      {
        id: 'w2',
        type: 'Build',
        name: 'Genetic Strategy Generation (H1)',
        enabled: true,
        status: 'idle',
        input: 'EURUSD H1',
        output: 'Generated',
        config: { symbol: 'EURUSD', timeframe: 'H1', targetCount: 30, minSharpe: 1.1, minTrades: 80 },
      },
      {
        id: 'w3',
        type: 'Retest',
        name: 'Higher Precision Multi-Market Retest',
        enabled: true,
        status: 'idle',
        input: 'Generated',
        output: 'Precise',
        config: { precision: 'M1 real tick data', spreadMultiplier: 1.5, slippagePips: 1.0 },
      },
      {
        id: 'w4',
        type: 'Filtering',
        name: 'Sharpe & Drawdown Robustness Filter',
        enabled: true,
        status: 'idle',
        input: 'Precise',
        output: 'Accepted',
        config: { filterMetric: 'Sharpe ratio >= 1.25', maxDrawdownPct: 20, minProfitFactor: 1.4 },
      },
      {
        id: 'w5',
        type: 'AutomaticPortfolioBuilder',
        name: 'Uncorrelated 5-Strategy Portfolio Assembly',
        enabled: true,
        status: 'idle',
        input: 'Accepted',
        output: 'Portfolio',
        config: { maxStrategies: 5, maxCorrelation: 0.45, weightingModel: 'Risk Parity' },
      },
      {
        id: 'w6',
        type: 'SaveToFiles',
        name: 'Export Compiled MQL5 / Python Robots',
        enabled: false,
        status: 'idle',
        input: 'Portfolio',
        output: 'Export Directory',
        config: { destinationPath: './exports/live_candidates/', format: 'MQL5 + Python' },
      },
    ],
  },
  {
    id: 'proj-2',
    name: 'NQ Futures Mean Reversion Scanner',
    description: 'High-frequency intraday mean reversion scanner with Monte Carlo validation.',
    status: 'idle',
    tasks: [
      {
        id: 'w2-1',
        type: 'UpdateData',
        name: 'Sync CME Tick Data Feed',
        enabled: true,
        status: 'idle',
        input: 'CME NQ Futures',
        output: 'Updated Market Cache',
        config: { provider: 'Futures Tick Feed', barsToSync: 50000 },
      },
      {
        id: 'w2-2',
        type: 'Build',
        name: 'Evolve Range Breakout Candidates',
        enabled: true,
        status: 'idle',
        input: 'NQ M15',
        output: 'Candidates',
        config: { symbol: 'NQ', timeframe: 'M15', targetCount: 20, maxDrawdownPct: 15 },
      },
      {
        id: 'w2-3',
        type: 'CustomAnalysis',
        name: 'Monte Carlo Trade Reshuffling Confidence',
        enabled: true,
        status: 'idle',
        input: 'Candidates',
        output: 'Robust Candidates',
        config: { confidenceLevel: 95, simulations: 1000 },
      },
      {
        id: 'w2-4',
        type: 'Notification',
        name: 'Send Slack / Webhook Alert',
        enabled: true,
        status: 'idle',
        input: 'Robust Candidates',
        output: 'Webhook Endpoint',
        config: { webhookUrl: 'https://hooks.slack.com/services/quant-alerts', notifyOnSuccess: true },
      },
    ],
  },
];
