import { useProjectWorkbench } from './documents';
import {useState} from 'react';
import {Settings} from 'lucide-react';

import {PortfolioMasterDialogs} from './PortfolioMasterDialogs';
import {masterError,type MasterDraft} from './portfolioMasterModel';
export function PortfolioMasterSettings({draft,onChange,banks,available,locked}:{draft:MasterDraft;onChange:(v:MasterDraft)=>void;banks:string[];available:number;locked:boolean}) {
const { ProjectSettings } = useProjectWorkbench();

 const [dialog,setDialog]=useState<'genetic'|'correlation'|null>(null);
 const patch=(v:Partial<MasterDraft>)=>onChange({...draft,...v});
 const number=(label:string,key:'min'|'max'|'limit'|'sectorLimit'|'capital'|'inSample',min=0)=><label className="pf-row"><span>{label}</span><input type="number" aria-label={label} min={min} value={draft[key]} onChange={e=>patch({[key]:Number(e.target.value)})}/></label>;
 const content=<div className="pf-master-form sqd-tab-content"><h3>Portfolio</h3><div className="pf-row"><span>Search for portfolios using</span>{(['Brute force','Genetic search'] as const).map(search=><label key={search}><input type="radio" name="pm-search" checked={draft.search===search} onChange={()=>patch({search})}/>{search}</label>)}<button className="sqd-link-button" aria-label="Genetic settings" onClick={()=>setDialog('genetic')}><Settings size={14}/></button></div>
 <div className="pf-row"><span>Data range</span>{(['Full available','Limited'] as const).map(dateRange=><label key={dateRange}><input type="radio" name="pm-range" checked={draft.dateRange===dateRange} onChange={()=>patch({dateRange})}/>{dateRange}</label>)}<input type="date" aria-label="Date from" disabled={draft.dateRange!=='Limited'} value={draft.from} onChange={e=>patch({from:e.target.value})}/><input type="date" aria-label="Date to" disabled={draft.dateRange!=='Limited'} value={draft.to} onChange={e=>patch({to:e.target.value})}/></div>
 {number('In Sample part (%)','inSample',1)}<label className="pf-check pf-indent"><input type="checkbox" checked={draft.reverse} onChange={e=>patch({reverse:e.target.checked})}/>reverse IS / OOS (if checked OOS part will be first)</label>
 <div className="pf-row"><span># of strategies in portfolio</span><label>min <input type="number" aria-label="Minimum strategies" min={2} value={draft.min} onChange={e=>patch({min:Number(e.target.value)})}/></label><label>max <input type="number" aria-label="Maximum strategies" min={draft.min} value={draft.max} onChange={e=>patch({max:Number(e.target.value)})}/></label></div>
 {number('Maximum portfolios to store in databank','limit',1)}<label className="pf-row"><span>Rank portfolios by</span><select value={draft.fitness} onChange={e=>patch({fitness:e.target.value})}>{['Return / Drawdown','Sharpe ratio','Net profit'].map(v=><option key={v}>{v}</option>)}</select></label>{number('Max allowed strategies from the same sector','sectorLimit')}
 <h3>Databanks</h3>{(['source','target'] as const).map(key=><label className="pf-row" key={key}><span>{key==='source'?'Source databank':'Target databank'}</span><select aria-label={key==='source'?'Source databank':'Target databank'} value={draft[key]} onChange={e=>patch({[key]:e.target.value})}>{banks.map(b=><option key={b}>{b}</option>)}</select></label>)}<label className="pf-check pf-indent"><input type="checkbox" checked={draft.selectedOnly} onChange={e=>patch({selectedOnly:e.target.checked})}/>only selected</label>
 <h3>Money Management</h3>{number('Initial capital','capital',1)}<div className="pf-row"><span>Used method</span><select aria-label="Used method" disabled={!draft.overrideMoney} value={draft.money} onChange={e=>patch({money:e.target.value})}>{['Fixed size','Risk fixed %','Fixed amount'].map(v=><option key={v}>{v}</option>)}</select><label><input type="checkbox" checked={draft.overrideMoney} onChange={e=>patch({overrideMoney:e.target.checked})}/>optional (otherwise use original strategy MM)</label></div>
 <h3>Filtering</h3><div className="pf-row"><span>Correlation</span><span>{draft.correlation.period} / {draft.correlation.type} / max {draft.correlation.max}</span><button className="sqd-link-button" aria-label="Correlation settings" onClick={()=>setDialog('correlation')}><Settings size={14}/></button></div><h4>Filter portfolios where</h4>
 <table className="pf-table"><thead><tr><th>Metric</th><th>Comparison</th><th>Value</th><th/></tr></thead><tbody>{draft.filters.map(f=><tr key={f.id}><td><select aria-label={`Filter ${f.id} metric`} value={f.metric} onChange={e=>patch({filters:draft.filters.map(v=>v.id===f.id?{...v,metric:e.target.value}:v)})}>{['Net profit','Drawdown','Profit factor'].map(v=><option key={v}>{v}</option>)}</select></td><td><select aria-label={`Filter ${f.id} comparison`} value={f.comparison} onChange={e=>patch({filters:draft.filters.map(v=>v.id===f.id?{...v,comparison:e.target.value}:v)})}>{['>','<','>=','<='].map(v=><option key={v}>{v}</option>)}</select></td><td><input aria-label={`Filter ${f.id} value`} type="number" value={f.value} onChange={e=>patch({filters:draft.filters.map(v=>v.id===f.id?{...v,value:Number(e.target.value)}:v)})}/></td><td><button className="sqd-btn" aria-label={`Delete filter ${f.id}`} onClick={()=>patch({filters:draft.filters.filter(v=>v.id!==f.id)})}>×</button></td></tr>)}</tbody></table><button className="sqd-btn" onClick={()=>patch({filters:[...draft.filters,{id:Math.max(0,...draft.filters.map(f=>f.id))+1,metric:'Net profit',comparison:'>',value:0}]})}>Add condition</button>
 {masterError(draft,available)&&<p role="alert">{masterError(draft,available)}</p>}{dialog&&<PortfolioMasterDialogs kind={dialog} draft={draft} onChange={onChange} onClose={()=>setDialog(null)}/>}
 </div>;
 return <ProjectSettings locked={locked} sections={[{id:'automatic',title:'Automatic Portfolio Builder',help:'Automatically create portfolios using the selected strategies and portfolio constraints.',helpUrl:'https://strategyquant.com/doc/strategyquant/automatic-portfolio-builder/',content}]}/>;
}
