"""Canonical public port for the complete Trading domain."""

from app.services.trading.actions import (
    TradingDependencies,
    cancel_all_orders,
    cancel_order,
    clear_kill_switch,
    close_all_positions,
    close_position,
    execute_portfolio_rebalance,
    modify_order,
    modify_position,
    pause_strategy,
    reduce_exposure,
    resume_strategy,
    run_live_evaluation_cycle,
    submit_order,
    sync_positions,
    trigger_kill_switch,
)
from app.services.trading.contracts import (
    TRADING_CONTRACT_VERSION,
    ExecutionReceipt,
    OrderIntent,
    PortfolioRebalanceExecutionRequest,
    StandardTradingEnvelope,
    TradeRecord,
    TradingError,
    TradingRequest,
    TradingRoute,
    create_trading_action_draft,
    get_public_contracts,
    map_trading_error,
    redact_trading_payload,
)
from app.services.trading.live import LiveSession, evaluate_live_gate
from app.services.trading.monitoring import (
    BudgetGate,
    OperationalEvent,
    emit_runtime_event,
)
from app.services.trading.reconciliation import (
    AuthorityResolution,
    AuthoritySnapshot,
    ReconciliationReport,
    compare_authority_state,
    resolve_unknown_outcome,
)
from app.services.trading.reporting import build_trading_report
from app.services.trading.routing import (
    classify_authority_response,
    dispatch_order_intent,
    validate_adapter_capability,
)
from app.services.trading.state import (
    TRADING_SCHEMA_VERSION,
    IdempotencyReservation,
    TradingEvent,
    TradingProjection,
    TradingStateStore,
    apply_execution_event,
    get_trading_migrations,
    reserve_idempotency,
)
from app.services.trading.validation import (
    ReadinessAssessment,
    RouteSnapshot,
    assess_execution_readiness,
    build_execution_plan,
    get_route_snapshot,
    validate_order_request,
)

__all__: tuple[str, ...] = (
    "TRADING_CONTRACT_VERSION",
    "TRADING_SCHEMA_VERSION",
    "AuthorityResolution",
    "AuthoritySnapshot",
    "BudgetGate",
    "ExecutionReceipt",
    "IdempotencyReservation",
    "LiveSession",
    "OperationalEvent",
    "OrderIntent",
    "PortfolioRebalanceExecutionRequest",
    "ReadinessAssessment",
    "ReconciliationReport",
    "RouteSnapshot",
    "StandardTradingEnvelope",
    "TradeRecord",
    "TradingDependencies",
    "TradingError",
    "TradingEvent",
    "TradingProjection",
    "TradingRequest",
    "TradingRoute",
    "TradingStateStore",
    "apply_execution_event",
    "assess_execution_readiness",
    "build_execution_plan",
    "build_trading_report",
    "cancel_all_orders",
    "cancel_order",
    "classify_authority_response",
    "clear_kill_switch",
    "close_all_positions",
    "close_position",
    "compare_authority_state",
    "create_trading_action_draft",
    "dispatch_order_intent",
    "emit_runtime_event",
    "evaluate_live_gate",
    "execute_portfolio_rebalance",
    "get_public_contracts",
    "get_route_snapshot",
    "get_trading_migrations",
    "map_trading_error",
    "modify_order",
    "modify_position",
    "pause_strategy",
    "redact_trading_payload",
    "reduce_exposure",
    "reserve_idempotency",
    "resolve_unknown_outcome",
    "resume_strategy",
    "run_live_evaluation_cycle",
    "submit_order",
    "sync_positions",
    "trigger_kill_switch",
    "validate_adapter_capability",
    "validate_order_request",
)
