"""Deterministic contract artifact generator with write and check modes.

Emits, solely from the strict Pydantic contracts under ``app/contracts/``:

- one canonical JSON Schema document per namespace at
  ``app/contracts/<owner>/wire/schema.json``;
- one TypeScript type module per namespace plus a barrel at
  ``app/ui/src/contracts/generated/``.

``--check`` compares the in-memory artifacts byte-for-byte with the working
tree, rejects missing/extra/stale files, and exits nonzero on any drift. The
output is a byte-reproducible generated artifact and never a semantic source.
"""

from __future__ import annotations

import argparse
import importlib
import json
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any, TypeAliasType

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

CONTRACTS_ROOT = REPO_ROOT / "app" / "contracts"
UI_GENERATED_DIR = REPO_ROOT / "app" / "ui" / "src" / "contracts" / "generated"

# Canonical namespace order used for the barrel and every deterministic list.
OWNERS: tuple[str, ...] = (
    "common",
    "workspace",
    "catalogue",
    "data",
    "strategy",
    "simulator",
    "analytics",
    "research",
    "portfolio",
    "orchestration",
    "interfaces",
    "ui",
    "plugins",
    "broker",
    "risk",
    "trading",
)

# Recursive JSON type aliases every generated module imports from "./common".
HEADER = (
    "// Generated by scripts/generate_contracts.py from app/contracts/. "
    "DO NOT EDIT; regenerate instead."
)

type JsonDict = dict[str, Any]

# Registry wire name -> owning namespace; populated by collect_owners().
WIRE_NAME_OWNER: dict[str, str] = {}

# Definition name -> namespace whose TypeScript module emits it; populated by
# build_placement() so every generated name is exported exactly once.
DEF_PLACEMENT: dict[str, str] = {}


def common_type_alias_names() -> frozenset[str]:
    """Introspect the type aliases declared by the common namespace.

    Returns:
        Names of every PEP 695 type alias exported by
        ``app.contracts.common.models``; their schema definitions are placed
        in the generated common module regardless of referencing namespace.
    """
    module = importlib.import_module("app.contracts.common.models")
    return frozenset(
        name
        for name in dir(module)
        if not name.startswith("_") and isinstance(getattr(module, name), TypeAliasType)
    )


def load_namespace(owner: str) -> dict[str, dict[str, type]]:
    """Load the wire registries exported by one namespace.

    Args:
        owner: Namespace name to inspect.

    Returns:
        Mapping of registry kind ("models", "events", "failures") to the
        name-to-class registry exported by the namespace category modules.

    Raises:
        ModuleNotFoundError: If an internal module dependency fails to import.
    """
    registries: dict[str, dict[str, type]] = {}

    for kind, module_name in (
        ("models", "models"),
        ("events", "events"),
        ("failures", "errors"),
    ):
        target_name = f"app.contracts.{owner}.{module_name}"
        try:
            module = importlib.import_module(target_name)
        except ModuleNotFoundError as err:
            if err.name == target_name:
                continue
            raise
        registry = getattr(module, f"WIRE_{kind.upper()}", None)
        if registry is not None:
            registries[kind] = dict(registry)
    return registries


def rename_refs(node: Any, mapping: dict[str, str]) -> Any:
    """Rewrite ``$defs`` keys and ``$ref`` targets inside a schema node.

    Args:
        node: Parsed JSON Schema value (object, list, or scalar).
        mapping: Class name to registry wire-name mapping applied to defs.

    Returns:
        The schema value with every def key and ref target renamed.
    """
    if isinstance(node, dict):
        rewritten = {
            mapping.get(k, k): rename_refs(v, mapping) for k, v in node.items()
        }
        ref = rewritten.get("$ref")
        if isinstance(ref, str) and ref.startswith("#/$defs/"):
            target = ref[len("#/$defs/") :]
            rewritten["$ref"] = f"#/$defs/{mapping.get(target, target)}"
        return rewritten
    if isinstance(node, list):
        return [rename_refs(item, mapping) for item in node]
    return node


def build_owner_schema(
    owner: str,
    registries: dict[str, dict[str, type]],
    class_to_wire: dict[str, str],
) -> JsonDict:
    """Build the canonical merged JSON Schema document for one namespace.

    Args:
        owner: Namespace identifier.
        registries: Wire registries of the namespace by kind.
        class_to_wire: Global class-name to wire-name mapping for ref renaming.

    Returns:
        The deterministic self-contained schema document.

    Raises:
        SystemExit: When two schema definitions collide with different bodies.
    """
    defs: JsonDict = {}
    sections: JsonDict = {kind: {} for kind in ("models", "events", "failures")}
    for kind in ("models", "events", "failures"):
        for wire_name, model in sorted(registries.get(kind, {}).items()):
            raw = model.model_json_schema(ref_template="#/$defs/{model}")
            inner = dict(raw.pop("$defs", {}))
            defs[wire_name] = rename_refs(raw, class_to_wire)
            sections[kind][wire_name] = {"$ref": f"#/$defs/{wire_name}"}
            for def_name, def_body in inner.items():
                target = class_to_wire.get(def_name, def_name)
                body = rename_refs(def_body, class_to_wire)
                existing = defs.get(target)
                if existing is not None and existing != body:
                    message = f"conflicting schema defs for {owner}:{target}"
                    raise SystemExit(message)
                defs[target] = body
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": f"{owner} wire contracts v1",
        "namespace": owner,
        "schema_version": 1,
        "models": sections["models"],
        "events": sections["events"],
        "failures": sections["failures"],
        "$defs": dict(sorted(defs.items())),
    }


def canonical_json(document: JsonDict) -> str:
    """Serialize a schema document to canonical deterministic bytes.

    Args:
        document: The schema document.

    Returns:
        Canonical JSON text ending in exactly one newline.
    """
    return json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _resolve_ref(name: str, owner: str, imports: dict[str, set[str]]) -> str:
    """Resolve one ``$ref`` target to a local name or a cross-module import.

    Args:
        name: Referenced definition name.
        owner: Namespace whose module is being emitted.
        imports: Collected cross-module imports, mutated in place.

    Returns:
        The referenced TypeScript type name.
    """
    owner_of_name = DEF_PLACEMENT.get(name, owner)
    if owner_of_name != owner:
        imports.setdefault(owner_of_name, set()).add(name)
    return name


def _ts_array(schema: JsonDict, owner: str, imports: dict[str, set[str]]) -> str:
    """Map an array schema node to a tuple or list TypeScript type.

    Args:
        schema: Array schema node.
        owner: Namespace whose module is being emitted.
        imports: Collected cross-module imports, mutated in place.

    Returns:
        The TypeScript type expression.
    """
    prefix = schema.get("prefixItems")
    if isinstance(prefix, list):
        joined = ", ".join(ts_type(part, owner, imports) for part in prefix)
        return f"[{joined}]"
    return f"{ts_type(schema.get('items', {}), owner, imports)}[]"


def _ts_object(schema: JsonDict, owner: str, imports: dict[str, set[str]]) -> str:
    """Map an object schema node to an indexed TypeScript type.

    Args:
        schema: Object schema node.
        owner: Namespace whose module is being emitted.
        imports: Collected cross-module imports, mutated in place.

    Returns:
        The TypeScript type expression.
    """
    additional = schema.get("additionalProperties")
    if isinstance(additional, dict):
        value = ts_type(additional, owner, imports)
        return f"{{ [key: string]: {value} }}"
    return "{ [key: string]: unknown }"


def _ts_composite(
    schema: JsonDict, owner: str, imports: dict[str, set[str]]
) -> str | None:
    """Map const/enum/union/intersection nodes, or return None.

    Args:
        schema: Parsed JSON Schema node.
        owner: Namespace whose module is being emitted.
        imports: Collected cross-module imports, mutated in place.

    Returns:
        The TypeScript type expression, or None when no composite key exists.
    """
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(part, owner, imports) for part in schema["anyOf"])
    if "allOf" in schema:
        return " & ".join(ts_type(part, owner, imports) for part in schema["allOf"])
    return None


def _ts_scalar(schema: JsonDict) -> str:
    """Map a scalar JSON Schema node to its TypeScript primitive.

    Args:
        schema: Scalar schema node carrying a ``type`` key.

    Returns:
        The TypeScript primitive name.
    """
    scalar = {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }
    return scalar[schema["type"]]


def _ts_unshaped(schema: JsonDict, owner: str, imports: dict[str, set[str]]) -> str:
    """Map a node without an explicit ``type`` key (dict value shapes).

    Args:
        schema: Parsed JSON Schema node.
        owner: Namespace whose module is being emitted.
        imports: Collected cross-module imports, mutated in place.

    Returns:
        The TypeScript type expression.
    """
    if isinstance(schema.get("additionalProperties"), dict):
        return _ts_object(schema, owner, imports)
    return "unknown"


def ts_type(schema: JsonDict, owner: str, imports: dict[str, set[str]]) -> str:
    """Map one JSON Schema node to a deterministic TypeScript type string.

    Args:
        schema: Parsed JSON Schema node.
        owner: Namespace whose module is being emitted.
        imports: Collected cross-module imports, mutated in place.

    Returns:
        The TypeScript type expression.
    """
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", maxsplit=1)[-1]
        return _resolve_ref(name, owner, imports)
    composite = _ts_composite(schema, owner, imports)
    if composite is not None:
        return composite
    match schema.get("type"):
        case "array":
            return _ts_array(schema, owner, imports)
        case "object":
            return _ts_object(schema, owner, imports)
        case "string" | "integer" | "number" | "boolean" | "null":
            return _ts_scalar(schema)
    return _ts_unshaped(schema, owner, imports)


def ts_def(
    name: str,
    schema: JsonDict,
    owner: str,
    imports: dict[str, set[str]],
) -> str:
    """Emit one TypeScript declaration for a schema definition.

    Args:
        name: Wire name of the definition.
        schema: The definition body.
        owner: Namespace whose module is being emitted.
        imports: Collected cross-module imports, mutated in place.

    Returns:
        The TypeScript declaration text.
    """
    if "properties" in schema:
        required = set(schema.get("required", []))
        lines = [f"export interface {name} {{"]
        for prop, prop_schema in schema["properties"].items():
            optional = "" if prop in required else "?"
            rendered = ts_type(prop_schema, owner, imports)
            if "default" in prop_schema:
                default = json.dumps(prop_schema["default"], sort_keys=True)
                lines.append(f"  {prop}{optional}: {rendered};  // default: {default}")
            else:
                lines.append(f"  {prop}{optional}: {rendered};")
        lines.append("}")
        return "\n".join(lines)
    return f"export type {name} = {ts_type(schema, owner, imports)};"


def build_global_defs(documents: dict[str, JsonDict]) -> dict[str, JsonDict]:
    """Merge every document's definitions into one conflict-checked pool.

    Args:
        documents: Schema documents by owner.

    Returns:
        Definition name to canonical body mapping.

    Raises:
        SystemExit: When one definition name has differing bodies across
            namespaces.
    """
    pool: dict[str, JsonDict] = {}
    for owner in OWNERS:
        for name, body in documents[owner]["$defs"].items():
            known = pool.get(name)
            if known is None:
                pool[name] = body
            elif known != body:
                message = f"def {name} differs between namespaces (seen in {owner})"
                raise SystemExit(message)
    return pool


def build_placement(documents: dict[str, JsonDict]) -> dict[str, str]:
    """Assign every definition to exactly one emitting namespace.

    Registered wire names belong to their registry owner; names declared as
    common type aliases belong to common; every other shared or nested
    definition belongs to the first namespace in canonical order whose
    document contains it.

    Args:
        documents: Schema documents by owner.

    Returns:
        Definition name to emitting namespace mapping.
    """
    common_aliases = common_type_alias_names()
    placement: dict[str, str] = {}
    for owner in OWNERS:
        for name in documents[owner]["$defs"]:
            if name in placement:
                continue
            if name in WIRE_NAME_OWNER:
                placement[name] = WIRE_NAME_OWNER[name]
            elif name in common_aliases:
                placement[name] = "common"
            else:
                placement[name] = owner
    return placement


def build_owner_typescript(owner: str, global_defs: dict[str, JsonDict]) -> str:
    """Build the deterministic TypeScript module for one namespace.

    Args:
        owner: Namespace identifier.
        global_defs: Conflict-checked definition pool.

    Returns:
        The complete TypeScript module text.
    """
    imports: dict[str, set[str]] = {}
    lines: list[str] = [HEADER, ""]
    emitted = [
        ts_def(name, global_defs[name], owner, imports)
        for name in sorted(global_defs)
        if DEF_PLACEMENT.get(name, owner) == owner
    ]
    if imports:
        for source in sorted(imports):
            names = ", ".join(sorted(imports[source]))
            lines.append(f'import type {{ {names} }} from "./{source}";')
        lines.append("")
    lines.extend(emitted)
    lines.append("")
    return "\n".join(lines)


def collect_owners() -> dict[str, dict[str, dict[str, type]]]:
    """Load every namespace registry and populate wire-name ownership.

    Returns:
        Registries by owner and kind.

    Raises:
        SystemExit: When a namespace exports no registry or a wire name is
            registered by two namespaces.
    """
    loaded: dict[str, dict[str, dict[str, type]]] = {}
    for owner in OWNERS:
        registries = load_namespace(owner)
        if not registries:
            message = f"namespace {owner} exports no wire registries"
            raise SystemExit(message)
        loaded[owner] = registries
        for registry in registries.values():
            for wire_name in registry:
                previous = WIRE_NAME_OWNER.setdefault(wire_name, owner)
                if previous != owner:
                    message = (
                        f"wire name {wire_name} registered by {previous} and {owner}"
                    )
                    raise SystemExit(message)
    return loaded


def verify_cross_owner_defs(documents: dict[str, JsonDict]) -> None:
    """Fail when a def shared across namespaces has differing bodies.

    Args:
        documents: Schema documents by owner.

    Raises:
        SystemExit: On any cross-owner definition body mismatch.
    """
    build_global_defs(documents)


def build_index_typescript() -> str:
    """Build the barrel module re-exporting every generated owner module.

    Returns:
        The barrel TypeScript module text.
    """
    lines = [HEADER, ""]
    lines.extend(f'export * from "./{owner}";' for owner in OWNERS)
    lines.append("")
    return "\n".join(lines)


def render_artifacts() -> dict[Path, str]:
    """Render every generated artifact path to its deterministic content.

    Returns:
        Artifact file path to canonical content mapping.
    """
    loaded = collect_owners()
    class_to_wire: dict[str, str] = {}
    for owner in OWNERS:
        for registry in loaded[owner].values():
            for wire_name, model in registry.items():
                class_to_wire.setdefault(model.__name__, wire_name)
    documents = {
        owner: build_owner_schema(owner, loaded[owner], class_to_wire)
        for owner in OWNERS
    }
    global_defs = build_global_defs(documents)
    DEF_PLACEMENT.clear()
    DEF_PLACEMENT.update(build_placement(documents))
    artifacts: dict[Path, str] = {}
    for owner in OWNERS:
        schema_path = CONTRACTS_ROOT / owner / "wire" / "schema.json"
        artifacts[schema_path] = canonical_json(documents[owner])
        artifacts[UI_GENERATED_DIR / f"{owner}.ts"] = build_owner_typescript(
            owner, global_defs
        )
    artifacts[UI_GENERATED_DIR / "index.ts"] = build_index_typescript()
    return artifacts


def check_stale_files(artifacts: dict[Path, str]) -> list[Path]:
    """Return generated-tree files the generator does not own.

    Args:
        artifacts: Expected artifact paths to their content.

    Returns:
        Stale or unexpected paths under the generated trees.
    """
    stale: list[Path] = []
    for directory in [
        UI_GENERATED_DIR,
        *(CONTRACTS_ROOT / owner / "wire" for owner in OWNERS),
    ]:
        if not directory.exists():
            continue
        for path in directory.iterdir():
            if path.is_file() and path not in artifacts:
                stale.append(path)
    return stale


def write_mode() -> int:
    """Write every artifact to disk and report the result.

    Returns:
        Process exit status.
    """
    artifacts = render_artifacts()
    for path, content in artifacts.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    for path in check_stale_files(artifacts):
        print(f"stale generated file remains: {path}")
    print(f"wrote {len(artifacts)} contract artifacts")
    return 0


def check_mode() -> int:
    """Compare rendered artifacts with the working tree.

    Returns:
        Process exit status; nonzero when any artifact is missing, stale,
        or an unexpected file exists in the generated trees.
    """
    artifacts = render_artifacts()
    failures = 0
    for path, content in sorted(artifacts.items()):
        on_disk = path.read_text(encoding="utf-8") if path.exists() else None
        if on_disk is None:
            print(f"missing: {path}")
            failures += 1
        elif on_disk.replace("\r\n", "\n") != content.replace("\r\n", "\n"):
            print(f"stale: {path}")
            failures += 1
    for path in check_stale_files(artifacts):
        print(f"unexpected generated file: {path}")
        failures += 1
    print(f"checked {len(artifacts)} artifacts: {failures} problem(s)")
    return 1 if failures else 0


def main(argv: Sequence[str] | None = None) -> int:
    """Run the generator in write or check mode.

    Args:
        argv: Optional argument vector; defaults to process arguments.

    Returns:
        Process exit status.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated artifacts match the contracts without writing",
    )
    args = parser.parse_args(argv)
    return check_mode() if args.check else write_mode()


if __name__ == "__main__":
    sys.exit(main())
