import type { Job, ModuleId, Strategy } from '../app/types';
import { strategies } from './fixtures';

export interface ResearchService { start(kind: ModuleId): Promise<Job>; createCandidates(count: number): Promise<Strategy[]>; retest(strategy: Strategy): Promise<Strategy>; exportStrategy(strategy: Strategy, target: string): Promise<Blob>; }
const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export const mockResearchService: ResearchService = {
  async start(kind) { await wait(180); return { id: `job-${Date.now()}`, kind, status: 'running', progress: 1, accepted: 0, rejected: 0, startedAt: new Date().toISOString(), message: `${kind} mock engine initialized` }; },
  async createCandidates(count) { await wait(220); return strategies.slice(0, Math.min(count, 12)); },
  async retest(strategy) { await wait(260); return { ...strategy, id: `${strategy.id}-r${strategy.revision + 1}`, revision: strategy.revision + 1, name: `${strategy.name} · Retest`, metrics: { ...strategy.metrics, netProfit: Math.round(strategy.metrics.netProfit * .93), maxDrawdown: Math.round(strategy.metrics.maxDrawdown * 1.08) } }; },
  async exportStrategy(strategy, target) { await wait(100); return new Blob([`// Illustrative ${target} source generated by the SQX frontend mock\n// ${strategy.name}, revision ${strategy.revision}\n// Parameters: ${JSON.stringify(strategy.parameters)}\n\nfunction onBar() {\n  if (ema(12) > ema(28)) enterLong();\n}`], { type: 'text/plain' }); },
};
