# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from enum import IntEnum
from typing import Final


class ENUM_ALIGN_MODE(IntEnum):
    """Defines the identifier set for align mode."""

    ALIGN_LEFT = 0
    ALIGN_CENTER = 1
    ALIGN_RIGHT = 2


ALIGN_LEFT: Final = ENUM_ALIGN_MODE.ALIGN_LEFT
ALIGN_CENTER: Final = ENUM_ALIGN_MODE.ALIGN_CENTER
ALIGN_RIGHT: Final = ENUM_ALIGN_MODE.ALIGN_RIGHT


class ENUM_ANCHOR_POINT(IntEnum):
    """Defines the identifier set for anchor point."""

    ANCHOR_LEFT_UPPER = 0
    ANCHOR_LEFT = 1
    ANCHOR_LEFT_LOWER = 2
    ANCHOR_LOWER = 3
    ANCHOR_RIGHT_LOWER = 4
    ANCHOR_RIGHT = 5
    ANCHOR_RIGHT_UPPER = 6
    ANCHOR_UPPER = 7
    ANCHOR_CENTER = 8


ANCHOR_LEFT_UPPER: Final = ENUM_ANCHOR_POINT.ANCHOR_LEFT_UPPER
ANCHOR_LEFT: Final = ENUM_ANCHOR_POINT.ANCHOR_LEFT
ANCHOR_LEFT_LOWER: Final = ENUM_ANCHOR_POINT.ANCHOR_LEFT_LOWER
ANCHOR_LOWER: Final = ENUM_ANCHOR_POINT.ANCHOR_LOWER
ANCHOR_RIGHT_LOWER: Final = ENUM_ANCHOR_POINT.ANCHOR_RIGHT_LOWER
ANCHOR_RIGHT: Final = ENUM_ANCHOR_POINT.ANCHOR_RIGHT
ANCHOR_RIGHT_UPPER: Final = ENUM_ANCHOR_POINT.ANCHOR_RIGHT_UPPER
ANCHOR_UPPER: Final = ENUM_ANCHOR_POINT.ANCHOR_UPPER
ANCHOR_CENTER: Final = ENUM_ANCHOR_POINT.ANCHOR_CENTER


class ENUM_ARROW_ANCHOR(IntEnum):
    """Defines the identifier set for arrow anchor."""

    ANCHOR_TOP = 0
    ANCHOR_BOTTOM = 1


ANCHOR_TOP: Final = ENUM_ARROW_ANCHOR.ANCHOR_TOP
ANCHOR_BOTTOM: Final = ENUM_ARROW_ANCHOR.ANCHOR_BOTTOM


class ENUM_BASE_CORNER(IntEnum):
    """Defines the identifier set for base corner."""

    CORNER_LEFT_UPPER = 0
    CORNER_LEFT_LOWER = 1
    CORNER_RIGHT_LOWER = 2
    CORNER_RIGHT_UPPER = 3


CORNER_LEFT_UPPER: Final = ENUM_BASE_CORNER.CORNER_LEFT_UPPER
CORNER_LEFT_LOWER: Final = ENUM_BASE_CORNER.CORNER_LEFT_LOWER
CORNER_RIGHT_LOWER: Final = ENUM_BASE_CORNER.CORNER_RIGHT_LOWER
CORNER_RIGHT_UPPER: Final = ENUM_BASE_CORNER.CORNER_RIGHT_UPPER


class ENUM_BORDER_TYPE(IntEnum):
    """Defines the identifier set for border type."""

    BORDER_FLAT = 0
    BORDER_RAISED = 1
    BORDER_SUNKEN = 2


BORDER_FLAT: Final = ENUM_BORDER_TYPE.BORDER_FLAT
BORDER_RAISED: Final = ENUM_BORDER_TYPE.BORDER_RAISED
BORDER_SUNKEN: Final = ENUM_BORDER_TYPE.BORDER_SUNKEN


class ENUM_CHART_EVENT(IntEnum):
    """Defines the identifier set for chart event."""

    CHARTEVENT_KEYUP = 0
    CHARTEVENT_KEYDOWN = 1
    CHARTEVENT_MOUSE_MOVE = 2
    CHARTEVENT_MOUSE_WHEEL = 3
    CHARTEVENT_OBJECT_CREATE = 4
    CHARTEVENT_OBJECT_CHANGE = 5
    CHARTEVENT_OBJECT_DELETE = 6
    CHARTEVENT_CLICK = 7
    CHARTEVENT_OBJECT_CLICK = 8
    CHARTEVENT_OBJECT_DRAG = 9
    CHARTEVENT_OBJECT_ENDEDIT = 10
    CHARTEVENT_CHART_CHANGE = 11
    CHARTEVENT_CUSTOM = 1000
    CHARTEVENT_CUSTOM_LAST = 66534


CHARTEVENT_KEYUP: Final = ENUM_CHART_EVENT.CHARTEVENT_KEYUP
CHARTEVENT_KEYDOWN: Final = ENUM_CHART_EVENT.CHARTEVENT_KEYDOWN
CHARTEVENT_MOUSE_MOVE: Final = ENUM_CHART_EVENT.CHARTEVENT_MOUSE_MOVE
CHARTEVENT_MOUSE_WHEEL: Final = ENUM_CHART_EVENT.CHARTEVENT_MOUSE_WHEEL
CHARTEVENT_OBJECT_CREATE: Final = ENUM_CHART_EVENT.CHARTEVENT_OBJECT_CREATE
CHARTEVENT_OBJECT_CHANGE: Final = ENUM_CHART_EVENT.CHARTEVENT_OBJECT_CHANGE
CHARTEVENT_OBJECT_DELETE: Final = ENUM_CHART_EVENT.CHARTEVENT_OBJECT_DELETE
CHARTEVENT_CLICK: Final = ENUM_CHART_EVENT.CHARTEVENT_CLICK
CHARTEVENT_OBJECT_CLICK: Final = ENUM_CHART_EVENT.CHARTEVENT_OBJECT_CLICK
CHARTEVENT_OBJECT_DRAG: Final = ENUM_CHART_EVENT.CHARTEVENT_OBJECT_DRAG
CHARTEVENT_OBJECT_ENDEDIT: Final = ENUM_CHART_EVENT.CHARTEVENT_OBJECT_ENDEDIT
CHARTEVENT_CHART_CHANGE: Final = ENUM_CHART_EVENT.CHARTEVENT_CHART_CHANGE
CHARTEVENT_CUSTOM: Final = ENUM_CHART_EVENT.CHARTEVENT_CUSTOM
CHARTEVENT_CUSTOM_LAST: Final = ENUM_CHART_EVENT.CHARTEVENT_CUSTOM_LAST


class ENUM_CHART_MODE(IntEnum):
    """Defines the identifier set for chart mode."""

    CHART_BARS = 0
    CHART_LINE = 1


CHART_BARS: Final = ENUM_CHART_MODE.CHART_BARS
CHART_LINE: Final = ENUM_CHART_MODE.CHART_LINE


class ENUM_CHART_POSITION(IntEnum):
    """Defines the identifier set for chart position."""

    CHART_BEGIN = 0
    CHART_CURRENT_POS = 1
    CHART_END = 2


CHART_BEGIN: Final = ENUM_CHART_POSITION.CHART_BEGIN
CHART_CURRENT_POS: Final = ENUM_CHART_POSITION.CHART_CURRENT_POS
CHART_END: Final = ENUM_CHART_POSITION.CHART_END


class ENUM_CHART_PROPERTY_DOUBLE(IntEnum):
    """Defines the identifier set for chart property double."""

    CHART_FLOAT_BOTTOM = 0
    CHART_SHIFT_SIZE = 1
    CHART_FIXED_POSITION = 2
    CHART_FIXED_MAX = 3
    CHART_FIXED_MIN = 4
    CHART_POINTS_PER_BAR = 5
    CHART_PRICE_MIN = 6
    CHART_PRICE_MAX = 7


CHART_FLOAT_BOTTOM: Final = ENUM_CHART_PROPERTY_DOUBLE.CHART_FLOAT_BOTTOM
CHART_SHIFT_SIZE: Final = ENUM_CHART_PROPERTY_DOUBLE.CHART_SHIFT_SIZE
CHART_FIXED_POSITION: Final = ENUM_CHART_PROPERTY_DOUBLE.CHART_FIXED_POSITION
CHART_FIXED_MAX: Final = ENUM_CHART_PROPERTY_DOUBLE.CHART_FIXED_MAX
CHART_FIXED_MIN: Final = ENUM_CHART_PROPERTY_DOUBLE.CHART_FIXED_MIN
CHART_POINTS_PER_BAR: Final = ENUM_CHART_PROPERTY_DOUBLE.CHART_POINTS_PER_BAR
CHART_PRICE_MIN: Final = ENUM_CHART_PROPERTY_DOUBLE.CHART_PRICE_MIN
CHART_PRICE_MAX: Final = ENUM_CHART_PROPERTY_DOUBLE.CHART_PRICE_MAX


class ENUM_CHART_PROPERTY_INTEGER(IntEnum):
    """Defines the identifier set for chart property integer."""

    CHART_SHOW = 0
    CHART_IS_OBJECT = 1
    CHART_BRING_TO_TOP = 2
    CHART_CONTEXT_MENU = 3
    CHART_CROSSHAIR_TOOL = 4
    CHART_MOUSE_SCROLL = 5
    CHART_EVENT_MOUSE_WHEEL = 6
    CHART_EVENT_MOUSE_MOVE = 7
    CHART_EVENT_OBJECT_CREATE = 8
    CHART_EVENT_OBJECT_DELETE = 9
    CHART_MODE = 10
    CHART_FOREGROUND = 11
    CHART_SHIFT = 12
    CHART_AUTOSCROLL = 13
    CHART_KEYBOARD_CONTROL = 14
    CHART_QUICK_NAVIGATION = 15
    CHART_SCALE = 16
    CHART_SCALEFIX = 17
    CHART_SCALEFIX_11 = 18
    CHART_SCALE_PT_PER_BAR = 19
    CHART_SHOW_TICKER = 20
    CHART_SHOW_OHLC = 21
    CHART_SHOW_BID_LINE = 22
    CHART_SHOW_ASK_LINE = 23
    CHART_SHOW_LAST_LINE = 24
    CHART_SHOW_PERIOD_SEP = 25
    CHART_SHOW_GRID = 26
    CHART_SHOW_VOLUMES = 27
    CHART_SHOW_OBJECT_DESCR = 28
    CHART_SHOW_TRADE_HISTORY = 29
    CHART_VISIBLE_BARS = 30
    CHART_WINDOWS_TOTAL = 31
    CHART_WINDOW_IS_VISIBLE = 32
    CHART_WINDOW_HANDLE = 33
    CHART_WINDOW_YDISTANCE = 34
    CHART_FIRST_VISIBLE_BAR = 35
    CHART_WIDTH_IN_BARS = 36
    CHART_WIDTH_IN_PIXELS = 37
    CHART_HEIGHT_IN_PIXELS = 38
    CHART_COLOR_BACKGROUND = 39
    CHART_COLOR_FOREGROUND = 40
    CHART_COLOR_GRID = 41
    CHART_COLOR_VOLUME = 42
    CHART_COLOR_CHART_UP = 43
    CHART_COLOR_CHART_DOWN = 44
    CHART_COLOR_CHART_LINE = 45
    CHART_COLOR_CANDLE_BULL = 46
    CHART_COLOR_CANDLE_BEAR = 47
    CHART_COLOR_BID = 48
    CHART_COLOR_ASK = 49
    CHART_COLOR_LAST = 50
    CHART_COLOR_STOP_LEVEL = 51
    CHART_SHOW_TRADE_LEVELS = 52
    CHART_DRAG_TRADE_LEVELS = 53
    CHART_SHOW_DATE_SCALE = 54
    CHART_SHOW_PRICE_SCALE = 55
    CHART_SHOW_ONE_CLICK = 56
    CHART_IS_MAXIMIZED = 57
    CHART_IS_MINIMIZED = 58
    CHART_IS_DOCKED = 59
    CHART_FLOAT_LEFT = 60
    CHART_FLOAT_TOP = 61
    CHART_FLOAT_RIGHT = 62


CHART_SHOW: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW
CHART_IS_OBJECT: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_IS_OBJECT
CHART_BRING_TO_TOP: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_BRING_TO_TOP
CHART_CONTEXT_MENU: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_CONTEXT_MENU
CHART_CROSSHAIR_TOOL: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_CROSSHAIR_TOOL
CHART_MOUSE_SCROLL: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_MOUSE_SCROLL
CHART_EVENT_MOUSE_WHEEL: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_EVENT_MOUSE_WHEEL
CHART_EVENT_MOUSE_MOVE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_EVENT_MOUSE_MOVE
CHART_EVENT_OBJECT_CREATE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_EVENT_OBJECT_CREATE
CHART_EVENT_OBJECT_DELETE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_EVENT_OBJECT_DELETE
CHART_MODE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_MODE
CHART_FOREGROUND: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_FOREGROUND
CHART_SHIFT: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHIFT
CHART_AUTOSCROLL: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_AUTOSCROLL
CHART_KEYBOARD_CONTROL: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_KEYBOARD_CONTROL
CHART_QUICK_NAVIGATION: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_QUICK_NAVIGATION
CHART_SCALE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SCALE
CHART_SCALEFIX: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SCALEFIX
CHART_SCALEFIX_11: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SCALEFIX_11
CHART_SCALE_PT_PER_BAR: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SCALE_PT_PER_BAR
CHART_SHOW_TICKER: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_TICKER
CHART_SHOW_OHLC: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_OHLC
CHART_SHOW_BID_LINE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_BID_LINE
CHART_SHOW_ASK_LINE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_ASK_LINE
CHART_SHOW_LAST_LINE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_LAST_LINE
CHART_SHOW_PERIOD_SEP: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_PERIOD_SEP
CHART_SHOW_GRID: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_GRID
CHART_SHOW_VOLUMES: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_VOLUMES
CHART_SHOW_OBJECT_DESCR: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_OBJECT_DESCR
CHART_SHOW_TRADE_HISTORY: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_TRADE_HISTORY
CHART_VISIBLE_BARS: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_VISIBLE_BARS
CHART_WINDOWS_TOTAL: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_WINDOWS_TOTAL
CHART_WINDOW_IS_VISIBLE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_WINDOW_IS_VISIBLE
CHART_WINDOW_HANDLE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_WINDOW_HANDLE
CHART_WINDOW_YDISTANCE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_WINDOW_YDISTANCE
CHART_FIRST_VISIBLE_BAR: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_FIRST_VISIBLE_BAR
CHART_WIDTH_IN_BARS: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_WIDTH_IN_BARS
CHART_WIDTH_IN_PIXELS: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_WIDTH_IN_PIXELS
CHART_HEIGHT_IN_PIXELS: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_HEIGHT_IN_PIXELS
CHART_COLOR_BACKGROUND: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_COLOR_BACKGROUND
CHART_COLOR_FOREGROUND: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_COLOR_FOREGROUND
CHART_COLOR_GRID: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_COLOR_GRID
CHART_COLOR_VOLUME: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_COLOR_VOLUME
CHART_COLOR_CHART_UP: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_COLOR_CHART_UP
CHART_COLOR_CHART_DOWN: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_COLOR_CHART_DOWN
CHART_COLOR_CHART_LINE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_COLOR_CHART_LINE
CHART_COLOR_CANDLE_BULL: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_COLOR_CANDLE_BULL
CHART_COLOR_CANDLE_BEAR: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_COLOR_CANDLE_BEAR
CHART_COLOR_BID: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_COLOR_BID
CHART_COLOR_ASK: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_COLOR_ASK
CHART_COLOR_LAST: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_COLOR_LAST
CHART_COLOR_STOP_LEVEL: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_COLOR_STOP_LEVEL
CHART_SHOW_TRADE_LEVELS: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_TRADE_LEVELS
CHART_DRAG_TRADE_LEVELS: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_DRAG_TRADE_LEVELS
CHART_SHOW_DATE_SCALE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_DATE_SCALE
CHART_SHOW_PRICE_SCALE: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_PRICE_SCALE
CHART_SHOW_ONE_CLICK: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_SHOW_ONE_CLICK
CHART_IS_MAXIMIZED: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_IS_MAXIMIZED
CHART_IS_MINIMIZED: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_IS_MINIMIZED
CHART_IS_DOCKED: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_IS_DOCKED
CHART_FLOAT_LEFT: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_FLOAT_LEFT
CHART_FLOAT_TOP: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_FLOAT_TOP
CHART_FLOAT_RIGHT: Final = ENUM_CHART_PROPERTY_INTEGER.CHART_FLOAT_RIGHT


class ENUM_CHART_PROPERTY_STRING(IntEnum):
    """Defines the identifier set for chart property string."""

    CHART_COMMENT = 0
    CHART_AUTOMATION_NAME = 1
    CHART_SCRIPT_NAME = 2


CHART_COMMENT: Final = ENUM_CHART_PROPERTY_STRING.CHART_COMMENT
CHART_AUTOMATION_NAME: Final = ENUM_CHART_PROPERTY_STRING.CHART_AUTOMATION_NAME
CHART_SCRIPT_NAME: Final = ENUM_CHART_PROPERTY_STRING.CHART_SCRIPT_NAME


class ENUM_CHART_VOLUME_MODE(IntEnum):
    """Defines the identifier set for chart volume mode."""

    CHART_CANDLES = 0
    CHART_VOLUME_HIDE = 1
    CHART_VOLUME_TICK = 2
    CHART_VOLUME_REAL = 3


CHART_CANDLES: Final = ENUM_CHART_VOLUME_MODE.CHART_CANDLES
CHART_VOLUME_HIDE: Final = ENUM_CHART_VOLUME_MODE.CHART_VOLUME_HIDE
CHART_VOLUME_TICK: Final = ENUM_CHART_VOLUME_MODE.CHART_VOLUME_TICK
CHART_VOLUME_REAL: Final = ENUM_CHART_VOLUME_MODE.CHART_VOLUME_REAL


class ENUM_ELLIOT_WAVE_DEGREE(IntEnum):
    """Defines the identifier set for elliot wave degree."""

    ELLIOTT_GRAND_SUPERCYCLE = 0
    ELLIOTT_SUPERCYCLE = 1
    ELLIOTT_CYCLE = 2
    ELLIOTT_PRIMARY = 3
    ELLIOTT_INTERMEDIATE = 4
    ELLIOTT_MINOR = 5
    ELLIOTT_MINUTE = 6
    ELLIOTT_MINUETTE = 7
    ELLIOTT_SUBMINUETTE = 8


ELLIOTT_GRAND_SUPERCYCLE: Final = ENUM_ELLIOT_WAVE_DEGREE.ELLIOTT_GRAND_SUPERCYCLE
ELLIOTT_SUPERCYCLE: Final = ENUM_ELLIOT_WAVE_DEGREE.ELLIOTT_SUPERCYCLE
ELLIOTT_CYCLE: Final = ENUM_ELLIOT_WAVE_DEGREE.ELLIOTT_CYCLE
ELLIOTT_PRIMARY: Final = ENUM_ELLIOT_WAVE_DEGREE.ELLIOTT_PRIMARY
ELLIOTT_INTERMEDIATE: Final = ENUM_ELLIOT_WAVE_DEGREE.ELLIOTT_INTERMEDIATE
ELLIOTT_MINOR: Final = ENUM_ELLIOT_WAVE_DEGREE.ELLIOTT_MINOR
ELLIOTT_MINUTE: Final = ENUM_ELLIOT_WAVE_DEGREE.ELLIOTT_MINUTE
ELLIOTT_MINUETTE: Final = ENUM_ELLIOT_WAVE_DEGREE.ELLIOTT_MINUETTE
ELLIOTT_SUBMINUETTE: Final = ENUM_ELLIOT_WAVE_DEGREE.ELLIOTT_SUBMINUETTE


class ENUM_GANN_DIRECTION(IntEnum):
    """Defines the identifier set for gann direction."""

    GANN_UP_TREND = 0
    GANN_DOWN_TREND = 1


GANN_UP_TREND: Final = ENUM_GANN_DIRECTION.GANN_UP_TREND
GANN_DOWN_TREND: Final = ENUM_GANN_DIRECTION.GANN_DOWN_TREND

CHARTS_MAX: Final[int] = 100

__all__ = [
    "ALIGN_CENTER",
    "ALIGN_LEFT",
    "ALIGN_RIGHT",
    "ANCHOR_BOTTOM",
    "ANCHOR_CENTER",
    "ANCHOR_LEFT",
    "ANCHOR_LEFT_LOWER",
    "ANCHOR_LEFT_UPPER",
    "ANCHOR_LOWER",
    "ANCHOR_RIGHT",
    "ANCHOR_RIGHT_LOWER",
    "ANCHOR_RIGHT_UPPER",
    "ANCHOR_TOP",
    "ANCHOR_UPPER",
    "BORDER_FLAT",
    "BORDER_RAISED",
    "BORDER_SUNKEN",
    "CHART_AUTOMATION_NAME",
    "CHART_AUTOSCROLL",
    "CHART_BARS",
    "CHART_BEGIN",
    "CHART_BRING_TO_TOP",
    "CHART_CANDLES",
    "CHART_COLOR_ASK",
    "CHART_COLOR_BACKGROUND",
    "CHART_COLOR_BID",
    "CHART_COLOR_CANDLE_BEAR",
    "CHART_COLOR_CANDLE_BULL",
    "CHART_COLOR_CHART_DOWN",
    "CHART_COLOR_CHART_LINE",
    "CHART_COLOR_CHART_UP",
    "CHART_COLOR_FOREGROUND",
    "CHART_COLOR_GRID",
    "CHART_COLOR_LAST",
    "CHART_COLOR_STOP_LEVEL",
    "CHART_COLOR_VOLUME",
    "CHART_COMMENT",
    "CHART_CONTEXT_MENU",
    "CHART_CROSSHAIR_TOOL",
    "CHART_CURRENT_POS",
    "CHART_DRAG_TRADE_LEVELS",
    "CHART_END",
    "CHART_EVENT_MOUSE_MOVE",
    "CHART_EVENT_MOUSE_WHEEL",
    "CHART_EVENT_OBJECT_CREATE",
    "CHART_EVENT_OBJECT_DELETE",
    "CHART_FIRST_VISIBLE_BAR",
    "CHART_FIXED_MAX",
    "CHART_FIXED_MIN",
    "CHART_FIXED_POSITION",
    "CHART_FLOAT_BOTTOM",
    "CHART_FLOAT_LEFT",
    "CHART_FLOAT_RIGHT",
    "CHART_FLOAT_TOP",
    "CHART_FOREGROUND",
    "CHART_HEIGHT_IN_PIXELS",
    "CHART_IS_DOCKED",
    "CHART_IS_MAXIMIZED",
    "CHART_IS_MINIMIZED",
    "CHART_IS_OBJECT",
    "CHART_KEYBOARD_CONTROL",
    "CHART_LINE",
    "CHART_MODE",
    "CHART_MOUSE_SCROLL",
    "CHART_POINTS_PER_BAR",
    "CHART_PRICE_MAX",
    "CHART_PRICE_MIN",
    "CHART_QUICK_NAVIGATION",
    "CHART_SCALE",
    "CHART_SCALE_PT_PER_BAR",
    "CHART_SCALEFIX",
    "CHART_SCALEFIX_11",
    "CHART_SCRIPT_NAME",
    "CHART_SHIFT",
    "CHART_SHIFT_SIZE",
    "CHART_SHOW",
    "CHART_SHOW_ASK_LINE",
    "CHART_SHOW_BID_LINE",
    "CHART_SHOW_DATE_SCALE",
    "CHART_SHOW_GRID",
    "CHART_SHOW_LAST_LINE",
    "CHART_SHOW_OBJECT_DESCR",
    "CHART_SHOW_OHLC",
    "CHART_SHOW_ONE_CLICK",
    "CHART_SHOW_PERIOD_SEP",
    "CHART_SHOW_PRICE_SCALE",
    "CHART_SHOW_TICKER",
    "CHART_SHOW_TRADE_HISTORY",
    "CHART_SHOW_TRADE_LEVELS",
    "CHART_SHOW_VOLUMES",
    "CHART_VISIBLE_BARS",
    "CHART_VOLUME_HIDE",
    "CHART_VOLUME_REAL",
    "CHART_VOLUME_TICK",
    "CHART_WIDTH_IN_BARS",
    "CHART_WIDTH_IN_PIXELS",
    "CHART_WINDOW_HANDLE",
    "CHART_WINDOW_IS_VISIBLE",
    "CHART_WINDOW_YDISTANCE",
    "CHART_WINDOWS_TOTAL",
    "CHARTEVENT_CHART_CHANGE",
    "CHARTEVENT_CLICK",
    "CHARTEVENT_CUSTOM",
    "CHARTEVENT_CUSTOM_LAST",
    "CHARTEVENT_KEYDOWN",
    "CHARTEVENT_KEYUP",
    "CHARTEVENT_MOUSE_MOVE",
    "CHARTEVENT_MOUSE_WHEEL",
    "CHARTEVENT_OBJECT_CHANGE",
    "CHARTEVENT_OBJECT_CLICK",
    "CHARTEVENT_OBJECT_CREATE",
    "CHARTEVENT_OBJECT_DELETE",
    "CHARTEVENT_OBJECT_DRAG",
    "CHARTEVENT_OBJECT_ENDEDIT",
    "CHARTS_MAX",
    "CORNER_LEFT_LOWER",
    "CORNER_LEFT_UPPER",
    "CORNER_RIGHT_LOWER",
    "CORNER_RIGHT_UPPER",
    "ELLIOTT_CYCLE",
    "ELLIOTT_GRAND_SUPERCYCLE",
    "ELLIOTT_INTERMEDIATE",
    "ELLIOTT_MINOR",
    "ELLIOTT_MINUETTE",
    "ELLIOTT_MINUTE",
    "ELLIOTT_PRIMARY",
    "ELLIOTT_SUBMINUETTE",
    "ELLIOTT_SUPERCYCLE",
    "ENUM_ALIGN_MODE",
    "ENUM_ANCHOR_POINT",
    "ENUM_ARROW_ANCHOR",
    "ENUM_BASE_CORNER",
    "ENUM_BORDER_TYPE",
    "ENUM_CHART_EVENT",
    "ENUM_CHART_MODE",
    "ENUM_CHART_POSITION",
    "ENUM_CHART_PROPERTY_DOUBLE",
    "ENUM_CHART_PROPERTY_INTEGER",
    "ENUM_CHART_PROPERTY_STRING",
    "ENUM_CHART_VOLUME_MODE",
    "ENUM_ELLIOT_WAVE_DEGREE",
    "ENUM_GANN_DIRECTION",
    "GANN_DOWN_TREND",
    "GANN_UP_TREND",
]
