# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from typing import Final

ERR_CHART_WRONG_ID: Final[int] = 4101
ERR_CHART_NO_REPLY: Final[int] = 4102
ERR_CHART_NOT_FOUND: Final[int] = 4103
ERR_CHART_NO_EXPERT: Final[int] = 4104
ERR_CHART_CANNOT_OPEN: Final[int] = 4105
ERR_CHART_CANNOT_CHANGE: Final[int] = 4106
ERR_CHART_WRONG_PARAMETER: Final[int] = 4107
ERR_CHART_CANNOT_CREATE_TIMER: Final[int] = 4108
ERR_CHART_WRONG_PROPERTY: Final[int] = 4109
ERR_CHART_SCREENSHOT_FAILED: Final[int] = 4110
ERR_CHART_NAVIGATE_FAILED: Final[int] = 4111
ERR_CHART_TEMPLATE_FAILED: Final[int] = 4112
ERR_CHART_WINDOW_NOT_FOUND: Final[int] = 4113
ERR_CHART_INDICATOR_CANNOT_ADD: Final[int] = 4114
ERR_CHART_INDICATOR_CANNOT_DEL: Final[int] = 4115
ERR_CHART_INDICATOR_NOT_FOUND: Final[int] = 4116

__all__ = [
    "ERR_CHART_CANNOT_CHANGE",
    "ERR_CHART_CANNOT_CREATE_TIMER",
    "ERR_CHART_CANNOT_OPEN",
    "ERR_CHART_INDICATOR_CANNOT_ADD",
    "ERR_CHART_INDICATOR_CANNOT_DEL",
    "ERR_CHART_INDICATOR_NOT_FOUND",
    "ERR_CHART_NAVIGATE_FAILED",
    "ERR_CHART_NO_EXPERT",
    "ERR_CHART_NO_REPLY",
    "ERR_CHART_NOT_FOUND",
    "ERR_CHART_SCREENSHOT_FAILED",
    "ERR_CHART_TEMPLATE_FAILED",
    "ERR_CHART_WINDOW_NOT_FOUND",
    "ERR_CHART_WRONG_ID",
    "ERR_CHART_WRONG_PARAMETER",
    "ERR_CHART_WRONG_PROPERTY",
]
