# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from enum import IntEnum
from typing import Final


class ENUM_OBJECT(IntEnum):
    """Defines the identifier set for object."""

    OBJ_VLINE = 0
    OBJ_HLINE = 1
    OBJ_TREND = 2
    OBJ_TRENDBYANGLE = 3
    OBJ_CYCLES = 4
    OBJ_ARROWED_LINE = 5
    OBJ_CHANNEL = 6
    OBJ_STDDEVCHANNEL = 7
    OBJ_REGRESSION = 8
    OBJ_PITCHFORK = 9
    OBJ_GANNLINE = 10
    OBJ_GANNFAN = 11
    OBJ_GANNGRID = 12
    OBJ_FIBO = 13
    OBJ_FIBOTIMES = 14
    OBJ_FIBOFAN = 15
    OBJ_FIBOARC = 16
    OBJ_FIBOCHANNEL = 17
    OBJ_EXPANSION = 18
    OBJ_ELLIOTWAVE5 = 19
    OBJ_ELLIOTWAVE3 = 20
    OBJ_RECTANGLE = 21
    OBJ_TRIANGLE = 22
    OBJ_ELLIPSE = 23
    OBJ_ARROW_THUMB_UP = 24
    OBJ_ARROW_THUMB_DOWN = 25
    OBJ_ARROW_UP = 26
    OBJ_ARROW_DOWN = 27
    OBJ_ARROW_STOP = 28
    OBJ_ARROW_CHECK = 29
    OBJ_ARROW_LEFT_PRICE = 30
    OBJ_ARROW_RIGHT_PRICE = 31
    OBJ_ARROW_BUY = 32
    OBJ_ARROW_SELL = 33
    OBJ_ARROW = 34
    OBJ_TEXT = 35
    OBJ_LABEL = 36
    OBJ_BUTTON = 37
    OBJ_CHART = 38
    OBJ_BITMAP = 39
    OBJ_BITMAP_LABEL = 40
    OBJ_EDIT = 41
    OBJ_EVENT = 42
    OBJ_RECTANGLE_LABEL = 43


OBJ_VLINE: Final = ENUM_OBJECT.OBJ_VLINE
OBJ_HLINE: Final = ENUM_OBJECT.OBJ_HLINE
OBJ_TREND: Final = ENUM_OBJECT.OBJ_TREND
OBJ_TRENDBYANGLE: Final = ENUM_OBJECT.OBJ_TRENDBYANGLE
OBJ_CYCLES: Final = ENUM_OBJECT.OBJ_CYCLES
OBJ_ARROWED_LINE: Final = ENUM_OBJECT.OBJ_ARROWED_LINE
OBJ_CHANNEL: Final = ENUM_OBJECT.OBJ_CHANNEL
OBJ_STDDEVCHANNEL: Final = ENUM_OBJECT.OBJ_STDDEVCHANNEL
OBJ_REGRESSION: Final = ENUM_OBJECT.OBJ_REGRESSION
OBJ_PITCHFORK: Final = ENUM_OBJECT.OBJ_PITCHFORK
OBJ_GANNLINE: Final = ENUM_OBJECT.OBJ_GANNLINE
OBJ_GANNFAN: Final = ENUM_OBJECT.OBJ_GANNFAN
OBJ_GANNGRID: Final = ENUM_OBJECT.OBJ_GANNGRID
OBJ_FIBO: Final = ENUM_OBJECT.OBJ_FIBO
OBJ_FIBOTIMES: Final = ENUM_OBJECT.OBJ_FIBOTIMES
OBJ_FIBOFAN: Final = ENUM_OBJECT.OBJ_FIBOFAN
OBJ_FIBOARC: Final = ENUM_OBJECT.OBJ_FIBOARC
OBJ_FIBOCHANNEL: Final = ENUM_OBJECT.OBJ_FIBOCHANNEL
OBJ_EXPANSION: Final = ENUM_OBJECT.OBJ_EXPANSION
OBJ_ELLIOTWAVE5: Final = ENUM_OBJECT.OBJ_ELLIOTWAVE5
OBJ_ELLIOTWAVE3: Final = ENUM_OBJECT.OBJ_ELLIOTWAVE3
OBJ_RECTANGLE: Final = ENUM_OBJECT.OBJ_RECTANGLE
OBJ_TRIANGLE: Final = ENUM_OBJECT.OBJ_TRIANGLE
OBJ_ELLIPSE: Final = ENUM_OBJECT.OBJ_ELLIPSE
OBJ_ARROW_THUMB_UP: Final = ENUM_OBJECT.OBJ_ARROW_THUMB_UP
OBJ_ARROW_THUMB_DOWN: Final = ENUM_OBJECT.OBJ_ARROW_THUMB_DOWN
OBJ_ARROW_UP: Final = ENUM_OBJECT.OBJ_ARROW_UP
OBJ_ARROW_DOWN: Final = ENUM_OBJECT.OBJ_ARROW_DOWN
OBJ_ARROW_STOP: Final = ENUM_OBJECT.OBJ_ARROW_STOP
OBJ_ARROW_CHECK: Final = ENUM_OBJECT.OBJ_ARROW_CHECK
OBJ_ARROW_LEFT_PRICE: Final = ENUM_OBJECT.OBJ_ARROW_LEFT_PRICE
OBJ_ARROW_RIGHT_PRICE: Final = ENUM_OBJECT.OBJ_ARROW_RIGHT_PRICE
OBJ_ARROW_BUY: Final = ENUM_OBJECT.OBJ_ARROW_BUY
OBJ_ARROW_SELL: Final = ENUM_OBJECT.OBJ_ARROW_SELL
OBJ_ARROW: Final = ENUM_OBJECT.OBJ_ARROW
OBJ_TEXT: Final = ENUM_OBJECT.OBJ_TEXT
OBJ_LABEL: Final = ENUM_OBJECT.OBJ_LABEL
OBJ_BUTTON: Final = ENUM_OBJECT.OBJ_BUTTON
OBJ_CHART: Final = ENUM_OBJECT.OBJ_CHART
OBJ_BITMAP: Final = ENUM_OBJECT.OBJ_BITMAP
OBJ_BITMAP_LABEL: Final = ENUM_OBJECT.OBJ_BITMAP_LABEL
OBJ_EDIT: Final = ENUM_OBJECT.OBJ_EDIT
OBJ_EVENT: Final = ENUM_OBJECT.OBJ_EVENT
OBJ_RECTANGLE_LABEL: Final = ENUM_OBJECT.OBJ_RECTANGLE_LABEL


class ENUM_OBJECT_PROPERTY_DOUBLE(IntEnum):
    """Defines the identifier set for object property double."""

    OBJPROP_PRICE = 0
    OBJPROP_LEVELVALUE = 1
    OBJPROP_SCALE = 2
    OBJPROP_ANGLE = 3


OBJPROP_PRICE: Final = ENUM_OBJECT_PROPERTY_DOUBLE.OBJPROP_PRICE
OBJPROP_LEVELVALUE: Final = ENUM_OBJECT_PROPERTY_DOUBLE.OBJPROP_LEVELVALUE
OBJPROP_SCALE: Final = ENUM_OBJECT_PROPERTY_DOUBLE.OBJPROP_SCALE
OBJPROP_ANGLE: Final = ENUM_OBJECT_PROPERTY_DOUBLE.OBJPROP_ANGLE


class ENUM_OBJECT_PROPERTY_INTEGER(IntEnum):
    """Defines the identifier set for object property integer."""

    OBJPROP_COLOR = 0
    OBJPROP_STYLE = 1
    OBJPROP_WIDTH = 2
    OBJPROP_BACK = 3
    OBJPROP_ZORDER = 4
    OBJPROP_FILL = 5
    OBJPROP_HIDDEN = 6
    OBJPROP_SELECTED = 7
    OBJPROP_READONLY = 8
    OBJPROP_TYPE = 9
    OBJPROP_TIME = 10
    OBJPROP_SELECTABLE = 11
    OBJPROP_CREATETIME = 12
    OBJPROP_LEVELS = 13
    OBJPROP_LEVELCOLOR = 14
    OBJPROP_LEVELSTYLE = 15
    OBJPROP_LEVELWIDTH = 16
    OBJPROP_ALIGN = 17
    OBJPROP_FONTSIZE = 18
    OBJPROP_RAY_LEFT = 19
    OBJPROP_RAY_RIGHT = 20
    OBJPROP_RAY = 21
    OBJPROP_ELLIPSE = 22
    OBJPROP_ARROWCODE = 23
    OBJPROP_TIMEFRAMES = 24
    OBJPROP_ANCHOR = 25
    OBJPROP_XDISTANCE = 26
    OBJPROP_YDISTANCE = 27
    OBJPROP_DIRECTION = 28
    OBJPROP_DEGREE = 29
    OBJPROP_DRAWLINES = 30
    OBJPROP_STATE = 31
    OBJPROP_CHART_ID = 32
    OBJPROP_XSIZE = 33
    OBJPROP_YSIZE = 34
    OBJPROP_XOFFSET = 35
    OBJPROP_YOFFSET = 36
    OBJPROP_PERIOD = 37
    OBJPROP_DATE_SCALE = 38
    OBJPROP_PRICE_SCALE = 39
    OBJPROP_CHART_SCALE = 40
    OBJPROP_BGCOLOR = 41
    OBJPROP_CORNER = 42
    OBJPROP_BORDER_TYPE = 43
    OBJPROP_BORDER_COLOR = 44


OBJPROP_COLOR: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_COLOR
OBJPROP_STYLE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_STYLE
OBJPROP_WIDTH: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_WIDTH
OBJPROP_BACK: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_BACK
OBJPROP_ZORDER: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_ZORDER
OBJPROP_FILL: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_FILL
OBJPROP_HIDDEN: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_HIDDEN
OBJPROP_SELECTED: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_SELECTED
OBJPROP_READONLY: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_READONLY
OBJPROP_TYPE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_TYPE
OBJPROP_TIME: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_TIME
OBJPROP_SELECTABLE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_SELECTABLE
OBJPROP_CREATETIME: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_CREATETIME
OBJPROP_LEVELS: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_LEVELS
OBJPROP_LEVELCOLOR: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_LEVELCOLOR
OBJPROP_LEVELSTYLE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_LEVELSTYLE
OBJPROP_LEVELWIDTH: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_LEVELWIDTH
OBJPROP_ALIGN: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_ALIGN
OBJPROP_FONTSIZE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_FONTSIZE
OBJPROP_RAY_LEFT: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_RAY_LEFT
OBJPROP_RAY_RIGHT: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_RAY_RIGHT
OBJPROP_RAY: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_RAY
OBJPROP_ELLIPSE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_ELLIPSE
OBJPROP_ARROWCODE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_ARROWCODE
OBJPROP_TIMEFRAMES: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_TIMEFRAMES
OBJPROP_ANCHOR: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_ANCHOR
OBJPROP_XDISTANCE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_XDISTANCE
OBJPROP_YDISTANCE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_YDISTANCE
OBJPROP_DIRECTION: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_DIRECTION
OBJPROP_DEGREE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_DEGREE
OBJPROP_DRAWLINES: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_DRAWLINES
OBJPROP_STATE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_STATE
OBJPROP_CHART_ID: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_CHART_ID
OBJPROP_XSIZE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_XSIZE
OBJPROP_YSIZE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_YSIZE
OBJPROP_XOFFSET: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_XOFFSET
OBJPROP_YOFFSET: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_YOFFSET
OBJPROP_PERIOD: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_PERIOD
OBJPROP_DATE_SCALE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_DATE_SCALE
OBJPROP_PRICE_SCALE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_PRICE_SCALE
OBJPROP_CHART_SCALE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_CHART_SCALE
OBJPROP_BGCOLOR: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_BGCOLOR
OBJPROP_CORNER: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_CORNER
OBJPROP_BORDER_TYPE: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_BORDER_TYPE
OBJPROP_BORDER_COLOR: Final = ENUM_OBJECT_PROPERTY_INTEGER.OBJPROP_BORDER_COLOR


class ENUM_OBJECT_PROPERTY_STRING(IntEnum):
    """Defines the identifier set for object property string."""

    OBJPROP_DEVIATION = 0
    OBJPROP_NAME = 1
    OBJPROP_TEXT = 2
    OBJPROP_TOOLTIP = 3
    OBJPROP_LEVELTEXT = 4
    OBJPROP_FONT = 5
    OBJPROP_BMPFILE = 6
    OBJPROP_SYMBOL = 7


OBJPROP_DEVIATION: Final = ENUM_OBJECT_PROPERTY_STRING.OBJPROP_DEVIATION
OBJPROP_NAME: Final = ENUM_OBJECT_PROPERTY_STRING.OBJPROP_NAME
OBJPROP_TEXT: Final = ENUM_OBJECT_PROPERTY_STRING.OBJPROP_TEXT
OBJPROP_TOOLTIP: Final = ENUM_OBJECT_PROPERTY_STRING.OBJPROP_TOOLTIP
OBJPROP_LEVELTEXT: Final = ENUM_OBJECT_PROPERTY_STRING.OBJPROP_LEVELTEXT
OBJPROP_FONT: Final = ENUM_OBJECT_PROPERTY_STRING.OBJPROP_FONT
OBJPROP_BMPFILE: Final = ENUM_OBJECT_PROPERTY_STRING.OBJPROP_BMPFILE
OBJPROP_SYMBOL: Final = ENUM_OBJECT_PROPERTY_STRING.OBJPROP_SYMBOL

OBJ_NO_PERIODS: Final[int] = 0
OBJ_PERIOD_M1: Final[int] = 1
OBJ_PERIOD_M2: Final[int] = 2
OBJ_PERIOD_M3: Final[int] = 4
OBJ_PERIOD_M4: Final[int] = 8
OBJ_PERIOD_M5: Final[int] = 16
OBJ_PERIOD_M6: Final[int] = 32
OBJ_PERIOD_M10: Final[int] = 64
OBJ_PERIOD_M12: Final[int] = 128
OBJ_PERIOD_M15: Final[int] = 256
OBJ_PERIOD_M20: Final[int] = 512
OBJ_PERIOD_M30: Final[int] = 1024
OBJ_PERIOD_H1: Final[int] = 2048
OBJ_PERIOD_H2: Final[int] = 4096
OBJ_PERIOD_H3: Final[int] = 8192
OBJ_PERIOD_H4: Final[int] = 16384
OBJ_PERIOD_H6: Final[int] = 32768
OBJ_PERIOD_H8: Final[int] = 65536
OBJ_PERIOD_H12: Final[int] = 131072
OBJ_PERIOD_D1: Final[int] = 262144
OBJ_PERIOD_W1: Final[int] = 524288
OBJ_PERIOD_MN1: Final[int] = 1048576
OBJ_ALL_PERIODS: Final[int] = 2097151

__all__ = [
    "ENUM_OBJECT",
    "ENUM_OBJECT_PROPERTY_DOUBLE",
    "ENUM_OBJECT_PROPERTY_INTEGER",
    "ENUM_OBJECT_PROPERTY_STRING",
    "OBJ_ALL_PERIODS",
    "OBJ_ARROW",
    "OBJ_ARROW_BUY",
    "OBJ_ARROW_CHECK",
    "OBJ_ARROW_DOWN",
    "OBJ_ARROW_LEFT_PRICE",
    "OBJ_ARROW_RIGHT_PRICE",
    "OBJ_ARROW_SELL",
    "OBJ_ARROW_STOP",
    "OBJ_ARROW_THUMB_DOWN",
    "OBJ_ARROW_THUMB_UP",
    "OBJ_ARROW_UP",
    "OBJ_ARROWED_LINE",
    "OBJ_BITMAP",
    "OBJ_BITMAP_LABEL",
    "OBJ_BUTTON",
    "OBJ_CHANNEL",
    "OBJ_CHART",
    "OBJ_CYCLES",
    "OBJ_EDIT",
    "OBJ_ELLIOTWAVE3",
    "OBJ_ELLIOTWAVE5",
    "OBJ_ELLIPSE",
    "OBJ_EVENT",
    "OBJ_EXPANSION",
    "OBJ_FIBO",
    "OBJ_FIBOARC",
    "OBJ_FIBOCHANNEL",
    "OBJ_FIBOFAN",
    "OBJ_FIBOTIMES",
    "OBJ_GANNFAN",
    "OBJ_GANNGRID",
    "OBJ_GANNLINE",
    "OBJ_HLINE",
    "OBJ_LABEL",
    "OBJ_NO_PERIODS",
    "OBJ_PERIOD_D1",
    "OBJ_PERIOD_H1",
    "OBJ_PERIOD_H2",
    "OBJ_PERIOD_H3",
    "OBJ_PERIOD_H4",
    "OBJ_PERIOD_H6",
    "OBJ_PERIOD_H8",
    "OBJ_PERIOD_H12",
    "OBJ_PERIOD_M1",
    "OBJ_PERIOD_M2",
    "OBJ_PERIOD_M3",
    "OBJ_PERIOD_M4",
    "OBJ_PERIOD_M5",
    "OBJ_PERIOD_M6",
    "OBJ_PERIOD_M10",
    "OBJ_PERIOD_M12",
    "OBJ_PERIOD_M15",
    "OBJ_PERIOD_M20",
    "OBJ_PERIOD_M30",
    "OBJ_PERIOD_MN1",
    "OBJ_PERIOD_W1",
    "OBJ_PITCHFORK",
    "OBJ_RECTANGLE",
    "OBJ_RECTANGLE_LABEL",
    "OBJ_REGRESSION",
    "OBJ_STDDEVCHANNEL",
    "OBJ_TEXT",
    "OBJ_TREND",
    "OBJ_TRENDBYANGLE",
    "OBJ_TRIANGLE",
    "OBJ_VLINE",
    "OBJPROP_ALIGN",
    "OBJPROP_ANCHOR",
    "OBJPROP_ANGLE",
    "OBJPROP_ARROWCODE",
    "OBJPROP_BACK",
    "OBJPROP_BGCOLOR",
    "OBJPROP_BMPFILE",
    "OBJPROP_BORDER_COLOR",
    "OBJPROP_BORDER_TYPE",
    "OBJPROP_CHART_ID",
    "OBJPROP_CHART_SCALE",
    "OBJPROP_COLOR",
    "OBJPROP_CORNER",
    "OBJPROP_CREATETIME",
    "OBJPROP_DATE_SCALE",
    "OBJPROP_DEGREE",
    "OBJPROP_DEVIATION",
    "OBJPROP_DIRECTION",
    "OBJPROP_DRAWLINES",
    "OBJPROP_ELLIPSE",
    "OBJPROP_FILL",
    "OBJPROP_FONT",
    "OBJPROP_FONTSIZE",
    "OBJPROP_HIDDEN",
    "OBJPROP_LEVELCOLOR",
    "OBJPROP_LEVELS",
    "OBJPROP_LEVELSTYLE",
    "OBJPROP_LEVELTEXT",
    "OBJPROP_LEVELVALUE",
    "OBJPROP_LEVELWIDTH",
    "OBJPROP_NAME",
    "OBJPROP_PERIOD",
    "OBJPROP_PRICE",
    "OBJPROP_PRICE_SCALE",
    "OBJPROP_RAY",
    "OBJPROP_RAY_LEFT",
    "OBJPROP_RAY_RIGHT",
    "OBJPROP_READONLY",
    "OBJPROP_SCALE",
    "OBJPROP_SELECTABLE",
    "OBJPROP_SELECTED",
    "OBJPROP_STATE",
    "OBJPROP_STYLE",
    "OBJPROP_SYMBOL",
    "OBJPROP_TEXT",
    "OBJPROP_TIME",
    "OBJPROP_TIMEFRAMES",
    "OBJPROP_TOOLTIP",
    "OBJPROP_TYPE",
    "OBJPROP_WIDTH",
    "OBJPROP_XDISTANCE",
    "OBJPROP_XOFFSET",
    "OBJPROP_XSIZE",
    "OBJPROP_YDISTANCE",
    "OBJPROP_YOFFSET",
    "OBJPROP_YSIZE",
    "OBJPROP_ZORDER",
]
