# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from enum import IntEnum
from typing import Final


class ENUM_THEME_COLOR(IntEnum):
    """HaruQuantAI UI theme color property identifiers."""

    THEME_COLOR_WINDOW = 50
    THEME_COLOR_WINDOWTEXT = 51
    THEME_COLOR_BTNTEXT = 52
    THEME_COLOR_GRAYTEXT = 53
    THEME_COLOR_INFOTEXT = 54
    THEME_COLOR_INFOBK = 55
    THEME_COLOR_3DFACE = 56
    THEME_COLOR_3DLIGHT = 57
    THEME_COLOR_3DSHADOW = 58
    THEME_COLOR_3DDKSHADOW = 59
    THEME_COLOR_3DHILIGHT = 60
    THEME_COLOR_HIGHLIGHT = 61
    THEME_COLOR_HIGHLIGHTTEXT = 62
    THEME_COLOR_BTNFACE = 63
    THEME_COLOR_BTNHILIGHT = 64
    THEME_COLOR_BTNSHADOW = 65
    THEME_COLOR_MENU = 66
    THEME_COLOR_MENUBAR = 67
    THEME_COLOR_MENUTEXT = 68
    THEME_COLOR_MENUHILIGHT = 69
    THEME_COLOR_ACTIVECAPTION = 70
    THEME_COLOR_INACTIVECAPTION = 71
    THEME_COLOR_GRADIENTINACTIVECAPTION = 72
    THEME_COLOR_CAPTIONTEXT = 73
    THEME_COLOR_INACTIVECAPTIONTEXT = 74
    THEME_COLOR_HOTTEXT = 75
    THEME_COLOR_NONE = 76
    THEME_COLOR_SEPARATOR = 77
    THEME_COLOR_SCROLLBACK = 78
    THEME_COLOR_LINE1 = 79
    THEME_COLOR_LINE2 = 80
    THEME_COLOR_GRID = 81
    THEME_COLOR_SUMMARY = 82
    THEME_COLOR_ERROR = 83
    THEME_COLOR_INVALID = 84
    THEME_COLOR_NEGATIVE = 85
    THEME_COLOR_POSITIVE = 86
    THEME_COLOR_LINK = 87
    THEME_COLOR_LINKHOVER = 88
    THEME_COLOR_LINKTESTER = 89
    THEME_COLOR_TEXTUP = 90
    THEME_COLOR_TEXTDOWN = 91
    THEME_COLOR_BACKUP = 92
    THEME_COLOR_BACKDOWN = 93
    THEME_COLOR_CLOSE = 94
    THEME_COLOR_BUY = 95
    THEME_COLOR_SELL = 96
    THEME_COLOR_DEPOSIT = 97
    THEME_COLOR_WITHDRAWAL = 98
    THEME_COLOR_BID = 99
    THEME_COLOR_ASK = 100
    THEME_COLOR_STOPS = 101
    THEME_COLOR_STOPS_RED = 102
    THEME_COLOR_STOPS_GREEN = 103
    THEME_COLOR_CONFIRM = 104
    THEME_COLOR_REQUOTE = 105
    THEME_COLOR_REJECT = 106
    THEME_COLOR_NOTIFICATION = 107
    THEME_COLOR_RATING = 108
    THEME_COLOR_BOOK_BUY = 109
    THEME_COLOR_BOOK_SELL = 110
    THEME_COLOR_BOOK_LAST = 111
    THEME_COLOR_BOOK_STOP = 112
    THEME_COLOR_BOOK_SPREAD = 113
    THEME_COLOR_TICKS_BID = 114
    THEME_COLOR_TICKS_ASK = 115
    THEME_COLOR_TICKS_LAST = 116
    THEME_COLOR_TICKS_CROSS = 117
    THEME_COLOR_TICKS_SL = 118
    THEME_COLOR_TICKS_TP = 119
    THEME_COLOR_TESTER_START = 120
    THEME_COLOR_TESTER_STOP = 121
    THEME_COLOR_TESTER_START_FRAME = 122
    THEME_COLOR_TESTER_STOP_FRAME = 123
    THEME_COLOR_TESTER_PROGRESS = 124
    THEME_COLOR_TESTER_BALANCE = 125
    THEME_COLOR_TESTER_EQUITY = 126
    THEME_COLOR_TESTER_MARGIN = 127
    THEME_COLOR_PROFILER_CALL = 128
    THEME_COLOR_PROFILER_CALLSEL = 129
    THEME_COLOR_PROFILER_LINE = 130
    THEME_COLOR_PROFILER_LINESEL = 131


THEME_COLOR_WINDOW: Final = ENUM_THEME_COLOR.THEME_COLOR_WINDOW
THEME_COLOR_WINDOWTEXT: Final = ENUM_THEME_COLOR.THEME_COLOR_WINDOWTEXT
THEME_COLOR_BTNTEXT: Final = ENUM_THEME_COLOR.THEME_COLOR_BTNTEXT
THEME_COLOR_GRAYTEXT: Final = ENUM_THEME_COLOR.THEME_COLOR_GRAYTEXT
THEME_COLOR_INFOTEXT: Final = ENUM_THEME_COLOR.THEME_COLOR_INFOTEXT
THEME_COLOR_INFOBK: Final = ENUM_THEME_COLOR.THEME_COLOR_INFOBK
THEME_COLOR_3DFACE: Final = ENUM_THEME_COLOR.THEME_COLOR_3DFACE
THEME_COLOR_3DLIGHT: Final = ENUM_THEME_COLOR.THEME_COLOR_3DLIGHT
THEME_COLOR_3DSHADOW: Final = ENUM_THEME_COLOR.THEME_COLOR_3DSHADOW
THEME_COLOR_3DDKSHADOW: Final = ENUM_THEME_COLOR.THEME_COLOR_3DDKSHADOW
THEME_COLOR_3DHILIGHT: Final = ENUM_THEME_COLOR.THEME_COLOR_3DHILIGHT
THEME_COLOR_HIGHLIGHT: Final = ENUM_THEME_COLOR.THEME_COLOR_HIGHLIGHT
THEME_COLOR_HIGHLIGHTTEXT: Final = ENUM_THEME_COLOR.THEME_COLOR_HIGHLIGHTTEXT
THEME_COLOR_BTNFACE: Final = ENUM_THEME_COLOR.THEME_COLOR_BTNFACE
THEME_COLOR_BTNHILIGHT: Final = ENUM_THEME_COLOR.THEME_COLOR_BTNHILIGHT
THEME_COLOR_BTNSHADOW: Final = ENUM_THEME_COLOR.THEME_COLOR_BTNSHADOW
THEME_COLOR_MENU: Final = ENUM_THEME_COLOR.THEME_COLOR_MENU
THEME_COLOR_MENUBAR: Final = ENUM_THEME_COLOR.THEME_COLOR_MENUBAR
THEME_COLOR_MENUTEXT: Final = ENUM_THEME_COLOR.THEME_COLOR_MENUTEXT
THEME_COLOR_MENUHILIGHT: Final = ENUM_THEME_COLOR.THEME_COLOR_MENUHILIGHT
THEME_COLOR_ACTIVECAPTION: Final = ENUM_THEME_COLOR.THEME_COLOR_ACTIVECAPTION
THEME_COLOR_INACTIVECAPTION: Final = ENUM_THEME_COLOR.THEME_COLOR_INACTIVECAPTION
THEME_COLOR_GRADIENTINACTIVECAPTION: Final = (
    ENUM_THEME_COLOR.THEME_COLOR_GRADIENTINACTIVECAPTION
)
THEME_COLOR_CAPTIONTEXT: Final = ENUM_THEME_COLOR.THEME_COLOR_CAPTIONTEXT
THEME_COLOR_INACTIVECAPTIONTEXT: Final = (
    ENUM_THEME_COLOR.THEME_COLOR_INACTIVECAPTIONTEXT
)
THEME_COLOR_HOTTEXT: Final = ENUM_THEME_COLOR.THEME_COLOR_HOTTEXT
THEME_COLOR_NONE: Final = ENUM_THEME_COLOR.THEME_COLOR_NONE
THEME_COLOR_SEPARATOR: Final = ENUM_THEME_COLOR.THEME_COLOR_SEPARATOR
THEME_COLOR_SCROLLBACK: Final = ENUM_THEME_COLOR.THEME_COLOR_SCROLLBACK
THEME_COLOR_LINE1: Final = ENUM_THEME_COLOR.THEME_COLOR_LINE1
THEME_COLOR_LINE2: Final = ENUM_THEME_COLOR.THEME_COLOR_LINE2
THEME_COLOR_GRID: Final = ENUM_THEME_COLOR.THEME_COLOR_GRID
THEME_COLOR_SUMMARY: Final = ENUM_THEME_COLOR.THEME_COLOR_SUMMARY
THEME_COLOR_ERROR: Final = ENUM_THEME_COLOR.THEME_COLOR_ERROR
THEME_COLOR_INVALID: Final = ENUM_THEME_COLOR.THEME_COLOR_INVALID
THEME_COLOR_NEGATIVE: Final = ENUM_THEME_COLOR.THEME_COLOR_NEGATIVE
THEME_COLOR_POSITIVE: Final = ENUM_THEME_COLOR.THEME_COLOR_POSITIVE
THEME_COLOR_LINK: Final = ENUM_THEME_COLOR.THEME_COLOR_LINK
THEME_COLOR_LINKHOVER: Final = ENUM_THEME_COLOR.THEME_COLOR_LINKHOVER
THEME_COLOR_LINKTESTER: Final = ENUM_THEME_COLOR.THEME_COLOR_LINKTESTER
THEME_COLOR_TEXTUP: Final = ENUM_THEME_COLOR.THEME_COLOR_TEXTUP
THEME_COLOR_TEXTDOWN: Final = ENUM_THEME_COLOR.THEME_COLOR_TEXTDOWN
THEME_COLOR_BACKUP: Final = ENUM_THEME_COLOR.THEME_COLOR_BACKUP
THEME_COLOR_BACKDOWN: Final = ENUM_THEME_COLOR.THEME_COLOR_BACKDOWN
THEME_COLOR_CLOSE: Final = ENUM_THEME_COLOR.THEME_COLOR_CLOSE
THEME_COLOR_BUY: Final = ENUM_THEME_COLOR.THEME_COLOR_BUY
THEME_COLOR_SELL: Final = ENUM_THEME_COLOR.THEME_COLOR_SELL
THEME_COLOR_DEPOSIT: Final = ENUM_THEME_COLOR.THEME_COLOR_DEPOSIT
THEME_COLOR_WITHDRAWAL: Final = ENUM_THEME_COLOR.THEME_COLOR_WITHDRAWAL
THEME_COLOR_BID: Final = ENUM_THEME_COLOR.THEME_COLOR_BID
THEME_COLOR_ASK: Final = ENUM_THEME_COLOR.THEME_COLOR_ASK
THEME_COLOR_STOPS: Final = ENUM_THEME_COLOR.THEME_COLOR_STOPS
THEME_COLOR_STOPS_RED: Final = ENUM_THEME_COLOR.THEME_COLOR_STOPS_RED
THEME_COLOR_STOPS_GREEN: Final = ENUM_THEME_COLOR.THEME_COLOR_STOPS_GREEN
THEME_COLOR_CONFIRM: Final = ENUM_THEME_COLOR.THEME_COLOR_CONFIRM
THEME_COLOR_REQUOTE: Final = ENUM_THEME_COLOR.THEME_COLOR_REQUOTE
THEME_COLOR_REJECT: Final = ENUM_THEME_COLOR.THEME_COLOR_REJECT
THEME_COLOR_NOTIFICATION: Final = ENUM_THEME_COLOR.THEME_COLOR_NOTIFICATION
THEME_COLOR_RATING: Final = ENUM_THEME_COLOR.THEME_COLOR_RATING
THEME_COLOR_BOOK_BUY: Final = ENUM_THEME_COLOR.THEME_COLOR_BOOK_BUY
THEME_COLOR_BOOK_SELL: Final = ENUM_THEME_COLOR.THEME_COLOR_BOOK_SELL
THEME_COLOR_BOOK_LAST: Final = ENUM_THEME_COLOR.THEME_COLOR_BOOK_LAST
THEME_COLOR_BOOK_STOP: Final = ENUM_THEME_COLOR.THEME_COLOR_BOOK_STOP
THEME_COLOR_BOOK_SPREAD: Final = ENUM_THEME_COLOR.THEME_COLOR_BOOK_SPREAD
THEME_COLOR_TICKS_BID: Final = ENUM_THEME_COLOR.THEME_COLOR_TICKS_BID
THEME_COLOR_TICKS_ASK: Final = ENUM_THEME_COLOR.THEME_COLOR_TICKS_ASK
THEME_COLOR_TICKS_LAST: Final = ENUM_THEME_COLOR.THEME_COLOR_TICKS_LAST
THEME_COLOR_TICKS_CROSS: Final = ENUM_THEME_COLOR.THEME_COLOR_TICKS_CROSS
THEME_COLOR_TICKS_SL: Final = ENUM_THEME_COLOR.THEME_COLOR_TICKS_SL
THEME_COLOR_TICKS_TP: Final = ENUM_THEME_COLOR.THEME_COLOR_TICKS_TP
THEME_COLOR_TESTER_START: Final = ENUM_THEME_COLOR.THEME_COLOR_TESTER_START
THEME_COLOR_TESTER_STOP: Final = ENUM_THEME_COLOR.THEME_COLOR_TESTER_STOP
THEME_COLOR_TESTER_START_FRAME: Final = ENUM_THEME_COLOR.THEME_COLOR_TESTER_START_FRAME
THEME_COLOR_TESTER_STOP_FRAME: Final = ENUM_THEME_COLOR.THEME_COLOR_TESTER_STOP_FRAME
THEME_COLOR_TESTER_PROGRESS: Final = ENUM_THEME_COLOR.THEME_COLOR_TESTER_PROGRESS
THEME_COLOR_TESTER_BALANCE: Final = ENUM_THEME_COLOR.THEME_COLOR_TESTER_BALANCE
THEME_COLOR_TESTER_EQUITY: Final = ENUM_THEME_COLOR.THEME_COLOR_TESTER_EQUITY
THEME_COLOR_TESTER_MARGIN: Final = ENUM_THEME_COLOR.THEME_COLOR_TESTER_MARGIN
THEME_COLOR_PROFILER_CALL: Final = ENUM_THEME_COLOR.THEME_COLOR_PROFILER_CALL
THEME_COLOR_PROFILER_CALLSEL: Final = ENUM_THEME_COLOR.THEME_COLOR_PROFILER_CALLSEL
THEME_COLOR_PROFILER_LINE: Final = ENUM_THEME_COLOR.THEME_COLOR_PROFILER_LINE
THEME_COLOR_PROFILER_LINESEL: Final = ENUM_THEME_COLOR.THEME_COLOR_PROFILER_LINESEL

__all__ = [
    "ENUM_THEME_COLOR",
    "THEME_COLOR_3DDKSHADOW",
    "THEME_COLOR_3DFACE",
    "THEME_COLOR_3DHILIGHT",
    "THEME_COLOR_3DLIGHT",
    "THEME_COLOR_3DSHADOW",
    "THEME_COLOR_ACTIVECAPTION",
    "THEME_COLOR_ASK",
    "THEME_COLOR_BACKDOWN",
    "THEME_COLOR_BACKUP",
    "THEME_COLOR_BID",
    "THEME_COLOR_BOOK_BUY",
    "THEME_COLOR_BOOK_LAST",
    "THEME_COLOR_BOOK_SELL",
    "THEME_COLOR_BOOK_SPREAD",
    "THEME_COLOR_BOOK_STOP",
    "THEME_COLOR_BTNFACE",
    "THEME_COLOR_BTNHILIGHT",
    "THEME_COLOR_BTNSHADOW",
    "THEME_COLOR_BTNTEXT",
    "THEME_COLOR_BUY",
    "THEME_COLOR_CAPTIONTEXT",
    "THEME_COLOR_CLOSE",
    "THEME_COLOR_CONFIRM",
    "THEME_COLOR_DEPOSIT",
    "THEME_COLOR_ERROR",
    "THEME_COLOR_GRADIENTINACTIVECAPTION",
    "THEME_COLOR_GRAYTEXT",
    "THEME_COLOR_GRID",
    "THEME_COLOR_HIGHLIGHT",
    "THEME_COLOR_HIGHLIGHTTEXT",
    "THEME_COLOR_HOTTEXT",
    "THEME_COLOR_INACTIVECAPTION",
    "THEME_COLOR_INACTIVECAPTIONTEXT",
    "THEME_COLOR_INFOBK",
    "THEME_COLOR_INFOTEXT",
    "THEME_COLOR_INVALID",
    "THEME_COLOR_LINE1",
    "THEME_COLOR_LINE2",
    "THEME_COLOR_LINK",
    "THEME_COLOR_LINKHOVER",
    "THEME_COLOR_LINKTESTER",
    "THEME_COLOR_MENU",
    "THEME_COLOR_MENUBAR",
    "THEME_COLOR_MENUHILIGHT",
    "THEME_COLOR_MENUTEXT",
    "THEME_COLOR_NEGATIVE",
    "THEME_COLOR_NONE",
    "THEME_COLOR_NOTIFICATION",
    "THEME_COLOR_POSITIVE",
    "THEME_COLOR_PROFILER_CALL",
    "THEME_COLOR_PROFILER_CALLSEL",
    "THEME_COLOR_PROFILER_LINE",
    "THEME_COLOR_PROFILER_LINESEL",
    "THEME_COLOR_RATING",
    "THEME_COLOR_REJECT",
    "THEME_COLOR_REQUOTE",
    "THEME_COLOR_SCROLLBACK",
    "THEME_COLOR_SELL",
    "THEME_COLOR_SEPARATOR",
    "THEME_COLOR_STOPS",
    "THEME_COLOR_STOPS_GREEN",
    "THEME_COLOR_STOPS_RED",
    "THEME_COLOR_SUMMARY",
    "THEME_COLOR_TESTER_BALANCE",
    "THEME_COLOR_TESTER_EQUITY",
    "THEME_COLOR_TESTER_MARGIN",
    "THEME_COLOR_TESTER_PROGRESS",
    "THEME_COLOR_TESTER_START",
    "THEME_COLOR_TESTER_START_FRAME",
    "THEME_COLOR_TESTER_STOP",
    "THEME_COLOR_TESTER_STOP_FRAME",
    "THEME_COLOR_TEXTDOWN",
    "THEME_COLOR_TEXTUP",
    "THEME_COLOR_TICKS_ASK",
    "THEME_COLOR_TICKS_BID",
    "THEME_COLOR_TICKS_CROSS",
    "THEME_COLOR_TICKS_LAST",
    "THEME_COLOR_TICKS_SL",
    "THEME_COLOR_TICKS_TP",
    "THEME_COLOR_WINDOW",
    "THEME_COLOR_WINDOWTEXT",
    "THEME_COLOR_WITHDRAWAL",
]
