/**
 * Generated by scripts/generate_ui_contracts.py.
 * DO NOT EDIT DIRECTLY. Run `uv run python scripts/generate_ui_contracts.py` to regenerate.
 */

export type ValueKind =
  | "scalar"
  | "aligned_series"
  | "unaligned_series"
  | "table"
  | "matrix"
  | "string"
  | "boolean"
  | "object"
  | "array"
  | "categorical"
  | "token"
  | "reference";

export type Unit =
  | "none"
  | "currency"
  | "percent"
  | "points"
  | "pips"
  | "bars"
  | "seconds"
  | "ratio"
  | "count";

export type Alignment =
  | "none"
  | "index"
  | "timestamp"
  | "symbol";

export type WidgetKind =
  | "default"
  | "number_input"
  | "slider"
  | "text_input"
  | "select"
  | "checkbox"
  | "date_picker"
  | "color_picker"
  | "code_editor";

export type OptimizationScale =
  | "linear"
  | "logarithmic"
  | "integer"
  | "discrete";

export interface PluginRef {
  id: string;
  version: [number, number, number];
}

export interface NumericConstraint {
  type: "numeric";
  min_value?: number | null;
  max_value?: number | null;
  step?: number | null;
  allow_negative: boolean;
}

export interface TextConstraint {
  type: "text";
  min_length: number;
  max_length: number;
  pattern?: string | null;
}

export interface EnumChoice {
  value: string;
  label: string;
  description: string;
}

export interface EnumConstraint {
  type: "enum";
  choices: EnumChoice[];
}

export type ParameterConstraint =
  | NumericConstraint
  | TextConstraint
  | EnumConstraint;

export interface OptimizationDomain {
  eligible: boolean;
  min_value?: number | null;
  max_value?: number | null;
  step?: number | null;
  scale: OptimizationScale;
}

export interface PresentationHint {
  widget: WidgetKind;
  group: string;
  order: number;
  label: string;
  help_text: string;
}

export interface ParameterSpec {
  key: string;
  kind: ValueKind;
  label: string;
  description: string;
  required: boolean;
  default?: unknown;
  constraint?: ParameterConstraint | null;
  optimization?: OptimizationDomain | null;
  presentation?: PresentationHint | null;
}

export interface PortSpec {
  key: string;
  kind: ValueKind;
  unit: Unit;
  alignment: Alignment;
  label: string;
  description: string;
}

export interface LoweringTarget {
  target_id: string;
  version: [number, number, number];
}

export interface NumericalPolicy {
  tolerance: number;
  nan_policy: string;
  missing_policy: string;
}

export interface OperationSpec {
  operation_id: string;
  title: string;
  description: string;
  parameters: ParameterSpec[];
  inputs: PortSpec[];
  outputs: PortSpec[];
  determinism: boolean;
  numerical_policy: NumericalPolicy;
  effects: string[];
  required_capabilities: string[];
  optional_capabilities: string[];
  permissions: string[];
  lowering_targets: LoweringTarget[];
}

export interface WorkspaceCommand {
  command_id: string;
  title: string;
  description: string;
}

export interface WorkspaceView {
  view_id: string;
  title: string;
  component: string;
}

export interface WorkspaceSpec {
  ref: string;
  title: string;
  description: string;
  commands: WorkspaceCommand[];
  views: WorkspaceView[];
  accepted_kinds: string[];
}

export interface CatalogEntryView {
  ref: string;
  kind: string;
  title: string;
  description: string;
  metamodel_major: number;
  operations: OperationSpec[];
  workspace?: WorkspaceSpec | null;
}

export interface CatalogView {
  entries: CatalogEntryView[];
  catalog_fingerprint: string;
}

export interface PortRef {
  node_id: string;
  port_key: string;
}

export interface NodeSpec {
  id: string;
  plugin_ref: string;
  operation_id: string;
  parameters: Record<string, unknown>;
  title?: string;
  extension_data?: Record<string, unknown>;
}

export interface EdgeSpec {
  source: PortRef;
  target: PortRef;
}

export interface GraphSpec {
  nodes: NodeSpec[];
  edges: EdgeSpec[];
  designated_roots: PortRef[];
  subgraphs?: unknown[];
}

export interface GraphDocument {
  schema_version: number;
  spec: GraphSpec;
  metadata?: Record<string, unknown>;
}

export interface ValidationIssue {
  path: string;
  code: string;
  message: string;
}

export interface GraphValidationResult {
  can_execute: boolean;
  issues: ValidationIssue[];
  normalized_document?: GraphDocument | null;
}

export interface ExecutionBudget {
  max_nodes?: number;
  max_samples?: number;
  max_output_values?: number;
  max_trials?: number;
  max_elapsed_seconds?: number;
}

export interface ExecutionReproducibilityRecord {
  graph_id: string;
  graph_fingerprint: string;
  catalog_fingerprint: string;
  dependency_fingerprint: string;
  plugin_versions: [string, string][];
  source_digests: [string, string][];
  normalized_parameters: Record<string, unknown>;
  input_hash: string;
  output_hash: string;
  seed?: number | null;
  numerical_policy: NumericalPolicy;
  engine_version: string;
  elapsed_seconds: number;
  status: string;
}

export interface SingleExecutionRequest {
  graph_document: GraphDocument;
  inputs?: Record<string, unknown>;
  budget?: ExecutionBudget;
  seed?: number | null;
}

export interface SingleExecutionResult {
  success: boolean;
  outputs: Record<string, unknown>;
  reproducibility?: ExecutionReproducibilityRecord | null;
  issues: ValidationIssue[];
  elapsed_seconds: number;
}

export interface BatchTrial {
  trial_id: string;
  parameter_overrides?: Record<string, Record<string, unknown>>;
  metadata?: Record<string, unknown>;
}

export interface BatchExecutionRequest {
  graph_document: GraphDocument;
  inputs?: Record<string, unknown>;
  trials: BatchTrial[];
  budget?: ExecutionBudget;
  seed?: number | null;
}

export interface BatchTrialResult {
  trial_id: string;
  success: boolean;
  outputs: Record<string, unknown>;
  issues: ValidationIssue[];
  elapsed_seconds: number;
}

export interface BatchExecutionResult {
  success: boolean;
  trials: BatchTrialResult[];
  issues: ValidationIssue[];
  elapsed_seconds: number;
}

export interface ExportRequest {
  graph_document: GraphDocument;
  target: LoweringTarget;
}

export interface ExportResult {
  success: boolean;
  target: LoweringTarget;
  source_code?: string | null;
  manifest?: Record<string, unknown> | null;
  issues: ValidationIssue[];
}

export interface ApiError {
  code: string;
  message: string;
  issues?: ValidationIssue[];
}

export interface ApiResponse<T = unknown> {
  api_version: string;
  request_id: string;
  status: "success" | "error";
  data?: T;
  error?: ApiError;
}
