"""Stable canonical enumerations for broker integrations."""

from enum import StrEnum


class BrokerId(StrEnum):
    """Registered broker/provider profiles."""

    MT5 = "mt5"
    CTRADER = "ctrader"
    BINANCE_SPOT = "binance_spot"
    BINANCE_USD_M_FUTURES = "binance_usd_m_futures"
    BINANCE_COIN_M_FUTURES = "binance_coin_m_futures"
    DUKASCOPY = "dukascopy"
    YAHOO = "yahoo"


class BrokerEnvironment(StrEnum):
    """Explicit provider environments."""

    LIVE = "live"
    DEMO = "demo"
    TESTNET = "testnet"
    SANDBOX = "sandbox"


class BrokerConnectionState(StrEnum):
    """Validated adapter lifecycle states."""

    DISCONNECTED = "disconnected"
    CONNECTING = "connecting"
    READY = "ready"
    DEGRADED = "degraded"
    CLOSING = "closing"
    FAILED = "failed"


class BrokerErrorCode(StrEnum):
    """Stable canonical broker error taxonomy."""

    BROKER_UNKNOWN = "BROKER_UNKNOWN"
    BROKER_CONFIGURATION_INVALID = "BROKER_CONFIGURATION_INVALID"
    BROKER_AUTHENTICATION_FAILED = "BROKER_AUTHENTICATION_FAILED"
    BROKER_AUTHORIZATION_FAILED = "BROKER_AUTHORIZATION_FAILED"
    BROKER_NOT_CONNECTED = "BROKER_NOT_CONNECTED"
    BROKER_CONNECTION_FAILED = "BROKER_CONNECTION_FAILED"
    BROKER_CONNECTION_LOST = "BROKER_CONNECTION_LOST"
    BROKER_TIMEOUT = "BROKER_TIMEOUT"
    BROKER_RATE_LIMITED = "BROKER_RATE_LIMITED"
    BROKER_BACKPRESSURE = "BROKER_BACKPRESSURE"
    BROKER_CIRCUIT_OPEN = "BROKER_CIRCUIT_OPEN"
    BROKER_CAPABILITY_UNSUPPORTED = "BROKER_CAPABILITY_UNSUPPORTED"
    BROKER_SYMBOL_NOT_FOUND = "BROKER_SYMBOL_NOT_FOUND"
    BROKER_ACCOUNT_NOT_FOUND = "BROKER_ACCOUNT_NOT_FOUND"
    BROKER_ORDER_NOT_FOUND = "BROKER_ORDER_NOT_FOUND"
    BROKER_POSITION_NOT_FOUND = "BROKER_POSITION_NOT_FOUND"
    BROKER_DEAL_NOT_FOUND = "BROKER_DEAL_NOT_FOUND"
    BROKER_REQUEST_INVALID = "BROKER_REQUEST_INVALID"
    BROKER_REQUEST_REJECTED = "BROKER_REQUEST_REJECTED"
    BROKER_MARKET_CLOSED = "BROKER_MARKET_CLOSED"
    BROKER_INSUFFICIENT_MARGIN = "BROKER_INSUFFICIENT_MARGIN"
    BROKER_INSUFFICIENT_FUNDS = "BROKER_INSUFFICIENT_FUNDS"
    BROKER_UNKNOWN_OUTCOME = "BROKER_UNKNOWN_OUTCOME"
    BROKER_PROVIDER_ERROR = "BROKER_PROVIDER_ERROR"
    BROKER_RESPONSE_INVALID = "BROKER_RESPONSE_INVALID"
    BROKER_SUBSCRIPTION_FAILED = "BROKER_SUBSCRIPTION_FAILED"
    BROKER_MAINTENANCE_MODE = "BROKER_MAINTENANCE_MODE"
    BROKER_SUBSCRIPTION_RESYNC_REQUIRED = "BROKER_SUBSCRIPTION_RESYNC_REQUIRED"
    BROKER_SUBSCRIPTION_NOT_FOUND = "BROKER_SUBSCRIPTION_NOT_FOUND"
    BROKER_DEPENDENCY_MISSING = "BROKER_DEPENDENCY_MISSING"
    BROKER_SESSION_CHANGED = "BROKER_SESSION_CHANGED"


class BrokerCapabilityId(StrEnum):
    """One identifier for every canonical adapter operation."""

    CONNECT = "connect"
    DISCONNECT = "disconnect"
    RECONNECT = "reconnect"
    IS_CONNECTED = "is_connected"
    GET_CONNECTION_STATUS = "get_connection_status"
    PING = "ping"
    REFRESH_SESSION = "refresh_session"
    GET_SERVER_TIME = "get_server_time"
    GET_LAST_ERROR = "get_last_error"
    CONNECTION_EVENTS = "connection_events"
    GET_SYMBOLS = "get_symbols"
    GET_SYMBOL_INFO = "get_symbol_info"
    SELECT_SYMBOL = "select_symbol"
    GET_MARKET_STATUS = "get_market_status"
    GET_TRADING_SESSIONS = "get_trading_sessions"
    GET_QUOTE = "get_quote"
    GET_TICKS = "get_ticks"
    GET_HISTORICAL_BARS = "get_historical_bars"
    GET_ORDER_BOOK = "get_order_book"
    GET_SPREAD = "get_spread"
    SUBSCRIBE_QUOTES = "subscribe_quotes"
    SUBSCRIBE_BARS = "subscribe_bars"
    SUBSCRIBE_ORDER_BOOK = "subscribe_order_book"
    UNSUBSCRIBE = "unsubscribe"
    LIST_SUBSCRIPTIONS = "list_subscriptions"
    GET_FEATURE_FLAGS = "get_feature_flags"
    SUPPORTS = "supports"
    GET_PLATFORM_INFO = "get_platform_info"
    GET_PERMISSIONS = "get_permissions"
    LIST_ACCOUNTS = "list_accounts"
    SELECT_ACCOUNT = "select_account"
    GET_ACCOUNT_INFO = "get_account_info"
    GET_BALANCES = "get_balances"
    LIST_ASSETS = "list_assets"
    GET_ASSET_INFO = "get_asset_info"
    GET_POSITIONS = "get_positions"
    GET_POSITION = "get_position"
    GET_ORDERS = "get_orders"
    GET_ORDER = "get_order"
    LIST_ORDER_HISTORY = "list_order_history"
    LIST_DEAL_HISTORY = "list_deal_history"
    GET_DEAL = "get_deal"
    LIST_ACCOUNT_TRANSACTIONS = "list_account_transactions"
    CHECK_ORDER = "check_order"
    PLACE_ORDER = "place_order"
    MODIFY_ORDER = "modify_order"
    CANCEL_ORDER = "cancel_order"
    MODIFY_POSITION = "modify_position"
    CLOSE_POSITION = "close_position"
    REPLACE_ORDER = "replace_order"
    CALCULATE_MARGIN = "calculate_margin"
    CALCULATE_PROFIT = "calculate_profit"
    GET_COMMISSION_ESTIMATE = "get_commission_estimate"
