# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from typing import Final

SHUTDOWN_REASON_PROGRAM: Final[int] = 0
SHUTDOWN_REASON_REMOVE: Final[int] = 1
SHUTDOWN_REASON_RECOMPILE: Final[int] = 2
SHUTDOWN_REASON_CHARTCHANGE: Final[int] = 3
SHUTDOWN_REASON_CHARTCLOSE: Final[int] = 4
SHUTDOWN_REASON_PARAMETERS: Final[int] = 5
SHUTDOWN_REASON_ACCOUNT: Final[int] = 6
SHUTDOWN_REASON_TEMPLATE: Final[int] = 7
SHUTDOWN_REASON_INITFAILED: Final[int] = 8
SHUTDOWN_REASON_CLOSE: Final[int] = 9

__all__ = [
    "SHUTDOWN_REASON_ACCOUNT",
    "SHUTDOWN_REASON_CHARTCHANGE",
    "SHUTDOWN_REASON_CHARTCLOSE",
    "SHUTDOWN_REASON_CLOSE",
    "SHUTDOWN_REASON_INITFAILED",
    "SHUTDOWN_REASON_PARAMETERS",
    "SHUTDOWN_REASON_PROGRAM",
    "SHUTDOWN_REASON_RECOMPILE",
    "SHUTDOWN_REASON_REMOVE",
    "SHUTDOWN_REASON_TEMPLATE",
]
