import { useMemo } from 'react';
import { Check, Copy, Download } from 'lucide-react';
import { DockviewReact, type DockviewReadyEvent } from 'dockview';
import { useAppStore } from '../../app/store';
import { Button, Section, Stat } from '../../components/ui';
import { EquityChart } from '../../components/EquityChart';

const views = ['Overview', 'Trade list', 'Equity chart', 'Drawdown', 'Trades on chart', 'Trade analysis', 'Strategy config', 'Source code', 'Robustness', 'Optimization profile', 'Parameter permutation', 'Walk-forward', 'Sequential optimization', 'Correlation', 'Portfolio', 'Reports', 'Prop analytics', 'Prop Monte Carlo'];

function Overview() { const s = useAppStore(x => x.strategies.find(y => y.id === x.selectedStrategyId)); if (!s) return <Empty/>; const wins = s.trades.filter(t => t.pnl > 0); return <div className="results-overview"><div className="metric-strip"><Stat label="Net profit" value={`$${s.metrics.netProfit.toLocaleString()}`} tone={s.metrics.netProfit > 0 ? 'good' : 'bad'}/><Stat label="Profit factor" value={s.metrics.profitFactor}/><Stat label="Max drawdown" value={`$${s.metrics.maxDrawdown.toLocaleString()}`} tone="bad"/><Stat label="Trades" value={s.metrics.trades}/><Stat label="Sharpe ratio" value={s.metrics.sharpe}/><Stat label="Stability" value={`${s.metrics.stability}%`}/></div><div className="results-columns"><Section title="Equity"><EquityChart data={s.equity} height={260}/></Section><Section title="Performance summary"><dl className="details"><dt>Strategy</dt><dd>{s.name}</dd><dt>Revision</dt><dd>{s.revision}</dd><dt>Market</dt><dd>{s.symbol} · {s.timeframe}</dd><dt>Winning trades</dt><dd>{wins.length} ({Math.round(wins.length / s.trades.length * 100)}%)</dd><dt>Average trade</dt><dd>${Math.round(s.metrics.netProfit / s.metrics.trades)}</dd><dt>Direction</dt><dd>{s.direction}</dd><dt>Sample</dt><dd>Full data (IS + OOS)</dd></dl></Section></div></div>; }
function TradeList() { const s = useAppStore(x => x.strategies.find(y => y.id === x.selectedStrategyId)); if (!s) return <Empty/>; return <div className="plain-table-wrap"><table className="plain-table"><thead><tr><th>#</th><th>Direction</th><th>Entry time</th><th>Exit time</th><th>Entry</th><th>Exit</th><th>Size</th><th>Profit/Loss</th><th>Sample</th></tr></thead><tbody>{s.trades.map((t, i) => <tr key={t.id}><td>{i + 1}</td><td><span className={t.side === 'Long' ? 'pill green' : 'pill red'}>{t.side}</span></td><td>{new Date(t.entryTime).toLocaleDateString()}</td><td>{new Date(t.exitTime).toLocaleDateString()}</td><td>{t.entry.toFixed(5)}</td><td>{t.exit.toFixed(5)}</td><td>{t.size.toFixed(2)}</td><td className={t.pnl >= 0 ? 'positive' : 'negative'}>${t.pnl.toFixed(2)}</td><td>{t.sample}</td></tr>)}</tbody></table></div>; }
function Analysis() { const s = useAppStore(x => x.strategies.find(y => y.id === x.selectedStrategyId)); if (!s) return <Empty/>; const buckets = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']; return <div className="analysis-grid"><Section title="Profit by weekday"><div className="bars">{buckets.map((b, i) => <div key={b}><span>{b}</span><i style={{ height: `${40 + ((s.id.length * 17 + i * 29) % 90)}px` }}/><strong>${(620 + i * 183).toLocaleString()}</strong></div>)}</div></Section><Section title="Trade statistics"><dl className="details"><dt>Average win</dt><dd>$482.19</dd><dt>Average loss</dt><dd>-$291.44</dd><dt>Win / loss ratio</dt><dd>1.65</dd><dt>Max consecutive wins</dt><dd>7</dd><dt>Max consecutive losses</dt><dd>4</dd><dt>Market exposure</dt><dd>12.8%</dd></dl></Section><Section title="Monthly stability"><div className="heatmap">{Array.from({ length: 48 }, (_, i) => <i key={i} style={{ background: i % 7 < 2 ? '#7b3444' : i % 5 ? '#27664f' : '#b47b32' }} title={`Month ${i + 1}`}/>)}</div></Section></div>; }
function Config() { const s = useAppStore(x => x.strategies.find(y => y.id === x.selectedStrategyId)); if (!s) return <Empty/>; return <div className="config-view"><Section title="Strategy properties"><dl className="details">{Object.entries(s.parameters).map(([k, v]) => <><dt key={`${k}k`}>{k}</dt><dd key={`${k}v`}>{v}</dd></>)}</dl></Section><Section title="Trading logic"><div className="code-block">On Bar Open{`\n`}  IF EMA(FastPeriod) crosses above EMA(SlowPeriod){`\n`}  AND ATR(ATRPeriod) &gt; 0.0012{`\n`}    Enter Long at Market{`\n`}    Stop Loss = StopLoss pips{`\n`}    Profit Target = StopLoss × 2</div></Section></div>; }
function Source() { const s = useAppStore(x => x.strategies.find(y => y.id === x.selectedStrategyId)); if (!s) return <Empty/>; return <div className="source-view"><div className="subtoolbar"><select className="text-input"><option>MetaTrader 5</option><option>MetaTrader 4</option><option>TradeStation EasyLanguage</option><option>JForex</option><option>PseudoCode</option></select><Button><Copy size={14}/> Copy</Button><Button><Download size={14}/> Download mock source</Button><span className="mock-badge">Illustrative preview — not compiled</span></div><pre className="code-block">{`// ${s.name} — generated frontend preview\ninput int FastPeriod = ${s.parameters.FastPeriod};\ninput int SlowPeriod = ${s.parameters.SlowPeriod};\n\nvoid OnTick() {\n  if (isNewBar() && CrossAbove(EMA(FastPeriod), EMA(SlowPeriod))) {\n    trade.Buy(CalculateSize(), _Symbol, Ask, ${s.parameters.StopLoss}, ${s.parameters.StopLoss * 2});\n  }\n}`}</pre></div>; }
function Robustness() { const tests = ['Higher testing precision', 'Additional markets', 'Monte Carlo — trade order', 'Monte Carlo — spread & slippage', 'What-if analysis', 'Parameter permutation', 'Walk-forward matrix']; return <div className="robust-grid">{tests.map((x, i) => <Section key={x} title={x} actions={<span className={`verdict ${i === 3 ? 'warn' : 'pass'}`}>{i === 3 ? 'MARGINAL' : 'PASSED'}</span>}><div className="scenario-line"><span>{i === 3 ? '82' : '94'} / 100 scenarios accepted</span><div><i style={{ width: `${i === 3 ? 82 : 94}%` }}/></div></div><p className="muted">Acceptance: Net profit &gt; 0 and Return/DD ≥ 1.4</p></Section>)}</div>; }
function OptimizationView({ mode }: { mode: string }) { const s = useAppStore(x => x.strategies.find(y => y.id === x.selectedStrategyId)); const trials = useMemo(() => Array.from({ length: 18 }, (_, i) => ({ p: 5 + i * 3, profit: (s?.metrics.netProfit ?? 5000) * (.65 + Math.sin(i / 3) * .22 + i / 45), dd: 900 + ((i * 389) % 1800) })), [s]); return <div className="optimization-result"><Section title={`${mode} results`} description="Trials use the same deterministic strategy record and parameter sets."><div className="profile-chart">{trials.map(t => <div key={t.p} title={`${t.p}: $${Math.round(t.profit)}`}><i style={{ height: `${Math.max(12, t.profit / 110)}px` }}/><span>{t.p}</span></div>)}</div></Section><div className="plain-table-wrap"><table className="plain-table"><thead><tr><th>Trial</th><th>FastPeriod</th><th>Net profit</th><th>Drawdown</th><th>Return / DD</th><th>Verdict</th></tr></thead><tbody>{trials.map((t, i) => <tr key={t.p}><td>#{i + 1}</td><td>{t.p}</td><td>${Math.round(t.profit).toLocaleString()}</td><td>${t.dd.toLocaleString()}</td><td>{(t.profit / t.dd).toFixed(2)}</td><td><Check size={14} className="positive"/></td></tr>)}</tbody></table></div></div>; }
function Empty() { return <div className="empty-state"><strong>No strategy selected</strong><span>Select a strategy in the databank to inspect its linked result set.</span></div>; }
function ResultPanel() { const view = useAppStore(s => s.resultView); const selected = useAppStore(s => s.strategies.find(x => x.id === s.selectedStrategyId)); let content = <Overview/>; if (view === 'Trade list') content = <TradeList/>; else if (view === 'Equity chart') content = selected ? <EquityChart data={selected.equity} height={400}/> : <Empty/>; else if (view === 'Drawdown') content = selected ? <EquityChart data={selected.equity} height={400} drawdown/> : <Empty/>; else if (view === 'Trade analysis' || view === 'Trades on chart') content = <Analysis/>; else if (view === 'Strategy config') content = <Config/>; else if (view === 'Source code') content = <Source/>; else if (view === 'Robustness' || view.includes('Prop')) content = <Robustness/>; else if (!['Overview'].includes(view)) content = <OptimizationView mode={view}/>; return <div className="docked-result-content">{content}</div>; }
const dockComponents = { result: ResultPanel };
export function ResultsWorkspace() { const view = useAppStore(s => s.resultView); const set = useAppStore(s => s.setResultView); const selected = useAppStore(s => s.strategies.find(x => x.id === s.selectedStrategyId)); const onReady = (event: DockviewReadyEvent) => { event.api.addPanel({ id: 'linked-result', component: 'result', title: 'Linked strategy result' }); };
  return <div className="results-workspace"><aside>{views.map(v => <button key={v} className={v === view ? 'active' : ''} onClick={() => set(v)}>{v}</button>)}</aside><main><div className="results-title"><div><strong>{selected?.name ?? 'No strategy'}</strong><span>{selected ? `${selected.symbol} · ${selected.timeframe} · revision ${selected.revision}` : ''}</span></div><div><select className="text-input"><option>Full data</option><option>In Sample</option><option>Out of Sample</option></select><select className="text-input"><option>All directions</option><option>Long</option><option>Short</option></select></div></div><div className="dock-host dockview-theme-dark"><DockviewReact components={dockComponents} onReady={onReady}/></div></main></div>;
}
