# ruff: noqa: N801, N816, RUF022, RUF100  # Exact public names/order.
"""Generated MQL5-based contract vocabulary. DO NOT EDIT."""

from __future__ import annotations

from typing import Final

ERR_SUCCESS: Final[int] = 0
ERR_INTERNAL_ERROR: Final[int] = 4001
ERR_WRONG_INTERNAL_PARAMETER: Final[int] = 4002
ERR_INVALID_PARAMETER: Final[int] = 4003
ERR_NOT_ENOUGH_MEMORY: Final[int] = 4004
ERR_STRUCT_WITHOBJECTS_ORCLASS: Final[int] = 4005
ERR_INVALID_ARRAY: Final[int] = 4006
ERR_ARRAY_RESIZE_ERROR: Final[int] = 4007
ERR_STRING_RESIZE_ERROR: Final[int] = 4008
ERR_NOTINITIALIZED_STRING: Final[int] = 4009
ERR_INVALID_DATETIME: Final[int] = 4010
ERR_ARRAY_BAD_SIZE: Final[int] = 4011
ERR_INVALID_POINTER: Final[int] = 4012
ERR_INVALID_POINTER_TYPE: Final[int] = 4013
ERR_FUNCTION_NOT_ALLOWED: Final[int] = 4014
ERR_RESOURCE_NAME_DUPLICATED: Final[int] = 4015
ERR_RESOURCE_NOT_FOUND: Final[int] = 4016
ERR_RESOURCE_UNSUPPORTED_TYPE: Final[int] = 4017
ERR_RESOURCE_NAME_IS_TOO_LONG: Final[int] = 4018
ERR_MATH_OVERFLOW: Final[int] = 4019
ERR_SLEEP_ERROR: Final[int] = 4020
ERR_PROGRAM_STOPPED: Final[int] = 4022
ERR_INVALID_TYPE: Final[int] = 4023
ERR_INVALID_HANDLE: Final[int] = 4024
ERR_TOO_MANY_OBJECTS: Final[int] = 4025
ERR_OBJECT_ERROR: Final[int] = 4201
ERR_OBJECT_NOT_FOUND: Final[int] = 4202
ERR_OBJECT_WRONG_PROPERTY: Final[int] = 4203
ERR_OBJECT_GETDATE_FAILED: Final[int] = 4204
ERR_OBJECT_GETVALUE_FAILED: Final[int] = 4205
ERR_GLOBALVARIABLE_NOT_FOUND: Final[int] = 4501
ERR_GLOBALVARIABLE_EXISTS: Final[int] = 4502
ERR_GLOBALVARIABLE_NOT_MODIFIED: Final[int] = 4503
ERR_GLOBALVARIABLE_CANNOTREAD: Final[int] = 4504
ERR_GLOBALVARIABLE_CANNOTWRITE: Final[int] = 4505
ERR_PLAY_SOUND_FAILED: Final[int] = 4511
ERR_TERMINAL_WRONG_PROPERTY: Final[int] = 4513
ERR_CUSTOM_WRONG_PROPERTY: Final[int] = 4603
ERR_NO_STRING_DATE: Final[int] = 5030
ERR_WRONG_STRING_DATE: Final[int] = 5031
ERR_WRONG_STRING_TIME: Final[int] = 5032
ERR_STRING_TIME_ERROR: Final[int] = 5033
ERR_STRING_OUT_OF_MEMORY: Final[int] = 5034
ERR_STRING_SMALL_LEN: Final[int] = 5035
ERR_STRING_TOO_BIGNUMBER: Final[int] = 5036
ERR_WRONG_FORMATSTRING: Final[int] = 5037
ERR_TOO_MANY_FORMATTERS: Final[int] = 5038
ERR_TOO_MANY_PARAMETERS: Final[int] = 5039
ERR_WRONG_STRING_PARAMETER: Final[int] = 5040
ERR_STRINGPOS_OUTOFRANGE: Final[int] = 5041
ERR_STRING_ZEROADDED: Final[int] = 5042
ERR_STRING_UNKNOWNTYPE: Final[int] = 5043
ERR_WRONG_STRING_OBJECT: Final[int] = 5044
ERR_INCOMPATIBLE_ARRAYS: Final[int] = 5050
ERR_SMALL_ASSERIES_ARRAY: Final[int] = 5051
ERR_SMALL_ARRAY: Final[int] = 5052
ERR_ZEROSIZE_ARRAY: Final[int] = 5053
ERR_NUMBER_ARRAYS_ONLY: Final[int] = 5054
ERR_ONEDIM_ARRAYS_ONLY: Final[int] = 5055
ERR_SERIES_ARRAY: Final[int] = 5056
ERR_DOUBLE_ARRAY_ONLY: Final[int] = 5057
ERR_FLOAT_ARRAY_ONLY: Final[int] = 5058
ERR_LONG_ARRAY_ONLY: Final[int] = 5059
ERR_INT_ARRAY_ONLY: Final[int] = 5060
ERR_SHORT_ARRAY_ONLY: Final[int] = 5061
ERR_CHAR_ARRAY_ONLY: Final[int] = 5062
ERR_STRING_ARRAY_ONLY: Final[int] = 5063
ERR_OPENCL_NOT_SUPPORTED: Final[int] = 5100
ERR_OPENCL_INTERNAL: Final[int] = 5101
ERR_OPENCL_INVALID_HANDLE: Final[int] = 5102
ERR_OPENCL_CONTEXT_CREATE: Final[int] = 5103
ERR_OPENCL_QUEUE_CREATE: Final[int] = 5104
ERR_OPENCL_PROGRAM_CREATE: Final[int] = 5105
ERR_OPENCL_TOO_LONG_KERNEL_NAME: Final[int] = 5106
ERR_OPENCL_KERNEL_CREATE: Final[int] = 5107
ERR_OPENCL_SET_KERNEL_PARAMETER: Final[int] = 5108
ERR_OPENCL_EXECUTE: Final[int] = 5109
ERR_OPENCL_WRONG_BUFFER_SIZE: Final[int] = 5110
ERR_OPENCL_WRONG_BUFFER_OFFSET: Final[int] = 5111
ERR_OPENCL_BUFFER_CREATE: Final[int] = 5112
ERR_OPENCL_TOO_MANY_OBJECTS: Final[int] = 5113
ERR_OPENCL_SELECTDEVICE: Final[int] = 5114
ERR_NOT_CUSTOM_SYMBOL: Final[int] = 5300
ERR_CUSTOM_TICKS_WRONG_ORDER: Final[int] = 5310
ERR_USER_ERROR_FIRST: Final[int] = 65536

__all__ = [
    "ERR_ARRAY_BAD_SIZE",
    "ERR_ARRAY_RESIZE_ERROR",
    "ERR_CHAR_ARRAY_ONLY",
    "ERR_CUSTOM_TICKS_WRONG_ORDER",
    "ERR_CUSTOM_WRONG_PROPERTY",
    "ERR_DOUBLE_ARRAY_ONLY",
    "ERR_FLOAT_ARRAY_ONLY",
    "ERR_FUNCTION_NOT_ALLOWED",
    "ERR_GLOBALVARIABLE_CANNOTREAD",
    "ERR_GLOBALVARIABLE_CANNOTWRITE",
    "ERR_GLOBALVARIABLE_EXISTS",
    "ERR_GLOBALVARIABLE_NOT_FOUND",
    "ERR_GLOBALVARIABLE_NOT_MODIFIED",
    "ERR_INCOMPATIBLE_ARRAYS",
    "ERR_INT_ARRAY_ONLY",
    "ERR_INTERNAL_ERROR",
    "ERR_INVALID_ARRAY",
    "ERR_INVALID_DATETIME",
    "ERR_INVALID_HANDLE",
    "ERR_INVALID_PARAMETER",
    "ERR_INVALID_POINTER",
    "ERR_INVALID_POINTER_TYPE",
    "ERR_INVALID_TYPE",
    "ERR_LONG_ARRAY_ONLY",
    "ERR_MATH_OVERFLOW",
    "ERR_NO_STRING_DATE",
    "ERR_NOT_CUSTOM_SYMBOL",
    "ERR_NOT_ENOUGH_MEMORY",
    "ERR_NOTINITIALIZED_STRING",
    "ERR_NUMBER_ARRAYS_ONLY",
    "ERR_OBJECT_ERROR",
    "ERR_OBJECT_GETDATE_FAILED",
    "ERR_OBJECT_GETVALUE_FAILED",
    "ERR_OBJECT_NOT_FOUND",
    "ERR_OBJECT_WRONG_PROPERTY",
    "ERR_ONEDIM_ARRAYS_ONLY",
    "ERR_OPENCL_BUFFER_CREATE",
    "ERR_OPENCL_CONTEXT_CREATE",
    "ERR_OPENCL_EXECUTE",
    "ERR_OPENCL_INTERNAL",
    "ERR_OPENCL_INVALID_HANDLE",
    "ERR_OPENCL_KERNEL_CREATE",
    "ERR_OPENCL_NOT_SUPPORTED",
    "ERR_OPENCL_PROGRAM_CREATE",
    "ERR_OPENCL_QUEUE_CREATE",
    "ERR_OPENCL_SELECTDEVICE",
    "ERR_OPENCL_SET_KERNEL_PARAMETER",
    "ERR_OPENCL_TOO_LONG_KERNEL_NAME",
    "ERR_OPENCL_TOO_MANY_OBJECTS",
    "ERR_OPENCL_WRONG_BUFFER_OFFSET",
    "ERR_OPENCL_WRONG_BUFFER_SIZE",
    "ERR_PLAY_SOUND_FAILED",
    "ERR_PROGRAM_STOPPED",
    "ERR_RESOURCE_NAME_DUPLICATED",
    "ERR_RESOURCE_NAME_IS_TOO_LONG",
    "ERR_RESOURCE_NOT_FOUND",
    "ERR_RESOURCE_UNSUPPORTED_TYPE",
    "ERR_SERIES_ARRAY",
    "ERR_SHORT_ARRAY_ONLY",
    "ERR_SLEEP_ERROR",
    "ERR_SMALL_ARRAY",
    "ERR_SMALL_ASSERIES_ARRAY",
    "ERR_STRING_ARRAY_ONLY",
    "ERR_STRING_OUT_OF_MEMORY",
    "ERR_STRING_RESIZE_ERROR",
    "ERR_STRING_SMALL_LEN",
    "ERR_STRING_TIME_ERROR",
    "ERR_STRING_TOO_BIGNUMBER",
    "ERR_STRING_UNKNOWNTYPE",
    "ERR_STRING_ZEROADDED",
    "ERR_STRINGPOS_OUTOFRANGE",
    "ERR_STRUCT_WITHOBJECTS_ORCLASS",
    "ERR_SUCCESS",
    "ERR_TERMINAL_WRONG_PROPERTY",
    "ERR_TOO_MANY_FORMATTERS",
    "ERR_TOO_MANY_OBJECTS",
    "ERR_TOO_MANY_PARAMETERS",
    "ERR_USER_ERROR_FIRST",
    "ERR_WRONG_FORMATSTRING",
    "ERR_WRONG_INTERNAL_PARAMETER",
    "ERR_WRONG_STRING_DATE",
    "ERR_WRONG_STRING_OBJECT",
    "ERR_WRONG_STRING_PARAMETER",
    "ERR_WRONG_STRING_TIME",
    "ERR_ZEROSIZE_ARRAY",
]
