"""Approved Brokers domain package-root public API.

Every cross-domain consumer must import these standalone functions from
``app.services.brokers``. The public API surface consists exclusively of
standalone functions. Classes, contracts, DTOs, enums, and protocols remain
internal implementation details.
"""

from app.services.brokers.contracts.error_catalog import get_broker_error_catalog
from app.services.brokers.operations import (
    build_broker_connection_config,
    build_broker_margin_request,
    build_broker_order_filter,
    build_broker_order_modification_request,
    build_broker_order_request,
    build_broker_position_close_request,
    build_broker_position_filter,
    build_broker_position_modification_request,
    build_broker_profit_request,
    calculate_broker_margin,
    calculate_broker_profit,
    cancel_broker_order,
    check_broker_order,
    close_broker_position,
    connect_broker,
    disconnect_broker,
    get_broker_account_info,
    get_broker_balances,
    get_broker_connection_status,
    get_broker_deal,
    get_broker_feature_flags,
    get_broker_historical_bars,
    get_broker_last_error,
    get_broker_market_status,
    get_broker_order,
    get_broker_order_book,
    get_broker_orders,
    get_broker_permissions,
    get_broker_platform_info,
    get_broker_position,
    get_broker_positions,
    get_broker_quote,
    get_broker_spread,
    get_broker_symbol_info,
    get_broker_symbols,
    get_broker_ticks,
    get_broker_trading_sessions,
    is_broker_connected,
    list_broker_account_transactions,
    list_broker_deal_history,
    list_broker_order_history,
    list_broker_subscriptions,
    modify_broker_order,
    modify_broker_position,
    ping_broker,
    place_broker_order,
    reconnect_broker,
    select_broker_symbol,
    subscribe_broker_bars,
    subscribe_broker_order_book,
    subscribe_broker_quotes,
    supports_broker_capability,
    unsubscribe_broker,
)
from app.services.brokers.registry.catalogue import (
    get_broker_capability_catalogue,
)
from app.services.brokers.registry.factory import (
    create_broker_adapter,
    get_registered_brokers,
)
from app.services.brokers.testing import (
    create_fake_broker_adapter,
)

__all__ = (
    "build_broker_connection_config",
    "build_broker_margin_request",
    "build_broker_order_filter",
    "build_broker_order_modification_request",
    "build_broker_order_request",
    "build_broker_position_close_request",
    "build_broker_position_filter",
    "build_broker_position_modification_request",
    "build_broker_profit_request",
    "calculate_broker_margin",
    "calculate_broker_profit",
    "cancel_broker_order",
    "check_broker_order",
    "close_broker_position",
    "connect_broker",
    "create_broker_adapter",
    "create_fake_broker_adapter",
    "disconnect_broker",
    "get_broker_account_info",
    "get_broker_balances",
    "get_broker_capability_catalogue",
    "get_broker_connection_status",
    "get_broker_deal",
    "get_broker_error_catalog",
    "get_broker_feature_flags",
    "get_broker_historical_bars",
    "get_broker_last_error",
    "get_broker_market_status",
    "get_broker_order",
    "get_broker_order_book",
    "get_broker_orders",
    "get_broker_permissions",
    "get_broker_platform_info",
    "get_broker_position",
    "get_broker_positions",
    "get_broker_quote",
    "get_broker_spread",
    "get_broker_symbol_info",
    "get_broker_symbols",
    "get_broker_ticks",
    "get_broker_trading_sessions",
    "get_registered_brokers",
    "is_broker_connected",
    "list_broker_account_transactions",
    "list_broker_deal_history",
    "list_broker_order_history",
    "list_broker_subscriptions",
    "modify_broker_order",
    "modify_broker_position",
    "ping_broker",
    "place_broker_order",
    "reconnect_broker",
    "select_broker_symbol",
    "subscribe_broker_bars",
    "subscribe_broker_order_book",
    "subscribe_broker_quotes",
    "supports_broker_capability",
    "unsubscribe_broker",
)
