"""Approved Brokers domain package-root public API.

Every cross-domain consumer must import these standalone functions from
``app.services.brokers``. The public API surface consists exclusively of
standalone functions. Classes, contracts, DTOs, enums, and protocols remain
internal implementation details.
"""

from app.services.brokers._shared.connections import (
    create_connected_broker,
    resolve_provider_connection_config,
)
from app.services.brokers._shared.factory import (
    create_broker_adapter,
    get_registered_brokers,
)
from app.services.brokers._shared.public import (
    attach_broker_protection,
    build_broker_order_protection_request,
    build_broker_position_reduce_request,
    calculate_broker_margin,
    calculate_broker_profit,
    cancel_broker_order,
    check_broker_order,
    close_broker_position,
    connect_broker,
    disconnect_broker,
    get_broker_account_info,
    get_broker_asset_info,
    get_broker_balances,
    get_broker_commission_estimate,
    get_broker_connection_events,
    get_broker_connection_status,
    get_broker_deal,
    get_broker_feature_flags,
    get_broker_historical_bars,
    get_broker_last_error,
    get_broker_market_status,
    get_broker_order,
    get_broker_order_book,
    get_broker_orders,
    get_broker_permissions,
    get_broker_platform_info,
    get_broker_position,
    get_broker_positions,
    get_broker_quote,
    get_broker_server_time,
    get_broker_spread,
    get_broker_symbol_info,
    get_broker_symbols,
    get_broker_ticks,
    get_broker_trading_sessions,
    is_broker_connected,
    list_broker_account_transactions,
    list_broker_accounts,
    list_broker_assets,
    list_broker_deal_history,
    list_broker_order_history,
    list_broker_subscriptions,
    modify_broker_order,
    modify_broker_position,
    ping_broker,
    place_broker_order,
    reconnect_broker,
    reduce_broker_position,
    refresh_broker_session,
    replace_broker_order,
    select_broker_account,
    select_broker_symbol,
    subscribe_broker_bars,
    subscribe_broker_order_book,
    subscribe_broker_quotes,
    supports_broker_capability,
    unsubscribe_broker,
)
from app.services.brokers.binance.health import record_binance_health_checkpoint
from app.services.brokers.canonical_contracts.account_snapshot import (
    build_broker_account_snapshot,
    parse_broker_account_snapshot,
)
from app.services.brokers.canonical_contracts.error_catalog import (
    get_broker_error_catalog,
)
from app.services.brokers.canonical_contracts.health import (
    build_broker_health,
    parse_broker_health,
)
from app.services.brokers.canonical_contracts.public import (
    build_broker_connection_config,
    build_broker_margin_request,
    build_broker_order_filter,
    build_broker_order_modification_request,
    build_broker_order_request,
    build_broker_order_request_v2,
    build_broker_position_close_request,
    build_broker_position_filter,
    build_broker_position_modification_request,
    build_broker_profit_request,
    build_broker_value,
    get_broker_adapter_contract_version,
    get_broker_adapter_schema_id,
    get_broker_capability_id,
    get_broker_connection_account_reference,
    get_broker_connection_environment,
    get_broker_connection_id,
    get_broker_environment,
    get_broker_error_code,
    get_broker_feature_flag_environment,
    get_broker_feature_flag_id,
    get_broker_id,
    get_broker_resubmission_policy,
    get_broker_uncertainty,
    get_broker_value_field,
    is_broker_connection_enabled,
)
from app.services.brokers.canonical_contracts.reconciliation import (
    build_broker_reconciliation_snapshot,
    parse_broker_reconciliation_snapshot,
)
from app.services.brokers.canonical_contracts.unknown_outcome import (
    build_broker_unknown_result,
    enforce_no_blind_resubmission,
    is_broker_unknown_result,
)
from app.services.brokers.capabilities.dashboard import get_broker_dashboard_snapshot
from app.services.brokers.capabilities.matrix import (
    get_broker_capability_catalogue,
)
from app.services.brokers.conformance.public import (
    create_configured_fake_broker_adapter,
    create_fake_broker_adapter,
    run_broker_adapter_conformance,
    set_fake_broker_error,
)
from app.services.brokers.ctrader.health import record_ctrader_health_checkpoint
from app.services.brokers.dukascopy.health import record_dukascopy_health_checkpoint
from app.services.brokers.environment_guards.permissions import (
    get_broker_environment_permission,
    register_broker_environment_permission,
)
from app.services.brokers.events.checkpoints import (
    get_broker_event_checkpoint,
    record_broker_event_checkpoint,
)
from app.services.brokers.events.normalization import (
    classify_broker_event,
    normalize_broker_event_envelope,
)
from app.services.brokers.instrument_profiles.mappings import (
    close_broker_symbol_mapping,
    disable_broker_symbol_mapping,
    register_broker_symbol_mapping,
)
from app.services.brokers.instrument_profiles.profiles import (
    build_instrument_venue_profile,
    parse_instrument_venue_profile,
)
from app.services.brokers.instrument_profiles.symbols import (
    resolve_broker_canonical_symbol,
    resolve_broker_provider_symbol,
    resolve_broker_provider_symbol_as_of,
)
from app.services.brokers.metatrader.health import (
    record_metatrader_health_checkpoint,
)
from app.services.brokers.metatrader.snapshot_gateway import (
    acquire_metatrader_snapshot_symbols,
    get_metatrader_snapshot_gateway_status,
    release_metatrader_snapshot_symbols,
    start_metatrader_snapshot_gateway,
    stop_metatrader_snapshot_gateway,
    stream_metatrader_snapshots,
)
from app.services.brokers.migrations.public import run_broker_migrations
from app.services.brokers.reconciliation.checkpoints import (
    get_broker_route_recovery,
    record_broker_route_recovery,
)
from app.services.brokers.reconciliation.public import (
    build_broker_failover_decision,
    build_broker_route_plan,
    parse_broker_failover_decision,
    parse_broker_route_plan,
)
from app.services.brokers.simulation.public import (
    create_simulation_broker_adapter,
    finalize_simulation_broker_session,
)
from app.services.brokers.specifications.public import (
    build_provider_specification_snapshot,
    dump_provider_specification_snapshot,
    get_broker_provider_specification,
    get_provider_specification_snapshot_field,
    parse_provider_specification_snapshot,
    verify_provider_specification_snapshot,
)
from app.services.brokers.yahoo.health import record_yahoo_health_checkpoint

__all__ = (
    "acquire_metatrader_snapshot_symbols",
    "attach_broker_protection",
    "build_broker_account_snapshot",
    "build_broker_connection_config",
    "build_broker_failover_decision",
    "build_broker_health",
    "build_broker_margin_request",
    "build_broker_order_filter",
    "build_broker_order_modification_request",
    "build_broker_order_protection_request",
    "build_broker_order_request",
    "build_broker_order_request_v2",
    "build_broker_position_close_request",
    "build_broker_position_filter",
    "build_broker_position_modification_request",
    "build_broker_position_reduce_request",
    "build_broker_profit_request",
    "build_broker_reconciliation_snapshot",
    "build_broker_route_plan",
    "build_broker_unknown_result",
    "build_broker_value",
    "build_instrument_venue_profile",
    "build_provider_specification_snapshot",
    "calculate_broker_margin",
    "calculate_broker_profit",
    "cancel_broker_order",
    "check_broker_order",
    "classify_broker_event",
    "close_broker_position",
    "close_broker_symbol_mapping",
    "connect_broker",
    "create_broker_adapter",
    "create_configured_fake_broker_adapter",
    "create_connected_broker",
    "create_fake_broker_adapter",
    "create_simulation_broker_adapter",
    "disable_broker_symbol_mapping",
    "disconnect_broker",
    "dump_provider_specification_snapshot",
    "enforce_no_blind_resubmission",
    "finalize_simulation_broker_session",
    "get_broker_account_info",
    "get_broker_adapter_contract_version",
    "get_broker_adapter_schema_id",
    "get_broker_asset_info",
    "get_broker_balances",
    "get_broker_capability_catalogue",
    "get_broker_capability_id",
    "get_broker_commission_estimate",
    "get_broker_connection_account_reference",
    "get_broker_connection_environment",
    "get_broker_connection_events",
    "get_broker_connection_id",
    "get_broker_connection_status",
    "get_broker_dashboard_snapshot",
    "get_broker_deal",
    "get_broker_environment",
    "get_broker_environment_permission",
    "get_broker_error_catalog",
    "get_broker_error_code",
    "get_broker_event_checkpoint",
    "get_broker_feature_flag_environment",
    "get_broker_feature_flag_id",
    "get_broker_feature_flags",
    "get_broker_historical_bars",
    "get_broker_id",
    "get_broker_last_error",
    "get_broker_market_status",
    "get_broker_order",
    "get_broker_order_book",
    "get_broker_orders",
    "get_broker_permissions",
    "get_broker_platform_info",
    "get_broker_position",
    "get_broker_positions",
    "get_broker_provider_specification",
    "get_broker_quote",
    "get_broker_resubmission_policy",
    "get_broker_route_recovery",
    "get_broker_server_time",
    "get_broker_spread",
    "get_broker_symbol_info",
    "get_broker_symbols",
    "get_broker_ticks",
    "get_broker_trading_sessions",
    "get_broker_uncertainty",
    "get_broker_value_field",
    "get_metatrader_snapshot_gateway_status",
    "get_provider_specification_snapshot_field",
    "get_registered_brokers",
    "is_broker_connected",
    "is_broker_connection_enabled",
    "is_broker_unknown_result",
    "list_broker_account_transactions",
    "list_broker_accounts",
    "list_broker_assets",
    "list_broker_deal_history",
    "list_broker_order_history",
    "list_broker_subscriptions",
    "modify_broker_order",
    "modify_broker_position",
    "normalize_broker_event_envelope",
    "parse_broker_account_snapshot",
    "parse_broker_failover_decision",
    "parse_broker_health",
    "parse_broker_reconciliation_snapshot",
    "parse_broker_route_plan",
    "parse_instrument_venue_profile",
    "parse_provider_specification_snapshot",
    "ping_broker",
    "place_broker_order",
    "reconnect_broker",
    "record_binance_health_checkpoint",
    "record_broker_event_checkpoint",
    "record_broker_route_recovery",
    "record_ctrader_health_checkpoint",
    "record_dukascopy_health_checkpoint",
    "record_metatrader_health_checkpoint",
    "record_yahoo_health_checkpoint",
    "reduce_broker_position",
    "refresh_broker_session",
    "register_broker_environment_permission",
    "register_broker_symbol_mapping",
    "release_metatrader_snapshot_symbols",
    "replace_broker_order",
    "resolve_broker_canonical_symbol",
    "resolve_broker_provider_symbol",
    "resolve_broker_provider_symbol_as_of",
    "resolve_provider_connection_config",
    "run_broker_adapter_conformance",
    "run_broker_migrations",
    "select_broker_account",
    "select_broker_symbol",
    "set_fake_broker_error",
    "start_metatrader_snapshot_gateway",
    "stop_metatrader_snapshot_gateway",
    "stream_metatrader_snapshots",
    "subscribe_broker_bars",
    "subscribe_broker_order_book",
    "subscribe_broker_quotes",
    "supports_broker_capability",
    "unsubscribe_broker",
    "verify_provider_specification_snapshot",
)
