import { useEffect, useState } from 'react';
import { Bell, Blocks, Bot, BriefcaseBusiness, ChartCandlestick, ChartNoAxesCombined, ChevronDown, CircleHelp, Code2, Database, FlaskConical, FolderKanban, Gauge, GitCompareArrows, Home, Layers3, Moon, Network, PanelBottom, RotateCcw, Settings, SlidersHorizontal, Sun, WandSparkles, Workflow, X } from 'lucide-react';
import type { ModuleId } from './types';
import { useAppStore } from './store';
import { Button, Checkbox, Field, Modal, Select, TextInput } from '../components/ui';
import { DatabankPanel } from '../components/DatabankPanel';
import { ResearchProject } from '../domains/strategy/ResearchProject';
import { DataManager } from '../domains/data/DataManager';
import { AlgoWizard } from '../domains/strategy/AlgoWizard';
import { PortfolioComposer } from '../domains/portfolio/PortfolioComposer';
import { WorkflowManager } from '../domains/workflow/WorkflowManager';
import { Business, CodeEditor } from '../domains/platform/ExtensionSurfaces';

const nav: { id: ModuleId; label: string; icon: typeof Home; group?: string }[] = [
  { id: 'home', label: 'Home', icon: Home }, { id: 'builder', label: 'Builder', icon: WandSparkles, group: 'Research' }, { id: 'improver', label: 'Improver', icon: Blocks },
  { id: 'retester', label: 'Retester', icon: GitCompareArrows }, { id: 'optimizer', label: 'Optimizer', icon: Gauge }, { id: 'datamanager', label: 'Data Manager', icon: Database, group: 'Data & authoring' },
  { id: 'algowizard', label: 'AlgoWizard', icon: Workflow }, { id: 'portfolio', label: 'Portfolio Master', icon: Layers3, group: 'Portfolio' }, { id: 'composer', label: 'Portfolio Composer', icon: ChartNoAxesCombined },
  { id: 'projects', label: 'Custom Projects', icon: FolderKanban, group: 'Automation' }, { id: 'codeeditor', label: 'Code Editor', icon: Code2, group: 'Extensions' }, { id: 'business', label: 'SQX Business', icon: BriefcaseBusiness },
];

function HomeScreen() { const store = useAppStore(); return <div className="home-screen"><div className="hero"><div><span>StrategyQuant X</span><h1>Research workspace</h1><p>Continue a research project, manage market data, or author a trading strategy.</p></div><div className="version">Build 144 · recreation<br/><small>Frontend mock profile</small></div></div><div className="home-grid"><section><h2>Recent projects</h2>{['EURUSD H1 — Genetic research', 'NQ Breakout — Retest pipeline', 'Diversified FX Portfolio'].map((x, i) => <button key={x} onClick={() => store.setModule(i === 2 ? 'composer' : 'builder')}><span className="project-thumb"><ChartCandlestick/></span><span><strong>{x}</strong><small>{i ? 'Last opened yesterday' : 'Last opened 12 minutes ago'}</small></span><em>{i === 2 ? 'Portfolio Composer' : 'Builder'}</em></button>)}</section><section><h2>Start</h2><div className="start-grid">{nav.slice(1, 9).map(x => <button key={x.id} onClick={() => store.setModule(x.id)}><x.icon/><span>{x.label}</span></button>)}</div></section><section><h2>Environment</h2><dl className="details"><dt>License profile</dt><dd>Full feature fixture</dd><dt>Engine</dt><dd>Deterministic mock</dd><dt>Persistence</dt><dd>Browser local storage</dd><dt>Market data</dt><dd>4 seeded datasets</dd><dt>Strategies</dt><dd>{store.strategies.length}</dd></dl></section></div><div className="home-note"><FlaskConical size={20}/><div><strong>This is a frontend research simulation.</strong><span>No backtests, broker connections, downloads, native compilation, external scripts, or trades are executed.</span></div></div></div>; }

function GlobalSettings({ onClose }: { onClose: () => void }) { const current = useAppStore(s => s.settings); const update = useAppStore(s => s.updateSettings); const reset = useAppStore(s => s.reset); const [draft, setDraft] = useState(current); const [page, setPage] = useState('Performance'); return <Modal title="Configuration" onClose={onClose} width={760} footer={<><Button onClick={onClose}>Cancel</Button><Button className="primary" onClick={() => { update(draft); onClose(); }}>Save configuration</Button></>}><div className="settings-dialog"><aside>{['Performance', 'Appearance', 'Language', 'Feature profile', 'Mock developer tools', 'Remote access', 'MCP Server', 'SMTP server'].map(x => <button key={x} className={page === x ? 'active' : ''} onClick={() => setPage(x)}>{x}</button>)}</aside><main><h3>{page}</h3>{page === 'Performance' && <><Field label="Worker processes"><TextInput type="number" min="1" max="64" value={draft.workers} onChange={e => setDraft({ ...draft, workers: Number(e.target.value) })}/></Field><Field label="Memory allocation (GB)"><TextInput type="number" min="2" max="64" value={draft.memoryGb} onChange={e => setDraft({ ...draft, memoryGb: Number(e.target.value) })}/></Field><Checkbox label="Autosave projects and workspace state" checked={draft.autosave} onChange={autosave => setDraft({ ...draft, autosave })}/><p className="dialog-note">Values configure only the frontend mock. They do not change native SQX or system settings.</p></>}{page === 'Appearance' && <Field label="Skin"><Select value={draft.theme} onChange={theme => setDraft({ ...draft, theme: theme as 'dark' | 'light' })}><option value="dark">Dark</option><option value="light">Light</option></Select></Field>}{page === 'Language' && <Field label="Application language"><Select value={draft.language} onChange={language => setDraft({ ...draft, language })}><option>English</option><option>Deutsch</option><option>Español</option><option>Português</option><option>中文</option></Select></Field>}{page === 'Feature profile' && <Field label="Edition fixture"><Select value={draft.profile} onChange={profile => setDraft({ ...draft, profile: profile as 'Full' | 'Starter' })}><option>Full</option><option>Starter</option></Select></Field>}{page === 'Mock developer tools' && <><p>Reset every persisted setting, strategy edit, job and workflow state to the deterministic seed.</p><Button className="danger" onClick={() => { reset(); onClose(); }}><RotateCcw size={14}/>Reset fixture workspace</Button></>}{['Remote access', 'MCP Server', 'SMTP server'].includes(page) && <><Field label="Status"><TextInput value="Disabled — mock configuration" readOnly/></Field><Checkbox label="Enable simulated adapter" checked={false} onChange={() => {}}/><p className="dialog-note">No external service is contacted and credentials are not stored.</p></>}</main></div></Modal>; }

export function App() { const store = useAppStore(); const [settings, setSettings] = useState(false); const [notifications, setNotifications] = useState(false); const [collapsed, setCollapsed] = useState(false); const showBank = ['builder', 'improver', 'retester', 'optimizer', 'portfolio', 'projects'].includes(store.module); useEffect(() => { document.documentElement.dataset.theme = store.settings.theme; }, [store.settings.theme]);
  let content = <HomeScreen/>; if (['builder','improver','retester','optimizer'].includes(store.module)) content = <ResearchProject module={store.module}/>; else if (store.module === 'portfolio') content = <PortfolioComposer master/>; else if (store.module === 'composer') content = <PortfolioComposer/>; else if (store.module === 'datamanager') content = <DataManager/>; else if (store.module === 'algowizard') content = <AlgoWizard/>; else if (store.module === 'projects') content = <WorkflowManager/>; else if (store.module === 'codeeditor') content = <CodeEditor/>; else if (store.module === 'business') content = <Business/>;
  return <div className={`app-shell ${collapsed ? 'nav-collapsed' : ''}`}><header className="topbar"><div className="brand"><div className="brand-mark"><ChartNoAxesCombined/></div><div><strong>StrategyQuant X</strong><span>Research platform</span></div></div><div className="workspace-select"><Bot size={14}/><span>Full Feature Profile</span><ChevronDown size={13}/></div><div className="top-actions"><button title="Theme" onClick={() => store.updateSettings({ theme: store.settings.theme === 'dark' ? 'light' : 'dark' })}>{store.settings.theme === 'dark' ? <Moon/> : <Sun/>}</button><button title="Notifications" onClick={() => setNotifications(!notifications)}><Bell/>{store.notifications.length > 0 && <i>{store.notifications.length}</i>}</button><button title="Help"><CircleHelp/></button><button title="Settings" onClick={() => setSettings(true)}><Settings/></button></div>{notifications && <div className="notifications"><header><strong>Notifications</strong><button onClick={() => setNotifications(false)}><X size={14}/></button></header>{store.notifications.length ? store.notifications.map((x, i) => <p key={`${x}${i}`}>{x}<small>Just now</small></p>) : <div className="empty-mini">No notifications</div>}</div>}</header><aside className="main-nav"><button className="collapse" title="Collapse navigation" onClick={() => setCollapsed(!collapsed)}><PanelBottom size={16}/><span>Applications</span></button>{nav.map((item, i) => <div key={item.id}>{item.group && <small className="nav-group">{item.group}</small>}<button title={item.label} className={store.module === item.id ? 'active' : ''} onClick={() => store.setModule(item.id)}><item.icon/><span>{item.label}</span>{i === 0 && <kbd>⌂</kbd>}</button></div>)}</aside><main className="app-main"><div className="module-area">{content}</div>{showBank && <div className="databank-resize"><DatabankPanel/></div>}</main><footer className="statusbar"><span><i className="online"/>Ready</span><span>Mock engine · no backend</span><span>Workers {store.settings.workers}</span><span>Memory {store.settings.memoryGb} GB</span><span>Build 144.2953 reference</span></footer>{settings && <GlobalSettings onClose={() => setSettings(false)}/>}</div>;
}
