import { useEffect, useState } from 'react';
import { Bell, BriefcaseBusiness, ChartCandlestick, ChartNoAxesCombined, Code2, Database, FlaskConical, FolderKanban, Gauge, GitCompareArrows, Home, Layers3, ListIndentDecrease, ListIndentIncrease, WandSparkles, Workflow, X } from 'lucide-react';
import type { ModuleId } from './types';
import { useAppStore } from './store';
import { DatabankPanel } from '../components/DatabankPanel';
import { ResearchProject } from '../domains/strategy/ResearchProject';
import { DataManager } from '../domains/data/DataManager';
import { AlgoWizard } from '../domains/strategy/AlgoWizard';
import { PortfolioComposer } from '../domains/portfolio/PortfolioComposer';
import { WorkflowManager } from '../domains/workflow/WorkflowManager';
import { Business, CodeEditor } from '../domains/platform/ExtensionSurfaces';
import { GlobalSettingsMenu } from './GlobalSettingsMenu';
import { DebugConsole, GridControl, HeaderApplicationActions } from './HeaderApplications';

const nav: { id: ModuleId; label: string; icon: typeof Home; group?: string }[] = [
  { id: 'home', label: 'Home', icon: Home }, { id: 'builder', label: 'Builder', icon: WandSparkles, group: 'Research' }, { id: 'retester', label: 'Retester', icon: GitCompareArrows },
  { id: 'optimizer', label: 'Optimizer', icon: Gauge }, { id: 'datamanager', label: 'Data Manager', icon: Database, group: 'Data & authoring' },
  { id: 'algowizard', label: 'AlgoWizard', icon: Workflow }, { id: 'portfolio', label: 'Portfolio Master', icon: Layers3, group: 'Portfolio' }, { id: 'composer', label: 'Portfolio Composer', icon: ChartNoAxesCombined },
  { id: 'projects', label: 'Custom Projects', icon: FolderKanban, group: 'Automation' }, { id: 'codeeditor', label: 'Code Editor', icon: Code2, group: 'Extensions' }, { id: 'business', label: 'Business', icon: BriefcaseBusiness },
];

function HomeScreen() { const store = useAppStore(); return <div className="home-screen"><div className="hero"><div><span>HaruQuantAI</span><h1>Research workspace</h1><p>Continue a research project, manage market data, or author a trading strategy.</p></div><div className="version">Build 144 · recreation<br/><small>Frontend mock profile</small></div></div><div className="home-grid"><section><h2>Recent projects</h2>{['EURUSD H1 — Genetic research', 'NQ Breakout — Retest pipeline', 'Diversified FX Portfolio'].map((x, i) => <button key={x} onClick={() => store.setModule(i === 2 ? 'composer' : 'builder')}><span className="project-thumb"><ChartCandlestick/></span><span><strong>{x}</strong><small>{i ? 'Last opened yesterday' : 'Last opened 12 minutes ago'}</small></span><em>{i === 2 ? 'Portfolio Composer' : 'Builder'}</em></button>)}</section><section><h2>Start</h2><div className="start-grid">{nav.slice(1, 9).map(x => <button key={x.id} onClick={() => store.setModule(x.id)}><x.icon/><span>{x.label}</span></button>)}</div></section><section><h2>Environment</h2><dl className="details"><dt>License profile</dt><dd>Full feature fixture</dd><dt>Engine</dt><dd>Deterministic mock</dd><dt>Persistence</dt><dd>Browser local storage</dd><dt>Market data</dt><dd>4 seeded datasets</dd><dt>Strategies</dt><dd>{store.strategies.length}</dd></dl></section></div><div className="home-note"><FlaskConical size={20}/><div><strong>This is a frontend research simulation.</strong><span>No backtests, broker connections, downloads, native compilation, external scripts, or trades are executed.</span></div></div></div>; }

export function App() { const store = useAppStore(); const [notifications, setNotifications] = useState(false); const collapsed = store.settings.navigationCollapsed; const showBank = ['builder', 'retester', 'optimizer', 'portfolio', 'projects'].includes(store.module); useEffect(() => { document.documentElement.dataset.theme = store.settings.theme; document.documentElement.dataset.profile = store.settings.profile; document.documentElement.style.setProperty('--app-zoom', String(store.settings.zoom)); }, [store.settings.profile, store.settings.theme, store.settings.zoom]);
  let content = <HomeScreen/>; if (['builder','retester','optimizer'].includes(store.module)) content = <ResearchProject module={store.module}/>; else if (store.module === 'portfolio') content = <PortfolioComposer master/>; else if (store.module === 'composer') content = <PortfolioComposer/>; else if (store.module === 'datamanager') content = <DataManager/>; else if (store.module === 'algowizard') content = <AlgoWizard/>; else if (store.module === 'projects') content = <WorkflowManager/>; else if (store.module === 'codeeditor') content = <CodeEditor/>; else if (store.module === 'business') content = <Business/>; else if (store.module === 'debugconsole') content = <DebugConsole/>; else if (store.module === 'gridcontrol') content = <GridControl/>;
  const navigationAction = collapsed ? 'Expand navigation' : 'Collapse navigation';
  return <div className={`app-shell ${collapsed ? 'nav-collapsed' : ''}`}><header className="topbar"><div className="brand"><div className="brand-mark"><ChartNoAxesCombined/></div><div><strong>HaruQuantAI</strong></div></div><button className="nav-toggle" type="button" title={navigationAction} aria-label={navigationAction} aria-pressed={collapsed} onClick={() => store.updateSettings({ navigationCollapsed: !collapsed })}>{collapsed ? <ListIndentIncrease size={16} aria-hidden="true"/> : <ListIndentDecrease size={16} aria-hidden="true"/>}</button><div className="top-actions"><button className="top-action" title="Notifications" onClick={() => setNotifications(!notifications)}><Bell/>{store.notifications.length > 0 && <i>{store.notifications.length}</i>}</button><HeaderApplicationActions/><GlobalSettingsMenu/></div>{notifications && <div className="notifications"><header><strong>Notifications</strong><button onClick={() => setNotifications(false)}><X size={14}/></button></header>{store.notifications.length ? store.notifications.map((x, i) => <p key={`${x}${i}`}>{x}<small>Just now</small></p>) : <div className="empty-mini">No notifications</div>}</div>}</header><aside className="main-nav" aria-label="Applications">{nav.map((item, i) => <div key={item.id}>{item.group && <small className="nav-group">{item.group}</small>}<button type="button" title={item.label} aria-label={item.label} className={store.module === item.id ? 'active' : ''} onClick={() => store.setModule(item.id)}><item.icon aria-hidden="true"/><span>{item.label}</span>{i === 0 && <kbd>⌂</kbd>}</button></div>)}</aside><main className="app-main"><div className="module-area">{content}</div>{showBank && <div className="databank-resize"><DatabankPanel/></div>}</main><footer className="statusbar"><span><i className="online"/>Ready</span><span>Mock engine · no backend</span><span>Workers {store.settings.workers}</span><span>Memory {store.settings.memoryGb} GB</span><span>Build 144.2953 reference</span></footer></div>;
}
