import { useEffect, useState } from 'react';
import { Bell, BriefcaseBusiness, ChartCandlestick, ChartNoAxesCombined, Code2, Database, FlaskConical, FolderKanban, Gauge, GitCompareArrows, Layers3, WandSparkles, Workflow, X } from 'lucide-react';
import type { ModuleId } from './types';
import { useAppStore } from './store';
import { DatabankPanel } from '../components/DatabankPanel';
import { ResearchProject } from '../domains/strategy/ResearchProject';
import { DataManager } from '../domains/data/DataManager';
import { AlgoWizard } from '../domains/strategy/AlgoWizard';
import { PortfolioComposer } from '../domains/portfolio/PortfolioComposer';
import { WorkflowManager } from '../domains/workflow/WorkflowManager';
import { Business, CodeEditor } from '../domains/platform/ExtensionSurfaces';
import { GlobalSettingsMenu } from './GlobalSettingsMenu';
import { DebugConsole, GridControl, HeaderApplicationActions } from './HeaderApplications';

const nav: { id: ModuleId; label: string; icon: typeof ChartNoAxesCombined; group?: string }[] = [
  { id: 'home', label: 'HaruQuantAI', icon: ChartNoAxesCombined }, { id: 'datamanager', label: 'Data Manager', icon: Database, group: 'Fundamentals' }, { id: 'business', label: 'Business', icon: BriefcaseBusiness },
  { id: 'builder', label: 'Builder', icon: WandSparkles, group: 'Development' }, { id: 'algowizard', label: 'AlgoWizard', icon: Workflow }, { id: 'codeeditor', label: 'Code Editor', icon: Code2 },
  { id: 'retester', label: 'Retester', icon: GitCompareArrows, group: 'Robustness' }, { id: 'optimizer', label: 'Optimizer', icon: Gauge },
  { id: 'projects', label: 'Custom Projects', icon: FolderKanban, group: 'Automation' }, { id: 'portfolio', label: 'Portfolio Master', icon: Layers3, group: 'Trading' }, { id: 'composer', label: 'Portfolio Composer', icon: ChartNoAxesCombined },
];

function HomeScreen() { const store = useAppStore(); return <div className="home-screen"><div className="hero"><div><span>HaruQuantAI</span><h1>Research workspace</h1><p>Continue a research project, manage market data, or author a trading strategy.</p></div><div className="version">Build 144 · recreation<br/><small>Frontend mock profile</small></div></div><div className="home-grid"><section><h2>Recent projects</h2>{['EURUSD H1 — Genetic research', 'NQ Breakout — Retest pipeline', 'Diversified FX Portfolio'].map((x, i) => <button key={x} onClick={() => store.setModule(i === 2 ? 'composer' : 'builder')}><span className="project-thumb"><ChartCandlestick/></span><span><strong>{x}</strong><small>{i ? 'Last opened yesterday' : 'Last opened 12 minutes ago'}</small></span><em>{i === 2 ? 'Portfolio Composer' : 'Builder'}</em></button>)}</section><section><h2>Start</h2><div className="start-grid">{nav.slice(1, 9).map(x => <button key={x.id} onClick={() => store.setModule(x.id)}><x.icon/><span>{x.label}</span></button>)}</div></section><section><h2>Environment</h2><dl className="details"><dt>License profile</dt><dd>Full feature fixture</dd><dt>Engine</dt><dd>Deterministic mock</dd><dt>Persistence</dt><dd>Browser local storage</dd><dt>Market data</dt><dd>4 seeded datasets</dd><dt>Strategies</dt><dd>{store.strategies.length}</dd></dl></section></div><div className="home-note"><FlaskConical size={20}/><div><strong>This is a frontend research simulation.</strong><span>No backtests, broker connections, downloads, native compilation, external scripts, or trades are executed.</span></div></div></div>; }

export function App() { const store = useAppStore(); const [notifications, setNotifications] = useState(false); const [navOpen, setNavOpen] = useState(false); const showBank = ['builder', 'retester', 'optimizer', 'portfolio', 'projects'].includes(store.module); useEffect(() => { document.documentElement.dataset.theme = store.settings.theme; document.documentElement.dataset.profile = store.settings.profile; document.documentElement.style.setProperty('--app-zoom', String(store.settings.zoom)); }, [store.settings.profile, store.settings.theme, store.settings.zoom]);
  let content = <HomeScreen/>; if (['builder','retester','optimizer'].includes(store.module)) content = <ResearchProject module={store.module}/>; else if (store.module === 'portfolio') content = <PortfolioComposer master/>; else if (store.module === 'composer') content = <PortfolioComposer/>; else if (store.module === 'datamanager') content = <DataManager/>; else if (store.module === 'algowizard') content = <AlgoWizard/>; else if (store.module === 'projects') content = <WorkflowManager/>; else if (store.module === 'codeeditor') content = <CodeEditor/>; else if (store.module === 'business') content = <Business/>; else if (store.module === 'debugconsole') content = <DebugConsole/>; else if (store.module === 'gridcontrol') content = <GridControl/>;
  return <div className="app-shell"><aside className={`main-nav ${navOpen ? 'nav-open' : ''}`} aria-label="Applications" onMouseEnter={() => setNavOpen(true)} onMouseLeave={() => setNavOpen(false)}><div className="nav-flyout">{nav.map((item) => <div key={item.id}>{item.group && <small className="nav-group">{item.group}</small>}<button type="button" title={item.label} aria-label={item.label} className={store.module === item.id ? 'active' : ''} onClick={() => { store.setModule(item.id); setNavOpen(false); }}>{item.id === 'home' ? <span className="brand-mark"><item.icon aria-hidden="true"/></span> : <item.icon aria-hidden="true"/>}<span>{item.label}</span></button></div>)}</div></aside><main className="app-main"><div className="module-area">{content}</div>{showBank && <div className="databank-resize"><DatabankPanel/></div>}</main><footer className="statusbar"><div className="status-metrics"><span>Workers {store.settings.workers}</span><span>Memory 4.2/{store.settings.memoryGb} GB</span><span>CPU 34%</span><span><i className="online"/>Backend</span><span>Latency 12 ms</span><span><i className="online"/>Database</span></div><div className="status-actions"><div className="status-bell"><button className="status-action" title="Notifications" aria-label="Notifications" onClick={() => setNotifications(!notifications)}><Bell/>{store.notifications.length > 0 && <i>{store.notifications.length}</i>}</button>{notifications && <div className="notifications"><header><strong>Notifications</strong><button onClick={() => setNotifications(false)}><X size={14}/></button></header>{store.notifications.length ? store.notifications.map((x, i) => <p key={`${x}${i}`}>{x}<small>Just now</small></p>) : <div className="empty-mini">No notifications</div>}</div>}</div><HeaderApplicationActions/><GlobalSettingsMenu/></div></footer></div>;
}
