import type { BusinessConfig, ComputeNode } from '../../host/types';

export const computeNodes: ComputeNode[] = [
  {
    id: 'node-local',
    name: 'Master Node (Local Engine)',
    host: '127.0.0.1',
    ip: '127.0.0.1',
    port: 9091,
    cores: 16,
    memoryGb: 32,
    gpu: true,
    status: 'Online',
    cpuUsagePct: 24,
    latencyMs: 1,
    activeTask: 'Pipeline Execution Manager',
  },
  {
    id: 'node-cluster-1',
    name: 'Cluster-Alpha (Dedicated Server)',
    host: 'alpha.cluster.internal',
    ip: '192.168.1.101',
    port: 9092,
    cores: 32,
    memoryGb: 64,
    gpu: true,
    status: 'Busy',
    cpuUsagePct: 88,
    latencyMs: 3,
    activeTask: 'Genetic Evolution: Gen 42/100 (EURUSD H1)',
  },
  {
    id: 'node-cluster-2',
    name: 'Cluster-Beta (Cloud Compute Instance)',
    host: 'beta.cluster.internal',
    ip: '10.0.0.15',
    port: 9092,
    cores: 16,
    memoryGb: 32,
    gpu: false,
    status: 'Idle',
    cpuUsagePct: 6,
    latencyMs: 18,
  },
  {
    id: 'node-cluster-3',
    name: 'Cluster-Gamma (Backup Instance)',
    host: 'gamma.cluster.internal',
    ip: '10.0.0.16',
    port: 9092,
    cores: 8,
    memoryGb: 16,
    gpu: false,
    status: 'Offline',
    cpuUsagePct: 0,
    latencyMs: 0,
  },
];

export const businessConfig: BusinessConfig = {
  organization: 'Haru Quant Capital Inc.',
  activeWorkspace: 'Production Quantitative Alpha',
  workspaces: [
    { id: 'ws-1', name: 'Production Quantitative Alpha', coresAllocated: 48, memoryAllocated: 96 },
    { id: 'ws-2', name: 'R&D Sandbox (Crypto / Futures)', coresAllocated: 16, memoryAllocated: 32 },
    { id: 'ws-3', name: 'Backtesting Cluster West', coresAllocated: 8, memoryAllocated: 16 },
  ],
  users: [
    { id: 'u-1', name: 'Haru Peri', email: 'haru@quantai.internal', role: 'Owner', status: 'Active' },
    { id: 'u-2', name: 'Alex Vance', email: 'alex@quantai.internal', role: 'Quant Researcher', status: 'Active' },
    { id: 'u-3', name: 'Elena Rostova', email: 'elena@quantai.internal', role: 'Risk Manager', status: 'Active' },
    { id: 'u-4', name: 'Audit Service Agent', email: 'audit@quantai.internal', role: 'Viewer', status: 'Service Account' },
  ],
  mcpServers: [
    {
      id: 'mcp-1',
      name: 'Antigravity Alpha Agent Gateway',
      url: 'http://localhost:8080/mcp/v1',
      transport: 'sse',
      status: 'Connected',
      capabilities: ['strategy_generation', 'backtest_execution', 'code_synthesis'],
      activeCalls: 2,
    },
    {
      id: 'mcp-2',
      name: 'QuantConnect Cloud Bridge',
      url: 'stdio:qc-bridge',
      transport: 'stdio',
      status: 'Connected',
      capabilities: ['live_data_feed', 'order_routing'],
      activeCalls: 0,
    },
    {
      id: 'mcp-3',
      name: 'OpenAI Reasoning Engine',
      url: 'http://localhost:8081/mcp/v1',
      transport: 'sse',
      status: 'Connected',
      capabilities: ['prompt_optimization', 'code_explanation'],
      activeCalls: 1,
    },
  ],
};
