import { expect, test, type Page } from '@playwright/test';
import { selectLightSkin, setFeatureProfileFixture } from './shellTestUtils';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import path from 'node:path';
async function open(page:Page, command='Add Darwinex data') { await page.getByRole('button',{name:'Darwinex Tick Data',exact:true}).click(); await page.getByRole('menuitem',{name:command,exact:true}).click(); return page.getByRole('dialog'); }
async function launch(page:Page) { await page.goto('/');await page.getByRole('button',{name:'Data Manager',exact:true}).click(); }
async function add(page:Page) { const dialog=await open(page);await dialog.getByRole('textbox',{name:'Filter items',exact:true}).fill('AUDUSD');await dialog.getByRole('checkbox',{name:'Select symbol AUDUSD',exact:true}).check();await dialog.getByRole('checkbox',{name:/I confirm/}).check();await dialog.getByRole('textbox',{name:'Data postfix',exact:true}).fill('_D');await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByLabel('Status for AUDUSD_D',{exact:true})).toHaveText('Completed',{timeout:10000}); }
test('catalogue validation, filtering, selection, persistence and shared job recovery',async({page},info)=>{
 await launch(page);const dialog=await open(page);await expect(dialog.getByRole('checkbox',{name:/^Select symbol /})).toHaveCount(328);
 await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog.getByRole('alert')).toHaveText('No symbols selected');
 await dialog.getByRole('textbox',{name:'Filter items',exact:true}).fill('AUDUSD');await dialog.getByRole('checkbox',{name:'Select all Darwinex symbols'}).check();await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('confirm');
 await dialog.getByRole('textbox',{name:'Filter items',exact:true}).fill('AUDCAD');await expect(dialog.getByRole('checkbox',{name:'Select symbol AUDCAD',exact:true})).not.toBeChecked();
 await dialog.getByRole('checkbox',{name:'Select symbol AUDCAD',exact:true}).check();await dialog.getByRole('checkbox',{name:/I confirm/}).check();await dialog.getByRole('textbox',{name:'Data postfix',exact:true}).fill('_D');await page.screenshot({path:info.outputPath('darwinex-add-dark.png')});
 await dialog.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:'Pause all',exact:true}).click();await page.reload();await expect(page.getByLabel('Data Manager progress')).toContainText('paused');await page.getByRole('button',{name:'Resume all',exact:true}).click();await expect(page.getByLabel('Status for AUDCAD_D',{exact:true})).toHaveText('Completed',{timeout:10000});await page.reload();await expect(page.getByLabel('Status for AUDCAD_D',{exact:true})).toHaveText('Completed');
});
test('broker mapping, unresolved mass actions, Back and all-skipped validation',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('sqx-data-manager-v1',JSON.stringify({version:1,definitions:[],brokers:[{id:'b',name:'Test broker',postfix:'_B',timezone:'Europe/Prague',mtUse:true,instruments:[]}]})));
 await launch(page);let dialog=await open(page);await dialog.getByRole('textbox',{name:'Filter items',exact:true}).fill('AUDUSD');await dialog.getByRole('checkbox',{name:'Select symbol AUDUSD',exact:true}).check();await dialog.getByRole('combobox',{name:'Broker profile',exact:true}).selectOption('b');await expect(dialog.getByRole('textbox',{name:'Data postfix',exact:true})).toHaveValue('_B');await expect(dialog.getByRole('status')).toContainText('non-default');await dialog.getByRole('checkbox',{name:/I confirm/}).check();await dialog.getByRole('button',{name:'Save',exact:true}).click();
 dialog=page.getByRole('dialog',{name:'Add Darwinex data - identify instruments',exact:true});await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('proper instrument');await dialog.getByRole('button',{name:'Skip adding the symbol',exact:true}).click();await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog.getByRole('alert')).toHaveText('No symbols selected');await dialog.getByRole('button',{name:'< Back',exact:true}).click();await expect(page.getByRole('checkbox',{name:'Select symbol AUDUSD',exact:true})).toBeChecked();await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await dialog.getByRole('button',{name:'Default instrument',exact:true}).click();await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByLabel('Status for AUDUSD_B',{exact:true})).toHaveText('Completed',{timeout:10000});await expect(page.getByRole('table',{name:'Historical data',exact:true})).toContainText('Europe/Prague');
});
test('folder import discovers compressed filenames, validates, cancels and persists',async({page},info)=>{
 const root=info.outputPath('Darwinex');await mkdir(path.join(root,'EURUSD'),{recursive:true});await mkdir(path.join(root,'GBPUSD'),{recursive:true});await writeFile(path.join(root,'EURUSD','a.log.gz'),'mock bytes');await writeFile(path.join(root,'GBPUSD','ignore.txt'),'not data');
 await launch(page);let dialog=await open(page,'Import data from a Darwinex folder');await dialog.getByRole('button',{name:'Start import',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Select Darwinex');await dialog.getByLabel('Select Darwinex data folder',{exact:true}).setInputFiles(root);await expect(dialog.getByRole('checkbox',{name:/^Select symbol /})).toHaveCount(1);await dialog.getByRole('checkbox',{name:'Select all import symbols'}).check();await dialog.getByRole('button',{name:'Start import',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('exists');await dialog.getByRole('textbox',{name:'Data postfix',exact:true}).fill('_I');await dialog.getByRole('button',{name:'Start import',exact:true}).click();await page.getByRole('button',{name:'Stop all',exact:true}).click();await expect(page.getByRole('checkbox',{name:'Select EURUSD_I',exact:true})).toHaveCount(0);
 dialog=await open(page,'Import data from a Darwinex folder');await dialog.getByLabel('Select Darwinex data folder',{exact:true}).setInputFiles(root);await dialog.getByRole('checkbox',{name:'Select all import symbols'}).check();await dialog.getByRole('button',{name:'Start import',exact:true}).click();await expect(page.getByLabel('Status for EURUSD_I',{exact:true})).toHaveText('Completed',{timeout:10000});expect(await readFile(path.join(root,'EURUSD','a.log.gz'),'utf8')).toBe('mock bytes');await page.reload();dialog=await open(page,'Import data from a Darwinex folder');await expect(dialog.getByText('Select the folder again to access its available symbols.')).toBeVisible();
});
test('download selection, date presets, validation, intervals and restricted profile',async({page},info)=>{
 await launch(page);await open(page,'Download data for existing symbols');await expect(page.getByLabel('Data Manager progress')).toContainText('at least one Darwinex');await add(page);await page.getByRole('checkbox',{name:'Select AUDUSD_D',exact:true}).check();await page.getByRole('checkbox',{name:'Select EURUSD',exact:true}).check();let dialog=await open(page,'Download data for existing symbols');await expect(dialog).toHaveAccessibleName("Download Darwinex data for 'AUDUSD_D'");
 for(const name of ['Last 6 months','Last year','Last 5 years','Last 10 years','All time','Since last date']) {await dialog.getByRole('button',{name,exact:true}).click();await expect(dialog.getByRole('button',{name,exact:true})).toHaveAttribute('aria-pressed','true');}
 await dialog.getByLabel('From',{exact:true}).fill('2025-01-03');await dialog.getByLabel('To',{exact:true}).fill('2025-01-01');await dialog.getByRole('button',{name:'Start download',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('valid date');await dialog.getByLabel('From',{exact:true}).fill('2025-01-01');await dialog.getByLabel('To',{exact:true}).fill('2025-01-03');await dialog.getByRole('radio',{name:'Overwrite existing data',exact:true}).check();await page.screenshot({path:info.outputPath('darwinex-download-dark.png')});await dialog.getByRole('button',{name:'Start download',exact:true}).click();await expect(page.getByLabel('Data Manager progress')).toContainText('download completed',{timeout:10000});await expect(page.getByRole('row').filter({has:page.getByRole('checkbox',{name:'Select AUDUSD_D',exact:true})})).toContainText('2025-01-03');
 await setFeatureProfileFixture(page,'Starter');await page.getByRole('checkbox',{name:'Select AUDUSD_D',exact:true}).check();dialog=await open(page,'Download data for existing symbols');await expect(dialog.getByText('Darwinex CDN download is available only for users of full license.')).toBeVisible();await expect(dialog.getByRole('button',{name:'Start download'})).toHaveCount(0);await dialog.getByRole('button',{name:'Upgrade To Pro Version'}).click();await expect(dialog.getByRole('link')).toHaveCount(0);
});
test('light narrow layout, focus, quota failure and cancellation',async({page},info)=>{
 await launch(page);await selectLightSkin(page);await page.setViewportSize({width:620,height:700});const dialog=await open(page);await dialog.getByRole('textbox',{name:'Filter items',exact:true}).fill('AUDUSD');await dialog.getByRole('checkbox',{name:'Select symbol AUDUSD',exact:true}).check();await dialog.getByRole('checkbox',{name:/I confirm/}).check();await expect(dialog.getByRole('button',{name:'Save',exact:true})).toBeInViewport();await page.screenshot({path:info.outputPath('darwinex-light-narrow.png')});await dialog.getByRole('button',{name:'Save',exact:true}).focus();await page.keyboard.press('Tab');await expect(dialog.getByRole('button',{name:'Close',exact:true}).first()).toBeFocused();await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw new Error('quota');};});await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Unable to save');await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Darwinex Tick Data',exact:true})).toBeFocused();
});
