import {test,expect} from './frontendStructureFixtures';
import {resolve} from 'node:path';
const evidence=resolve(process.cwd(),'../../.agents/logs/2026-09-25T164633_portfolio-master-composer-ui-plan/verification');
test('Composer members, independent weights, dialogs and preview serialization',async({page})=>{
 await page.goto('/composer');await expect(page.getByRole('tablist',{name:'Composer settings tabs'})).toBeVisible();await expect(page.getByRole('button',{name:'Expand databanks',exact:true})).toHaveCount(0);
 const weight=page.locator('.pf-member-grid input[type=number]').first();await weight.fill('200');await page.getByRole('tab',{name:'Configuration - account, MM',exact:true}).click();await page.getByLabel('Initial capital',{exact:true}).fill('25000');await page.getByRole('tab',{name:'Portfolio composition',exact:true}).click();await expect(weight).toHaveValue('200');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Save',exact:true}).click();expect((await download).suggestedFilename()).toBe('portfolio-composition.preview.json');
 await page.getByRole('button',{name:'Clear all',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await expect(weight).toHaveValue('200');
 await page.getByRole('button',{name:'Add Buy and Hold strategy',exact:true}).click();await page.getByLabel('Buy and Hold symbol',{exact:true}).selectOption('QQQ');await page.getByRole('dialog').getByRole('button',{name:'Add',exact:true}).click();await expect(page.getByLabel('Buy and Hold QQQ weight',{exact:true})).toHaveValue('100');
 await page.getByLabel('Select all members',{exact:true}).uncheck();await page.getByLabel('Select Buy and Hold QQQ',{exact:true}).check();await page.getByRole('button',{name:'Move up',exact:true}).click();await expect(page.locator('.pf-member-grid tbody tr').nth(7)).toContainText('Buy and Hold QQQ');
 await page.getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Delete',exact:true}).click();await expect(page.getByLabel('Buy and Hold QQQ weight',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Load',exact:true}).click();await page.getByLabel('Search examples',{exact:true}).fill('Strategy 001');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Load selected',exact:true}).click();await expect(page.getByLabel('Strategy 001 weight',{exact:true})).toHaveValue('100');
});
test('Composer computation, stale result invalidation, log and automatic views',async({page})=>{
 test.setTimeout(45000);const writes:string[]=[];page.on('request',r=>{if(r.method()==='POST'&&/executions|portfolio/i.test(r.url()))writes.push(r.url());});
 await page.goto('/composer');await page.getByRole('button',{name:'Recompute portfolio',exact:true}).click();await expect(page.locator('.pf-composer-form')).toHaveAttribute('inert','');await page.getByRole('button',{name:'Stop',exact:true}).click();await expect(page.locator('.sqd-task-desc')).toContainText('idle');
 await page.getByRole('button',{name:'Recompute portfolio',exact:true}).click();await expect(page.locator('.sqd-task-desc')).toContainText('complete',{timeout:15000});await page.getByRole('tab',{name:'Log',exact:true}).click();await page.getByLabel('Log actions',{exact:true}).selectOption('Skipped');await expect(page.locator('.sqr-panel-slot:not([hidden]) tbody tr')).toHaveCount(1);
 await page.locator('.pf-member-grid input[type=number]').first().fill('250');await expect(page.locator('.sqr-info-line')).toContainText('No portfolio result');await expect(page.getByRole('button',{name:'Save portfolio',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Automatic computation',exact:true}).click();await expect(page.locator('.sqd-task-desc')).toContainText('complete',{timeout:15000});await page.getByRole('tab',{name:'Automatic computation simulations',exact:true}).click();await expect(page.getByRole('img',{name:/Automatic computation simulations/})).toBeVisible();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Save portfolio',exact:true}).click();expect((await download).suggestedFilename()).toBe('portfolio-result.preview.json');expect(writes).toEqual([]);
 await page.setViewportSize({width:1840,height:1000});await page.screenshot({path:resolve(evidence,'composer-results.png')});
});
test('Composer empty state, import failure, range guard and responsive states',async({page})=>{
 await page.goto('/composer');await page.getByRole('button',{name:'Clear all',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Clear all',exact:true}).click();await expect(page.getByRole('button',{name:'Recompute portfolio',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Load',exact:true}).click();await page.getByLabel('Import preview composition',{exact:true}).setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{}')});await expect(page.getByRole('dialog').getByRole('alert')).toContainText('preview JSON');await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('button',{name:'Add Buy and Hold strategy',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Add',exact:true}).click();
 await page.getByRole('tab',{name:'Configuration - account, MM',exact:true}).click();await page.getByLabel('Leverage',{exact:true}).fill('0');await expect(page.getByRole('button',{name:'Recompute portfolio',exact:true})).toBeDisabled();await page.getByLabel('Leverage',{exact:true}).fill('2');
 await page.setViewportSize({width:1567,height:958});await page.screenshot({path:resolve(evidence,'composer-configuration.png')});await page.evaluate(()=>document.documentElement.dataset.theme='light');await expect(page.locator('.pf-composer')).toHaveCSS('color','rgb(85, 85, 85)');await expect(page.locator('.pf-composer .sqr-tabs-body')).toHaveCSS('background-color','rgb(236, 236, 236)');await page.screenshot({path:resolve(evidence,'composer-light.png')});await page.setViewportSize({width:900,height:760});await page.screenshot({path:resolve(evidence,'composer-narrow.png')});await page.evaluate(()=>document.body.style.zoom='0.8');await page.screenshot({path:resolve(evidence,'composer-zoom.png')});
});

test('Composer preview import round trip preserves weights and failed file does not replace draft',async({page})=>{
 await page.goto('/composer');const doc={format:'haruquantai.portfolio-ui-preview',version:1,config:{range:'Full available',from:'2020-01-01',to:'2025-12-31',capital:100000,leverage:1,fitness:'Sharpe ratio',simulations:10,riskFree:0.7},members:[{id:'import-a',name:'Imported A',symbol:'SPY',weight:250,selected:true,equity:[100,110],money:'Fixed size'}]};
 await page.getByRole('button',{name:'Load',exact:true}).click();await page.getByLabel('Import preview composition',{exact:true}).setInputFiles({name:'preview.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await expect(page.getByLabel('Imported A weight',{exact:true})).toHaveValue('250');
 await page.getByRole('button',{name:'Load',exact:true}).click();await page.getByLabel('Import preview composition',{exact:true}).setInputFiles({name:'bad.sqx',mimeType:'application/octet-stream',buffer:Buffer.from('native unsupported')});await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByLabel('Imported A weight',{exact:true})).toHaveValue('250');
});
